import type { CourseLesson } from '@/domain/content/schema';

export const aula2: CourseLesson = {
  id: 'course-aula-2',
  order: 2,
  aula: 'Aula 2',
  track: 'federal',
  titleFa: 'معرفی خود و ضمایر شخصی',
  titlePt: 'Apresentação Pessoal e Pronomes Pessoais',
  cefr: 'A1',
  summaryFa:
    'در این درس یاد می‌گیرید چطور به‌صورت رسمی و غیررسمی سلام و احوال‌پرسی کنید و تعارف‌های روزمره را به‌کار ببرید؛ خودتان را کامل معرفی کنید (نام، سن، تاریخ تولد، وضعیت تأهل، شغل، نشانی، تلفن، ایمیل و ملیت)؛ فهرست کامل ملیت‌ها را بشناسید؛ ضمایر شخصی پرتغالی برزیلی و کاربرد «a gente» را یاد بگیرید؛ و مهم‌ترین نکتهٔ گرامری این سطح یعنی تفاوت دو فعل «بودن» (SER و ESTAR) را همراه با صرف کامل و تمرین‌های فراوان تمرین کنید.',
  objectivesFa: [
    'سلام و احوال‌پرسی رسمی و غیررسمی و تعارف‌های ادب را به‌کار ببرید.',
    'با یک الگوی آماده خودتان را کامل معرفی کنید و فرم اطلاعات شخصی را پر کنید.',
    'ملیت‌ها را با شکل مذکر و مؤنث بشناسید.',
    'ضمایر شخصی (eu, tu/você, ele/ela, a gente, nós, vós/vocês, eles/elas) را تشخیص دهید.',
    'صرف زمان حال فعل‌های SER و ESTAR را بدانید و تفاوت آن‌ها (ثابت در برابر موقتی) را درست به‌کار ببرید.',
  ],
  sections: [
    {
      headingFa: '۱. احوال‌پرسی رسمی (Formal)',
      bodyFa:
        'در موقعیت‌های رسمی (با غریبه، در اداره، محل کار، با افراد بزرگ‌تر) از این عبارت‌ها استفاده کنید. سلام بر اساس ساعت روز خیلی رایج است: صبح، بعدازظهر و شب هرکدام عبارت خودشان را دارند. عبارت‌های آشناییِ رسمی هم «Muito prazer!» (از آشنایی‌تان خوشوقتم) و پاسخ آن «O prazer é meu!» (افتخار از من است) هستند.',
      examples: [
        {
          pt: 'Bom dia!',
          fa: 'صبح بخیر!',
          pron: 'بُن جیا',
          note: 'تا حدود ظهر.',
        },
        {
          pt: 'Boa tarde!',
          fa: 'بعدازظهر بخیر!',
          pron: 'بُووا تارجی',
          note: 'از ظهر تا غروب.',
        },
        {
          pt: 'Boa noite!',
          fa: 'شب بخیر!',
          pron: 'بُووا نُویتی',
          note: 'هم هنگام رسیدن و هم هنگام خداحافظی شبانه.',
        },
        {
          pt: 'Como vai? Tudo bem?',
          fa: 'حالتان چطور است؟ همه‌چیز خوب است؟',
          pron: 'کُمو وای؟ تودو بِین؟',
          note: '«Tudo bem?» هم سؤال است هم جواب؛ در پاسخ «Tudo bem!» یعنی «خوبم».',
        },
        {
          pt: 'Muito prazer! — O prazer é meu!',
          fa: 'از آشنایی‌تان خوشوقتم! — افتخار از من است!',
          pron: 'مویتو پرازِر! — او پرازِر اِ مِئو!',
          note: 'هنگام معرفی و دست‌دادن رسمی.',
        },
      ],
    },
    {
      headingFa: '۲. احوال‌پرسی غیررسمی و تعارف‌ها (Informal)',
      bodyFa:
        'با دوستان و افراد نزدیک از حالت غیررسمی استفاده می‌کنید. در این بخش عبارت‌های تشکر، عذرخواهی، خواهش و خداحافظی را هم یاد بگیرید. نکتهٔ مهم: در پرتغالی تشکر به جنسیت گوینده بستگی دارد، نه شنونده.',
      examples: [
        {
          pt: 'Oi! / Olá! / E aí?',
          fa: 'سلام! / سلام! / چطوری؟ (چه خبر؟)',
          pron: 'اُی! / اُلا! / ای آیی؟',
          note: '«E aí?» خیلی خودمانی است.',
        },
        {
          pt: 'Obrigado! / Obrigada!',
          fa: 'ممنون!',
          pron: 'اُبریگادو / اُبریگادا',
          note: 'مرد «obrigado» و زن «obrigada» می‌گوید. مترادف رسمی: agradecido/agradecida.',
        },
        {
          pt: 'Por nada. / De nada.',
          fa: 'خواهش می‌کنم. / قابلی نداشت.',
          pron: 'پور نادا / جی نادا',
          note: 'پاسخ به تشکر.',
        },
        {
          pt: '(Me) desculpe. / Com licença.',
          fa: 'ببخشید (عذر می‌خواهم). / با اجازه.',
          pron: 'می جِسکولپی / کُن لیسِنسا',
          note: '«com licença» هنگام رد شدن یا وارد شدن.',
        },
        {
          pt: 'Por favor. / Por gentileza. / Igualmente.',
          fa: 'لطفاً. / لطفاً (مؤدبانه‌تر). / همچنین (شما هم).',
          pron: 'پور فاوُر / پور جِنتیلِزا / ایگوالمِنتی',
          note: '«Igualmente» پاسخ به یک آرزوی خوب است.',
        },
        {
          pt: 'Até logo! / Até mais tarde! / Até amanhã!',
          fa: 'تا بعد! / تا کمی بعد! / تا فردا!',
          pron: 'آته لوگو / آته مایس تارجی / آته آمانیا',
        },
        {
          pt: 'Bom fim de semana! / Adeus! / Tchau!',
          fa: 'آخر هفتهٔ خوبی داشته باشی! / بدرود! / خداحافظ!',
          pron: 'بُن فین جی سِمانا / آدِئوس / چاو',
          note: '«Tchau» غیررسمی و بسیار رایج؛ «Adeus» خداحافظیِ قطعی‌تر.',
        },
      ],
    },
    {
      headingFa: '۳. معرفی خود ـ اطلاعات پایه',
      bodyFa:
        'وقتی خودتان را معرفی می‌کنید، ابتدا این موارد گفته می‌شود: نام (nome)، سن (idade) و تاریخ تولد (data de nascimento). قالب تاریخ در برزیل DD/MM/AAAA است، یعنی روز/ماه/سال (مثلاً ۱۰/۰۱/۱۹۹۵ = ۱۰ ژانویه ۱۹۹۵). نکتهٔ کلیدی: برای سن از فعل ter (داشتن) استفاده می‌شود، نه ser.',
      examples: [
        {
          pt: 'Meu nome é Ana Maria Fernandes.',
          fa: 'نام من آنا ماریا فرناندس است.',
          pron: 'مِئو نُمی اِ آنا ماریا فِرنانجِس',
        },
        {
          pt: 'Minha idade: 30 anos.',
          fa: 'سن من: ۳۰ سال.',
          pron: 'مینیا ایدادی: ترینتا آنوس',
          note: 'در جمله می‌گوییم «Eu tenho 30 anos» (من ۳۰ سال دارم).',
        },
        {
          pt: 'Data de nascimento: 10/01/1995.',
          fa: 'تاریخ تولد: ۱۰/۰۱/۱۹۹۵ (۱۰ ژانویه ۱۹۹۵).',
          pron: 'داتا جی نَسیمِنتو',
          note: 'قالب: روز/ماه/سال، برخلاف ترتیب انگلیسی آمریکایی.',
        },
      ],
    },
    {
      headingFa: '۴. معرفی خود ـ اطلاعات تکمیلی (فرم)',
      bodyFa:
        'در ادامهٔ فرم اطلاعات شخصی معمولاً این موارد می‌آید: وضعیت تأهل (estado civil)، شغل (profissão)، نشانی (endereço)، تلفن ثابت (telefone fixo)، تلفن همراه (celular) و ایمیل (e-mail). گزینه‌های وضعیت تأهل: Solteiro (مجرد)، Casado (متأهل)، Divorciado (طلاق‌گرفته)، Viúvo (بیوه). نشانی می‌تواند با Rua (خیابان)، Avenida (بلوار)، Estrada (جاده) یا Praça (میدان) شروع شود و شامل Complemento (بلوک/واحد)، Bairro (محله)، Cidade (شهر)، Estado (ایالت) و CEP (کد پستی) است. شمارهٔ تلفن با DDD (کد شهر) شروع می‌شود.',
      examples: [
        {
          pt: 'Estado civil: solteira. Profissão: vendedora.',
          fa: 'وضعیت تأهل: مجرد (زن). شغل: فروشنده (زن).',
          pron: 'اِستادو سیویل: سُلتِیرا. پروفیسائو: وِندِدورا',
          note: 'برای زن پایانه به «a» تغییر می‌کند: solteira, casada, viúva; vendedora.',
        },
        {
          pt: 'Meu endereço: Avenida Paulista, n° 100, Bloco A, Ap. 22.',
          fa: 'نشانی من: بلوار پائولیستا، شمارهٔ ۱۰۰، بلوک A، واحد ۲۲.',
          pron: 'مِئو اِندِرِسو: آوِنیدا پائولیستا',
          note: '«n°» یعنی número (شماره)؛ «Ap.» یعنی apartamento (آپارتمان).',
        },
        {
          pt: 'Bairro: Bela Vista. Cidade: São Paulo. Estado: SP. CEP: 00000-000.',
          fa: 'محله: بلا ویستا. شهر: سائوپائولو. ایالت: SP. کد پستی: ۰۰۰۰۰-۰۰۰.',
          pron: 'بایرو / سیدادی / اِستادو / سِپ',
        },
        {
          pt: 'Meu telefone fixo: (11) 0000-0000. Meu celular: (11) 90000-0000.',
          fa: 'تلفن ثابت من: (۱۱) ۰۰۰۰-۰۰۰۰. موبایل من: (۱۱) ۹۰۰۰۰-۰۰۰۰.',
          pron: 'تِلِفُنی فیکسو / سِلولار',
          note: 'DDD = کد منطقه؛ برای سائوپائولو ۱۱ است. موبایل معمولاً با ۹ شروع می‌شود.',
        },
        {
          pt: 'E-mail: anamaria@gmail.com',
          fa: 'ایمیل: anamaria@gmail.com',
          pron: 'ایمِیل',
        },
      ],
    },
    {
      headingFa: '۵. ملیت‌ها (Nacionalidades) ـ فهرست کامل',
      bodyFa:
        'ملیت در پرتغالی دو شکل دارد: مذکر و مؤنث. معمولاً پایانهٔ مؤنث به «a» ختم می‌شود (مثلاً brasileiro / brasileira). بعضی ملیت‌ها فقط یک شکل دارند (مثل iemenita, bengali). فهرست کامل ملیت‌های این درس:\n\njaponês / japonesa — ژاپنی\njordaniano / jordaniana (یا jordano / jordana) — اردنی\ncolombiano / colombiana — کلمبیایی\nmexicano / mexicana — مکزیکی\nbrasileiro / brasileira — برزیلی\nmalaio / malaia — مالزیایی\nfrancês / francesa — فرانسوی\ntunisiano / tunisiana — تونسی\nsenegalês / senegalesa — سنگالی\nsírio / síria (یا siríaco / siríaca) — سوری\negípcio / egípcia — مصری\nbengalês / bengalesa (یا bengali) — بنگالی\nvenezuelano / venezuelana — ونزوئلایی\nhaitiano / haitiana — هائیتیایی\niemenita — یمنی\nindiano / indiana — هندی\nfilipino / filipina — فیلیپینی\ncongolês / congolesa — کنگویی\niraquiano / iraquiana — عراقی\nlibanês / libanesa — لبنانی\ncubano / cubana — کوبایی\nsul-africano / sul-africana — اهل آفریقای جنوبی\nchinês / chinesa — چینی\nnigeriano / nigeriana — نیجریه‌ای\ncamaronês / camaronesa — کامرونی\nguineano / guineana (یا guineense) — گینه‌ای\npaquistanês / paquistanesa — پاکستانی\nmarroquino / marroquina — مراکشی\nganês / ganesa (یا ganense) — غنایی\ngambiano / gambiana — گامبیایی\nargelino / argelina — الجزایری\nneozelandês / neozelandesa — نیوزیلندی\ndominicano / dominicana — دومینیکنی\nrusso / russa — روسی\nitaliano / italiana — ایتالیایی\nboliviano / boliviana — بولیویایی',
      examples: [
        {
          pt: 'Eu sou brasileiro. / Eu sou brasileira.',
          fa: 'من برزیلی هستم (مرد). / من برزیلی هستم (زن).',
          pron: 'اِئو سُ برازیلِیرو / برازیلِیرا',
          note: 'ملیت با فعل SER می‌آید چون ویژگی ثابت است.',
        },
        {
          pt: 'Ela é francesa. Ele é francês.',
          fa: 'او (زن) فرانسوی است. او (مرد) فرانسوی است.',
          pron: 'اِلا اِ فرانسِزا. اِلی اِ فرانسِس',
          note: 'پایانهٔ «-ês» مذکر و «-esa» مؤنث.',
        },
        {
          pt: 'Ele é iemenita. Ela é iemenita.',
          fa: 'او (مرد) یمنی است. او (زن) یمنی است.',
          pron: 'ایِمِنیتا',
          note: 'برخی ملیت‌ها برای مرد و زن یک شکل دارند.',
        },
      ],
    },
    {
      headingFa: '۶. الگوی جملهٔ معرفی خود',
      bodyFa:
        'با این الگوی آماده می‌توانید خودتان را به‌طور کامل معرفی کنید؛ جای خالی‌ها را با اطلاعات خودتان پر کنید:\n\nMEU NOME É _____. (نام من … است)\nEU SOU (ESTADO CIVIL) _____. (من … هستم ـ وضعیت تأهل)\nEU SOU DE/DO/DA _____. (من اهل … هستم ـ شهر/محل تولد ـ naturalidade)\nMINHA NACIONALIDADE É _____. (ملیت من … است ـ کشور محل تولد)\nEU TENHO _____ ANOS. (من … سال دارم)\nEU MORO EM/NO/NA _____. (من در … زندگی می‌کنم)\nEU TRABALHO COMO (PROFISSÃO) _____. (من به‌عنوان … کار می‌کنم)\nEU GOSTO DE _____. (من … را دوست دارم)',
      examples: [
        {
          pt: 'Meu nome é Ana. Eu sou solteira.',
          fa: 'نام من آنا است. من مجرد هستم.',
          pron: 'مِئو نُمی اِ آنا. اِئو سُ سُلتِیرا',
        },
        {
          pt: 'Eu sou de Teerã. Minha nacionalidade é iraniana.',
          fa: 'من اهل تهران هستم. ملیت من ایرانی است.',
          pron: 'اِئو سُ جی تِئِران. مینیا ناسیونالیدادی اِ ایرانیانا',
          note: '«Eu sou de…» یعنی اهلِ کجا بودن (naturalidade). حرف اضافه بسته به مکان de/do/da می‌شود.',
        },
        {
          pt: 'Eu tenho trinta anos. Eu moro em São Paulo.',
          fa: 'من سی سال دارم. من در سائوپائولو زندگی می‌کنم.',
          pron: 'اِئو تِنیو ترینتا آنوس. اِئو مُرو اِین سائو پائولو',
          note: 'برای سن فعل ter؛ گفتن «sou … anos» اشتباه است.',
        },
        {
          pt: 'Eu trabalho como vendedora. Eu gosto de música.',
          fa: 'من به‌عنوان فروشنده کار می‌کنم. من موسیقی دوست دارم.',
          pron: 'اِئو ترابایو کُمو وِندِدورا. اِئو گُستو جی موزیکا',
        },
      ],
    },
    {
      headingFa: '۷. ضمایر شخصی (Pronomes Pessoais) ـ جدول',
      bodyFa:
        'در گفتار و نوشتار سه «شخص» وجود دارد. ستون اول شکل کلاسیک/سنتی و ستون دوم شکل رایج در برزیل است:\n\nشخص | مفرد | جمع\nاول‌شخص | EU (من) | NÓS (ما)\nدوم‌شخص | TU → VOCÊ (تو/شما) | VÓS → VOCÊS (شما)\nسوم‌شخص | ELE / ELA (او مرد/زن) | ELES / ELAS (آن‌ها مرد/زن)\nغیررسمی برای «ما» | A GENTE (فقط در گفتار) |\n\nتوضیح: اول‌شخص = کسی که حرف می‌زند (EU, NÓS)؛ دوم‌شخص = کسی که با او حرف می‌زنیم (VOCÊ, VOCÊS)؛ سوم‌شخص = کسی که درباره‌اش حرف می‌زنیم (ELE, ELA, ELES, ELAS). در برزیل بیشتر به‌جای TU از VOCÊ و به‌جای VÓS از VOCÊS استفاده می‌شود.',
      examples: [
        {
          pt: 'eu — tu / você — ele / ela',
          fa: 'من — تو / شما — او (مرد) / او (زن)',
          pron: 'اِئو — تو / وُسه — اِلی / اِلا',
        },
        {
          pt: 'nós — vós / vocês — eles / elas',
          fa: 'ما — شما (قدیمی) / شما — آن‌ها (مردانه) / آن‌ها (زنانه)',
          pron: 'نُس — وُس / وُسِس — اِلیس / اِلاس',
        },
      ],
    },
    {
      headingFa: '۸. کاربرد «a gente»',
      bodyFa:
        '«a gente» یعنی «ما» به‌شکل غیررسمی و فقط باید در گفتار به‌کار رود، نه در نوشتار رسمی. نکتهٔ مهم گرامری: هرچند معنی «ما» می‌دهد، فعلِ آن سوم‌شخص مفرد است (مثل ele/ela). پس می‌گوییم «a gente vai» نه «a gente vamos»، و «a gente é» نه «a gente somos».',
      examples: [
        {
          pt: 'A gente vai ao cinema hoje.',
          fa: 'ما امروز به سینما می‌رویم.',
          pron: 'آ جِنتی وای آئو سینِما اُژی',
          note: 'فعل سوم‌شخص مفرد (vai)، نه اول‌شخص جمع (vamos).',
        },
        {
          pt: 'A gente é espanhola. (informal = Nós somos espanhóis)',
          fa: 'ما اسپانیایی هستیم. (غیررسمی)',
          pron: 'آ جِنتی اِ اِسپانیولا',
          note: 'در نوشتار رسمی: «Nós somos…».',
        },
      ],
    },
    {
      headingFa: '۹. فعل SER (بودنِ ثابت / هویت)',
      bodyFa:
        'پرتغالی دو فعل برای «بودن» دارد. SER برای چیزهای ثابت و همیشگی است: هویت، ملیت، شغل، ویژگی‌های ذاتی. صرف زمان حال:\n\nEU — SOU\nVOCÊ — É\nELE / ELA — É\nA GENTE — É\nNÓS — SOMOS\nVOCÊS — SÃO\nELES / ELAS — SÃO',
      examples: [
        {
          pt: 'Eu sou do Brasil. Eu sou brasileiro.',
          fa: 'من اهل برزیل هستم. من برزیلی هستم.',
          pron: 'اِئو سُ دو برازیل. اِئو سُ برازیلِیرو',
          note: 'اصل و ملیت ثابت‌اند → SER.',
        },
        {
          pt: 'Nós somos amigos.',
          fa: 'ما دوست هستیم.',
          pron: 'نُس سُموس آمیگوس',
        },
        {
          pt: 'Eu sou estudante. Eu sou gordinho (sempre).',
          fa: 'من دانشجو هستم. من (همیشه) کمی چاق هستم.',
          pron: 'اِئو سُ اِستودانتی. اِئو سُ گُردینیو',
          note: 'نقش و ویژگی همیشگی → SER.',
        },
      ],
    },
    {
      headingFa: '۱۰. فعل ESTAR (بودنِ موقتی / حالت / مکان)',
      bodyFa:
        'ESTAR برای حالت‌های موقتی، احساس لحظه‌ای، مکان و کارِ در جریان است. صرف زمان حال:\n\nEU — ESTOU\nVOCÊ — ESTÁ\nELE / ELA — ESTÁ\nA GENTE — ESTÁ\nNÓS — ESTAMOS\nVOCÊS — ESTÃO\nELES / ELAS — ESTÃO',
      examples: [
        {
          pt: 'Eu estou no Brasil para trabalhar.',
          fa: 'من (الان) برای کار در برزیل هستم.',
          pron: 'اِئو اِستُ نو برازیل پارا ترابایار',
          note: 'مکان موقتی → ESTAR. مقایسه با «sou do Brasil» (اصل ثابت → SER).',
        },
        {
          pt: 'Eu estou resfriada. Eu estou aqui faz 40 minutos.',
          fa: 'من سرما خورده‌ام. من ۴۰ دقیقه است که اینجا هستم.',
          pron: 'اِئو اِستُ رِسفریادا. اِئو اِستُ آکی فَس کوارِنتا مینوتوس',
          note: 'حالت موقتی بدن و حضور موقت در مکان → ESTAR.',
        },
        {
          pt: 'Eu estou aprendendo português.',
          fa: 'من در حال یادگیری پرتغالی هستم.',
          pron: 'اِئو اِستُ آپرِندِندو پُرتوگِس',
          note: 'کارِ در جریان (estar + gerúndio) → ESTAR.',
        },
      ],
    },
    {
      headingFa: '۱۱. SER یا ESTAR؟ تفاوت کلیدی',
      bodyFa:
        'اشتباه رایج فارسی‌زبانان این است که چون در فارسی فقط یک فعل «بودن» داریم، SER و ESTAR را قاطی می‌کنند. قاعده: اگر ویژگی همیشگی/هویتی است SER، اگر حالت این لحظه یا مکان یا موقتی است ESTAR. یک جمله با دو فعل معنای متفاوت پیدا می‌کند.',
      examples: [
        {
          pt: 'Eu sou feliz. / Eu estou feliz.',
          fa: 'من (آدمِ) شادی هستم. / من (الان) خوشحالم.',
          pron: 'اِئو سُ فِلیس / اِئو اِستُ فِلیس',
          note: 'sou feliz = ویژگی همیشگی؛ estou feliz = حسِ همین الان.',
        },
        {
          pt: 'Eu sou gordinho. / Eu estou gordinho.',
          fa: 'من (همیشه) چاق هستم. / من (این روزها) چاق شده‌ام.',
          pron: 'اِئو سُ گُردینیو / اِئو اِستُ گُردینیو',
          note: 'همیشگی → SER؛ موقتی/تازه → ESTAR.',
        },
        {
          pt: 'Eu sou estudante. / Eu estou estudando.',
          fa: 'من دانشجو هستم. / من در حال درس خواندن هستم.',
          pron: 'اِئو سُ اِستودانتی / اِئو اِستُ اِستودَندو',
          note: 'هویت/نقش → SER؛ کارِ در جریان → ESTAR.',
        },
      ],
    },
    {
      headingFa: '۱۲. مشاغل (Profissões)',
      bodyFa:
        'در تمرین‌های این درس چند شغل به‌کار رفته است. بیشتر مشاغل شکل مذکر و مؤنث دارند (پایانهٔ مؤنث معمولاً «-a») و بعضی برای مرد و زن یک شکل‌اند:\n\nadvogado / advogada — وکیل\nmédico / médica — پزشک\nsecretário / secretária — منشی\nenfermeiro / enfermeira — پرستار\nengenheiro / engenheira — مهندس\nescritor / escritora — نویسنده\nprofessor / professora — معلم/استاد\nvendedor / vendedora — فروشنده\nmotorista — راننده (برای مرد و زن یک شکل)\ndentista — دندان‌پزشک (برای مرد و زن یک شکل)\n\nنکته: مشاغل ویژگی/نقش هستند و با فعل SER می‌آیند (Eu sou dentista).',
      examples: [
        {
          pt: 'Eu sou advogado. / Eu sou advogada.',
          fa: 'من وکیل هستم (مرد). / من وکیل هستم (زن).',
          pron: 'اِئو سُ آدووگادو / آدووگادا',
        },
        {
          pt: 'Ele é dentista. Ela é dentista.',
          fa: 'او (مرد) دندان‌پزشک است. او (زن) دندان‌پزشک است.',
          pron: 'اِلی اِ دِنتیستا. اِلا اِ دِنتیستا',
          note: '«dentista» و «motorista» برای مرد و زن یک شکل دارند.',
        },
        {
          pt: 'Ela é secretária. Ela é engenheira.',
          fa: 'او (زن) منشی است. او (زن) مهندس است.',
          pron: 'اِلا اِ سِکرِتاریا. اِلا اِ اِنژِنیِیرا',
        },
      ],
    },
    {
      headingFa: '۱۳. اعضای خانواده (Família)',
      bodyFa:
        'در تمرین جایگزینی ضمیرها چند واژهٔ خانواده آمده است. با شناختن جنسیت این واژه‌ها می‌توانید ضمیر درست (ele/ela/eles/elas) را انتخاب کنید:\n\npai — پدر\nmãe — مادر\nirmão / irmã — برادر / خواهر\ntio / tia — عمو یا دایی / عمه یا خاله\navô / avó — پدربزرگ / مادربزرگ\nfilho / filha — پسر / دختر (فرزند)\nfamília — خانواده (واژه‌ای مؤنث → ela)\n\nنکته: در گروهِ مختلط (مرد + زن) از شکل مذکر جمع «eles» استفاده می‌شود.',
      examples: [
        {
          pt: 'Meu pai e minha mãe = Eles',
          fa: 'پدرم و مادرم = آن‌ها (Eles)',
          pron: 'مِئو پای ای مینیا مِین = اِلیس',
          note: 'گروه مختلط (مرد+زن) → مذکر جمع «eles».',
        },
        {
          pt: 'Minha família = Ela',
          fa: 'خانواده‌ام = او/آن (Ela)',
          pron: 'مینیا فامیلیا = اِلا',
          note: '«família» واژه‌ای مؤنث و مفرد است → «ela».',
        },
      ],
    },
  ],
  keyPointsFa: [
    'رسمی از ساعت روز استفاده کن (Bom dia/Boa tarde/Boa noite)؛ غیررسمی: Oi/Olá/E aí.',
    'تشکر بر اساس جنسیتِ گوینده: مرد obrigado، زن obrigada.',
    'برای سن از ter استفاده کن: «tenho … anos» نه «sou … anos».',
    'ملیت‌ها مذکر/مؤنث دارند (brasileiro/brasileira) و با SER می‌آیند.',
    '«a gente» یعنی «nós» غیررسمی، اما فعلش سوم‌شخص مفرد است (a gente é/vai).',
    'در برزیل você به‌جای tu و vocês به‌جای vós رایج است.',
    'SER = ثابت/هویت/ملیت/شغل؛ ESTAR = موقتی/حالت/مکان/کارِ در جریان.',
  ],
  quiz: [
    {
      id: 'course-aula-2-q1',
      type: 'mcq',
      prompt: 'Escolha a saudação formal usada de manhã:',
      promptFa: 'کدام سلامِ رسمیِ صبح است؟',
      options: ['Bom dia!', 'E aí?', 'Tchau!', 'Boa noite!'],
      answer: 'Bom dia!',
      explanationFa: '«Bom dia!» یعنی صبح بخیر و تا حدود ظهر به‌کار می‌رود.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-2-q2',
      type: 'mcq',
      prompt: 'Uma mulher agradece. Ela diz:',
      promptFa: 'یک زن می‌خواهد تشکر کند. کدام درست است؟',
      options: ['Obrigada!', 'Obrigado!', 'De nada!', 'Por favor!'],
      answer: 'Obrigada!',
      explanationFa: 'تشکر به جنسیت گوینده بستگی دارد؛ زن «obrigada» می‌گوید.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-2-q3',
      type: 'mcq',
      prompt: 'Qual é a forma feminina de "francês"?',
      promptFa: 'شکل مؤنث «francês» کدام است؟',
      options: ['francesa', 'francês', 'francêsa', 'francesā'],
      answer: 'francesa',
      explanationFa:
        'پایانهٔ «-ês» مذکر است و مؤنث آن «-esa» می‌شود: francês/francesa.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-2-q4',
      type: 'translate-fa-pt',
      prompt: '«اسم من آنا است. من سی سال دارم.» را به پرتغالی بنویسید.',
      promptFa: 'این جمله را به پرتغالی برزیلی ترجمه کنید.',
      options: [],
      answer: 'Meu nome é Ana. Eu tenho trinta anos.',
      explanationFa:
        'برای سن از ter استفاده می‌شود؛ «sou trinta anos» اشتباه رایج است.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-2-q5',
      type: 'translate-pt-fa',
      prompt: 'Traduza para o persa: "Muito prazer! O prazer é meu!"',
      promptFa: 'این دو عبارت آشنایی را به فارسی ترجمه کنید.',
      options: [],
      answer: 'از آشنایی‌تان خوشوقتم! افتخار از من است!',
      explanationFa: 'این عبارت‌ها هنگام معرفی رسمی به‌کار می‌روند.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-2-q6',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Eu e meu irmão" =',
      promptFa: 'جای مناسب ضمیر: «من و برادرم» با کدام ضمیر جایگزین می‌شود؟',
      options: ['Nós', 'Eles', 'Vocês', 'Eu'],
      answer: 'Nós',
      explanationFa: '«من و …» همیشه اول‌شخص جمع (nós) می‌شود.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q7',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Minha tia e minha avó" =',
      promptFa:
        '«عمه‌ام و مادربزرگم» (دو زن، سوم‌شخص) با کدام ضمیر جایگزین می‌شود؟',
      options: ['Elas', 'Eles', 'Nós', 'Ela'],
      answer: 'Elas',
      explanationFa:
        'دو زن که درباره‌شان حرف می‌زنیم → سوم‌شخص جمع مؤنث «elas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q8',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "João e Maria" =',
      promptFa: '«ژوائو و ماریا» (یک مرد و یک زن) با کدام ضمیر جایگزین می‌شود؟',
      options: ['Eles', 'Elas', 'Nós', 'Vocês'],
      answer: 'Eles',
      explanationFa:
        'وقتی گروه مختلط (مرد+زن) باشد از شکل مذکر جمع «eles» استفاده می‌شود.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q9',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Minha irmã" =',
      promptFa: '«خواهرم» (یک زن) با کدام ضمیر جایگزین می‌شود؟',
      options: ['Ela', 'Ele', 'Elas', 'Você'],
      answer: 'Ela',
      explanationFa:
        'یک زن که درباره‌اش حرف می‌زنیم → سوم‌شخص مفرد مؤنث «ela».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q10',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Seus filhos" =',
      promptFa:
        '«فرزندانِ او/شما» (دوم‌شخص جمع، افرادی که خطاب می‌کنیم) با کدام ضمیر؟',
      options: ['Vocês', 'Nós', 'Eu', 'Ela'],
      answer: 'Vocês',
      explanationFa:
        '«seus filhos» به مخاطبانی که با آن‌ها حرف می‌زنیم برمی‌گردد → «vocês».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q11',
      type: 'fill-blank',
      prompt: '____ gosto de estudar.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل gosto اول‌شخص مفرد است).',
      options: [],
      answer: 'Eu',
      explanationFa: 'پایانهٔ «-o» در gosto نشانهٔ اول‌شخص مفرد است → Eu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q12',
      type: 'fill-blank',
      prompt: '____ foram ao mercado.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل foram سوم‌شخص جمع است).',
      options: [],
      answer: 'Eles',
      explanationFa:
        '«foram» سوم‌شخص جمع است؛ «Eles» (یا Elas/Vocês) درست است.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q13',
      type: 'fill-blank',
      prompt: '____ vamos jogar bola.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل vamos اول‌شخص جمع است).',
      options: [],
      answer: 'Nós',
      explanationFa: '«vamos» اول‌شخص جمع است → Nós.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q14',
      type: 'fill-blank',
      prompt: '____ tenho cabelo castanho.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل tenho اول‌شخص مفرد است).',
      options: [],
      answer: 'Eu',
      explanationFa: '«tenho» اول‌شخص مفرد فعل ter است → Eu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q15',
      type: 'fill-blank',
      prompt: '____ gostam muito de ouvir música.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل gostam سوم‌شخص جمع است).',
      options: [],
      answer: 'Eles',
      explanationFa: '«gostam» سوم‌شخص جمع است → Eles (یا Elas/Vocês).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q16',
      type: 'fill-blank',
      prompt: '____ falo muito bem português.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل falo اول‌شخص مفرد است).',
      options: [],
      answer: 'Eu',
      explanationFa: '«falo» اول‌شخص مفرد است → Eu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q17',
      type: 'mcq',
      prompt: 'Eu ___ do Brasil.',
      promptFa: 'اصلیت (اهل کجا بودن) ثابت است؛ کدام فعل درست است؟',
      options: ['sou', 'estou', 'é', 'estão'],
      answer: 'sou',
      explanationFa: 'اصل و منشأ ویژگی ثابت است → SER: «Eu sou do Brasil».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q18',
      type: 'mcq',
      prompt: 'Eu ___ no Brasil para trabalhar.',
      promptFa: 'حضور موقت در یک مکان؛ کدام فعل درست است؟',
      options: ['estou', 'sou', 'tenho', 'são'],
      answer: 'estou',
      explanationFa: 'مکان و حضور موقت → ESTAR: «Eu estou no Brasil».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q19',
      type: 'mcq',
      prompt: 'Eu ___ feliz. (SEMPRE)',
      promptFa: 'اگر شادی ویژگیِ همیشگی باشد، کدام فعل؟',
      options: ['sou', 'estou', 'está', 'somos'],
      answer: 'sou',
      explanationFa: 'ویژگی همیشگی → SER: «Eu sou feliz».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q20',
      type: 'mcq',
      prompt: 'Eu ___ feliz. (AGORA)',
      promptFa: 'اگر خوشحالیِ همین لحظه باشد، کدام فعل؟',
      options: ['estou', 'sou', 'é', 'estam'],
      answer: 'estou',
      explanationFa: 'حالِ لحظه‌ای → ESTAR: «Eu estou feliz».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q21',
      type: 'fill-blank',
      prompt: 'Eu ___ resfriada.',
      promptFa: 'سرماخوردگی حالتی موقتی است؛ فعل درست را بگذارید.',
      options: [],
      answer: 'estou',
      explanationFa: 'حالت موقتی بدن → ESTAR: «Eu estou resfriada».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q22',
      type: 'fill-blank',
      prompt: 'Eu ___ estudante. Eu ___ estudando.',
      promptFa: 'اولی نقش/هویت و دومی کارِ در جریان است؛ دو فعل را بگذارید.',
      options: [],
      answer: 'sou / estou',
      explanationFa:
        'هویت → SER (sou estudante)؛ کارِ در جریان → ESTAR (estou estudando).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q23',
      type: 'fill-blank',
      prompt: 'Eu ___ gordinho (SEMPRE) / Eu ___ gordinho (AGORA).',
      promptFa: 'همیشگی در برابر موقتی؛ دو فعل مناسب را بگذارید.',
      options: [],
      answer: 'sou / estou',
      explanationFa: 'همیشگی → SER (sou)؛ تازه/موقتی → ESTAR (estou).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q24',
      type: 'mcq',
      prompt: '________ são médicos. [1 homem + 1 mulher]',
      promptFa: 'یک مرد و یک زن؛ کدام ضمیر؟',
      options: ['Eles', 'Elas', 'Nós', 'Vocês'],
      answer: 'Eles',
      explanationFa: 'گروه مختلط → شکل مذکر جمع «Eles».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q25',
      type: 'fill-blank',
      prompt: '________ é enfermeiro. [= nós, informal]',
      promptFa: 'شکل غیررسمیِ «ما» که فعلش سوم‌شخص مفرد است؛ چه بگذاریم؟',
      options: [],
      answer: 'A gente',
      explanationFa:
        '«a gente» یعنی «ما» غیررسمی و با فعل سوم‌شخص مفرد (é) می‌آید.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q26',
      type: 'mcq',
      prompt: '________ são escritores. [2 homens]',
      promptFa: 'دو مرد؛ کدام ضمیر؟',
      options: ['Eles', 'Elas', 'Vocês', 'Nós'],
      answer: 'Eles',
      explanationFa: 'دو مرد → سوم‌شخص جمع مذکر «Eles».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q27',
      type: 'mcq',
      prompt: '________ são motoristas. [2 mulheres]',
      promptFa: 'دو زن؛ کدام ضمیر؟',
      options: ['Elas', 'Eles', 'Nós', 'Você'],
      answer: 'Elas',
      explanationFa: 'دو زن → سوم‌شخص جمع مؤنث «Elas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q28',
      type: 'mcq',
      prompt: '________ é professor? [a pessoa com quem falamos]',
      promptFa: 'کسی که با او حرف می‌زنیم (دوم‌شخص)؛ کدام ضمیر؟',
      options: ['Você', 'Ele', 'Eu', 'Eles'],
      answer: 'Você',
      explanationFa: 'مخاطبِ مفرد در برزیل → «Você».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q29',
      type: 'fill-blank',
      prompt: 'Complete com SER: A gente ___ espanhola.',
      promptFa: 'با فعل ser کامل کنید (توجه: a gente سوم‌شخص مفرد).',
      options: [],
      answer: 'é',
      explanationFa: '«a gente» با فعل سوم‌شخص مفرد می‌آید → «a gente é».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q30',
      type: 'fill-blank',
      prompt: 'Complete com SER: Nós ___ chineses.',
      promptFa: 'با فعل ser کامل کنید (اول‌شخص جمع).',
      options: [],
      answer: 'somos',
      explanationFa: 'اول‌شخص جمع فعل ser → «somos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q31',
      type: 'fill-blank',
      prompt: 'Complete com SER: Vocês ___ argentinas?',
      promptFa: 'با فعل ser کامل کنید (دوم‌شخص جمع).',
      options: [],
      answer: 'são',
      explanationFa: 'دوم/سوم‌شخص جمع فعل ser → «são».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q32',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Ela não ___ em casa.',
      promptFa: 'با فعل estar کامل کنید (سوم‌شخص مفرد، مکان).',
      options: [],
      answer: 'está',
      explanationFa: 'مکان → ESTAR؛ سوم‌شخص مفرد → «está».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q33',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Nós ___ com fome.',
      promptFa: 'با فعل estar کامل کنید (اول‌شخص جمع، حالت موقتی).',
      options: [],
      answer: 'estamos',
      explanationFa: 'گرسنگی حالتی موقتی است → ESTAR؛ اول‌شخص جمع → «estamos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q34',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Onde ___ minhas roupas?',
      promptFa: 'با فعل estar کامل کنید (سوم‌شخص جمع، مکان).',
      options: [],
      answer: 'estão',
      explanationFa: 'پرسش از مکانِ چند چیز → ESTAR سوم‌شخص جمع → «estão».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q35',
      type: 'mcq',
      prompt: 'SER ou ESTAR? Ele ___ inteligente.',
      promptFa: 'هوش ویژگیِ ثابت است؛ کدام فعل؟',
      options: ['é', 'está', 'sou', 'estão'],
      answer: 'é',
      explanationFa: 'هوش ویژگی ثابت است → SER: «Ele é inteligente».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q36',
      type: 'mcq',
      prompt: 'SER ou ESTAR? João e Maria ___ atrasados.',
      promptFa: 'دیر رسیدن حالتی موقتی است؛ کدام فعل؟',
      options: ['estão', 'são', 'é', 'somos'],
      answer: 'estão',
      explanationFa: 'تأخیر حالتی موقتی است → ESTAR سوم‌شخص جمع → «estão».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q37',
      type: 'mcq',
      prompt: 'SER ou ESTAR? Nós ___ amigos.',
      promptFa: 'دوستی رابطه‌ای پایدار است؛ کدام فعل؟',
      options: ['somos', 'estamos', 'são', 'é'],
      answer: 'somos',
      explanationFa: 'رابطهٔ پایدار → SER اول‌شخص جمع → «somos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q38',
      type: 'mcq',
      prompt: 'SER ou ESTAR? Ele ___ doente.',
      promptFa: 'بیماری در این جمله حالتی موقتی است؛ کدام فعل؟',
      options: ['está', 'é', 'sou', 'estão'],
      answer: 'está',
      explanationFa: 'حالِ موقتیِ سلامتی → ESTAR: «Ele está doente».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q39',
      type: 'fill-blank',
      prompt: 'SER ou ESTAR? Eu ___ brasileiro.',
      promptFa: 'ملیت ثابت است؛ فعل درست را بگذارید.',
      options: [],
      answer: 'sou',
      explanationFa: 'ملیت ثابت است → SER: «Eu sou brasileiro».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q40',
      type: 'fill-blank',
      prompt: 'SER ou ESTAR? A gente ___ aprendendo português.',
      promptFa: 'کارِ در جریان با «a gente»؛ فعل درست را بگذارید.',
      options: [],
      answer: 'está',
      explanationFa:
        'کارِ در جریان → ESTAR؛ «a gente» سوم‌شخص مفرد → «está aprendendo».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q41',
      type: 'translate-fa-pt',
      prompt:
        '«من در سائوپائولو زندگی می‌کنم و به‌عنوان فروشنده کار می‌کنم.» را به پرتغالی بنویسید.',
      promptFa: 'با الگوی معرفی خود ترجمه کنید.',
      options: [],
      answer: 'Eu moro em São Paulo e trabalho como vendedora.',
      explanationFa:
        '«morar em» برای محل زندگی و «trabalhar como» برای شغل به‌کار می‌رود.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-2-q42',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Meu pai e minha mãe" =',
      promptFa: '«پدرم و مادرم» (یک مرد و یک زن) با کدام ضمیر جایگزین می‌شود؟',
      options: ['Eles', 'Elas', 'Nós', 'Ela'],
      answer: 'Eles',
      explanationFa: 'گروه مختلط (مرد+زن) → شکل مذکر جمع «Eles».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q43',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Meus irmãos" =',
      promptFa: '«برادرانم» با کدام ضمیر جایگزین می‌شود؟',
      options: ['Eles', 'Elas', 'Nós', 'Ele'],
      answer: 'Eles',
      explanationFa:
        'گروهی که درباره‌شان حرف می‌زنیم و مذکر/مختلط است → «Eles».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q44',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Meus filhos" =',
      promptFa: '«فرزندانم» با کدام ضمیر جایگزین می‌شود؟',
      options: ['Eles', 'Elas', 'Vocês', 'Nós'],
      answer: 'Eles',
      explanationFa:
        'گروهِ فرزندان (مذکر/مختلط) که درباره‌شان حرف می‌زنیم → «Eles».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q45',
      type: 'mcq',
      prompt: 'Substitua pelo pronome: "Minha família" =',
      promptFa: '«خانواده‌ام» با کدام ضمیر جایگزین می‌شود؟',
      options: ['Ela', 'Eles', 'Nós', 'Elas'],
      answer: 'Ela',
      explanationFa:
        '«família» واژه‌ای مؤنث و مفرد است → سوم‌شخص مفرد مؤنث «Ela».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q46',
      type: 'fill-blank',
      prompt: '____ vai ao cinema hoje.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل vai سوم‌شخص مفرد است).',
      options: [],
      answer: 'Ele',
      explanationFa: '«vai» سوم‌شخص مفرد است → Ele (یا Ela/Você/A gente).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q47',
      type: 'fill-blank',
      prompt: '____ queremos morar aqui nesta cidade.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل queremos اول‌شخص جمع است).',
      options: [],
      answer: 'Nós',
      explanationFa: '«queremos» اول‌شخص جمع فعل querer است → Nós.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q48',
      type: 'fill-blank',
      prompt: '____ quer morar aqui nesta cidade.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل quer سوم‌شخص مفرد است).',
      options: [],
      answer: 'Ele',
      explanationFa: '«quer» سوم‌شخص مفرد است → Ele (یا Ela/Você/A gente).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q49',
      type: 'fill-blank',
      prompt: '____ trabalham muito.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل trabalham سوم‌شخص جمع است).',
      options: [],
      answer: 'Eles',
      explanationFa: '«trabalham» سوم‌شخص جمع است → Eles (یا Elas/Vocês).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q50',
      type: 'fill-blank',
      prompt: 'Eu ___ aprendendo português.',
      promptFa: 'کارِ در جریان است؛ فعل درست را بگذارید.',
      options: [],
      answer: 'estou',
      explanationFa:
        'کارِ در جریان (estar + gerúndio) → ESTAR اول‌شخص مفرد → «estou».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q51',
      type: 'fill-blank',
      prompt: 'Eu ___ aqui faz 40 minutos.',
      promptFa: 'حضور موقت در یک مکان؛ فعل درست را بگذارید.',
      options: [],
      answer: 'estou',
      explanationFa:
        'حضور موقت در مکان → ESTAR: «Eu estou aqui faz 40 minutos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q52',
      type: 'fill-blank',
      prompt: 'Complete com o pronome: ________ sou advogado.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل sou اول‌شخص مفرد است).',
      options: [],
      answer: 'Eu',
      explanationFa: '«sou» اول‌شخص مفرد فعل ser است → Eu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q53',
      type: 'mcq',
      prompt: 'Complete com o pronome: ________ é secretária.',
      promptFa: 'منشی (یک زن، سوم‌شخص مفرد)؛ کدام ضمیر؟',
      options: ['Ela', 'Ele', 'Você', 'Elas'],
      answer: 'Ela',
      explanationFa: '«secretária» مؤنث و فعل «é» سوم‌شخص مفرد است → Ela.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q54',
      type: 'mcq',
      prompt: 'Complete com o pronome: ________ é engenheira.',
      promptFa: 'مهندس (یک زن، سوم‌شخص مفرد)؛ کدام ضمیر؟',
      options: ['Ela', 'Ele', 'Nós', 'Vocês'],
      answer: 'Ela',
      explanationFa: '«engenheira» مؤنث و فعل «é» سوم‌شخص مفرد است → Ela.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q55',
      type: 'fill-blank',
      prompt: 'Complete com o pronome: ________ somos advogados.',
      promptFa: 'ضمیر مناسب را بگذارید (فعل somos اول‌شخص جمع است).',
      options: [],
      answer: 'Nós',
      explanationFa: '«somos» اول‌شخص جمع فعل ser است → Nós.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q56',
      type: 'mcq',
      prompt: 'Complete com o pronome: ________ é dentista. [1 homem]',
      promptFa: 'دندان‌پزشک (یک مرد، سوم‌شخص مفرد)؛ کدام ضمیر؟',
      options: ['Ele', 'Ela', 'Você', 'Eles'],
      answer: 'Ele',
      explanationFa:
        'یک مرد که درباره‌اش حرف می‌زنیم → سوم‌شخص مفرد مذکر «Ele».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q57',
      type: 'mcq',
      prompt: 'Complete com o pronome: ________ é motorista. [1 mulher]',
      promptFa: 'راننده (یک زن، سوم‌شخص مفرد)؛ کدام ضمیر؟',
      options: ['Ela', 'Ele', 'Nós', 'Elas'],
      answer: 'Ela',
      explanationFa:
        'یک زن که درباره‌اش حرف می‌زنیم → سوم‌شخص مفرد مؤنث «Ela».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q58',
      type: 'mcq',
      prompt:
        'Complete com o pronome: ________ são dentistas? [as pessoas com quem falamos]',
      promptFa: 'کسانی که با آن‌ها حرف می‌زنیم (دوم‌شخص جمع)؛ کدام ضمیر؟',
      options: ['Vocês', 'Eles', 'Nós', 'Elas'],
      answer: 'Vocês',
      explanationFa: 'مخاطبانِ جمع در برزیل → «Vocês».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q59',
      type: 'fill-blank',
      prompt: 'Complete com SER: Eles ___ professores.',
      promptFa: 'با فعل ser کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'são',
      explanationFa: 'سوم‌شخص جمع فعل ser → «são».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q60',
      type: 'fill-blank',
      prompt: 'Complete com SER: Eu ___ dentista.',
      promptFa: 'با فعل ser کامل کنید (اول‌شخص مفرد).',
      options: [],
      answer: 'sou',
      explanationFa: 'اول‌شخص مفرد فعل ser → «sou».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q61',
      type: 'fill-blank',
      prompt: 'Complete com SER: Elas ___ advogadas.',
      promptFa: 'با فعل ser کامل کنید (سوم‌شخص جمع مؤنث).',
      options: [],
      answer: 'são',
      explanationFa: 'سوم‌شخص جمع فعل ser → «são».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q62',
      type: 'fill-blank',
      prompt: 'Complete com SER: Você ___ escritora?',
      promptFa: 'با فعل ser کامل کنید (دوم‌شخص مفرد، você).',
      options: [],
      answer: 'é',
      explanationFa: '«você» با فعل سوم‌شخص مفرد می‌آید → «é».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q63',
      type: 'fill-blank',
      prompt: 'Complete com SER: Ele ___ médico.',
      promptFa: 'با فعل ser کامل کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'é',
      explanationFa: 'سوم‌شخص مفرد فعل ser → «é».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q64',
      type: 'fill-blank',
      prompt: 'Complete com SER: Ela ___ francesa.',
      promptFa: 'با فعل ser کامل کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'é',
      explanationFa: 'سوم‌شخص مفرد فعل ser → «é».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q65',
      type: 'fill-blank',
      prompt: 'Complete com SER: Nós ___ japoneses.',
      promptFa: 'با فعل ser کامل کنید (اول‌شخص جمع).',
      options: [],
      answer: 'somos',
      explanationFa: 'اول‌شخص جمع فعل ser → «somos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q66',
      type: 'fill-blank',
      prompt: 'Complete com SER: Eu ___ motorista.',
      promptFa: 'با فعل ser کامل کنید (اول‌شخص مفرد).',
      options: [],
      answer: 'sou',
      explanationFa: 'اول‌شخص مفرد فعل ser → «sou».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q67',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Eu ___ no Brasil.',
      promptFa: 'با فعل estar کامل کنید (اول‌شخص مفرد، مکان).',
      options: [],
      answer: 'estou',
      explanationFa: 'مکان → ESTAR؛ اول‌شخص مفرد → «estou».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q68',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: A comida ___ boa, mas ___ um pouco fria.',
      promptFa: 'با فعل estar کامل کنید (هر دو جای خالی، سوم‌شخص مفرد).',
      options: [],
      answer: 'está / está',
      explanationFa: 'حالتِ لحظه‌ای غذا → ESTAR سوم‌شخص مفرد → «está / está».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q69',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Elas ___ felizes.',
      promptFa: 'با فعل estar کامل کنید (سوم‌شخص جمع، حالت موقتی).',
      options: [],
      answer: 'estão',
      explanationFa: 'خوشحالیِ لحظه‌ای → ESTAR؛ سوم‌شخص جمع → «estão».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q70',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Hoje ele ___ de mau humor.',
      promptFa: 'با فعل estar کامل کنید (سوم‌شخص مفرد، حالت موقتی).',
      options: [],
      answer: 'está',
      explanationFa:
        'بدخلقیِ امروز حالتی موقتی است → ESTAR سوم‌شخص مفرد → «está».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q71',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Nossa! Hoje ___ muito calor.',
      promptFa: 'با فعل estar کامل کنید (سوم‌شخص مفرد، وضعیت هوا).',
      options: [],
      answer: 'está',
      explanationFa:
        'گرمای امروز وضعیتی موقتی است → ESTAR سوم‌شخص مفرد → «está».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q72',
      type: 'fill-blank',
      prompt: 'Complete com ESTAR: Você ___ bem?',
      promptFa: 'با فعل estar کامل کنید (دوم‌شخص مفرد، حال احوال).',
      options: [],
      answer: 'está',
      explanationFa:
        'پرسش از حالِ لحظه‌ای → ESTAR؛ «você» سوم‌شخص مفرد → «está».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q73',
      type: 'fill-blank',
      prompt:
        'Complete com ESTAR: Eles querem fazer uma festa, mas nós ___ trabalhando agora.',
      promptFa: 'با فعل estar کامل کنید (اول‌شخص جمع، کارِ در جریان).',
      options: [],
      answer: 'estamos',
      explanationFa:
        'کارِ در جریان → ESTAR؛ اول‌شخص جمع → «estamos trabalhando».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q74',
      type: 'mcq',
      prompt: 'SER ou ESTAR? Eu ___ com fome.',
      promptFa: 'گرسنگی حالتی موقتی است؛ کدام فعل؟',
      options: ['estou', 'sou', 'é', 'somos'],
      answer: 'estou',
      explanationFa: 'گرسنگی حالتی موقتی است → ESTAR: «Eu estou com fome».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q75',
      type: 'mcq',
      prompt: 'SER ou ESTAR? Vocês ___ inteligentes.',
      promptFa: 'هوش ویژگیِ ثابت است؛ کدام فعل؟',
      options: ['são', 'estão', 'somos', 'é'],
      answer: 'são',
      explanationFa: 'هوش ویژگی ثابت است → SER؛ دوم‌شخص جمع → «são».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q76',
      type: 'mcq',
      prompt: 'SER ou ESTAR? Nós ___ bem.',
      promptFa: '«خوب بودن» در این جمله حالِ لحظه‌ای است؛ کدام فعل؟',
      options: ['estamos', 'somos', 'são', 'está'],
      answer: 'estamos',
      explanationFa:
        'حالِ لحظه‌ای (خوب بودن) → ESTAR اول‌شخص جمع → «estamos bem».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-2-q77',
      type: 'mcq',
      prompt: 'SER ou ESTAR? Elas ___ simpáticas.',
      promptFa: 'خوش‌برخوردی ویژگیِ ثابت است؛ کدام فعل؟',
      options: ['são', 'estão', 'somos', 'é'],
      answer: 'são',
      explanationFa:
        'خوش‌برخوردی ویژگی ثابت شخصیت است → SER؛ سوم‌شخص جمع → «são».',
      cefr: 'A1',
      skill: 'grammar',
    },
  ],
  estimatedMinutes: 40,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 2 (کامل).',
};
