import type { CourseLesson } from '@/domain/content/schema';

export const aula14: CourseLesson = {
  id: 'course-aula-14',
  order: 14,
  aula: 'Aula 14',
  titleFa: 'حروف اضافه (Preposições)',
  titlePt: 'Preposições',
  cefr: 'A2',
  summaryFa:
    'در این درس حروف اضافهٔ پرتغالی برزیلی را کامل یاد می‌گیرید: تعریف حرف اضافه و نقش آن در پیوند دادن دو کلمه؛ فهرست کامل روابطی که حروف اضافه می‌سازند (مکان، زمان، حالت، علت، موضوع، هدف، ابزار، همراهی، وسیله، جنس/ماده، مالکیت، تقابل)؛ کاربردهای دقیق حرف اضافهٔ DE (اصلیت، مالکیت، جنس) همراه با قاعدهٔ شهرها/ایالت‌ها و کشورها؛ حرف اضافهٔ PARA و تفاوت گفتاری pra/pro؛ حرف اضافهٔ EM برای مکان و زمان؛ حرف اضافهٔ POR؛ حرف اضافهٔ A و پدیدهٔ crase؛ فرق «ترکیب» (combinação) و «ادغام/انقباض» (contração)؛ و در پایان دسته‌بندی حروف اضافه به «اصلی» (essenciais) و «عارضی» (acidentais) با تمرین‌های فراوان.',
  objectivesFa: [
    'تعریف حرف اضافه را بدانید و نقش پیونددهندهٔ آن را در جمله تشخیص دهید.',
    'انواع روابط معنایی که حروف اضافه می‌سازند را بشناسید (مکان، زمان، علت و …).',
    'سه کاربرد اصلی DE (اصلیت، مالکیت، جنس) و قاعدهٔ شهر/ایالت در برابر کشور را به‌کار ببرید.',
    'حرف اضافهٔ PARA و شکل‌های گفتاری pra/pro را درست استفاده کنید.',
    'حرف اضافهٔ EM را برای مکان و زمان و همراه فعل estar به‌کار ببرید.',
    'حرف اضافه‌های POR و A و پدیدهٔ crase را بشناسید.',
    'فرق combinação و contração را بدانید و ادغام‌های do/no/pela/ao و … را درست بسازید.',
    'حروف اضافهٔ اصلی و عارضی را از هم تشخیص دهید.',
  ],
  sections: [
    {
      headingFa: '۱. حرف اضافه چیست؟ (Preposição)',
      bodyFa:
        'حرف اضافه (preposição) کلمه‌ای است بدون تغییر (invariável) که دو جزء جمله را به هم مرتبط می‌کند، به‌طوری‌که یکی معنای دیگری را کامل یا توضیح می‌دهد. به بیان ساده، هر کلمه‌ای که دو کلمهٔ دیگر را به هم می‌بندد و میان آن‌ها رابطهٔ معنایی و وابستگی برقرار می‌کند، حرف اضافه است.\n\nبه جملهٔ «Estou com medo» نگاه کنید: معنای فعل «estou» با کلمهٔ «medo» کامل می‌شود و رابطهٔ بین این دو را کلمهٔ «com» می‌سازد که یک حرف اضافه است.',
      examples: [
        {
          pt: 'Estou com medo.',
          fa: 'من می‌ترسم (با ترس هستم).',
          pron: 'اِستُ کُن مِدو',
          note: '«com» رابطهٔ بین estou و medo را می‌سازد.',
        },
        {
          pt: 'Ele ficou sem dinheiro.',
          fa: 'او بی‌پول ماند.',
          pron: 'اِلی فیکُ سِین جینیِرو',
          note: '«sem» یعنی بدونِ.',
        },
        {
          pt: 'Mariana foi até a sala de reuniões.',
          fa: 'ماریانا تا اتاق جلسات رفت.',
          pron: 'ماریانا فُی آته آ سالا جی رِئونیُئِس',
          note: '«até» یعنی تا.',
        },
        {
          pt: 'Os meninos continuaram contra a ideia de viajar.',
          fa: 'پسرها همچنان مخالف ایدهٔ سفر بودند.',
          pron: 'اوس مِنینوس کُنتینوارام کُنترا آ ایدِیا جی ویاژار',
          note: '«contra» یعنی برخلاف/مخالفِ.',
        },
        {
          pt: 'Alimentar-se bem ajuda a crescer com saúde.',
          fa: 'خوب غذا خوردن به رشد سالم کمک می‌کند.',
          pron: 'آلیمِنتار-سی بِین آژودا آ کرِسِر کُن سائوجی',
        },
        {
          pt: 'Casa de Luiz = Casa do Luiz.',
          fa: 'خانهٔ لوئیز.',
          pron: 'کازا جی لوئیس = کازا دو لوئیس',
          note: 'de + o = do هنگام آمدنِ حرف تعریف.',
        },
        {
          pt: 'Chegou com ela.',
          fa: 'با او رسید.',
          pron: 'شِگُ کُن اِلا',
        },
      ],
    },
    {
      headingFa: '۲. انواع روابطی که حروف اضافه می‌سازند',
      bodyFa:
        'یک حرف اضافه بسته به بافت جمله می‌تواند رابطه‌های معنایی گوناگونی بسازد. مهم‌ترین این رابطه‌ها:\n\n• مکان (Lugar)\n• زمان (Tempo)\n• حالت/روش (Modo)\n• علت (Causa)\n• موضوع (Assunto)\n• هدف/غایت (Fim ou finalidade)\n• ابزار (Instrumento)\n• همراهی (Companhia)\n• وسیله (Meio)\n• جنس/ماده (Matéria)\n• مالکیت (Posse)\n• تقابل/مخالفت (Oposição)',
      examples: [
        {
          pt: 'de Lugar — Estou em casa.',
          fa: 'مکان — من در خانه هستم.',
          pron: 'اِستُ اِین کازا',
        },
        {
          pt: 'de Tempo — Eu viajei durante as férias.',
          fa: 'زمان — من در طول تعطیلات سفر کردم.',
          pron: 'اِئو ویاژِی دورانتی آس فِریاس',
        },
        {
          pt: 'de Modo — Vamos escolher por sorteio.',
          fa: 'حالت — با قرعه‌کشی انتخاب می‌کنیم.',
          pron: 'واموس اِسکولِر پور سُرتِیو',
        },
        {
          pt: 'de Causa — Estou tremendo de frio.',
          fa: 'علت — از سرما می‌لرزم.',
          pron: 'اِستُ ترِمِندو جی فریو',
        },
        {
          pt: 'de Assunto — Não gosto de falar sobre política.',
          fa: 'موضوع — دوست ندارم دربارهٔ سیاست حرف بزنم.',
          pron: 'نائو گُستو جی فالار سُبری پُلیتیکا',
        },
        {
          pt: 'de Fim/finalidade — Eu vim para ficar.',
          fa: 'هدف — من آمدم که بمانم.',
          pron: 'اِئو وین پارا فیکار',
        },
        {
          pt: 'de Instrumento — Paulo feriu-se com a faca.',
          fa: 'ابزار — پائولو با چاقو زخمی شد.',
          pron: 'پائولو فِریو-سی کُن آ فاکا',
        },
        {
          pt: 'de Companhia — Hoje vou sair com meus amigos.',
          fa: 'همراهی — امروز با دوستانم بیرون می‌روم.',
          pron: 'اُژی وُ سائیر کُن مِئوس آمیگوس',
        },
        {
          pt: 'de Meio — Voltarei a andar a cavalo.',
          fa: 'وسیله — دوباره سوار اسب می‌شوم (با اسب راه می‌روم).',
          pron: 'وُلتارِی آ آندار آ کاوالو',
        },
        {
          pt: 'de Matéria — Devolva-me meu anel de prata.',
          fa: 'جنس/ماده — انگشتر نقره‌ام را به من برگردان.',
          pron: 'دِوُلوا-می مِئو آنِل جی پراتا',
        },
        {
          pt: 'de Posse — Este é o carro de João = do João.',
          fa: 'مالکیت — این ماشین ژوائو است.',
          pron: 'اِستی اِ او کارو جی ژوائو',
        },
        {
          pt: 'de Oposição — O Flamengo jogou contra o Fluminense.',
          fa: 'تقابل — فلامِنگو مقابل فلومینِنسه بازی کرد.',
          pron: 'او فلامِنگو ژوگُ کُنترا او فلومینِنسی',
        },
      ],
    },
    {
      headingFa: '۳. حرف اضافهٔ DE',
      bodyFa:
        'حرف اضافهٔ DE شکل‌های گوناگون و کاربردهای متعددی دارد. سه کاربرد اصلی آن عبارت‌اند از تعیین اصلیت (origem)، مالکیت (posse) و جنس/مادهٔ یک شیء (material). در ادامه هر سه کاربرد را جداگانه می‌بینیم.',
      examples: [],
    },
    {
      headingFa: '۴. DE برای اصلیت (شهرها و ایالت‌ها)',
      bodyFa:
        'برای پرسش و پاسخ دربارهٔ اهل کجا بودن از DE استفاده می‌کنیم.\n\nقاعدهٔ کلی: شهرها و ایالت‌ها = de (بدون حرف تعریف)\nمثال: de São Paulo, de Minas Gerais, de Paris\n\nاستثناها:\n• o Rio de Janeiro → Ele é do Rio de Janeiro (de + o = do)\n• a Bahia → Ele é da Bahia (de + a = da)',
      examples: [
        {
          pt: 'De onde você é?',
          fa: 'اهل کجا هستی؟',
          pron: 'جی اُنجی وُسه اِ؟',
        },
        {
          pt: 'Eu sou do Rio de Janeiro.',
          fa: 'من اهل ریو دو ژانیرو هستم.',
          pron: 'اِئو سُ دو هیو جی ژانِیرو',
          note: 'استثنا: de + o = do.',
        },
        {
          pt: 'Ele é dos Estados Unidos.',
          fa: 'او اهل ایالات متحده است.',
          pron: 'اِلی اِ دوس اِستادوس اونیدوس',
          note: 'de + os = dos.',
        },
        {
          pt: 'Nós somos de Porto Alegre.',
          fa: 'ما اهل پورتو آلگره هستیم.',
          pron: 'نُس سُموس جی پُرتو آلِگری',
          note: 'شهر معمولی → فقط de.',
        },
      ],
    },
    {
      headingFa: '۵. DE برای اصلیت (کشورها) و برای مالکیت',
      bodyFa:
        'قاعدهٔ کلی کشورها = do / da / dos / das (چون بیشتر کشورها با حرف تعریف می‌آیند و DE با آن ادغام می‌شود):\n\nde + o = do → do Brasil, do Japão, do Marrocos, do Haiti\nde + os = dos → dos Estados Unidos\nde + a = da → da Alemanha, da Argentina, da França, da Síria\nde + as = das → das Filipinas\n\nاستثناها (بدون حرف تعریف): de Portugal, de Cuba\n\nDE برای مالکیت (posse): نشان می‌دهد چیزی به چه کسی تعلق دارد. توجه کنید که DE بسته به مذکر/مؤنث و مفرد/جمعِ کلمهٔ بعد از خودش تغییر می‌کند (do/da/dos/das).',
      examples: [
        {
          pt: 'O carro de meu pai é azul. = O carro do meu pai é azul.',
          fa: 'ماشین پدرم آبی است.',
          pron: 'او کارو جی مِئو پای اِ آزول',
          note: 'مالکیت؛ هر دو شکل درست است.',
        },
        {
          pt: 'As bolsas das mulheres são muito bonitas.',
          fa: 'کیف‌های زن‌ها خیلی زیبا هستند.',
          pron: 'آس بُلساس داس مولِرِس سائو مویتو بونیتاس',
          note: 'de + as = das (جمع مؤنث).',
        },
        {
          pt: 'O cachorro do menino late o dia todo.',
          fa: 'سگِ پسربچه تمام روز پارس می‌کند.',
          pron: 'او کاشُرو دو مِنینو لاتی او جیا تُدو',
          note: 'de + o = do (مفرد مذکر).',
        },
      ],
    },
    {
      headingFa: '۶. DE برای جنس/ماده (Material)',
      bodyFa:
        'وقتی می‌خواهیم بگوییم چیزی از چه جنسی ساخته شده است، از DE استفاده می‌کنیم. نکتهٔ مهم: هنگام صحبت دربارهٔ جنس/ماده، حرف اضافهٔ DE هیچ تغییری نمی‌کند و همیشه به شکل ساده «de» می‌ماند (چون معمولاً حرف تعریف بعد از آن نمی‌آید).',
      examples: [
        {
          pt: 'Esta casa é de madeira.',
          fa: 'این خانه از چوب است.',
          pron: 'اِستا کازا اِ جی مادِیرا',
        },
        {
          pt: 'O copo é de plástico.',
          fa: 'لیوان از پلاستیک است.',
          pron: 'او کُپو اِ جی پلاستیکو',
        },
        {
          pt: 'Você tem uma blusa de algodão?',
          fa: 'بلوز نخی (از پنبه) داری؟',
          pron: 'وُسه تِین اوما بلوزا جی آلگُدائو؟',
          note: 'برای جنس/ماده، DE ثابت می‌ماند.',
        },
      ],
    },
    {
      headingFa: '۷. حرف اضافهٔ PARA',
      bodyFa:
        'حرف اضافهٔ PARA سه کاربرد اصلی دارد:\n\n• حرکت به سمت یک مقصد (movimento em direção a um destino)\n• هدفی که می‌خواهید به آن برسید (um objetivo)\n• نشان‌دادنِ کسی که چیزی را دریافت می‌کند (a pessoa que recebe algo)',
      examples: [
        {
          pt: 'Eu vou para a escola.',
          fa: 'من به مدرسه می‌روم.',
          pron: 'اِئو وُ پارا آ اِسکولا',
          note: 'حرکت به سمت مقصد.',
        },
        {
          pt: 'Ele trabalha muito para viajar.',
          fa: 'او خیلی کار می‌کند تا سفر کند.',
          pron: 'اِلی ترابایا مویتو پارا ویاژار',
          note: 'هدف.',
        },
        {
          pt: 'Eu comprei um presente para você.',
          fa: 'من برای تو یک هدیه خریدم.',
          pron: 'اِئو کُمپرِی اون پرِزِنتی پارا وُسه',
          note: 'گیرندهٔ چیزی.',
        },
      ],
    },
    {
      headingFa: '۸. PRA و PRO در گفتار در برابر PARA',
      bodyFa:
        'در پرتغالی برزیل، کلمهٔ «para» در گفتار معمولاً «pra» تلفظ می‌شود:\n\npra = para  یا  para a\npro = para  یا  para o\n\nنکتهٔ مهم: PRA و PRO فقط باید در گفتار (fala) به‌کار روند و در نوشتار رسمی (escrita formal) باید شکل کامل «para / para a / para o» نوشته شود.',
      examples: [
        {
          pt: 'Ele vai pra Portugal. (para)',
          fa: 'او به پرتغال می‌رود.',
          pron: 'اِلی وای پرا پُرتوگال',
          note: 'pra = para (پرتغال بدون حرف تعریف).',
        },
        {
          pt: 'Eu vou pra Colômbia. (para a)',
          fa: 'من به کلمبیا می‌روم.',
          pron: 'اِئو وُ پرا کُلُمبیا',
          note: 'pra = para a.',
        },
        {
          pt: 'Vou pro Rio. (para o)',
          fa: 'به ریو می‌روم.',
          pron: 'وُ پرو هیو',
          note: 'pro = para o.',
        },
        {
          pt: 'Ela vai pro Ceará. (para o)',
          fa: 'او به سئارا می‌رود.',
          pron: 'اِلا وای پرو سِئارا',
          note: 'pro = para o.',
        },
        {
          pt: 'Compramos esse livro pro João. (para / para o)',
          fa: 'این کتاب را برای ژوائو خریدیم.',
          pron: 'کُمپراموس اِسی لیورو پرو ژوائو',
          note: 'pro = para o.',
        },
      ],
    },
    {
      headingFa: '۹. حرف اضافهٔ EM',
      bodyFa:
        'حرف اضافهٔ EM شکل‌های گوناگون و کاربردهای متعددی دارد. کاربردهای اصلی آن برای صحبت دربارهٔ مکان‌ها، زمان و موقعیت‌ها است. این حرف اضافه معمولاً همراه فعل estar به‌کار می‌رود، چون خیلی برای گفتنِ «کجا هستیم» استفاده می‌شود.',
      examples: [
        {
          pt: 'Moro em São Paulo.',
          fa: 'در سائوپائولو زندگی می‌کنم.',
          pron: 'مُرو اِین سائو پائولو',
          note: 'شهر معمولی → em.',
        },
        {
          pt: 'Moro no Rio de Janeiro.',
          fa: 'در ریو دو ژانیرو زندگی می‌کنم.',
          pron: 'مُرو نو هیو جی ژانِیرو',
          note: 'استثنا: em + o = no.',
        },
        {
          pt: 'Chegarei em cinco minutos.',
          fa: 'تا پنج دقیقهٔ دیگر می‌رسم.',
          pron: 'شِگارِی اِین سینکو مینوتوس',
          note: 'کاربرد زمانی.',
        },
        {
          pt: 'A loja fica no centro.',
          fa: 'مغازه در مرکز شهر است.',
          pron: 'آ لُژا فیکا نو سِنترو',
          note: 'em + o = no.',
        },
      ],
    },
    {
      headingFa: '۱۰. قاعدهٔ EM برای شهر/ایالت و کشور',
      bodyFa:
        'قاعدهٔ کلی شهرها و ایالت‌ها = em (بدون حرف تعریف)\nمثال: em São Paulo, em Minas Gerais, em Paris\n\nاستثناها:\n• o Rio de Janeiro → Ele mora no Rio de Janeiro (em + o = no)\n• a Bahia → Ele mora na Bahia (em + a = na)\n\nقاعدهٔ کلی کشورها = no / na / nos / nas:\nem + o = no → no Brasil, no Japão, no Marrocos, no Haiti\nem + os = nos → nos Estados Unidos\nem + a = na → na Alemanha, na Argentina, na França, na Síria\nem + as = nas → nas Filipinas\n\nاستثناها (بدون حرف تعریف): em Portugal, em Cuba',
      examples: [
        {
          pt: 'Ele mora no Rio de Janeiro.',
          fa: 'او در ریو دو ژانیرو زندگی می‌کند.',
          pron: 'اِلی مُرا نو هیو جی ژانِیرو',
          note: 'em + o = no (استثنا).',
        },
        {
          pt: 'Ele mora na Bahia.',
          fa: 'او در باهیا زندگی می‌کند.',
          pron: 'اِلی مُرا نا باایا',
          note: 'em + a = na (استثنا).',
        },
        {
          pt: 'Moro no Brasil, mas ela mora em Portugal.',
          fa: 'من در برزیل زندگی می‌کنم، اما او در پرتغال زندگی می‌کند.',
          pron: 'مُرو نو برازیل، ماس اِلا مُرا اِین پُرتوگال',
          note: 'کشورها با no/na؛ اما Portugal استثناست.',
        },
        {
          pt: 'Elas moram nos Estados Unidos.',
          fa: 'آن‌ها در ایالات متحده زندگی می‌کنند.',
          pron: 'اِلاس مُرام نوس اِستادوس اونیدوس',
          note: 'em + os = nos.',
        },
      ],
    },
    {
      headingFa: '۱۱. حرف اضافهٔ POR',
      bodyFa:
        'حرف اضافهٔ POR را برای بیان زمان (tempo)، قیمت (preço)، علت (causa)، مکانی که از آن عبور می‌کنیم (lugar por onde se passa) و موارد دیگر به‌کار می‌بریم. POR هم با حرف تعریف ادغام می‌شود: por + o = pelo, por + a = pela, por + os = pelos, por + as = pelas.',
      examples: [
        {
          pt: 'Joana me esperou por duas horas ontem.',
          fa: 'ژوآنا دیروز دو ساعت منتظر من ماند.',
          pron: 'ژوانا می اِسپِرُ پور دوآس اُراس اُنتِم',
          note: 'زمان.',
        },
        {
          pt: 'Comprei essa blusa por 30,00 reais.',
          fa: 'این بلوز را ۳۰ رئال خریدم.',
          pron: 'کُمپرِی اِسا بلوزا پور ترینتا هِئایس',
          note: 'قیمت.',
        },
        {
          pt: 'Ele não veio por medo da chuva.',
          fa: 'او از ترسِ باران نیامد.',
          pron: 'اِلی نائو وِیو پور مِدو دا شووا',
          note: 'علت.',
        },
        {
          pt: 'Nós viajamos por muitas cidades da Europa.',
          fa: 'ما از شهرهای زیادی در اروپا گذشتیم.',
          pron: 'نُس ویاژاموس پور مویتاس سیدادِس دا اِئوروپا',
          note: 'مکانی که از آن عبور می‌کنیم.',
        },
        {
          pt: 'Nós vamos passar pela Inglaterra mas não vamos passar pela França.',
          fa: 'ما از انگلستان عبور می‌کنیم اما از فرانسه عبور نمی‌کنیم.',
          pron: 'نُس واموس پاسار پِلا اینگلاتِرا ماس نائو واموس پاسار پِلا فرانسا',
          note: 'por + a = pela.',
        },
        {
          pt: 'Você precisa passar pelo túnel para chegar ao centro.',
          fa: 'باید از تونل عبور کنی تا به مرکز شهر برسی.',
          pron: 'وُسه پرِسیزا پاسار پِلو تونِل پارا شِگار آئو سِنترو',
          note: 'por + o = pelo.',
        },
        {
          pt: 'Eu faço qualquer coisa por/ pelos meus amigos.',
          fa: 'من برای دوستانم هر کاری می‌کنم.',
          pron: 'اِئو فاسو کوالکِر کُیزا پور/ پِلوس مِئوس آمیگوس',
          note: 'por + os = pelos.',
        },
        {
          pt: 'Ela sempre sobe o edifício pelas escadas.',
          fa: 'او همیشه از پله‌ها بالای ساختمان می‌رود.',
          pron: 'اِلا سِمپری سُبی او اِدیفیسیو پِلاس اِسکاداس',
          note: 'por + as = pelas.',
        },
      ],
    },
    {
      headingFa: '۱۲. حرف اضافهٔ A و پدیدهٔ Crase',
      bodyFa:
        'حرف اضافهٔ A از جمله برای بیان زمان (tempo)، وسیله (meio) و مقصد (destino) به‌کار می‌رود. همچنین برای ساختنِ crase استفاده می‌شود.\n\nCrase یعنی ادغام حرف اضافهٔ «a» با حرف تعریف مؤنث «a»، که با علامت accent grave نوشته می‌شود: a + a = à (و a + as = às). Crase معمولاً پیش از اسم‌های مؤنث می‌آید (à escola, à praia) و در ساعت‌ها (às 16 horas).',
      examples: [
        {
          pt: 'Chegarei daqui a uma hora.',
          fa: 'یک ساعت دیگر می‌رسم.',
          pron: 'شِگارِی داکی آ اوما اُرا',
          note: 'زمان.',
        },
        {
          pt: 'Ele gosta de andar a pé.',
          fa: 'او دوست دارد پیاده راه برود.',
          pron: 'اِلی گُستا جی آندار آ په',
          note: 'وسیله (a pé = پیاده).',
        },
        {
          pt: 'Vou sempre a São Paulo. (destino = para)',
          fa: 'من همیشه به سائوپائولو می‌روم.',
          pron: 'وُ سِمپری آ سائو پائولو',
          note: 'مقصد؛ شهر بدون حرف تعریف → a (بدون crase).',
        },
        {
          pt: 'Fui ao Rio de Janeiro três vezes. (destino = para o)',
          fa: 'سه بار به ریو دو ژانیرو رفتم.',
          pron: 'فوی آئو هیو جی ژانِیرو ترِس وِزِس',
          note: 'a + o = ao.',
        },
        {
          pt: 'Vou à escola pela manhã.',
          fa: 'صبح‌ها به مدرسه می‌روم.',
          pron: 'وُ آ اِسکولا پِلا مانیا',
          note: 'crase: a + a = à.',
        },
        {
          pt: 'Eles vão à praia no verão.',
          fa: 'آن‌ها تابستان به ساحل می‌روند.',
          pron: 'اِلیس وائو آ پرایا نو وِرائو',
          note: 'crase پیش از اسم مؤنث.',
        },
        {
          pt: 'O evento será às 16 horas.',
          fa: 'رویداد ساعت ۱۶ خواهد بود.',
          pron: 'او اِوِنتو سِرا آس دِزِسِیس اُراس',
          note: 'crase در ساعت: a + as = às.',
        },
      ],
    },
    {
      headingFa: '۱۳. ترکیب و ادغام (Combinação / Contração) ـ مقدمه',
      bodyFa:
        'گاهی حرف اضافه با کلمهٔ بعد از خود یکی می‌شود و «ترکیب» (combinação) یا «ادغام/انقباض» (contração) می‌سازد.\n\nمثال: «As pessoas da cidade vão sempre ao cinema.»\n• da = contração (de + a، با کاهش)\n• ao = combinação (a + o، بدون کاهش)',
      examples: [
        {
          pt: 'As pessoas da cidade vão sempre ao cinema.',
          fa: 'مردمِ شهر همیشه به سینما می‌روند.',
          pron: 'آس پِسُآس دا سیدادی وائو سِمپری آئو سینِما',
          note: 'da = contração؛ ao = combinação.',
        },
      ],
    },
    {
      headingFa: '۱۴. ترکیب (COMBINAÇÃO)',
      bodyFa:
        'ترکیب (combinação) وقتی رخ می‌دهد که حرف اضافه به کلمهٔ دیگر می‌چسبد بدون این‌که کوتاه/کاسته شود (sem sofrer redução). نمونهٔ آن ادغامِ a + o = ao و a + os = aos و a + onde = aonde است.\n\nنکته: «Aonde» یعنی «به کجا» و برای حرکت به‌کار می‌رود (aonde = para onde).',
      examples: [
        {
          pt: 'Eles foram ao parque.',
          fa: 'آن‌ها به پارک رفتند.',
          pron: 'اِلیس فُرام آئو پارکی',
          note: 'preposição (a) + artigo (o) = ao.',
        },
        {
          pt: 'O crédito oferecido aos empreiteiros não foi suficiente para a realização da obra.',
          fa: 'اعتبار داده‌شده به پیمانکاران برای انجام پروژه کافی نبود.',
          pron: 'او کرِجیتو اُفِرِسیدو آئوس اِمپرِیتِیروس نائو فُی سوفیسیِنتی',
          note: 'a + os = aos.',
        },
        {
          pt: 'O motorista foi aonde eu determinei.',
          fa: 'راننده به جایی رفت که من تعیین کردم.',
          pron: 'او مُتوریستا فُی آئُنجی اِئو دِتِرمینِی',
          note: 'a + onde = aonde (حرکت).',
        },
      ],
    },
    {
      headingFa: '۱۵. ادغام/انقباض (CONTRAÇÃO)',
      bodyFa:
        'انقباض (contração) وقتی رخ می‌دهد که حرف اضافه با کلمهٔ دیگر یکی می‌شود و در این کار کوتاه/کاسته می‌شود (sofrendo redução). نمونه‌ها: de + o = do، por + a = pela، em + a = na.',
      examples: [
        {
          pt: 'A colheita do café começará em breve.',
          fa: 'برداشت قهوه به‌زودی آغاز می‌شود.',
          pron: 'آ کُلِیتا دو کافه کُمِسارا اِین برِوی',
          note: 'de + o = do.',
        },
        {
          pt: 'Nas férias, faremos uma viagem pela Amazônia.',
          fa: 'در تعطیلات سفری به آمازون خواهیم داشت.',
          pron: 'ناس فِریاس، فارِموس اوما ویاژِین پِلا آمازُنیا',
          note: 'por + a = pela (و em + as = nas).',
        },
        {
          pt: 'A casa dela é na rua da padaria.',
          fa: 'خانهٔ او در خیابانِ نانوایی است.',
          pron: 'آ کازا دِلا اِ نا هووا دا پاداریا',
          note: 'em + a = na؛ de + a = da.',
        },
      ],
    },
    {
      headingFa: '۱۶. جدول ترکیب/انقباض حروف اضافه',
      bodyFa:
        'حروف اضافه می‌توانند با حروف تعریف، بعضی ضمایر و قیدها ترکیب شوند و کلماتی مثل do, disto, pelas و … بسازند. جدول اصلی ادغام‌ها:\n\nحرف اضافه | + o | + a | + os | + as\nDE        | do  | da  | dos  | das\nEM        | no  | na  | nos  | nas\nPOR       | pelo| pela| pelos| pelas\nA         | ao  | à   | aos  | às\n\nنمونه‌های ادغام با ضمایر/قیدها:\nde + este = deste ، de + isto = disto ، de + ele = dele ، de + eles = deles\nem + este = neste ، em + isto = nisto ، em + ele = nele ، em + eles = neles\na + onde = aonde',
      examples: [
        {
          pt: 'Gosto muito deste livro. (de + este)',
          fa: 'این کتاب را خیلی دوست دارم.',
          pron: 'گُستو مویتو دِستی لیورو',
          note: 'de + este = deste.',
        },
        {
          pt: 'Não entendi nada disto. (de + isto)',
          fa: 'هیچ‌چیز از این را نفهمیدم.',
          pron: 'نائو اِنتِنجی نادا جیستو',
          note: 'de + isto = disto.',
        },
        {
          pt: 'O livro é dele. (de + ele)',
          fa: 'کتاب مالِ اوست.',
          pron: 'او لیورو اِ دِلی',
          note: 'de + ele = dele.',
        },
        {
          pt: 'Penso nele todos os dias. (em + ele)',
          fa: 'هر روز به او فکر می‌کنم.',
          pron: 'پِنسو نِلی تُدوس اوس جیاس',
          note: 'em + ele = nele.',
        },
      ],
    },
    {
      headingFa: '۱۷. دسته‌بندی حروف اضافه',
      bodyFa:
        'حروف اضافه به دو دسته تقسیم می‌شوند:\n\n• اصلی (Essenciais): کلماتی که فقط نقش حرف اضافه دارند.\n• عارضی (Acidentais): کلماتی از دسته‌های دستوری دیگر که در برخی جمله‌ها مثل حرف اضافه عمل می‌کنند.',
      examples: [],
    },
    {
      headingFa: '۱۸. حروف اضافهٔ اصلی (Essenciais)',
      bodyFa:
        'حروف اضافهٔ اصلی کلماتی هستند که فقط به‌عنوان حرف اضافه به‌کار می‌روند. فهرست کامل:\n\na, ante, até, com, contra, de, desde, em, entre, para, perante, por, sem, sob, sobre, trás.\n\nمعنی برخی از این‌ها: a (به)، ante (پیشِ/در برابر)، até (تا)، com (با)، contra (برخلاف)، de (از/مالِ)، desde (از زمانِ)، em (در)، entre (بین)، para (برای/به‌سوی)، perante (در برابرِ)، por (به‌واسطهٔ/از)، sem (بدونِ)، sob (زیرِ)، sobre (روی/دربارهٔ)، trás (پشت).',
      examples: [
        {
          pt: 'Entre mim e você existe uma antiga amizade.',
          fa: 'بین من و تو دوستی قدیمی وجود دارد.',
          pron: 'اِنتری مین ای وُسه اِگزیستی اوما آنتیگا آمیزادی',
          note: 'entre = بین.',
        },
        {
          pt: 'Ele não mora com seus pais.',
          fa: 'او با والدینش زندگی نمی‌کند.',
          pron: 'اِلی نائو مُرا کُن سِئوس پایس',
          note: 'com = با.',
        },
      ],
    },
    {
      headingFa: '۱۹. حروف اضافهٔ عارضی (Acidentais)',
      bodyFa:
        'حروف اضافهٔ عارضی کلماتی از دسته‌های دستوری دیگر هستند که در جمله‌های خاص نقش حرف اضافه پیدا می‌کنند. فهرست:\n\nafora, como, conforme, durante, exceto, mediante, menos, salvo, segundo, visto...\n\nمعنی برخی: afora (به‌جز/سراسرِ)، como (به‌عنوان/مثلِ)، conforme (بر طبقِ)، durante (در طولِ)، exceto (به‌جز)، mediante (با/به‌واسطهٔ)، menos (به‌جز)، salvo (به‌جز)، segundo (بر طبقِ)، visto (با توجه به).\n\nنکته: یک کلمه می‌تواند بسته به جمله معنای متفاوتی داشته باشد؛ مثلاً «segundo» گاهی حرف اضافه است و گاهی عدد ترتیبی (دومین).',
      examples: [
        {
          pt: 'A garota agiu segundo suas convicções. (preposição)',
          fa: 'دختر بر طبق باورهایش عمل کرد.',
          pron: 'آ گارُتا آژیو سِگوندو سوآس کُنویکسُئِس',
          note: 'اینجا segundo = بر طبقِ (حرف اضافه).',
        },
        {
          pt: 'Ele foi o segundo aluno a entrar na sala. (numeral ordinal)',
          fa: 'او دومین دانش‌آموزی بود که وارد کلاس شد.',
          pron: 'اِلی فُی او سِگوندو آلونو آ اِنترار نا سالا',
          note: 'اینجا segundo = دومین (عدد ترتیبی).',
        },
      ],
    },
  ],
  keyPointsFa: [
    'حرف اضافه کلمه‌ای بدون تغییر است که دو جزء جمله را با رابطهٔ معنایی به هم می‌پیوندد.',
    'DE سه کاربرد اصلی دارد: اصلیت، مالکیت و جنس؛ برای جنس/ماده هیچ تغییری نمی‌کند.',
    'شهرها/ایالت‌ها با de و em بدون حرف تعریف؛ کشورها با do/da/dos/das و no/na/nos/nas؛ استثناها: Rio de Janeiro (do/no)، Bahia (da/na)، Portugal و Cuba (بدون حرف تعریف).',
    'PARA برای مقصد، هدف و گیرنده؛ در گفتار pra/pro، اما در نوشتار رسمی همیشه para / para a / para o.',
    'EM برای مکان و زمان و اغلب با فعل estar به‌کار می‌رود.',
    'POR برای زمان، قیمت، علت و مسیر عبور؛ با حرف تعریف می‌شود pelo/pela/pelos/pelas.',
    'A برای زمان، وسیله و مقصد؛ a + a = à پدیدهٔ crase را می‌سازد (à escola, às 16 horas).',
    'Combinação بدون کاهش (ao, aos, aonde)؛ Contração با کاهش (do, na, pela).',
    'حروف اضافهٔ اصلی فقط حرف اضافه‌اند؛ حروف اضافهٔ عارضی از دسته‌های دیگرند که گاهی حرف اضافه می‌شوند.',
  ],
  quiz: [
    {
      id: 'course-aula-14-q1',
      type: 'mcq',
      prompt: 'Na frase "Estou com medo", qual é a preposição?',
      promptFa: 'در جملهٔ «Estou com medo» کدام کلمه حرف اضافه است؟',
      options: ['com', 'estou', 'medo', 'eu'],
      answer: 'com',
      explanationFa: '«com» رابطهٔ بین estou و medo را می‌سازد و حرف اضافه است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q2',
      type: 'mcq',
      prompt: 'Complete: Eu sou ___ Rio de Janeiro.',
      promptFa: 'اصلیت با شهرِ استثنایی «o Rio de Janeiro»؛ کدام درست است؟',
      options: ['do', 'de', 'da', 'no'],
      answer: 'do',
      explanationFa: 'Rio de Janeiro با حرف تعریف o می‌آید؛ de + o = do.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q3',
      type: 'mcq',
      prompt: 'Complete: Ele é ___ Bahia.',
      promptFa: 'اصلیت با ایالتِ استثنایی «a Bahia»؛ کدام درست است؟',
      options: ['da', 'de', 'do', 'na'],
      answer: 'da',
      explanationFa: 'Bahia با حرف تعریف a می‌آید؛ de + a = da.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q4',
      type: 'mcq',
      prompt: 'Qual está correto para material?',
      promptFa: 'برای بیان جنس/ماده کدام درست است؟',
      options: [
        'Esta casa é de madeira.',
        'Esta casa é da madeira.',
        'Esta casa é do madeira.',
        'Esta casa é na madeira.',
      ],
      answer: 'Esta casa é de madeira.',
      explanationFa: 'برای جنس/ماده، DE ثابت می‌ماند و با حرف تعریف ادغام نمی‌شود.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q5',
      type: 'mcq',
      prompt: '"Vou pro Rio" — a forma escrita formal é:',
      promptFa: 'شکل نوشتاریِ رسمیِ «Vou pro Rio» چیست؟',
      options: ['Vou para o Rio.', 'Vou pra Rio.', 'Vou por o Rio.', 'Vou no Rio.'],
      answer: 'Vou para o Rio.',
      explanationFa: 'pro = para o؛ در نوشتار رسمی باید «para o» نوشته شود.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q6',
      type: 'mcq',
      prompt: 'Complete: Moro ___ Brasil.',
      promptFa: 'محل زندگی با کشورِ «o Brasil»؛ کدام درست است؟',
      options: ['no', 'em', 'na', 'do'],
      answer: 'no',
      explanationFa: 'Brasil با حرف تعریف o می‌آید؛ em + o = no.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q7',
      type: 'mcq',
      prompt: 'Complete: Nós viajamos ___ muitas cidades da Europa.',
      promptFa: 'برای «مکانی که از آن عبور می‌کنیم» کدام حرف اضافه؟',
      options: ['por', 'para', 'de', 'em'],
      answer: 'por',
      explanationFa: 'مسیرِ عبور با POR بیان می‌شود.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q8',
      type: 'fill-blank',
      prompt: 'Você precisa passar ___ túnel para chegar ao centro. (por + o)',
      promptFa: 'ادغام por + o را بگذارید.',
      options: [],
      answer: 'pelo',
      explanationFa: 'por + o = pelo.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q9',
      type: 'mcq',
      prompt: 'Qual frase usa crase corretamente?',
      promptFa: 'کدام جمله crase را درست به‌کار برده است؟',
      options: [
        'Vou à escola pela manhã.',
        'Vou a escola pela manhã.',
        'Vou ao escola pela manhã.',
        'Vou na escola pela manhã.',
      ],
      answer: 'Vou à escola pela manhã.',
      explanationFa: 'a (حرف اضافه) + a (حرف تعریف مؤنث) = à → crase.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q10',
      type: 'mcq',
      prompt: 'Em "Eles foram ao parque", "ao" é:',
      promptFa: '«ao» در «Eles foram ao parque» چیست؟',
      options: [
        'combinação (a + o)',
        'contração (de + o)',
        'crase (a + a)',
        'combinação (em + o)',
      ],
      answer: 'combinação (a + o)',
      explanationFa: 'a + o = ao؛ ترکیب بدون کاهش (combinação).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q11',
      type: 'mcq',
      prompt: 'Em "A casa dela é na rua da padaria", "na" é:',
      promptFa: '«na» در جملهٔ نمونه چیست؟',
      options: [
        'contração (em + a)',
        'combinação (a + a)',
        'contração (de + a)',
        'combinação (em + o)',
      ],
      answer: 'contração (em + a)',
      explanationFa: 'em + a = na؛ انقباض همراه با کاهش (contração).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q12',
      type: 'fill-blank',
      prompt: 'Já vou embora. ___ amanhã! (preposição essencial)',
      promptFa: 'با حرف اضافهٔ اصلی کامل کنید (خداحافظی «تا فردا»).',
      options: [],
      answer: 'Até',
      explanationFa: '«Até amanhã!» یعنی تا فردا؛ até حرف اضافهٔ اصلی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q13',
      type: 'fill-blank',
      prompt: '___ mim e você existe uma antiga amizade. (preposição essencial)',
      promptFa: 'با حرف اضافهٔ اصلی کامل کنید (رابطهٔ «بین»).',
      options: [],
      answer: 'Entre',
      explanationFa: '«Entre mim e você» یعنی بین من و تو؛ entre حرف اضافهٔ اصلی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q14',
      type: 'fill-blank',
      prompt: '___ você estudar, precisa de silêncio. (preposição essencial)',
      promptFa: 'با حرف اضافهٔ اصلی کامل کنید (هدف/برای این‌که).',
      options: [],
      answer: 'Para',
      explanationFa: '«Para você estudar» یعنی برای این‌که درس بخوانی؛ para حرف اضافهٔ اصلی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q15',
      type: 'fill-blank',
      prompt: 'Ele não mora ___ seus pais. (preposição essencial)',
      promptFa: 'با حرف اضافهٔ اصلی کامل کنید (همراهی).',
      options: [],
      answer: 'com',
      explanationFa: '«mora com seus pais» یعنی با والدینش زندگی می‌کند؛ com حرف اضافهٔ اصلی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q16',
      type: 'fill-blank',
      prompt: '___ o documento, eu estou livre. (preposição acidental)',
      promptFa: 'با حرف اضافهٔ عارضی کامل کنید (با ارائهٔ/به‌واسطهٔ سند).',
      options: [],
      answer: 'Mediante',
      explanationFa: '«Mediante o documento» یعنی با ارائهٔ سند؛ mediante حرف اضافهٔ عارضی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q17',
      type: 'fill-blank',
      prompt: 'Ele trabalha ___ garçom naquele restaurante novo. (preposição acidental)',
      promptFa: 'با حرف اضافهٔ عارضی کامل کنید (به‌عنوانِ).',
      options: [],
      answer: 'como',
      explanationFa: '«trabalha como garçom» یعنی به‌عنوان پیشخدمت کار می‌کند؛ como اینجا حرف اضافهٔ عارضی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q18',
      type: 'fill-blank',
      prompt: '___ a aula não pode abrir o microfone. (preposição acidental)',
      promptFa: 'با حرف اضافهٔ عارضی کامل کنید (در طولِ).',
      options: [],
      answer: 'Durante',
      explanationFa: '«Durante a aula» یعنی در طول کلاس؛ durante حرف اضافهٔ عارضی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q19',
      type: 'fill-blank',
      prompt: 'Todos vão à festa, ___ o João. (preposição acidental)',
      promptFa: 'با حرف اضافهٔ عارضی کامل کنید (به‌جز).',
      options: [],
      answer: 'exceto',
      explanationFa: '«exceto o João» یعنی به‌جز ژوائو؛ exceto حرف اضافهٔ عارضی است (menos/salvo هم درست‌اند).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q20',
      type: 'mcq',
      prompt:
        'Quais são as preposições no texto: "...tomo meu café, sempre às 6 horas. Muitos pássaros me acompanham no meu ritual, são como meus convidados. Isso tudo é para alegrar o meu dia."',
      promptFa: 'حروف اضافهٔ متن را انتخاب کنید.',
      options: [
        'às (a), no (em), como, para',
        'meu, café, ritual, dia',
        'tomo, acompanham, alegrar',
        'sempre, muitos, tudo',
      ],
      answer: 'às (a), no (em), como, para',
      explanationFa: 'às = a + as (crase)، no = em + o، como و para همگی حرف اضافه‌اند.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-14-q21',
      type: 'fill-blank',
      prompt: 'Ontem ao acordar, eu levantei ___ cama. (de + a)',
      promptFa: 'ادغام de + a را بگذارید.',
      options: [],
      answer: 'da',
      explanationFa: 'de + a = da.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q22',
      type: 'fill-blank',
      prompt: '...e fui caminhar ___ parque. (em + o)',
      promptFa: 'ادغام em + o را بگذارید.',
      options: [],
      answer: 'no',
      explanationFa: 'em + o = no.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q23',
      type: 'fill-blank',
      prompt: 'Ao voltar, sentei ___ cadeira. (em + a)',
      promptFa: 'ادغام em + a را بگذارید.',
      options: [],
      answer: 'na',
      explanationFa: 'em + a = na.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q24',
      type: 'fill-blank',
      prompt: 'Fui tomar banho ___ banheiro ___ andar de cima. (em + o) / (de + o)',
      promptFa: 'دو ادغام em + o و de + o را به‌ترتیب بگذارید.',
      options: [],
      answer: 'no / do',
      explanationFa: 'em + o = no؛ de + o = do.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q25',
      type: 'fill-blank',
      prompt: '___ ida ao trabalho, fiquei admirando os prédios. (Em + a)',
      promptFa: 'ادغام Em + a را بگذارید.',
      options: [],
      answer: 'Na',
      explanationFa: 'Em + a = Na.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q26',
      type: 'fill-blank',
      prompt: '...imaginando as histórias das pessoas que trabalham ___. (em + eles)',
      promptFa: 'ادغام em + eles را بگذارید.',
      options: [],
      answer: 'neles',
      explanationFa: 'em + eles = neles.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q27',
      type: 'fill-blank',
      prompt: 'Gosto muito de viajar ___ histórias da minha própria mente. (em + as)',
      promptFa: 'ادغام em + as را بگذارید.',
      options: [],
      answer: 'nas',
      explanationFa: 'em + as = nas.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-14-q28',
      type: 'translate-fa-pt',
      prompt: '«من به مدرسه می‌روم تا یاد بگیرم.» را به پرتغالی بنویسید.',
      promptFa: 'با حرف اضافهٔ PARA ترجمه کنید.',
      options: [],
      answer: 'Eu vou para a escola para aprender.',
      explanationFa: 'PARA هم برای مقصد (para a escola) و هم برای هدف (para aprender) به‌کار می‌رود.',
      cefr: 'A2',
      skill: 'writing',
    },
    {
      id: 'course-aula-14-q29',
      type: 'translate-pt-fa',
      prompt: 'Traduza para o persa: "Ela sempre sobe o edifício pelas escadas."',
      promptFa: 'این جمله را به فارسی ترجمه کنید.',
      options: [],
      answer: 'او همیشه از پله‌ها بالای ساختمان می‌رود.',
      explanationFa: 'pelas = por + as؛ مسیرِ عبور با POR بیان می‌شود.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-14-q30',
      type: 'order-words',
      prompt: 'Ordene: [do / é / carro / meu pai / O / azul]',
      promptFa: 'کلمات را مرتب کنید تا جملهٔ مالکیت درست شود.',
      options: ['O', 'carro', 'do', 'meu pai', 'é', 'azul'],
      answer: 'O carro do meu pai é azul.',
      explanationFa: 'مالکیت با DE بیان می‌شود؛ de + o = do (do meu pai).',
      cefr: 'A2',
      skill: 'writing',
    },
  ],
  estimatedMinutes: 28,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 14 (کامل).',
};
