import type { CourseLesson } from '@/domain/content/schema';

export const aula4: CourseLesson = {
  id: 'course-aula-4',
  order: 4,
  aula: 'Aula 4',
  track: 'federal',
  titleFa: 'عدد و حروف تعریف',
  titlePt: 'Numeral e Artigos',
  cefr: 'A1',
  summaryFa:
    'این درس دو موضوع مهم گرامری را کامل پوشش می‌دهد. بخش نخست دربارهٔ «عدد» (numeral) است: اعداد اصلی (cardinais) که مقدار را نشان می‌دهند و اعداد ترتیبی (ordinais) که ترتیب یا جایگاه را نشان می‌دهند، همراه با فهرست کامل اعداد از یک تا هزار به هر دو شکل، قاعدهٔ کاربرد «e» در خواندن اعداد بزرگ، و شیوهٔ نوشتنِ اعداد به حروف. بخش دوم دربارهٔ «حروف تعریف» (artigos) است: حرف تعریف معرفه (o, a, os, as) و نکره (um, uma, uns, umas)، هماهنگی آن‌ها با اسم در جنس و شمار، کاربردشان پیش از اسم‌های خاص و نام کشورها/شهرها، و در پایان تفاوت ظریف میان «um» به‌عنوان عدد و «um» به‌عنوان حرف تعریف نکره.',
  objectivesFa: [
    'تفاوت اعداد اصلی (cardinais) و ترتیبی (ordinais) را بشناسید.',
    'اعداد اصلی از ۰ تا ۱۰۰۰ و اعداد ترتیبی از ۱ تا ۱۰۰۰ را بخوانید و بنویسید.',
    'اعداد بزرگ را با قاعدهٔ درستِ «e» به حروف بنویسید.',
    'حروف تعریف معرفه (o, a, os, as) و نکره (um, uma, uns, umas) را با اسم در جنس و شمار هماهنگ کنید.',
    'کاربرد حرف تعریف پیش از اسم‌های خاص و نام کشورها و شهرها را بدانید.',
    'تفاوت میان «um» عدد و «um» حرف تعریف نکره را تشخیص دهید.',
  ],
  sections: [
    {
      headingFa: '۱. عدد چیست؟ (Numeral)',
      bodyFa:
        'عدد (numeral) دسته‌ای از واژه‌هاست که مقدار را مشخص می‌کند و بر پایهٔ شمار (مفرد/جمع) و جنس (مذکر/مؤنث) تغییر می‌کند. اعدادی که هر روز به‌کار می‌بریم بر اساس ارزشی که نشان می‌دهند به دو گروه تقسیم می‌شوند:\n\n۱) اعداد اصلی (cardinais) که مقدار را نشان می‌دهند.\n۲) اعداد ترتیبی (ordinais) که ترتیب یا جایگاه را نشان می‌دهند.',
      examples: [],
    },
    {
      headingFa: '۲. اعداد اصلی (Números cardinais)',
      bodyFa:
        'اعداد اصلی مقدار را نشان می‌دهند (um, dois, três, quatro = یک، دو، سه، چهار) و با ارقام عربی نوشته می‌شوند (۱، ۲، ۳، ۴). این اعداد در جملهٔ روزمره برای شمردن، گفتن سن و بیان تاریخ به‌کار می‌روند.',
      examples: [
        {
          pt: 'Comprei cinco caixas de chocolate.',
          fa: 'من پنج جعبه شکلات خریدم.',
          pron: 'کُمپری سینکو کایشاس جی شوکولاتی',
        },
        {
          pt: 'Em 2019 completarei vinte e nove anos de idade.',
          fa: 'در سال ۲۰۱۹ بیست‌ونه ساله می‌شوم.',
          pron: 'اِین دویس میل اِ دِزِنووی کُمپلِتارِی وینتی اِ نووی آنوس جی ایدادی',
        },
        {
          pt: 'Hoje é vinte e dois de maio.',
          fa: 'امروز بیست‌ودوم ماه مه است.',
          pron: 'اُژی اِ وینتی اِ دویس جی مایو',
          note: 'برای روزهای ماه از عدد اصلی استفاده می‌شود، جز روز اول که ترتیبی است (primeiro).',
        },
      ],
    },
    {
      headingFa: '۳. خواندن اعداد بزرگ + قاعدهٔ «e»',
      bodyFa:
        'برای خواندن اعداد بزرگ، بخش‌ها را با «e» (و) به هم می‌پیوندیم. چند نمونه:\n\n52 — cinquenta e dois\n127 — cento e vinte e sete\n1.473 — mil quatrocentos e setenta e três\n6.100 — seis mil e cem\n6.118 — seis mil cento e dezoito\n24.621 — vinte e quatro mil seiscentos e vinte e um\n\nنکته‌ها (Atenção):\n۱) میان هزارگان و صدگان فقط وقتی «e» می‌آید که عدد به یک صدگان کامل ختم شود.\n   6.100 — seis mil e cem\n   1.500 — mil e quinhentos\n(اما 6.118 = seis mil cento e dezoito، چون به صدگان کامل ختم نمی‌شود.)\n\n۲) واژه‌های zero (0 = صفر) و ambos نیز جزو اعداد اصلی‌اند؛ «ambos» یعنی «هر دو / آن دو».\n   مثال: Pai e filho procuraram emprego, ambos já estão trabalhando. (پدر و پسر دنبال کار گشتند، هر دو الان مشغول به کارند.)',
      examples: [
        {
          pt: '6.100 — seis mil e cem',
          fa: '۶۱۰۰ — شش هزار و صد',
          pron: 'سِیس میل اِ سِین',
          note: 'به صدگانِ کامل (cem) ختم می‌شود، پس «e» می‌آید.',
        },
        {
          pt: '6.118 — seis mil cento e dezoito',
          fa: '۶۱۱۸ — شش هزار و صد و هجده',
          pron: 'سِیس میل سِنتو اِ دِزُیتو',
          note: 'به صدگانِ کامل ختم نمی‌شود، پس میان هزار و صد «e» نمی‌آید.',
        },
        {
          pt: 'Ambos já estão trabalhando.',
          fa: 'هر دو الان مشغول به کارند.',
          pron: 'آمبوس ژا اِستائو ترابالیاندو',
          note: '«ambos» یعنی «os dois» (آن دو).',
        },
      ],
    },
    {
      headingFa: '۴. فهرست کامل اعداد اصلی (۱ تا ۱۰۰۰)',
      bodyFa:
        'برخی اعداد شکل مذکر و مؤنث دارند (um/uma, dois/duas و صدگان‌ها). فهرست کامل:\n\n1 — um / uma\n2 — dois / duas\n3 — três\n4 — quatro\n5 — cinco\n6 — seis\n7 — sete\n8 — oito\n9 — nove\n10 — dez\n11 — onze\n12 — doze\n13 — treze\n14 — quatorze (ou catorze)\n15 — quinze\n16 — dezesseis\n17 — dezessete\n18 — dezoito\n19 — dezenove\n20 — vinte\n21 — vinte e um / vinte e uma\n22 — vinte e dois / vinte e duas\n23 — vinte e três\n30 — trinta\n40 — quarenta\n50 — cinquenta\n60 — sessenta\n70 — setenta\n80 — oitenta\n90 — noventa\n100 — cem\n200 — duzentos / duzentas\n300 — trezentos / trezentas\n400 — quatrocentos / quatrocentas\n500 — quinhentos / quinhentas\n600 — seiscentos / seiscentas\n700 — setecentos / setecentas\n800 — oitocentos / oitocentas\n900 — novecentos / novecentas\n1000 — mil',
      examples: [
        {
          pt: 'um / uma — dois / duas',
          fa: 'یک (مذکر/مؤنث) — دو (مذکر/مؤنث)',
          pron: 'اون / اوما — دویس / دواس',
          note: 'فقط ۱ و ۲ و صدگان‌ها با جنس اسم هماهنگ می‌شوند: uma casa، duas casas، duzentas casas.',
        },
        {
          pt: '100 — cem / cento',
          fa: '۱۰۰ — «cem» هنگام تنها بودن، «cento» پیش از عدد دیگر.',
          pron: 'سِین / سِنتو',
          note: 'cem reais اما cento e vinte reais.',
        },
      ],
    },
    {
      headingFa: '۵. تمرین: اعداد را به حروف بنویسید',
      bodyFa:
        'اعداد داخل پرانتز را به حروف بنویسید:\n\nPedimos 550 (____) salgadinhos para a festa.\n1.700 (____) pessoas participaram do evento.\nCompramos uma TV, em promoção, por R$ 1.230,00 (____) reais.\nA população da cidade é de 230.000 (____) habitantes.\nUm ano tem 365 (____) dias.\n\nپرسش‌های گفت‌وگویی برای تمرین شفاهی:\nQuantos anos você tem? (چند سال داری؟)\nQuantos irmãos você tem? (چند خواهر و برادر داری؟)\nQuantos filhos você tem? (چند فرزند داری؟)',
      examples: [
        {
          pt: '550 — quinhentos e cinquenta',
          fa: '۵۵۰ — پانصد و پنجاه',
          pron: 'کینیِنتوس اِ سینکوئنتا',
        },
        {
          pt: '1.700 — mil e setecentos',
          fa: '۱۷۰۰ — هزار و هفتصد',
          pron: 'میل اِ سِتِسِنتوس',
          note: 'به صدگانِ کامل ختم می‌شود، پس «e» می‌آید.',
        },
        {
          pt: '230.000 — duzentos e trinta mil',
          fa: '۲۳۰۰۰۰ — دویست و سی هزار',
          pron: 'دوزِنتوس اِ ترینتا میل',
        },
      ],
    },
    {
      headingFa: '۶. اعداد ترتیبی (Números ordinais)',
      bodyFa:
        'اعداد ترتیبی جایگاه یا ترتیب در یک مجموعه را نشان می‌دهند (primeiro, segundo, terceiro, quarto = اول، دوم، سوم، چهارم) و معمولاً به‌شکل کوتاه با نشانهٔ «º» (مذکر) یا «ª» (مؤنث) نوشته می‌شوند (1.º, 2.º, 3.º, 4.º). این اعداد نیز با جنس اسم هماهنگ می‌شوند: primeiro/primeira.',
      examples: [
        {
          pt: 'Mariana está sentada na segunda fileira.',
          fa: 'ماریانا در ردیف دوم نشسته است.',
          pron: 'ماریانا اِستا سِنتادا نا سِگوندا فیلِیرا',
        },
        {
          pt: 'Eu cheguei em primeiro lugar na maratona do Rio.',
          fa: 'من در ماراتن ریو اول شدم (به مقام اول رسیدم).',
          pron: 'اِئو شِگِی اِین پریمِیرو لوگار نا ماراتونا دو ریو',
        },
        {
          pt: 'O consultório fica no décimo andar.',
          fa: 'مطب در طبقهٔ دهم است.',
          pron: 'او کُنسولتوریو فیکا نو دِسیمو آندار',
        },
        {
          pt: 'Hoje é primeiro de setembro.',
          fa: 'امروز اول سپتامبر است.',
          pron: 'اُژی اِ پریمِیرو جی سِتِمبرو',
          note: 'تنها روز اول ماه با عدد ترتیبی (primeiro) گفته می‌شود؛ بقیهٔ روزها اصلی‌اند.',
        },
      ],
    },
    {
      headingFa: '۷. فهرست کامل اعداد ترتیبی (۱ تا ۱۰۰۰)',
      bodyFa:
        'فهرست کامل اعداد ترتیبی؛ هر کدام شکل مذکر (a) و مؤنث دارد، مثلاً primeiro/primeira:\n\n1.º — primeiro(a)\n2.º — segundo(a)\n3.º — terceiro(a)\n4.º — quarto(a)\n5.º — quinto(a)\n6.º — sexto(a)\n7.º — sétimo(a)\n8.º — oitavo(a)\n9.º — nono(a)\n10.º — décimo(a)\n11.º — décimo primeiro\n12.º — décimo segundo\n13.º — décimo terceiro\n14.º — décimo quarto\n15.º — décimo quinto\n16.º — décimo sexto\n17.º — décimo sétimo\n18.º — décimo oitavo\n19.º — décimo nono\n20.º — vigésimo\n21.º — vigésimo primeiro\n22.º — vigésimo segundo\n23.º — vigésimo terceiro\n30.º — trigésimo\n40.º — quadragésimo\n50.º — quinquagésimo\n60.º — sexagésimo\n70.º — septuagésimo\n80.º — octogésimo\n90.º — nonagésimo\n100.º — centésimo\n200.º — ducentésimo\n300.º — trecentésimo\n400.º — quadringentésimo\n500.º — quingentésimo\n600.º — sexcentésimo\n700.º — septingentésimo\n800.º — octingentésimo\n900.º — noningentésimo\n1000.º — milésimo',
      examples: [
        {
          pt: '11.º — décimo primeiro',
          fa: '۱۱اُم — یازدهم',
          pron: 'دِسیمو پریمِیرو',
          note: 'از ۱۱ به بعد دو بخش کنار هم می‌آیند: décimo + primeiro.',
        },
        {
          pt: '20.º — vigésimo / 30.º — trigésimo',
          fa: '۲۰اُم — بیستم / ۳۰اُم — سی‌اُم',
          pron: 'ویژِزیمو / تریژِزیمو',
        },
      ],
    },
    {
      headingFa: '۸. تمرین: رتبهٔ دوندگان را به حروف بنویسید',
      bodyFa:
        'گروهی از دوستان در یک ماراتن دویدند. رتبهٔ هر کدام را به‌صورت عدد ترتیبی و به حروف بنویسید:\n\nCARLOS: 26.º\nLUCAS: 5.º\nCARMEM: 13.º\nPRISCILA: 17.º\nFELIPE: 23.º\nCLAUDIA: 8.º\nJOÃO: 9.º',
      examples: [
        {
          pt: '26.º — vigésimo sexto',
          fa: '۲۶اُم — بیست‌وششم',
          pron: 'ویژِزیمو سِستو',
        },
        {
          pt: '13.º — décimo terceiro',
          fa: '۱۳اُم — سیزدهم',
          pron: 'دِسیمو تِرسِیرو',
        },
        {
          pt: '9.º — nono',
          fa: '۹اُم — نهم',
          pron: 'نونو',
        },
      ],
    },
    {
      headingFa: '۹. حروف تعریف چیست؟ (Artigos)',
      bodyFa:
        'حروف تعریف واژه‌هایی هستند که همراه اسم می‌آیند و شمار (مفرد/جمع) و جنس (مذکر/مؤنث) آن را نشان می‌دهند. حرف تعریف همیشه باید با اسمِ خود در جنس و شمار هماهنگ باشد. حروف تعریف به دو گروه تقسیم می‌شوند: معرفه (definidos) و نکره (indefinidos). در فارسی حرف تعریف معرفه معادل مستقیم ندارد، بنابراین برای فارسی‌زبان‌ها یادگیری این بخش نیاز به دقت دارد.',
      examples: [],
    },
    {
      headingFa: '۱۰. حرف تعریف معرفه (Artigo definido)',
      bodyFa:
        'حرف تعریف معرفه برای اشاره به چیزِ مشخص و شناخته‌شده به‌کار می‌رود. جدول کامل:\n\n            مفرد        جمع\nمذکر:      O           OS\nمؤنث:      A           AS\n\nنکته: حرف تعریف معرفه پیش از اسم می‌آید و می‌تواند پیش از ضمایر صفتیِ ملکی و اسم‌های خاص هم بیاید؛ یعنی کاربرد آن پیش از ملکی و اسم خاص اجباری نیست.',
      examples: [
        {
          pt: 'O carro',
          fa: 'ماشین (آن ماشین مشخص)',
          pron: 'او کارو',
          note: 'مذکر مفرد.',
        },
        { pt: 'Os nomes', fa: 'نام‌ها', pron: 'اوس نُمیس', note: 'مذکر جمع.' },
        { pt: 'A caneta', fa: 'خودکار', pron: 'آ کانِتا', note: 'مؤنث مفرد.' },
        {
          pt: 'As meninas',
          fa: 'دخترها',
          pron: 'آس مِنیناس',
          note: 'مؤنث جمع.',
        },
      ],
    },
    {
      headingFa: '۱۱. معرفه پیش از اسم خاص، شهرها و کشورها',
      bodyFa:
        'پیش از اسم‌های خاص و ضمایر ملکی، کاربرد حرف تعریف اختیاری است:\n\nO Paulo یا Paulo\nA Carla یا Carla\nO meu carro یا meu carro\nA nossa irmã یا nossa irmã\n\nبرای برخی نام شهرها، ایالت‌ها و کشورها حرف تعریف می‌آید و برای برخی نمی‌آید:\nبا حرف تعریف: O Brasil، Os Estados Unidos، O Rio de Janeiro، A Bahia\nبدون حرف تعریف: São Paulo، Santa Catarina، Cuba، Portugal',
      examples: [
        {
          pt: 'Ele viu o professor de matemática.',
          fa: 'او معلم ریاضی را دید.',
          pron: 'اِلی ویو او پروفِسور جی ماتِماتیکا',
        },
        {
          pt: 'A casa do Paulo é muito grande.',
          fa: 'خانهٔ پائولو خیلی بزرگ است.',
          pron: 'آ کازا دو پائولو اِ مویتو گراندی',
          note: 'do = de + o (ترکیب حرف اضافه با حرف تعریف مذکر مفرد).',
        },
        {
          pt: 'O sol está brilhando e as nuvens estão brancas no céu.',
          fa: 'خورشید می‌درخشد و ابرها در آسمان سفیدند.',
          pron: 'او سُل اِستا بریلیاندو اِ آس نووِنس اِستائو برانکاس نو سِئو',
        },
        {
          pt: 'A aula começou e os alunos já chegaram.',
          fa: 'کلاس شروع شد و دانش‌آموزها رسیده‌اند.',
          pron: 'آ آئولا کومِسو اِ اوس آلونوس ژا شِگارام',
        },
        {
          pt: 'Eu vi os irmãos do meu amigo.',
          fa: 'من برادرهای دوستم را دیدم.',
          pron: 'اِئو وی اوس ایرمائوس دو مِئو آمیگو',
          note: 'do = de + o.',
        },
        {
          pt: 'Felipe viu as notas do seu boletim.',
          fa: 'فِلیپه نمره‌های کارنامه‌اش را دید.',
          pron: 'فِلیپی ویو آس نوتاس دو سِئو بولِتین',
        },
        {
          pt: 'O aparelho de som estragou.',
          fa: 'دستگاه صوتی خراب شد.',
          pron: 'او آپارِلیو جی سُم اِستراگو',
        },
        {
          pt: 'Fernanda aproveitou para rever as amigas.',
          fa: 'فرناندا از فرصت استفاده کرد تا دوستانش را دوباره ببیند.',
          pron: 'فِرناندا آپروِویتو پارا رِوِر آس آمیگاس',
        },
        {
          pt: 'Ela é a secretária da escola.',
          fa: 'او منشیِ مدرسه است.',
          pron: 'اِلا اِ آ سِکرِتاریا دا اِسکولا',
          note: 'da = de + a.',
        },
        {
          pt: 'As laranjas estão maduras.',
          fa: 'پرتقال‌ها رسیده‌اند.',
          pron: 'آس لارانژاس اِستائو مادوراس',
        },
      ],
    },
    {
      headingFa: '۱۲. تمرین: حرف تعریف معرفهٔ درست را بگذارید',
      bodyFa:
        'با حرف تعریف معرفهٔ مناسب (o, os, a, as) کامل کنید:\n\n___ cão\n___ montanhas\n___ empresas\n___ cartão de crédito\n___ computadores\n___ telefones\n___ motorista\n___ repórter\nFiz ___ lição de casa ontem.\n___ ondas faziam o navio balançar.\nLevei ___ bolo para ___ vovó.\n___ água da piscina estava morna.\nRenato está brincando com ___ meninos na rua.',
      examples: [
        {
          pt: 'o motorista / a motorista',
          fa: 'راننده (این واژه هم مذکر هم مؤنث است)',
          pron: 'او/آ موتوریستا',
          note: 'motorista دوجنسی است؛ جنس با حرف تعریف مشخص می‌شود.',
        },
        {
          pt: 'a água',
          fa: 'آب',
          pron: 'آ آگوا',
          note: 'água مؤنث است، هرچند با a شروع می‌شود: a água.',
        },
      ],
    },
    {
      headingFa: '۱۳. حرف تعریف نکره (Artigo indefinido)',
      bodyFa:
        'حرف تعریف نکره اسم را نامشخص و کلی معرفی می‌کند، بدون اینکه فرد یا شیء خاصی را مشخص کند. جدول کامل:\n\n            مفرد        جمع\nمذکر:      UM          UNS\nمؤنث:      UMA         UMAS\n\nنکته: حرف تعریف نکره پیش از اسم می‌آید. «uns/umas» در فارسی معادل «چندتا / یک‌سری» است.',
      examples: [
        { pt: 'Um nome', fa: 'یک نام', pron: 'اون نُمی', note: 'مذکر مفرد.' },
        {
          pt: 'Uns nomes',
          fa: 'چند نام',
          pron: 'اونس نُمیس',
          note: 'مذکر جمع.',
        },
        {
          pt: 'Uma caneta',
          fa: 'یک خودکار',
          pron: 'اوما کانِتا',
          note: 'مؤنث مفرد.',
        },
        {
          pt: 'Umas canetas',
          fa: 'چند خودکار',
          pron: 'اوماس کانِتاس',
          note: 'مؤنث جمع.',
        },
        {
          pt: 'Comprei uns remédios na farmácia hoje de manhã.',
          fa: 'امروز صبح چند دارو از داروخانه خریدم.',
          pron: 'کُمپری اونس رِمِجیوس نا فارماسیا اُژی جی مانیا',
        },
        {
          pt: 'A empresa vai contratar uns funcionários novos.',
          fa: 'شرکت چند کارمند جدید استخدام خواهد کرد.',
          pron: 'آ اِمپرِزا وای کُنتراتار اونس فونسیوناریوس نووُس',
        },
        {
          pt: 'Um vizinho ganhou a loteria.',
          fa: 'یک همسایه در لاتاری برنده شد.',
          pron: 'اون ویزینیو گانیو آ لوتِریا',
        },
        {
          pt: 'Uma criança caiu na praça.',
          fa: 'یک بچه در میدان افتاد.',
          pron: 'اوما کریانسا کایو نا پراسا',
        },
        {
          pt: 'Chamei uns amigos para jogar comigo.',
          fa: 'چند دوست را صدا زدم تا با من بازی کنند.',
          pron: 'شامِی اونس آمیگوس پارا ژوگار کومیگو',
        },
        {
          pt: 'Quebrei um copo.',
          fa: 'یک لیوان شکستم.',
          pron: 'کِبرِی اون کوپو',
        },
        {
          pt: 'Ganhei uma blusa.',
          fa: 'یک بلوز هدیه گرفتم.',
          pron: 'گانیِی اوما بلوزا',
        },
        {
          pt: 'Fui a um parque.',
          fa: 'به یک پارک رفتم.',
          pron: 'فویی آ اون پارکی',
        },
        {
          pt: 'Estou procurando um professor de matemática.',
          fa: 'دنبال یک معلم ریاضی می‌گردم.',
          pron: 'اِستو پروکوراندو اون پروفِسور جی ماتِماتیکا',
        },
        {
          pt: 'Comprei uma casa para minha família.',
          fa: 'برای خانواده‌ام یک خانه خریدم.',
          pron: 'کُمپری اوما کازا پارا مینیا فامیلیا',
        },
      ],
    },
    {
      headingFa: '۱۴. تمرین: حرف تعریف نکرهٔ درست را بگذارید',
      bodyFa:
        'با حرف تعریف نکرهٔ مناسب (um, uns, uma, umas) کامل کنید:\n\n___ carro\n___ flores\n___ mulher\n___ fotografia\n___ festa\n___ país\n___ cidade\n___ crianças\n___ presente\nPeguei ___ panela para cozinhar.\nChamei ___ meninos para brincar.\n___ dia iremos nos encontrar.\nJoana convidou ___ amigas estrangeiras para a festa.\nComprei ___ camisa para o meu pai.',
      examples: [
        {
          pt: 'umas flores',
          fa: 'چند گل',
          pron: 'اوماس فلورِس',
          note: 'flor مؤنث است، جمعش flores → umas flores.',
        },
        {
          pt: 'um país',
          fa: 'یک کشور',
          pron: 'اون پاییس',
          note: 'país مذکر است → um país.',
        },
      ],
    },
    {
      headingFa: '۱۵. «um» عدد است یا حرف تعریف نکره؟',
      bodyFa:
        'عدد اصلیِ «um» (۱) و حرف تعریف نکرهٔ «um» گاهی باعث سردرگمی می‌شوند. قاعده:\n\n- «um» را وقتی عدد می‌دانیم که مقدارِ دقیق را نشان دهد؛ جمعِ آن عدد «dois» است.\n- «um» را وقتی حرف تعریف نکره می‌دانیم که به موجودی نامشخص اشاره کند؛ جمعِ آن «uns» است.\n\nمقایسه کنید:\nApenas um garoto compareceu ao treinamento. (فقط یک پسر آمد → عدد؛ جمع: dois garotos)\nUm garoto estava circulando no pátio da escola. (یک پسری در حیاط می‌گشت → حرف تعریف نکره؛ جمع: uns garotos)',
      examples: [
        {
          pt: 'Apenas um garoto compareceu ao treinamento.',
          fa: 'فقط یک پسر در تمرین حاضر شد.',
          pron: 'آپِناس اون گاروتو کُمپارِسِئو آئو ترِیناِمنتو',
          note: '«apenas» (فقط) نشان می‌دهد که «um» اینجا عدد است (مقدار دقیق).',
        },
        {
          pt: 'Um garoto estava circulando no pátio da escola.',
          fa: 'پسری در حیاط مدرسه می‌گشت.',
          pron: 'اون گاروتو اِستاوا سیرکولاندو نو پاتیو دا اِسکولا',
          note: 'اشاره به موجودی نامشخص → حرف تعریف نکره.',
        },
      ],
    },
    {
      headingFa: '۱۶. تمرین پایانی: اعداد',
      bodyFa:
        'اعداد داخل پرانتز را به حروف بنویسید:\n\na) O cheque, no valor de R$634,00 (____) reais, estava sem fundos.\nb) Esta escola tem mais de 3.230 (____) alunos.\nc) Tenho 2 (____) notas de R$50,00 (____) reais.\nd) 252 (____) policiais saíram às ruas no dia da greve.\ne) Ana e Guilherme moram no (11.º) ____ andar.\nf) Eles têm um apartamento no (7.º) ____ andar.\ng) O escritório fica no (6.º) ____ andar.',
      examples: [
        {
          pt: '634 — seiscentos e trinta e quatro',
          fa: '۶۳۴ — ششصد و سی و چهار',
          pron: 'سِیسِنتوس اِ ترینتا اِ کواترو',
        },
        {
          pt: '3.230 — três mil duzentos e trinta',
          fa: '۳۲۳۰ — سه هزار و دویست و سی',
          pron: 'ترِس میل دوزِنتوس اِ ترینتا',
          note: 'به صدگانِ کامل ختم نمی‌شود، پس میان هزار و صد «e» نمی‌آید.',
        },
      ],
    },
    {
      headingFa: '۱۷. تمرین پایانی: حروف تعریف',
      bodyFa:
        'با حرف تعریف معرفه (o, os, a, as) کامل کنید:\n۱. Ganhamos ____ bicicleta que esperávamos.\n۲. Luísa aproveitou para rever ____ amigos.\n۳. ____ meninas foram viajar.\n۴. Ela está feliz com ____ novo trabalho.\n\nبا حرف تعریف نکره (um, uns, uma, umas) کامل کنید:\n۱. Eu estou lendo ____ livro muito interessante.\n۲. Nós vamos viajar para ____ cidade no interior.\n۳. Você comprou ____ carro novo?\n۴. Na frente da minha casa tem ____ árvore.',
      examples: [
        {
          pt: 'a bicicleta / os amigos / as meninas / o novo trabalho',
          fa: 'دوچرخه / دوستان / دخترها / شغل جدید',
          pron: 'آ بیسیکلِتا / اوس آمیگوس / آس مِنیناس / او نووُ ترابالیو',
        },
        {
          pt: 'um livro / uma cidade / um carro / uma árvore',
          fa: 'یک کتاب / یک شهر / یک ماشین / یک درخت',
          pron: 'اون لیورو / اوما سیدادی / اون کارو / اوما آرووری',
        },
      ],
    },
  ],
  keyPointsFa: [
    'اعداد اصلی (cardinais) مقدار را نشان می‌دهند؛ اعداد ترتیبی (ordinais) ترتیب/جایگاه را.',
    'فقط ۱ و ۲ و صدگان‌ها (۲۰۰ تا ۹۰۰) با جنس اسم هماهنگ می‌شوند: um/uma, dois/duas, duzentos/duzentas.',
    'میان هزارگان و صدگان فقط وقتی «e» می‌آید که عدد به صدگانِ کامل ختم شود (seis mil e cem؛ اما seis mil cento e dezoito).',
    'روز اول ماه ترتیبی است (primeiro de setembro)؛ بقیهٔ روزها با عدد اصلی گفته می‌شوند.',
    'حرف تعریف باید در جنس و شمار با اسم هماهنگ باشد: معرفه o/a/os/as، نکره um/uma/uns/umas.',
    'کاربرد حرف تعریف پیش از اسم خاص و ضمیر ملکی اختیاری است (O Paulo یا Paulo).',
    'برخی کشورها/شهرها حرف تعریف می‌گیرند (O Brasil, A Bahia) و برخی نه (São Paulo, Portugal, Cuba).',
    '«um» عدد = مقدار دقیق (جمع dois)؛ «um» حرف تعریف نکره = موجودی نامشخص (جمع uns).',
  ],
  quiz: [
    {
      id: 'course-aula-4-q1',
      type: 'mcq',
      prompt: 'Qual é a classe de palavras que indica quantidade?',
      promptFa: 'کدام دستهٔ واژه‌ها مقدار را نشان می‌دهد؟',
      options: ['Numeral', 'Artigo', 'Substantivo', 'Verbo'],
      answer: 'Numeral',
      explanationFa: '«Numeral» (عدد) دسته‌ای است که مقدار را مشخص می‌کند.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q2',
      type: 'mcq',
      prompt: 'Escreva 52 por extenso:',
      promptFa: 'عدد ۵۲ را به حروف انتخاب کنید:',
      options: [
        'cinquenta e dois',
        'cinco e dois',
        'quarenta e dois',
        'cinquenta e duas',
      ],
      answer: 'cinquenta e dois',
      explanationFa:
        '۵۲ = cinquenta e dois. برای اشیای مذکر «dois» و برای مؤنث «duas».',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q3',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: 550 salgadinhos.',
      promptFa: 'عدد ۵۵۰ را به حروف بنویسید (به‌شکل مذکر).',
      options: [],
      answer: 'quinhentos e cinquenta',
      explanationFa: '۵۵۰ = quinhentos e cinquenta.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q4',
      type: 'mcq',
      prompt: 'Escreva 1.700 por extenso:',
      promptFa: 'عدد ۱۷۰۰ را به حروف انتخاب کنید:',
      options: [
        'mil e setecentos',
        'mil setecentos',
        'mil e sete',
        'um mil setecentos',
      ],
      answer: 'mil e setecentos',
      explanationFa:
        '۱۷۰۰ به صدگانِ کامل (setecentos) ختم می‌شود، پس «e» می‌آید: mil e setecentos.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q5',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: R$ 1.230,00.',
      promptFa: 'عدد ۱۲۳۰ را به حروف بنویسید.',
      options: [],
      answer: 'mil duzentos e trinta',
      explanationFa:
        '۱۲۳۰ به صدگانِ کامل ختم نمی‌شود، پس میان هزار و صد «e» نمی‌آید: mil duzentos e trinta.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q6',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: 230.000 habitantes.',
      promptFa: 'عدد ۲۳۰۰۰۰ را به حروف بنویسید.',
      options: [],
      answer: 'duzentos e trinta mil',
      explanationFa: '۲۳۰۰۰۰ = duzentos e trinta mil.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q7',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: 365 dias.',
      promptFa: 'عدد ۳۶۵ را به حروف بنویسید.',
      options: [],
      answer: 'trezentos e sessenta e cinco',
      explanationFa: '۳۶۵ = trezentos e sessenta e cinco.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q8',
      type: 'mcq',
      prompt: 'Por que 6.100 se escreve "seis mil E cem"?',
      promptFa: 'چرا ۶۱۰۰ به‌صورت «seis mil e cem» نوشته می‌شود؟',
      options: [
        'Porque o número termina em centena exata',
        'Porque é um número par',
        'Porque tem quatro algarismos',
        'Porque é maior que mil',
      ],
      answer: 'Porque o número termina em centena exata',
      explanationFa:
        'قاعده: میان هزارگان و صدگان فقط وقتی «e» می‌آید که عدد به صدگانِ کامل ختم شود (cem).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q9',
      type: 'mcq',
      prompt: 'O que significa a palavra "ambos"?',
      promptFa: 'واژهٔ «ambos» یعنی چه؟',
      options: ['os dois', 'nenhum', 'muitos', 'alguns'],
      answer: 'os dois',
      explanationFa:
        '«ambos» یعنی «os dois» (هر دو / آن دو) و جزو اعداد اصلی است.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-4-q10',
      type: 'mcq',
      prompt: 'Complete: Eu comprei ___ casas. (2, feminino)',
      promptFa: 'شکل درست عدد ۲ پیش از اسم مؤنث «casas» کدام است؟',
      options: ['duas', 'dois', 'duzentas', 'duplas'],
      answer: 'duas',
      explanationFa: 'عدد ۲ با جنس اسم هماهنگ می‌شود؛ برای مؤنث «duas casas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q11',
      type: 'mcq',
      prompt: 'Os numerais ordinais indicam:',
      promptFa: 'اعداد ترتیبی چه چیزی را نشان می‌دهند؟',
      options: ['ordem ou posição', 'quantidade exata', 'gênero', 'preço'],
      answer: 'ordem ou posição',
      explanationFa:
        'اعداد ترتیبی (ordinais) ترتیب یا جایگاه در یک مجموعه را نشان می‌دهند.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q12',
      type: 'fill-blank',
      prompt: 'Escreva o ordinal por extenso: 26.º (Carlos).',
      promptFa: 'رتبهٔ ۲۶اُم را به‌شکل عدد ترتیبی بنویسید.',
      options: [],
      answer: 'vigésimo sexto',
      explanationFa: '۲۶اُم = vigésimo sexto (بیست‌وششم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q13',
      type: 'fill-blank',
      prompt: 'Escreva o ordinal por extenso: 5.º (Lucas).',
      promptFa: 'رتبهٔ ۵اُم را به‌شکل عدد ترتیبی بنویسید.',
      options: [],
      answer: 'quinto',
      explanationFa: '۵اُم = quinto (پنجم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q14',
      type: 'mcq',
      prompt: 'Escreva o ordinal 13.º por extenso (Carmem):',
      promptFa: 'رتبهٔ ۱۳اُم را انتخاب کنید:',
      options: ['décimo terceiro', 'treze', 'trigésimo', 'décimo três'],
      answer: 'décimo terceiro',
      explanationFa: '۱۳اُم = décimo terceiro (سیزدهم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q15',
      type: 'fill-blank',
      prompt: 'Escreva o ordinal por extenso: 17.º (Priscila).',
      promptFa: 'رتبهٔ ۱۷اُم را به‌شکل عدد ترتیبی بنویسید.',
      options: [],
      answer: 'décimo sétimo',
      explanationFa: '۱۷اُم = décimo sétimo (هفدهم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q16',
      type: 'fill-blank',
      prompt: 'Escreva o ordinal por extenso: 23.º (Felipe).',
      promptFa: 'رتبهٔ ۲۳اُم را به‌شکل عدد ترتیبی بنویسید.',
      options: [],
      answer: 'vigésimo terceiro',
      explanationFa: '۲۳اُم = vigésimo terceiro (بیست‌وسوم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q17',
      type: 'fill-blank',
      prompt: 'Escreva o ordinal por extenso: 8.º (Claudia).',
      promptFa: 'رتبهٔ ۸اُم را به‌شکل عدد ترتیبی بنویسید.',
      options: [],
      answer: 'oitavo',
      explanationFa: '۸اُم = oitavo (هشتم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q18',
      type: 'fill-blank',
      prompt: 'Escreva o ordinal por extenso: 9.º (João).',
      promptFa: 'رتبهٔ ۹اُم را به‌شکل عدد ترتیبی بنویسید.',
      options: [],
      answer: 'nono',
      explanationFa: '۹اُم = nono (نهم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q19',
      type: 'mcq',
      prompt: 'Os artigos concordam com o substantivo em:',
      promptFa: 'حرف تعریف با اسم در چه چیزی هماهنگ می‌شود؟',
      options: [
        'gênero e número',
        'só em gênero',
        'só em número',
        'tempo e modo',
      ],
      answer: 'gênero e número',
      explanationFa:
        'حرف تعریف باید در جنس (مذکر/مؤنث) و شمار (مفرد/جمع) با اسم هماهنگ باشد.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q20',
      type: 'mcq',
      prompt: 'Qual é o artigo definido feminino plural?',
      promptFa: 'حرف تعریف معرفهٔ مؤنثِ جمع کدام است؟',
      options: ['as', 'os', 'a', 'umas'],
      answer: 'as',
      explanationFa: 'جدول معرفه: مذکر o/os، مؤنث a/as. مؤنث جمع = «as».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q21',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ montanhas.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (montanhas مؤنث جمع).',
      options: [],
      answer: 'As',
      explanationFa: 'montanhas مؤنث و جمع است → «as montanhas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q22',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ cartão de crédito.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (cartão مذکر مفرد).',
      options: [],
      answer: 'O',
      explanationFa: 'cartão مذکر و مفرد است → «o cartão de crédito».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q23',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ computadores.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (computadores مذکر جمع).',
      options: [],
      answer: 'Os',
      explanationFa: 'computadores مذکر و جمع است → «os computadores».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q24',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: Fiz ___ lição de casa ontem.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (lição مؤنث مفرد).',
      options: [],
      answer: 'a',
      explanationFa: 'lição مؤنث و مفرد است → «a lição de casa».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q25',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo definido: ___ água da piscina estava morna.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (água مؤنث مفرد).',
      options: [],
      answer: 'A',
      explanationFa: 'água مؤنث است، هرچند با a شروع می‌شود → «a água».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q26',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: Levei ___ bolo para ___ vovó.',
      promptFa: 'دو حرف تعریف معرفه را بگذارید (bolo مذکر، vovó مؤنث).',
      options: [],
      answer: 'o / a',
      explanationFa: 'bolo مذکر → «o bolo»؛ vovó مؤنث → «a vovó».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q27',
      type: 'mcq',
      prompt: 'Em quais casos o artigo definido NÃO é obrigatório?',
      promptFa: 'کاربرد حرف تعریف معرفه در کدام حالت اجباری نیست؟',
      options: [
        'antes de nomes próprios e possessivos',
        'antes de verbos',
        'antes de plurais',
        'nunca é obrigatório',
      ],
      answer: 'antes de nomes próprios e possessivos',
      explanationFa:
        'پیش از اسم خاص و ضمیر ملکی اختیاری است: O Paulo یا Paulo؛ O meu carro یا meu carro.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q28',
      type: 'mcq',
      prompt: 'Qual país usa artigo definido?',
      promptFa: 'کدام کشور با حرف تعریف می‌آید؟',
      options: ['O Brasil', 'Portugal', 'Cuba', 'São Paulo'],
      answer: 'O Brasil',
      explanationFa:
        'برخی کشورها حرف تعریف می‌گیرند (O Brasil, A Bahia) و برخی نه (Portugal, Cuba).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q29',
      type: 'mcq',
      prompt: 'Qual é o artigo indefinido masculino plural?',
      promptFa: 'حرف تعریف نکرهٔ مذکرِ جمع کدام است؟',
      options: ['uns', 'umas', 'um', 'os'],
      answer: 'uns',
      explanationFa: 'جدول نکره: مذکر um/uns، مؤنث uma/umas. مذکر جمع = «uns».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q30',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ flores.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (flores مؤنث جمع).',
      options: [],
      answer: 'Umas',
      explanationFa: 'flor مؤنث است، جمعش flores → «umas flores».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q31',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ país.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (país مذکر مفرد).',
      options: [],
      answer: 'Um',
      explanationFa: 'país مذکر و مفرد است → «um país».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q32',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ crianças.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (crianças مؤنث جمع).',
      options: [],
      answer: 'Umas',
      explanationFa: 'criança مؤنث است، جمعش crianças → «umas crianças».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q33',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo indefinido: Chamei ___ meninos para brincar.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (meninos مذکر جمع).',
      options: [],
      answer: 'uns',
      explanationFa: 'meninos مذکر و جمع است → «uns meninos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q34',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo indefinido: Comprei ___ camisa para o meu pai.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (camisa مؤنث مفرد).',
      options: [],
      answer: 'uma',
      explanationFa: 'camisa مؤنث و مفرد است → «uma camisa».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q35',
      type: 'mcq',
      prompt: 'Em "Apenas um garoto compareceu", "um" é:',
      promptFa: 'در جملهٔ «Apenas um garoto compareceu»، واژهٔ «um» چیست؟',
      options: ['numeral', 'artigo indefinido', 'artigo definido', 'pronome'],
      answer: 'numeral',
      explanationFa:
        '«apenas» (فقط) مقدار دقیق را می‌رساند؛ پس «um» عدد است (جمع: dois).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q36',
      type: 'mcq',
      prompt: 'Em "Um garoto estava circulando no pátio", "um" é:',
      promptFa:
        'در جملهٔ «Um garoto estava circulando no pátio»، واژهٔ «um» چیست؟',
      options: ['artigo indefinido', 'numeral', 'artigo definido', 'verbo'],
      answer: 'artigo indefinido',
      explanationFa:
        'اشاره به موجودی نامشخص است، نه مقدار دقیق → حرف تعریف نکره (جمع: uns).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q37',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: R$ 634,00 reais.',
      promptFa: 'عدد ۶۳۴ را به حروف بنویسید.',
      options: [],
      answer: 'seiscentos e trinta e quatro',
      explanationFa: '۶۳۴ = seiscentos e trinta e quatro.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q38',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: 3.230 alunos.',
      promptFa: 'عدد ۳۲۳۰ را به حروف بنویسید.',
      options: [],
      answer: 'três mil duzentos e trinta',
      explanationFa:
        '۳۲۳۰ به صدگانِ کامل ختم نمی‌شود، پس میان هزار و صد «e» نمی‌آید: três mil duzentos e trinta.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q39',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: 252 policiais.',
      promptFa: 'عدد ۲۵۲ را به حروف بنویسید.',
      options: [],
      answer: 'duzentos e cinquenta e dois',
      explanationFa: '۲۵۲ = duzentos e cinquenta e dois.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q40',
      type: 'mcq',
      prompt: 'Ana e Guilherme moram no (11.º) ___ andar.',
      promptFa: 'رتبهٔ ۱۱اُم را برای «andar» انتخاب کنید:',
      options: ['décimo primeiro', 'onze', 'décimo', 'vigésimo primeiro'],
      answer: 'décimo primeiro',
      explanationFa: '۱۱اُم = décimo primeiro andar (طبقهٔ یازدهم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q41',
      type: 'fill-blank',
      prompt: 'Eles têm um apartamento no (7.º) ___ andar.',
      promptFa: 'رتبهٔ ۷اُم را برای «andar» بنویسید.',
      options: [],
      answer: 'sétimo',
      explanationFa: '۷اُم = sétimo andar (طبقهٔ هفتم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q42',
      type: 'fill-blank',
      prompt: 'O escritório fica no (6.º) ___ andar.',
      promptFa: 'رتبهٔ ۶اُم را برای «andar» بنویسید.',
      options: [],
      answer: 'sexto',
      explanationFa: '۶اُم = sexto andar (طبقهٔ ششم).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q43',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo definido: Ganhamos ___ bicicleta que esperávamos.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (bicicleta مؤنث مفرد).',
      options: [],
      answer: 'a',
      explanationFa: 'bicicleta مؤنث و مفرد است → «a bicicleta».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q44',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo definido: Luísa aproveitou para rever ___ amigos.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (amigos مذکر جمع).',
      options: [],
      answer: 'os',
      explanationFa: 'amigos مذکر و جمع است → «os amigos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q45',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo indefinido: Eu estou lendo ___ livro muito interessante.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (livro مذکر مفرد).',
      options: [],
      answer: 'um',
      explanationFa: 'livro مذکر و مفرد است → «um livro».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q46',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo indefinido: Na frente da minha casa tem ___ árvore.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (árvore مؤنث مفرد).',
      options: [],
      answer: 'uma',
      explanationFa: 'árvore مؤنث و مفرد است → «uma árvore».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q47',
      type: 'translate-fa-pt',
      prompt: '«امروز بیست‌ودوم ماه مه است.» را به پرتغالی بنویسید.',
      promptFa: 'این جمله را به پرتغالی برزیلی ترجمه کنید (تاریخ با عدد اصلی).',
      options: [],
      answer: 'Hoje é vinte e dois de maio.',
      explanationFa:
        'روزهای ماه (جز روز اول) با عدد اصلی گفته می‌شوند: vinte e dois de maio.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q48',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ cão.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (cão مذکر مفرد).',
      options: [],
      answer: 'O',
      explanationFa: 'cão (سگ) مذکر و مفرد است → «o cão».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q49',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ empresas.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (empresas مؤنث جمع).',
      options: [],
      answer: 'As',
      explanationFa: 'empresa مؤنث است، جمعش empresas → «as empresas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q50',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ telefones.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (telefones مذکر جمع).',
      options: [],
      answer: 'Os',
      explanationFa: 'telefone مذکر است، جمعش telefones → «os telefones».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q51',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ motorista.',
      promptFa:
        'حرف تعریف معرفهٔ درست را بگذارید (motorista دوجنسی است؛ برای مذکر).',
      options: [],
      answer: 'O',
      explanationFa:
        'motorista دوجنسی است؛ جنس با حرف تعریف مشخص می‌شود: «o motorista» (مرد) یا «a motorista» (زن).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q52',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ repórter.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (repórter؛ برای مذکر).',
      options: [],
      answer: 'O',
      explanationFa:
        'repórter دوجنسی است: «o repórter» (مرد) یا «a repórter» (زن).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q53',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo definido: ___ ondas faziam o navio balançar.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (ondas مؤنث جمع).',
      options: [],
      answer: 'As',
      explanationFa: 'onda مؤنث است، جمعش ondas → «as ondas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q54',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo definido: Renato está brincando com ___ meninos na rua.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (meninos مذکر جمع).',
      options: [],
      answer: 'os',
      explanationFa: 'meninos مذکر و جمع است → «os meninos».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q55',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ carro.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (carro مذکر مفرد).',
      options: [],
      answer: 'Um',
      explanationFa: 'carro مذکر و مفرد است → «um carro».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q56',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ mulher.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (mulher مؤنث مفرد).',
      options: [],
      answer: 'Uma',
      explanationFa: 'mulher مؤنث و مفرد است → «uma mulher».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q57',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ fotografia.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (fotografia مؤنث مفرد).',
      options: [],
      answer: 'Uma',
      explanationFa: 'fotografia مؤنث و مفرد است → «uma fotografia».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q58',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ festa.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (festa مؤنث مفرد).',
      options: [],
      answer: 'Uma',
      explanationFa: 'festa مؤنث و مفرد است → «uma festa».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q59',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ cidade.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (cidade مؤنث مفرد).',
      options: [],
      answer: 'Uma',
      explanationFa: 'cidade مؤنث و مفرد است → «uma cidade».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q60',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ presente.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (presente مذکر مفرد).',
      options: [],
      answer: 'Um',
      explanationFa: 'presente (هدیه) مذکر و مفرد است → «um presente».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q61',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo indefinido: Peguei ___ panela para cozinhar.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (panela مؤنث مفرد).',
      options: [],
      answer: 'uma',
      explanationFa: 'panela مؤنث و مفرد است → «uma panela».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q62',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: ___ dia iremos nos encontrar.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (dia مذکر مفرد).',
      options: [],
      answer: 'Um',
      explanationFa:
        'dia مذکر است (استثنا: با a ختم می‌شود ولی مذکر است) → «um dia».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q63',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo indefinido: Joana convidou ___ amigas estrangeiras para a festa.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (amigas مؤنث جمع).',
      options: [],
      answer: 'umas',
      explanationFa: 'amigas مؤنث و جمع است → «umas amigas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q64',
      type: 'fill-blank',
      prompt: 'Escreva por extenso o numeral: Tenho 2 (___) notas.',
      promptFa: 'عدد ۲ را به حروف بنویسید (notas مؤنث).',
      options: [],
      answer: 'duas',
      explanationFa: 'notas مؤنث است، پس عدد ۲ هم مؤنث می‌شود → «duas notas».',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q65',
      type: 'fill-blank',
      prompt: 'Escreva por extenso: R$ 50,00 reais.',
      promptFa: 'عدد ۵۰ را به حروف بنویسید.',
      options: [],
      answer: 'cinquenta',
      explanationFa: '۵۰ = cinquenta (پنجاه).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-4-q66',
      type: 'fill-blank',
      prompt: 'Complete com o artigo definido: ___ meninas foram viajar.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (meninas مؤنث جمع).',
      options: [],
      answer: 'As',
      explanationFa: 'meninas مؤنث و جمع است → «as meninas».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q67',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo definido: Ela está feliz com ___ novo trabalho.',
      promptFa: 'حرف تعریف معرفهٔ درست را بگذارید (trabalho مذکر مفرد).',
      options: [],
      answer: 'o',
      explanationFa: 'trabalho مذکر و مفرد است → «o novo trabalho».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q68',
      type: 'fill-blank',
      prompt:
        'Complete com o artigo indefinido: Nós vamos viajar para ___ cidade no interior.',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (cidade مؤنث مفرد).',
      options: [],
      answer: 'uma',
      explanationFa: 'cidade مؤنث و مفرد است → «uma cidade».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-4-q69',
      type: 'fill-blank',
      prompt: 'Complete com o artigo indefinido: Você comprou ___ carro novo?',
      promptFa: 'حرف تعریف نکرهٔ درست را بگذارید (carro مذکر مفرد).',
      options: [],
      answer: 'um',
      explanationFa: 'carro مذکر و مفرد است → «um carro».',
      cefr: 'A1',
      skill: 'grammar',
    },
  ],
  estimatedMinutes: 30,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 4 (کامل).',
};
