import type { CourseLesson } from '@/domain/content/schema';

export const aula9: CourseLesson = {
  id: 'course-aula-9',
  order: 9,
  aula: 'Aula 9',
  titleFa: 'افعال ۳ — تمرین (افعال باقاعده و بی‌قاعده)',
  titlePt: 'Verbos 3 — Prática (Regulares e Irregulares)',
  cefr: 'A2',
  summaryFa:
    'این درس یک درسِ تمرینی کامل است که صرف افعال را در چهار زمانِ اصلی جمع‌بندی و تمرین می‌کند: زمان حال (Presente do Indicativo)، گذشتهٔ ساده/کامل (Pretérito Perfeito)، گذشتهٔ استمراری (Pretérito Imperfeito) و آینده (Futuro به‌شکل برزیلی: ir + مصدر). ابتدا الگوی صرفِ افعال باقاعدهٔ سه گروه (پایانه‌های ‑AR / ‑ER / ‑IR) و مهم‌ترین افعال بی‌قاعده (SER, IR, FAZER, ESTAR, PEDIR, VESTIR) را مرور می‌کنید و سپس با ده‌ها تمرینِ پرکردنی — از یک گفت‌وگوی معرفی گرفته تا جمله‌های مربوط به مدارک اقامت و کار در برزیل و زندگی روزمره — همهٔ این صرف‌ها را تمرین می‌کنید.',
  objectivesFa: [
    'تفاوت افعال باقاعده و بی‌قاعده و سه گروهِ ‑AR / ‑ER / ‑IR را بشناسید.',
    'صرف افعال باقاعده را در زمان حال، گذشتهٔ کامل، گذشتهٔ استمراری و آینده به‌کار ببرید.',
    'افعال بی‌قاعدهٔ پرکاربرد SER و IR و FAZER را در جمله درست صرف کنید.',
    'زمان آیندهٔ برزیلی را با ساختار «ir در زمان حال + مصدر» بسازید.',
    'فعل درست را در جمله‌های مربوط به مدارک (CPF, RNE, Carteira de Trabalho)، کار و زندگی روزمره انتخاب و صرف کنید.',
  ],
  sections: [
    {
      headingFa: '۱. افعال باقاعده و بی‌قاعده و سه گروه صرف',
      bodyFa:
        'افعال پرتغالی بر اساس پایانهٔ مصدر به سه گروه تقسیم می‌شوند:\n\nگروه اول: پایانهٔ ‑AR (falar, trabalhar, morar, tomar, comprar)\nگروه دوم: پایانهٔ ‑ER (comer, escrever, receber, beber)\nگروه سوم: پایانهٔ ‑IR (partir, dividir, existir)\n\nافعالِ «باقاعده» (regulares) از یک الگوی ثابتِ پایانه پیروی می‌کنند و ریشه‌شان تغییر نمی‌کند. افعالِ «بی‌قاعده» (irregulares) مانند SER، IR، FAZER، ESTAR، PEDIR و VESTIR الگوی خاص خودشان را دارند و باید حفظ شوند. در این درس هر دو دسته را در چهار زمان تمرین می‌کنیم.',
      examples: [
        {
          pt: 'falar (‑AR), comer (‑ER), partir (‑IR)',
          fa: 'حرف زدن (گروه ۱)، خوردن (گروه ۲)، رفتن/عزیمت (گروه ۳)',
          pron: 'فالار، کُمِر، پارتیر',
          note: 'سه فعلِ نمونه برای سه گروهِ باقاعده.',
        },
        {
          pt: 'ser, ir, fazer — verbos irregulares',
          fa: 'بودن، رفتن، انجام‌دادن — افعال بی‌قاعده',
          pron: 'سِر، ایر، فازِر',
        },
      ],
    },
    {
      headingFa: '۲. زمان حال (Presente do Indicativo) — افعال باقاعده',
      bodyFa:
        'در برزیل چهار شخصِ کاربردی داریم: EU / VOCÊ‑ELE‑ELA‑A GENTE / NÓS / VOCÊS‑ELES‑ELAS. پایانه‌های زمان حالِ افعال باقاعده:\n\nگروه ‑AR (falar):\nEU falo\nVOCÊ/ELE/ELA/A GENTE fala\nNÓS falamos\nVOCÊS/ELES/ELAS falam\n\nگروه ‑ER (comer):\nEU como\nVOCÊ/ELE/ELA/A GENTE come\nNÓS comemos\nVOCÊS/ELES/ELAS comem\n\nگروه ‑IR (partir):\nEU parto\nVOCÊ/ELE/ELA/A GENTE parte\nNÓS partimos\nVOCÊS/ELES/ELAS partem',
      examples: [
        {
          pt: 'Eu acordo cedo. Meus pais acordam mais tarde.',
          fa: 'من زود بیدار می‌شوم. پدر و مادرم دیرتر بیدار می‌شوند.',
          pron: 'اِئو آکوردو سِدو. مِئوس پایس آکوردام مایس تارجی',
          note: 'acordar فعل باقاعدهٔ ‑AR است.',
        },
        {
          pt: 'Eu como pouco. Os meus tios comem arroz com feijão.',
          fa: 'من کم می‌خورم. عموها/دایی‌هایم برنج با لوبیا می‌خورند.',
          pron: 'اِئو کُمو پُوکو. اوس مِئوس تیوس کُمِین آخوز کُن فِیژائو',
        },
        {
          pt: 'Eu parto cedo de casa. Nós não partimos sozinhos.',
          fa: 'من زود از خانه بیرون می‌روم. ما تنها بیرون نمی‌رویم.',
          pron: 'اِئو پارتو سِدو جی کازا. نُس نائو پارتیموس سُزینیوس',
        },
      ],
    },
    {
      headingFa: '۳. گذشتهٔ کامل (Pretérito Perfeito) — افعال باقاعده',
      bodyFa:
        'گذشتهٔ کامل برای کارِ تمام‌شده در گذشته به‌کار می‌رود (دیروز، هفتهٔ گذشته، پارسال). پایانه‌ها:\n\nگروه ‑AR (tirar):\nEU tirei\nVOCÊ/ELE/ELA tirou\nNÓS tiramos\nELES/ELAS tiraram\n\nگروه ‑ER (receber):\nEU recebi\nVOCÊ/ELE/ELA recebeu\nNÓS recebemos\nELES/ELAS receberam\n\nگروه ‑IR (partir):\nEU parti\nVOCÊ/ELE/ELA partiu\nNÓS partimos\nELES/ELAS partiram\n\nنکتهٔ املایی: بعضی افعال ‑AR در اول‌شخص تغییر املایی دارند تا صدا حفظ شود، مثلاً explicar → expliquei، ficar → fiquei.',
      examples: [
        {
          pt: 'Eu já tirei a minha Carteira de Trabalho.',
          fa: 'من همین حالا کارت کارم را گرفتم.',
          pron: 'اِئو ژا تیرِی آ مینیا کارتِیرا جی ترابالیو',
        },
        {
          pt: 'Meu chefe me explicou as regras.',
          fa: 'رئیسم قوانین را برایم توضیح داد.',
          pron: 'مِئو شِفی می اِکسپلیکُو آس هِگراس',
          note: 'explicar → expliquei (اول‌شخص) / explicou (سوم‌شخص).',
        },
        {
          pt: 'Ana e Estevam pediram um bolo na padaria.',
          fa: 'آنا و اِستِوام یک کیک از نانوایی سفارش دادند.',
          pron: 'آنا ای اِستِوام پِدیرام اون بولو',
        },
      ],
    },
    {
      headingFa: '۴. گذشتهٔ استمراری (Pretérito Imperfeito)',
      bodyFa:
        'گذشتهٔ استمراری برای کارِ عادتی یا موقعیتِ ادامه‌دار در گذشته است («در کشورم …»، «قبلاً …»). پایانه‌ها:\n\nگروه ‑AR (trabalhar):\nEU trabalhava\nVOCÊ/ELE/ELA trabalhava\nNÓS trabalhávamos\nELES/ELAS trabalhavam\n\nگروه ‑ER و ‑IR (comer / dividir):\nEU comia / dividia\nVOCÊ/ELE/ELA comia / dividia\nNÓS comíamos / dividíamos\nELES/ELAS comiam / dividiam',
      examples: [
        {
          pt: 'No meu país, eu trabalhava como professor.',
          fa: 'در کشورم، من به‌عنوان معلم کار می‌کردم.',
          pron: 'نو مِئو پاییس، اِئو ترابالیاوا کُمو پروفِسور',
        },
        {
          pt: 'No meu país, eu comia arroz todos os dias.',
          fa: 'در کشورم، من هر روز برنج می‌خوردم.',
          pron: 'اِئو کُمیا آخوز تودوس اوس دیاس',
        },
        {
          pt: 'Eu e meus pais morávamos em outro continente.',
          fa: 'من و پدر و مادرم در قارهٔ دیگری زندگی می‌کردیم.',
          pron: 'اِئو ای مِئوس پایس موراواموس',
        },
      ],
    },
    {
      headingFa: '۵. آینده (Futuro) — ساختار برزیلی «ir + مصدر»',
      bodyFa:
        'در گفتار برزیلی، آینده معمولاً با فعلِ IR در زمان حال + مصدرِ فعل ساخته می‌شود:\n\nEU vou + مصدر (vou comprar = خواهم خرید)\nVOCÊ/ELE/ELA vai + مصدر (vai ser = خواهد بود)\nNÓS vamos + مصدر (vamos fazer = انجام خواهیم داد)\nVOCÊS/ELES/ELAS vão + مصدر (vão comer = خواهند خورد)\n\nنکته: وقتی خودِ فعلِ اصلی «ir» باشد، آن را تکرار نمی‌کنیم؛ فقط IR را صرف می‌کنیم: «Amanhã eu vou à praia» (فردا به ساحل می‌روم)، «nós vamos ao cinema» (به سینما می‌رویم).',
      examples: [
        {
          pt: 'Amanhã eu vou à praia e depois nós vamos ao cinema.',
          fa: 'فردا به ساحل می‌روم و بعد با هم به سینما می‌رویم.',
          pron: 'آمانیا اِئو وُ آ پرایا ای دِپویس نُس واموس آئو سینِما',
        },
        {
          pt: 'Domingo nós vamos fazer um grande almoço em família.',
          fa: 'یکشنبه یک ناهار بزرگ خانوادگی درست می‌کنیم.',
          pron: 'دومینگو نُس واموس فازِر اون گرانجی آلموسو',
        },
        {
          pt: 'Tenho certeza que amanhã vai ser um grande dia para você!',
          fa: 'مطمئنم فردا روز بزرگی برایت خواهد بود!',
          pron: 'تِنیو سِرتِزا کی آمانیا وای سِر اون گرانجی دیا',
        },
      ],
    },
    {
      headingFa: '۶. فعل بی‌قاعدهٔ SER (بودن)',
      bodyFa:
        'SER فعلِ بی‌قاعده برای هویت، ملیت، شغل و ویژگی‌های ثابت است. زمان حال:\n\nEU sou\nVOCÊ/ELE/ELA/A GENTE é\nNÓS somos\nVOCÊS/ELES/ELAS são\n\nدر گفت‌وگوی معرفی: «Qual é seu nome?» (نامت چیست؟)، «Eu sou a Andreia» (من آندریا هستم)، «Você é estudante?» (تو دانشجویی؟).',
      examples: [
        {
          pt: 'Como é seu nome? — Meu nome é Carol.',
          fa: 'نامت چیست؟ — نام من کارول است.',
          pron: 'کُمو اِ سِئو نُمی؟ — مِئو نُمی اِ کارول',
        },
        {
          pt: 'Eu sou a Andreia. Você é estudante?',
          fa: 'من آندریا هستم. تو دانشجویی؟',
          pron: 'اِئو سُ آ آندرِیا. وُسه اِ اِستودانتی؟',
        },
        {
          pt: 'Não, eu sou professora.',
          fa: 'نه، من معلم (زن) هستم.',
          pron: 'نائو، اِئو سُ پروفِسورا',
        },
      ],
    },
    {
      headingFa: '۷. فعل بی‌قاعدهٔ IR (رفتن)',
      bodyFa:
        'IR فعلِ بی‌قاعده برای «رفتن» و نیز پایهٔ ساختِ زمان آینده است. زمان حال:\n\nEU vou\nVOCÊ/ELE/ELA/A GENTE vai\nNÓS vamos\nVOCÊS/ELES/ELAS vão\n\nحرف اضافه پس از ir معمولاً «a/ao/à» یا «para» است: ir ao cinema، ir para a escola.',
      examples: [
        {
          pt: 'Maria vai ao cinema. Eu vou ao parque.',
          fa: 'ماریا به سینما می‌رود. من به پارک می‌روم.',
          pron: 'ماریا وای آئو سینِما. اِئو وُ آئو پارکی',
        },
        {
          pt: 'Eu e Luciana vamos para uma festa.',
          fa: 'من و لوسیانا به یک مهمانی می‌رویم.',
          pron: 'اِئو ای لوسیانا واموس پارا اوما فِستا',
        },
        {
          pt: 'Vocês nunca vão para a piscina com a gente.',
          fa: 'شما هیچ‌وقت با ما به استخر نمی‌آیید.',
          pron: 'وُسِس نونکا وائو پارا آ پیسینا کُن آ جِنتی',
        },
      ],
    },
    {
      headingFa: '۸. افعال بی‌قاعدهٔ FAZER و ESTAR در آینده',
      bodyFa:
        'در تمرین‌های آینده این افعال بی‌قاعده هم می‌آیند، اما چون آینده را با «ir + مصدر» می‌سازیم، فقط مصدرِ آن‌ها را به‌کار می‌بریم:\n\nvamos fazer (انجام خواهیم داد)\nvamos estar (خواهیم بود ـ حالت/مکان موقتی)\nvai ser (خواهد بود ـ ویژگی ثابت)\n\nیادآوری تفاوت SER/ESTAR: SER برای ثابت، ESTAR برای موقتی و مکان.',
      examples: [
        {
          pt: 'Hoje, mais tarde, nós vamos estar todos juntos na festa.',
          fa: 'امروز، کمی بعد، همه با هم در مهمانی خواهیم بود.',
          pron: 'اُژی مایس تارجی نُس واموس اِستار تودوس ژونتوس',
        },
        {
          pt: 'Domingo nós vamos fazer um grande almoço.',
          fa: 'یکشنبه یک ناهار بزرگ درست می‌کنیم.',
          pron: 'نُس واموس فازِر اون گرانجی آلموسو',
        },
      ],
    },
    {
      headingFa: '۹. افعال بی‌قاعدهٔ PEDIR / VESTIR / DIRIGIR',
      bodyFa:
        'این افعال ‑IR در زمان حالِ اول‌شخص تغییرِ مصوت دارند (e→i در ریشه)، اما در گذشتهٔ کامل مانند افعال باقاعده صرف می‌شوند:\n\nحال: eu peço / visto / dirijo — ele pede / veste / dirige\nگذشتهٔ کامل: eu pedi, ele pediu, eles pediram / eu vesti, ele vestiu / eu dirigi, ele dirigiu\n\nدر تمرین‌های این درس بیشتر زمانِ گذشتهٔ کاملِ آن‌ها به‌کار رفته است.',
      examples: [
        {
          pt: 'Ele pediu brigadeiro de sobremesa de novo.',
          fa: 'او دوباره بریگادیرو برای دسر سفارش داد.',
          pron: 'اِلی پِدیو بریگادِیرو جی سوبرِمِزا',
        },
        {
          pt: 'Meu primo vestiu roupas quentes porque estava frio ontem.',
          fa: 'پسرعمویم لباس گرم پوشید چون دیروز هوا سرد بود.',
          pron: 'مِئو پریمو وِستیو هُپاس کِنتِس',
        },
        {
          pt: 'O motorista dirigiu o ônibus com cuidado ontem.',
          fa: 'راننده دیروز اتوبوس را با احتیاط راند.',
          pron: 'او موتوریستا دیریژیو او اونیبوس',
        },
      ],
    },
    {
      headingFa: '۱۰. واژگان و افعالِ مربوط به مدارک (زمان حال)',
      bodyFa:
        'بخشی از تمرین‌ها دربارهٔ مدارک قانونیِ زندگی و کار در برزیل است. افعال باقاعده در زمان حال:\n\nprecisar (نیاز داشتن) → eu preciso, você precisa\nsignificar (معنی دادن) → significa\nexistir (وجود داشتن) → existe\nencontrar (پیدا کردن) → encontra\nficar (واقع بودن) → fica\natender (پاسخ‌گویی کردن) → atende\n\nمدارک: CPF = Cadastro da Pessoa Física؛ RNE = Registro Nacional de Estrangeiro؛ Carteira de Trabalho = کارت کار؛ CRAI = Centro de Referência e Acolhida para Imigrantes (مرکز مرجع و پذیرش مهاجران).',
      examples: [
        {
          pt: 'Eu preciso tirar CPF, RNE e Carteira de Trabalho.',
          fa: 'من باید CPF و RNE و کارت کار بگیرم.',
          pron: 'اِئو پرِسیزو تیرار',
          note: 'precisar + مصدر = «باید/لازم است».',
        },
        {
          pt: 'CPF significa Cadastro da Pessoa Física.',
          fa: 'CPF یعنی «ثبت شخص حقیقی».',
          pron: 'سِپِاِفی سیگنیفیکا',
        },
        {
          pt: 'O CRAI fica na Rua Japurá, 212 – Bela Vista, e atende pelo telefone 3598-7200.',
          fa: 'CRAI در خیابان ژاپورا، شمارهٔ ۲۱۲ – بلا ویستا واقع است و با تلفن ۳۵۹۸-۷۲۰۰ پاسخ‌گوست.',
          pron: 'او کرای فیکا نا هوا ژاپورا',
        },
      ],
    },
    {
      headingFa: '۱۱. واژگان و افعالِ مربوط به کار (گذشتهٔ کامل)',
      bodyFa:
        'بخش دیگر تمرین‌ها دربارهٔ حقوق کار است. افعال باقاعده در گذشتهٔ کامل:\n\ntirar (گرفتن ـ مدرک) → tirei/tirou\nregularizar (قانونی کردن) → regularizou\nassinar (امضا کردن) → assinei\ncontratar (استخدام کردن) → contratou\ntrabalhar (کار کردن) → trabalhei/trabalhou\ndescobrir (کشف کردن) → descobri\npassar (گذشتن/رد شدن) → passou\nexplicar (توضیح دادن) → explicou/expliquei\nreceber (دریافت کردن) → recebi/recebeu\nfolgar (مرخصی داشتن) → folgou\nconseguir (موفق شدن/به‌دست آوردن) → consegui\n\nنکته‌های حقوق کار: کارِ بیش از ۸ ساعت → hora extra؛ کارِ شبانه (۲۲ تا ۵) → adicional noturno ۲۰٪؛ یک روز مرخصی در هفته (folga)؛ کسورات حقوق: INSS، مالیات، اتحادیه، بلیط ایاب‌وذهاب.',
      examples: [
        {
          pt: 'A empresa me contratou por 90 dias.',
          fa: 'شرکت مرا برای ۹۰ روز استخدام کرد.',
          pron: 'آ اِمپرِزا می کُنتراتُو پور نووِنتا دیاس',
        },
        {
          pt: 'Eu trabalhei 12 horas por dia, mas depois descobri que o trabalho decente é de no máximo 8 horas.',
          fa: 'من روزی ۱۲ ساعت کار کردم، اما بعد فهمیدم کارِ شایسته حداکثر ۸ ساعت است.',
          pron: 'اِئو ترابالیِی دوزی اوراس',
        },
        {
          pt: 'Ontem eu recebi o meu salário com o adicional noturno de 20%.',
          fa: 'دیروز حقوقم را با ۲۰٪ فوق‌العادهٔ شب‌کاری گرفتم.',
          pron: 'اُنتِم اِئو هِسِبی او مِئو سالاریو',
        },
      ],
    },
    {
      headingFa: '۱۲. افعالِ زندگی روزمره (خوردن، نوشیدن، پوشیدن، رانندگی)',
      bodyFa:
        'در تمرین‌های پایانی افعال روزمره در گذشتهٔ کامل و آینده تمرین می‌شوند:\n\ntomar (نوشیدن/گرفتن) → tomei/tomou\ncomer (خوردن) → comi/comeu\npedir (سفارش دادن) → pedi/pediu/pediram\nescrever (نوشتن) → escrevi/escreveu\nentregar (تحویل دادن) → entregou\naprender (یاد گرفتن) → aprenderam\nbeber (نوشیدن) → bebi (آینده: vamos beber)\ncomprar (خریدن) → comprei (آینده: vou/vai comprar)\narrumar (مرتب کردن) → آینده: vão arrumar\n\nواژگان: leite com mel (شیر با عسل)، suco (آبمیوه)، refrigerante (نوشابه)، frango assado (مرغ کبابی)، pastel، bolo (کیک)، brigadeiro، lanche (میان‌وعده).',
      examples: [
        {
          pt: 'Karen tomou leite com mel ontem à noite.',
          fa: 'کارِن دیشب شیر با عسل نوشید.',
          pron: 'کارِن تُمُو لِیتی کُن مِل',
        },
        {
          pt: 'O carteiro entregou cartas para mim semana passada.',
          fa: 'پستچی هفتهٔ گذشته برایم نامه‌ها را تحویل داد.',
          pron: 'او کارتِیرو اِنترِگُو کارتاس',
        },
        {
          pt: 'Quarta-feira ela vai comprar um computador novo.',
          fa: 'چهارشنبه او یک کامپیوتر جدید می‌خرد.',
          pron: 'کوارتا-فِیرا اِلا وای کُمپرار',
        },
      ],
    },
  ],
  keyPointsFa: [
    'سه گروهِ باقاعده: ‑AR / ‑ER / ‑IR؛ هر گروه پایانه‌های خاص خود را در هر زمان دارد.',
    'زمان حالِ باقاعده: falo/fala/falamos/falam؛ como/come/comemos/comem؛ parto/parte/partimos/partem.',
    'گذشتهٔ کامل باقاعده: ‑ei/‑ou/‑amos/‑aram (‑AR)؛ ‑i/‑eu/‑emos/‑eram (‑ER)؛ ‑i/‑iu/‑imos/‑iram (‑IR).',
    'گذشتهٔ استمراری: ‑ava (‑AR) و ‑ia (‑ER/‑IR) برای کارِ عادتی در گذشته.',
    'آیندهٔ برزیلی = IR در حال (vou/vai/vamos/vão) + مصدر؛ اگر خودِ فعل «ir» باشد فقط IR صرف می‌شود.',
    'SER بی‌قاعده: sou/é/somos/são؛ IR بی‌قاعده: vou/vai/vamos/vão.',
    'املای اول‌شخص گذشته: explicar→expliquei، ficar→fiquei (حفظ صدای k).',
  ],
  quiz: [
    {
      id: 'course-aula-9-q1',
      type: 'fill-blank',
      prompt:
        'Complete o diálogo com o verbo SER (presente): Como ___ seu nome? — Meu nome ___ Carol. E você, qual ___ seu nome? — Eu ___ a Andreia. Você ___ estudante? — ___, sim. E você também ___ estudante? — Não, eu ___ professora.',
      promptFa: 'گفت‌وگوی معرفی را با فعل SER در زمان حال کامل کنید (به‌ترتیب هشت جای خالی).',
      options: [],
      answer: ['é', 'é', 'é', 'sou', 'é', 'Sou', 'é', 'sou'],
      explanationFa:
        'SER: eu sou، você/ele/ela é. برای «تو/او» → é و برای «من» → sou. پاسخِ «Você é estudante?» می‌شود «Sou, sim».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q2',
      type: 'fill-blank',
      prompt: 'Maria ___ ao cinema. (IR, presente)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'vai',
      explanationFa: 'IR سوم‌شخص مفرد → vai.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q3',
      type: 'fill-blank',
      prompt: 'Eu ___ ao parque. (IR)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (اول‌شخص مفرد).',
      options: [],
      answer: 'vou',
      explanationFa: 'IR اول‌شخص مفرد → vou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q4',
      type: 'fill-blank',
      prompt: 'Mário ___ para a escola. (IR)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'vai',
      explanationFa: 'IR سوم‌شخص مفرد → vai.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q5',
      type: 'fill-blank',
      prompt: 'Eu e Luciana ___ para uma festa. (IR)',
      promptFa: 'با فعل IR در زمان حال کامل کنید («من و لوسیانا» = ما).',
      options: [],
      answer: 'vamos',
      explanationFa: '«Eu e Luciana» = nós → vamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q6',
      type: 'fill-blank',
      prompt: 'João e Tatiana ___ para o trabalho. (IR)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'vão',
      explanationFa: 'IR سوم‌شخص جمع → vão.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q7',
      type: 'fill-blank',
      prompt: 'Vocês nunca ___ para a piscina com a gente. (IR)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (vocês).',
      options: [],
      answer: 'vão',
      explanationFa: 'vocês → vão.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q8',
      type: 'fill-blank',
      prompt: 'Eu ___ cedo durante a semana. (acordar, presente)',
      promptFa: 'فعل acordar را در زمان حال صرف کنید (eu).',
      options: [],
      answer: 'acordo',
      explanationFa: '‑AR اول‌شخص مفرد → acordo.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q9',
      type: 'fill-blank',
      prompt: 'Meus pais ___ mais tarde durante o fim de semana. (acordar)',
      promptFa: 'فعل acordar را در زمان حال صرف کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'acordam',
      explanationFa: '‑AR سوم‌شخص جمع → acordam.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q10',
      type: 'fill-blank',
      prompt: 'Minha irmã não ___ cedo aos domingos. (acordar)',
      promptFa: 'فعل acordar را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'acorda',
      explanationFa: '‑AR سوم‌شخص مفرد → acorda.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q11',
      type: 'fill-blank',
      prompt: 'Minha avó ___ bastante aos sábados. (comer)',
      promptFa: 'فعل comer را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'come',
      explanationFa: '‑ER سوم‌شخص مفرد → come.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q12',
      type: 'fill-blank',
      prompt: 'Eu ___ pouco durante o verão. (comer)',
      promptFa: 'فعل comer را در زمان حال صرف کنید (eu).',
      options: [],
      answer: 'como',
      explanationFa: '‑ER اول‌شخص مفرد → como.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q13',
      type: 'fill-blank',
      prompt: 'Os seus tios ___ arroz com feijão? (comer)',
      promptFa: 'فعل comer را در زمان حال صرف کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'comem',
      explanationFa: '‑ER سوم‌شخص جمع → comem.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q14',
      type: 'fill-blank',
      prompt: 'Meu primo ___ na segunda-feira para São Paulo. (partir)',
      promptFa: 'فعل partir را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'parte',
      explanationFa: '‑IR سوم‌شخص مفرد → parte.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q15',
      type: 'fill-blank',
      prompt: 'Eu ___ cedo de casa. (partir)',
      promptFa: 'فعل partir را در زمان حال صرف کنید (eu).',
      options: [],
      answer: 'parto',
      explanationFa: '‑IR اول‌شخص مفرد → parto.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q16',
      type: 'fill-blank',
      prompt: 'Nós não ___ de casa sozinhos sem nossos pais. (partir)',
      promptFa: 'فعل partir را در زمان حال صرف کنید (nós).',
      options: [],
      answer: 'partimos',
      explanationFa: '‑IR اول‌شخص جمع → partimos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q17',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ como professor. (trabalhar, pretérito imperfeito)',
      promptFa: 'فعل trabalhar را در گذشتهٔ استمراری صرف کنید (eu).',
      options: [],
      answer: 'trabalhava',
      explanationFa: '‑AR گذشتهٔ استمراری اول‌شخص → trabalhava.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q18',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ arroz todos os dias. (comer, pretérito imperfeito)',
      promptFa: 'فعل comer را در گذشتهٔ استمراری صرف کنید (eu).',
      options: [],
      answer: 'comia',
      explanationFa: '‑ER گذشتهٔ استمراری اول‌شخص → comia.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q19',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ a minha casa com amigos. (dividir, pretérito imperfeito)',
      promptFa: 'فعل dividir را در گذشتهٔ استمراری صرف کنید (eu).',
      options: [],
      answer: 'dividia',
      explanationFa: '‑IR گذشتهٔ استمراری اول‌شخص → dividia.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q20',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ café no café da manhã. (tomar, pretérito imperfeito)',
      promptFa: 'فعل tomar را در گذشتهٔ استمراری صرف کنید (eu).',
      options: [],
      answer: 'tomava',
      explanationFa: '‑AR گذشتهٔ استمراری اول‌شخص → tomava.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q21',
      type: 'fill-blank',
      prompt: 'Na minha cidade, eu ___ de caminhar no parque. (gostar, pretérito imperfeito)',
      promptFa: 'فعل gostar را در گذشتهٔ استمراری صرف کنید (eu).',
      options: [],
      answer: 'gostava',
      explanationFa: '‑AR گذشتهٔ استمراری اول‌شخص → gostava.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q22',
      type: 'fill-blank',
      prompt:
        'Eu ___ tirar CPF, RNE e Carteira de Trabalho para ter documentação legal no Brasil. (precisar, presente)',
      promptFa: 'فعل precisar را در زمان حال صرف کنید (eu).',
      options: [],
      answer: 'preciso',
      explanationFa: 'precisar اول‌شخص مفرد → preciso.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q23',
      type: 'fill-blank',
      prompt: 'CPF ___ Cadastro da Pessoa Física. (significar, presente)',
      promptFa: 'فعل significar را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'significa',
      explanationFa: 'significar سوم‌شخص مفرد → significa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q24',
      type: 'fill-blank',
      prompt: 'Você ___ ir até a Receita Federal para tirar o CPF. (precisar)',
      promptFa: 'فعل precisar را در زمان حال صرف کنید (você).',
      options: [],
      answer: 'precisa',
      explanationFa: 'você → precisa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q25',
      type: 'fill-blank',
      prompt: 'RNE ___ Registro Nacional de Estrangeiro. (significar)',
      promptFa: 'فعل significar را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'significa',
      explanationFa: 'significar سوم‌شخص مفرد → significa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q26',
      type: 'fill-blank',
      prompt: 'Você ___ ir até a Polícia Federal para tirar o RNE. (precisar)',
      promptFa: 'فعل precisar را در زمان حال صرف کنید (você).',
      options: [],
      answer: 'precisa',
      explanationFa: 'você → precisa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q27',
      type: 'fill-blank',
      prompt:
        'Você ___ ir até a Superintendência Regional do Trabalho e Emprego para tirar a Carteira de Trabalho. (precisar)',
      promptFa: 'فعل precisar را در زمان حال صرف کنید (você).',
      options: [],
      answer: 'precisa',
      explanationFa: 'você → precisa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q28',
      type: 'fill-blank',
      prompt: 'Eu ___ e ___ trabalho todos os dias. (acordar / procurar, presente)',
      promptFa: 'دو فعل را در زمان حال صرف کنید (eu): acordar و procurar.',
      options: [],
      answer: ['acordo', 'procuro'],
      explanationFa: '‑AR اول‌شخص مفرد → acordo / procuro.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q29',
      type: 'fill-blank',
      prompt: 'Para informações e apoio geral ___ o CRAI. (existir, presente)',
      promptFa: 'فعل existir را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'existe',
      explanationFa: 'existir سوم‌شخص مفرد → existe.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q30',
      type: 'fill-blank',
      prompt:
        'No CRAI você ___ informações e orientações jurídicas para refugiados e imigrantes. (encontrar, presente)',
      promptFa: 'فعل encontrar را در زمان حال صرف کنید (você).',
      options: [],
      answer: 'encontra',
      explanationFa: 'você → encontra.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q31',
      type: 'fill-blank',
      prompt: 'O CRAI ___ na Rua Japurá, 212 – Bela Vista. (ficar, presente)',
      promptFa: 'فعل ficar را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'fica',
      explanationFa: 'ficar سوم‌شخص مفرد → fica (به معنی «واقع بودن»).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q32',
      type: 'fill-blank',
      prompt: 'O CRAI ___ pelo telefone 3598-7200. (atender, presente)',
      promptFa: 'فعل atender را در زمان حال صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'atende',
      explanationFa: 'atender سوم‌شخص مفرد → atende.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q33',
      type: 'fill-blank',
      prompt: 'Eu já ___ a minha Carteira de Trabalho. (tirar, pretérito perfeito)',
      promptFa: 'فعل tirar را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'tirei',
      explanationFa: '‑AR گذشتهٔ کامل اول‌شخص → tirei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q34',
      type: 'fill-blank',
      prompt:
        'Se você ainda não ___ a sua Carteira de Trabalho, precisa ir até a Superintendência. (tirar, pretérito perfeito)',
      promptFa: 'فعل tirar را در گذشتهٔ کامل صرف کنید (você).',
      options: [],
      answer: 'tirou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → tirou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q35',
      type: 'fill-blank',
      prompt:
        'Se você já ___ a sua documentação de trabalho, você pode ter um Contrato de até 90 dias. (regularizar, pretérito perfeito)',
      promptFa: 'فعل regularizar را در گذشتهٔ کامل صرف کنید (você).',
      options: [],
      answer: 'regularizou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → regularizou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q36',
      type: 'fill-blank',
      prompt: 'Eu já ___ meu Contrato de Trabalho. (assinar, pretérito perfeito)',
      promptFa: 'فعل assinar را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'assinei',
      explanationFa: '‑AR گذشتهٔ کامل اول‌شخص → assinei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q37',
      type: 'fill-blank',
      prompt: 'A empresa me ___ por 90 dias. (contratar, pretérito perfeito)',
      promptFa: 'فعل contratar را در گذشتهٔ کامل صرف کنید (a empresa = سوم‌شخص مفرد).',
      options: [],
      answer: 'contratou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → contratou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q38',
      type: 'fill-blank',
      prompt:
        'Eu já ___ 12 horas por dia em uma confecção, mas depois ___ que o trabalho decente é de no máximo 8 horas. (trabalhar / descobrir, pretérito perfeito)',
      promptFa: 'دو فعل را در گذشتهٔ کامل صرف کنید (eu): trabalhar و descobrir.',
      options: [],
      answer: ['trabalhei', 'descobri'],
      explanationFa: '‑AR → trabalhei؛ ‑IR → descobri (اول‌شخص).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q39',
      type: 'fill-blank',
      prompt:
        'Se você trabalhou e ___ de 8 horas por dia, deve receber hora extra. (passar, pretérito perfeito)',
      promptFa: 'فعل passar را در گذشتهٔ کامل صرف کنید (você).',
      options: [],
      answer: 'passou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → passou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q40',
      type: 'fill-blank',
      prompt:
        'Meu chefe me ___ que a hora extra não pode passar de duas horas por dia. (explicar, pretérito perfeito)',
      promptFa: 'فعل explicar را در گذشتهٔ کامل صرف کنید (meu chefe = سوم‌شخص مفرد).',
      options: [],
      answer: 'explicou',
      explanationFa: 'explicar سوم‌شخص → explicou. (اول‌شخص می‌شد expliquei با qu.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q41',
      type: 'fill-blank',
      prompt:
        'Eu fiz duas horas extras e ___ 50% a mais que a hora normal. (receber, pretérito perfeito)',
      promptFa: 'فعل receber را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'recebi',
      explanationFa: '‑ER گذشتهٔ کامل اول‌شخص → recebi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q42',
      type: 'fill-blank',
      prompt:
        'Se você ___ de segunda a segunda e não ___, tem direito a um dia de folga por semana. (trabalhar / folgar, pretérito perfeito)',
      promptFa: 'دو فعل را در گذشتهٔ کامل صرف کنید (você): trabalhar و folgar.',
      options: [],
      answer: ['trabalhou', 'folgou'],
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → trabalhou / folgou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q43',
      type: 'fill-blank',
      prompt:
        'Ontem eu ___ o meu salário com o adicional noturno de 20%. (receber, pretérito perfeito)',
      promptFa: 'فعل receber را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'recebi',
      explanationFa: '‑ER گذشتهٔ کامل اول‌شخص → recebi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q44',
      type: 'fill-blank',
      prompt:
        'Meu amigo ___ R$ 600,00 de salário, então eu ___ que não está dentro da Lei. (receber / explicar, pretérito perfeito)',
      promptFa: 'دو فعل را در گذشتهٔ کامل صرف کنید: receber (سوم‌شخص) و explicar (eu).',
      options: [],
      answer: ['recebeu', 'expliquei'],
      explanationFa: 'receber سوم‌شخص → recebeu؛ explicar اول‌شخص → expliquei (با qu).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q45',
      type: 'fill-blank',
      prompt:
        'Eu ___ um trabalho registrado e dentro da Lei, então tenho descontos: INSS, Taxas Sindicais, Imposto de Renda e Vale Transporte. (conseguir, pretérito perfeito)',
      promptFa: 'فعل conseguir را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'consegui',
      explanationFa: '‑IR گذشتهٔ کامل اول‌شخص → consegui.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q46',
      type: 'fill-blank',
      prompt: 'Eu ___ em outro país no passado. (morar, pretérito imperfeito)',
      promptFa: 'فعل morar را در گذشتهٔ استمراری صرف کنید (eu).',
      options: [],
      answer: 'morava',
      explanationFa: 'زندگیِ عادتی در گذشته → استمراری: morava.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q47',
      type: 'fill-blank',
      prompt: 'Eu e meus pais ___ em outro continente. (morar, pretérito imperfeito)',
      promptFa: 'فعل morar را در گذشتهٔ استمراری صرف کنید (nós).',
      options: [],
      answer: 'morávamos',
      explanationFa: '‑AR استمراری اول‌شخص جمع → morávamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q48',
      type: 'fill-blank',
      prompt: 'Minha irmã gosta de ___ no Brasil. (morar)',
      promptFa: 'بعد از «gosta de» فعل به چه شکلی می‌آید؟',
      options: [],
      answer: 'morar',
      explanationFa: 'بعد از «gostar de» فعل به‌صورت مصدر می‌آید → morar.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q49',
      type: 'fill-blank',
      prompt: 'Minha avó ___ o Brasil como país de refúgio. (escolher, pretérito perfeito)',
      promptFa: 'فعل escolher را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'escolheu',
      explanationFa: '‑ER گذشتهٔ کامل سوم‌شخص → escolheu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q50',
      type: 'fill-blank',
      prompt: 'Eu ___ aprender português. (escolher, pretérito perfeito)',
      promptFa: 'فعل escolher را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'escolhi',
      explanationFa: '‑ER گذشتهٔ کامل اول‌شخص → escolhi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q51',
      type: 'fill-blank',
      prompt: 'Elas ___ os móveis da casa. (escolher, pretérito perfeito)',
      promptFa: 'فعل escolher را در گذشتهٔ کامل صرف کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'escolheram',
      explanationFa: '‑ER گذشتهٔ کامل سوم‌شخص جمع → escolheram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q52',
      type: 'fill-blank',
      prompt: 'Meu primo ___ roupas quentes porque estava frio ontem. (vestir, pretérito perfeito)',
      promptFa: 'فعل vestir را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'vestiu',
      explanationFa: '‑IR گذشتهٔ کامل سوم‌شخص → vestiu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q53',
      type: 'fill-blank',
      prompt: 'Eu ___ roupas leves porque semana passada estava quente. (vestir, pretérito perfeito)',
      promptFa: 'فعل vestir را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'vesti',
      explanationFa: '‑IR گذشتهٔ کامل اول‌شخص → vesti.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q54',
      type: 'fill-blank',
      prompt: 'Nós não ___ calças ontem porque fez calor. (vestir, pretérito perfeito)',
      promptFa: 'فعل vestir را در گذشتهٔ کامل صرف کنید (nós).',
      options: [],
      answer: 'vestimos',
      explanationFa: '‑IR گذشتهٔ کامل اول‌شخص جمع → vestimos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q55',
      type: 'fill-blank',
      prompt: 'Eu ___ como motorista no ano passado. (trabalhar, pretérito perfeito)',
      promptFa: 'فعل trabalhar را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'trabalhei',
      explanationFa: '‑AR گذشتهٔ کامل اول‌شخص → trabalhei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q56',
      type: 'fill-blank',
      prompt: 'Os meus amigos ___ muito durante o verão passado. (trabalhar, pretérito perfeito)',
      promptFa: 'فعل trabalhar را در گذشتهٔ کامل صرف کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'trabalharam',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص جمع → trabalharam.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q57',
      type: 'fill-blank',
      prompt: 'Meu pai ___ muitos anos na mesma empresa. (trabalhar, pretérito perfeito)',
      promptFa: 'فعل trabalhar را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'trabalhou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → trabalhou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q58',
      type: 'fill-blank',
      prompt: 'Eu ___ um texto sobre profissões na escola. (escrever, pretérito perfeito)',
      promptFa: 'فعل escrever را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'escrevi',
      explanationFa: '‑ER گذشتهٔ کامل اول‌شخص → escrevi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q59',
      type: 'fill-blank',
      prompt: 'O carteiro ___ cartas para mim semana passada. (entregar, pretérito perfeito)',
      promptFa: 'فعل entregar را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'entregou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → entregou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q60',
      type: 'fill-blank',
      prompt: 'A professora ___ as lições no caderno ontem. (escrever, pretérito perfeito)',
      promptFa: 'فعل escrever را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'escreveu',
      explanationFa: '‑ER گذشتهٔ کامل سوم‌شخص → escreveu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q61',
      type: 'fill-blank',
      prompt:
        'O motorista ___ cuidadosamente o ônibus no trajeto para casa ontem. (dirigir, pretérito perfeito)',
      promptFa: 'فعل dirigir را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'dirigiu',
      explanationFa: '‑IR گذشتهٔ کامل سوم‌شخص → dirigiu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q62',
      type: 'fill-blank',
      prompt: 'A taxista e o motorista ___ a dirigir quando eram jovens. (aprender, pretérito perfeito)',
      promptFa: 'فعل aprender را در گذشتهٔ کامل صرف کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'aprenderam',
      explanationFa: '‑ER گذشتهٔ کامل سوم‌شخص جمع → aprenderam.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q63',
      type: 'fill-blank',
      prompt: 'Eu não ___ o carro depois da festa porque eu tinha bebido. (dirigir, pretérito perfeito)',
      promptFa: 'فعل dirigir را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'dirigi',
      explanationFa: '‑IR گذشتهٔ کامل اول‌شخص → dirigi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q64',
      type: 'fill-blank',
      prompt: 'Karen ___ leite com mel ontem à noite. (tomar, pretérito perfeito)',
      promptFa: 'فعل tomar را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'tomou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → tomou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q65',
      type: 'fill-blank',
      prompt: 'Eu ___ toda a água do filtro. (tomar, pretérito perfeito)',
      promptFa: 'فعل tomar را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'tomei',
      explanationFa: '‑AR گذشتهٔ کامل اول‌شخص → tomei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q66',
      type: 'fill-blank',
      prompt: 'Por que você não ___ o suco? (tomar, pretérito perfeito)',
      promptFa: 'فعل tomar را در گذشتهٔ کامل صرف کنید (você).',
      options: [],
      answer: 'tomou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → tomou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q67',
      type: 'fill-blank',
      prompt: 'Ele ___ apenas refrigerante. (tomar, pretérito perfeito)',
      promptFa: 'فعل tomar را در گذشتهٔ کامل صرف کنید (ele).',
      options: [],
      answer: 'tomou',
      explanationFa: '‑AR گذشتهٔ کامل سوم‌شخص → tomou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q68',
      type: 'fill-blank',
      prompt: 'Eu não ___ quando cheguei porque estava com muito sono. (comer, pretérito perfeito)',
      promptFa: 'فعل comer را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'comi',
      explanationFa: '‑ER گذشتهٔ کامل اول‌شخص → comi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q69',
      type: 'fill-blank',
      prompt: 'Rogério ___ frango assado, arroz e batatas fritas. (comer, pretérito perfeito)',
      promptFa: 'فعل comer را در گذشتهٔ کامل صرف کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'comeu',
      explanationFa: '‑ER گذشتهٔ کامل سوم‌شخص → comeu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q70',
      type: 'fill-blank',
      prompt: 'Você já ___, agora já pode ir dormir. (comer, pretérito perfeito)',
      promptFa: 'فعل comer را در گذشتهٔ کامل صرف کنید (você).',
      options: [],
      answer: 'comeu',
      explanationFa: '‑ER گذشتهٔ کامل سوم‌شخص → comeu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q71',
      type: 'fill-blank',
      prompt: 'Ela ___ na casa dos vizinhos. (comer, pretérito perfeito)',
      promptFa: 'فعل comer را در گذشتهٔ کامل صرف کنید (ela).',
      options: [],
      answer: 'comeu',
      explanationFa: '‑ER گذشتهٔ کامل سوم‌شخص → comeu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q72',
      type: 'fill-blank',
      prompt:
        'Eu não me lembro se ___ pastel de carne ou de queijo na última vez. (pedir, pretérito perfeito)',
      promptFa: 'فعل pedir را در گذشتهٔ کامل صرف کنید (eu).',
      options: [],
      answer: 'pedi',
      explanationFa: '‑IR گذشتهٔ کامل اول‌شخص → pedi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q73',
      type: 'fill-blank',
      prompt: 'Você ___ o café para mim? (pedir, pretérito perfeito)',
      promptFa: 'فعل pedir را در گذشتهٔ کامل صرف کنید (você).',
      options: [],
      answer: 'pediu',
      explanationFa: '‑IR گذشتهٔ کامل سوم‌شخص → pediu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q74',
      type: 'fill-blank',
      prompt: 'Ana e Estevam ___ um bolo na padaria. (pedir, pretérito perfeito)',
      promptFa: 'فعل pedir را در گذشتهٔ کامل صرف کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'pediram',
      explanationFa: '‑IR گذشتهٔ کامل سوم‌شخص جمع → pediram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q75',
      type: 'fill-blank',
      prompt: 'Ele ___ brigadeiro de sobremesa de novo. (pedir, pretérito perfeito)',
      promptFa: 'فعل pedir را در گذشتهٔ کامل صرف کنید (ele).',
      options: [],
      answer: 'pediu',
      explanationFa: '‑IR گذشتهٔ کامل سوم‌شخص → pediu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q76',
      type: 'fill-blank',
      prompt:
        'Amanhã eu ___ (ir) à praia com os meus amigos e depois nós ___ (ir) ao cinema juntos! (futuro)',
      promptFa: 'با ساختار آینده کامل کنید (خودِ فعل ir است، فقط ir را صرف کنید).',
      options: [],
      answer: ['vou', 'vamos'],
      explanationFa: 'وقتی فعل «ir» است فقط آن را صرف می‌کنیم: eu vou / nós vamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q77',
      type: 'fill-blank',
      prompt:
        'Domingo nós ___ (fazer) um grande almoço em família e, depois, nós ___ (ir) ao parque. (futuro)',
      promptFa: 'با ساختار آینده کامل کنید: fazer (با vamos + مصدر) و ir.',
      options: [],
      answer: ['vamos fazer', 'vamos'],
      explanationFa: 'آینده = ir در حال + مصدر: «vamos fazer»؛ برای خودِ ir فقط «vamos».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q78',
      type: 'fill-blank',
      prompt: 'Hoje eu ___ (comprar) algumas frutas no mercado para fazer uma salada de frutas. (futuro)',
      promptFa: 'با ساختار آینده کامل کنید (eu + comprar).',
      options: [],
      answer: 'vou comprar',
      explanationFa: 'آینده = vou + comprar.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q79',
      type: 'mcq',
      prompt: 'Tenho certeza que amanhã ___ um grande dia para você! (futuro, ser)',
      promptFa: 'کدام شکلِ آینده برای فعل ser درست است؟',
      options: ['vai ser', 'vou ser', 'vamos ser', 'vão ser'],
      answer: 'vai ser',
      explanationFa: 'فاعل «um grande dia» سوم‌شخص مفرد است → «vai ser».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q80',
      type: 'fill-blank',
      prompt: 'Hoje, mais tarde, nós ___ (estar) todos juntos para a festa de casamento. (futuro)',
      promptFa: 'با ساختار آینده کامل کنید (nós + estar).',
      options: [],
      answer: 'vamos estar',
      explanationFa: 'آینده = vamos + estar.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q81',
      type: 'fill-blank',
      prompt: 'Terça-feira ___ (falar) com o meu professor de português sobre as minhas dúvidas. (futuro)',
      promptFa: 'با ساختار آینده کامل کنید (فاعل «من» ضمنی + falar).',
      options: [],
      answer: 'vou falar',
      explanationFa: 'فاعلِ ضمنی «eu» → «vou falar».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q82',
      type: 'fill-blank',
      prompt: 'Hoje eles ___ (comer) um lanche no intervalo da aula. (futuro)',
      promptFa: 'با ساختار آینده کامل کنید (eles + comer).',
      options: [],
      answer: 'vão comer',
      explanationFa: 'آینده = vão + comer.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q83',
      type: 'fill-blank',
      prompt:
        'Segunda-feira vocês ___ (arrumar) a casa toda porque nós ___ (receber) os nossos visitantes do Brasil! (futuro)',
      promptFa: 'با ساختار آینده کامل کنید: vocês + arrumar و nós + receber.',
      options: [],
      answer: ['vão arrumar', 'vamos receber'],
      explanationFa: 'vocês → vão arrumar؛ nós → vamos receber.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q84',
      type: 'fill-blank',
      prompt:
        'Hoje nós ___ (beber) muito na festa do Diogo e, depois, nós ___ (ir) para casa dormir. (futuro)',
      promptFa: 'با ساختار آینده کامل کنید: nós + beber و nós + ir.',
      options: [],
      answer: ['vamos beber', 'vamos'],
      explanationFa: 'آینده = vamos + beber؛ برای خودِ ir فقط «vamos».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q85',
      type: 'fill-blank',
      prompt: 'Quarta-feira ela ___ (comprar) um computador novo. (futuro)',
      promptFa: 'با ساختار آینده کامل کنید (ela + comprar).',
      options: [],
      answer: 'vai comprar',
      explanationFa: 'ela → «vai comprar».',
      cefr: 'A2',
      skill: 'grammar',
    },
  ],
  estimatedMinutes: 30,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 9 (کامل).',
};
