import type { CourseLesson } from '@/domain/content/schema';

export const aula1: CourseLesson = {
  id: 'course-aula-1',
  order: 1,
  aula: 'Aula 1',
  titleFa: 'الفبا، سدیلها و دیگرافوها',
  titlePt: 'Alfabeto, Cedilha e Dígrafos',
  cefr: 'A1',
  summaryFa:
    'در این درس با الفبای پرتغالی برزیلی (۲۶ حرف: ۲۱ همخوان و ۵ واکه) و نام هر حرف آشنا می‌شوید و برای هر حرف یک واژه یا نامِ نمادینِ برزیلی یاد می‌گیرید. سپس نشانهٔ سدیلها (Ç) و قاعدهٔ به‌کارگیری آن را می‌آموزید و در پایان با دیگرافوها (ترکیب دو حرف که یک صدا می‌سازند) آشنا می‌شوید — هم دیگرافوهای همخوانی و هم دیگرافوهای واکه‌ای (خیشومی).',
  objectivesFa: [
    'الفبای پرتغالی و نام هر حرف را بشناسید و بدانید ۲۶ حرف شامل ۲۱ همخوان و ۵ واکه است.',
    'ترکیب‌هایی را که در الفبا نیستند بشناسید: ch, lh, nh, rr, ss, sc, xc, gu, qu.',
    'قاعدهٔ سدیلها (Ç) را یاد بگیرید: چه زمانی C و چه زمانی Ç برای صدای /s/ به‌کار می‌رود.',
    'دیگرافوهای همخوانی و واکه‌ای را تشخیص دهید و بدانید GU و QU کِی دیگراف هستند و کِی نه.',
  ],
  sections: [
    {
      headingFa: '۱. الفبای پرتغالی: نگاه کلی',
      bodyFa:
        'الفبای ما ۲۶ (بیست‌وشش) حرف دارد: ۲۱ (بیست‌ویک) همخوان و ۵ (پنج) واکه. واکه‌ها عبارت‌اند از: A, E, I, O, U. صدای واژه‌ها از هجاها (سیلاب‌ها) ساخته می‌شود و برخی ترکیب‌ها هستند که جزو الفبا به‌شمار نمی‌آیند اما در نوشتار پرتغالی بسیار پرکاربردند:\n\nch, nh, lh, ss, rr, sc, xc, gu, qu\n\nدر ادامهٔ درس (بخش دیگرافوها) این ترکیب‌ها را کامل بررسی می‌کنیم.',
      examples: [
        {
          pt: '26 letras = 21 consoantes + 5 vogais',
          fa: '۲۶ حرف = ۲۱ همخوان + ۵ واکه',
          pron: 'وینتی ای سِیس لِتراس',
        },
        {
          pt: 'Vogais: A, E, I, O, U',
          fa: 'واکه‌ها: A, E, I, O, U',
          pron: 'وُگایس: آ، اِ، ای، اُ، او',
        },
        {
          pt: 'Combinações fora do alfabeto: ch, nh, lh, ss, rr, sc, xc, gu, qu',
          fa: 'ترکیب‌های خارج از الفبا: ch, nh, lh, ss, rr, sc, xc, gu, qu',
          note: 'اینها «دیگرافو» هستند؛ دو حرف که یک صدا می‌دهند.',
        },
      ],
    },
    {
      headingFa: '۲. حروف A تا H با واژه‌های نمونهٔ برزیلی',
      bodyFa:
        'برای هر حرف یک نام یا واژهٔ نمادین برزیلی همراه با نام خودِ حرف (تلفظ حرف) آورده شده است. ستون pron نامِ حرف در پرتغالی است.',
      examples: [
        {
          pt: 'A a — Ayrton Senna',
          fa: 'آیرتون سنا؛ راننده‌ای بزرگ در فرمول یک بود.',
          pron: 'آ',
          note: 'Foi um grande piloto de fórmula 1.',
        },
        {
          pt: 'B b — Berimbau',
          fa: 'بریمبائو؛ سازی که در کاپوئیرا به‌کار می‌رود.',
          pron: 'بِه',
          note: 'Instrumento usado na capoeira.',
        },
        {
          pt: 'C c — Carnaval',
          fa: 'کارناوال؛ محبوب‌ترین جشن در برزیل.',
          pron: 'سِه',
          note: 'Festa mais popular no Brasil.',
        },
        {
          pt: 'D d — Diamantina',
          fa: 'دیامانتینا؛ شهرستانی در ایالت میناس‌ژِرایس.',
          pron: 'دِه',
          note: 'Município do estado de Minas Gerais.',
        },
        {
          pt: 'E e — Elis Regina',
          fa: 'اِلیس رِژینا؛ خوانندهٔ مشهور برزیلی بود.',
          pron: 'اِ',
          note: 'Foi uma famosa cantora brasileira.',
        },
        {
          pt: 'F f — Frevo',
          fa: 'فرِوو؛ سبک موسیقی و رقصی برزیلی با خاستگاه ایالت پِرنامبوکو.',
          pron: 'اِفی',
          note: 'É um ritmo musical e uma dança brasileira com origem no estado de Pernambuco.',
        },
        {
          pt: 'G g — Guaraná',
          fa: 'گوآرانا؛ گیاهی بومیِ آمازون.',
          pron: 'ژِه',
          note: 'Planta originária da Amazônia.',
        },
        {
          pt: 'H h — Heitor Villa-Lobos',
          fa: 'اِیتور ویلا-لوبوس؛ آهنگسازِ برجستهٔ برزیلی بود.',
          pron: 'آگا',
          note: 'Foi um brilhante compositor brasileiro. حرف H در ابتدای واژه معمولاً بی‌صداست.',
        },
      ],
    },
    {
      headingFa: '۳. حروف I تا P با واژه‌های نمونهٔ برزیلی',
      bodyFa: 'ادامهٔ الفبا از I تا P. به نامِ حرف در ستون pron دقت کنید.',
      examples: [
        {
          pt: 'I i — Itaparica',
          fa: 'ایتاپاریکا؛ شهرستانی در ایالت باهیا.',
          pron: 'ای',
          note: 'Município do estado da Bahia.',
        },
        {
          pt: 'J j — Jabuticaba',
          fa: 'ژابوتیکابا؛ میوه‌ای برزیلی و بومیِ جنگل آتلانتیک.',
          pron: 'ژُتا',
          note: 'Fruta brasileira nativa da mata atlântica.',
        },
        {
          pt: 'K k — Kadiwéu',
          fa: 'کادیوِئو؛ قبیله‌ای بومی که در ایالت ماتو-گروسو-دو-سول زندگی می‌کند.',
          pron: 'کا',
          note: 'Tribo indígena que vive no estado do Mato Grosso do Sul.',
        },
        {
          pt: 'L l — Lobo-Guará',
          fa: 'لوبو-گوآرا (گرگ یال‌دار)؛ جانوری که در مناطق ساوانای (Cerrado) برزیل یافت می‌شود.',
          pron: 'اِلی',
          note: 'Animal encontrado em regiões de Cerrado do Brasil.',
        },
        {
          pt: 'M m — Machado de Assis',
          fa: 'ماشادو دِ آسیس؛ نویسندهٔ برزیلی که بزرگ‌ترین نامِ ادبیات برزیل شناخته می‌شود.',
          pron: 'اِمی',
          note: 'Foi um escritor brasileiro, amplamente considerado como o maior nome da literatura brasileira.',
        },
        {
          pt: 'N n — Neymar',
          fa: 'نِیمار؛ فوتبالیستِ موفق برزیلی.',
          pron: 'اِنی',
          note: 'É um futebolista brasileiro de sucesso.',
        },
        {
          pt: 'O o — Onça-pintada',
          fa: 'اونسا-پینتادا (یوزپلنگ خال‌دار/جگوار)؛ بزرگ‌ترین گربه‌سانِ قارهٔ آمریکا.',
          pron: 'اُ',
          note: 'É o maior felino do continente americano.',
        },
        {
          pt: 'P p — Pão de queijo',
          fa: 'پائو دِ کِیژو (نان پنیر)؛ غذای بومیِ برزیل، از ایالت میناس‌ژِرایس.',
          pron: 'پِه',
          note: 'Comida típica brasileira, do estado de Minas Gerais.',
        },
      ],
    },
    {
      headingFa: '۴. حروف Q تا Z با واژه‌های نمونهٔ برزیلی',
      bodyFa:
        'بخش پایانی الفبا از Q تا Z. توجه کنید که Y با نام «ípsilon» و W با نام «dáblio» خوانده می‌شوند.',
      examples: [
        {
          pt: 'Q q — Quero-quero',
          fa: 'کِرو-کِرو؛ پرنده‌ای که نمادِ ایالت ریو-گراندی-دو-سول است.',
          pron: 'کِه',
          note: 'É uma ave-símbolo do Rio Grande do Sul.',
        },
        {
          pt: 'R r — Rio de Janeiro',
          fa: 'ریو دِ ژانِیرو؛ مشهورترین شهر برزیل در جهان.',
          pron: 'اِری',
          note: 'É a cidade brasileira mais conhecida no mundo.',
        },
        {
          pt: 'S s — Saudade',
          fa: 'سائوداجی؛ واژه‌ای کاملاً برزیلی برای توصیف احساس دلتنگیِ ناشی از دوری از یک شخص، یک چیز یا یک مکان.',
          pron: 'اِسی',
          note: 'Palavra tipicamente brasileira para definir o sentimento melancólico devido ao afastamento de uma pessoa, uma coisa ou um lugar.',
        },
        {
          pt: 'T t — Tapioca',
          fa: 'تاپیوکا؛ مادهٔ اصلیِ برخی خوراکی‌های سنتی برزیل.',
          pron: 'تِه',
          note: 'Ingrediente principal de algumas iguarias típicas do Brasil.',
        },
        {
          pt: 'U u — Uirapuru',
          fa: 'اویراپورو؛ پرنده‌ای که در جنگل آمازون زندگی می‌کند.',
          pron: 'او',
          note: 'Pássaro que vive na mata amazônica.',
        },
        {
          pt: 'V v — Vitória-régia',
          fa: 'ویتوریا-رِژیا؛ گیاهِ آبزیِ بومیِ منطقهٔ آمازون.',
          pron: 'وِه',
          note: 'Planta aquática típica da região amazônica.',
        },
        {
          pt: 'W w — Wilson Simonal',
          fa: 'ویلسون سیمونال؛ خوانندهٔ موفق برزیلی در دهه‌های ۱۹۶۰ و ۱۹۷۰ بود.',
          pron: 'دابلیو',
          note: 'Foi um cantor brasileiro de sucesso nas décadas de 1960 e 1970.',
        },
        {
          pt: 'X x — Xuxa',
          fa: 'شوشا؛ مجریِ مشهور برزیلی.',
          pron: 'شیس',
          note: 'Famosa apresentadora brasileira.',
        },
        {
          pt: 'Y y — Yo-yo (ou Iô-iô)',
          fa: 'یویو (یا ایو-ایو)؛ اسباب‌بازیِ بسیار محبوبی در دهه‌های ۱۹۸۰ و ۱۹۹۰ بود.',
          pron: 'ایپسیلون',
          note: 'Foi um brinquedo muito popular nas décadas de 1980 e 1990.',
        },
        {
          pt: 'Z z — Zabumba',
          fa: 'زابومبا؛ سازِ کوبه‌ای که در موسیقیِ فوهّو (forró) برزیل به‌کار می‌رود.',
          pron: 'زِه',
          note: 'Instrumento musical utilizado no forró brasileiro.',
        },
      ],
    },
    {
      headingFa: '۵. سدیلها (Ç): تعریف و قاعدهٔ اصلی',
      bodyFa:
        'سدیلها (Ç) نشانه‌ای گرافیکی است که زیر حرف C گذاشته می‌شود؛ یعنی وقتی این همخوان پیش از واکه‌های A، O، U بیاید. سدیلها هرگز در ابتدای واژه به‌کار نمی‌رود.\n\nنکتهٔ کلیدی: حرف C به‌تنهایی وقتی پیش از واکه‌های E و I بیاید صدای /s/ می‌دهد (CE، CI). بنابراین پیش از E و I فقط از حرف C (بدون نشانه) استفاده می‌کنیم، چه در ابتدا و چه در میان واژه.\n\nاما برای ساختن صدای /s/ پیش از واکه‌های A، O، U باید از سدیلها استفاده کنیم: ÇA، ÇO، ÇU.',
      examples: [
        {
          pt: 'CE, CI → som de /s/ sem cedilha',
          fa: 'پیش از E و I: صدای /s/ بدون سدیلها (فقط C).',
          pron: 'سِه، سی',
        },
        {
          pt: 'cenoura, circo, certo',
          fa: 'هویج، سیرک، درست/صحیح.',
          pron: 'سِنُرا، سیرکو، سِرتو',
          note: 'پیش از E/I فقط C می‌آید، بدون سدیلها.',
        },
        {
          pt: 'anoitecer, bacia, saci',
          fa: 'شب‌شدن، لگن/حوضچه، ساسی (موجودِ فولکلور برزیلی).',
          pron: 'آنُیتِسِر، باسیا، ساسی',
        },
        {
          pt: 'ÇA, ÇO, ÇU → som de /s/ com cedilha',
          fa: 'پیش از A، O، U: صدای /s/ فقط با سدیلها ساخته می‌شود.',
          pron: 'سا، سو، سو',
        },
        {
          pt: 'açafrão, abraço, açúcar, moço',
          fa: 'زعفران، آغوش/در آغوش گرفتن، شکر، جوان/پسر جوان.',
          pron: 'آسافرائو، آبراسو، آسوکار، موسو',
          note: 'در همهٔ اینها Ç پیش از A/O/U صدای /s/ می‌دهد.',
        },
      ],
    },
    {
      headingFa: '۶. تمرین سدیلها: پرکردن جای خالی',
      bodyFa:
        'در جزوهٔ اصلی این تمرین آمده است: جای خالی را با CE، CI یا ÇA، ÇO، ÇU کامل کنید. قاعده را به‌خاطر بسپارید: پیش از E/I فقط C (بدون نشانه)، و پیش از A/O/U سدیلها (Ç). پاسخ‌های کامل در بخش آزمون آمده است.',
      examples: [
        {
          pt: 'FUMA___ → FUMAÇA | RE___ITA → RECEITA',
          fa: 'دود / نسخه (دستور پخت).',
          pron: 'فوماسا / رِسِیتا',
        },
        {
          pt: 'ALMO___ → ALMOÇO | A___CAR → AÇÚCAR',
          fa: 'ناهار / شکر.',
          pron: 'آلموسو / آسوکار',
        },
        {
          pt: 'CARO___ → CAROÇO | ___BOLA → CEBOLA',
          fa: 'هسته / پیاز.',
          pron: 'کاروسو / سِبولا',
        },
        {
          pt: 'AVAN___R → AVANÇAR | CA___LA → CAÇULA',
          fa: 'پیشروی کردن / کوچک‌ترین فرزند خانواده.',
          pron: 'آوانسار / کاسولا',
        },
        {
          pt: 'CRIAN___ → CRIANÇA | DIFEREN___ → DIFERENÇA',
          fa: 'کودک / تفاوت.',
          pron: 'کریانسا / دیفِرِنسا',
        },
        {
          pt: '___NEMA → CINEMA | ENDERE___ → ENDEREÇO',
          fa: 'سینما / نشانی (آدرس).',
          pron: 'سینِما / اِندِرِسو',
        },
      ],
    },
    {
      headingFa: '۷. دیگرافوها: تعریف',
      bodyFa:
        'دیگرافو (dígrafo) به وضعیتی می‌گوییم که دو حرف در کنار هم یک صدای واحد می‌سازند. دو نوع دیگرافو داریم: دیگرافوهای همخوانی (consonantais) و دیگرافوهای واکه‌ای (vocálicos).',
      examples: [
        {
          pt: 'dígrafo = duas letras, um único som',
          fa: 'دیگرافو = دو حرف، یک صدای واحد.',
          pron: 'دیگرافو',
        },
      ],
    },
    {
      headingFa: '۸. دیگرافوهای همخوانی',
      bodyFa:
        'در دیگرافوهای همخوانی، دو حرف در کنار هم یک صدای همخوانیِ واحد می‌سازند. این دیگرافوها عبارت‌اند از: lh, ch, nh, rr, ss, sc, sç, xc, qu, gu.',
      examples: [
        {
          pt: 'LH: milho, muralha',
          fa: 'ذرت، دیوار بزرگ/حصار.',
          pron: 'میلیو، مورالیا',
          note: 'LH صدایی شبیه «لی» نرم دارد.',
        },
        {
          pt: 'CH: chuva, chave',
          fa: 'باران، کلید.',
          pron: 'شووا، شاوی',
          note: 'CH صدای «ش» می‌دهد.',
        },
        {
          pt: 'NH: amanhã, estranho',
          fa: 'فردا، عجیب/غریبه.',
          pron: 'آمانیا، اِسترانیو',
          note: 'NH صدایی شبیه «نی» نرم دارد.',
        },
        {
          pt: 'RR: carro, macarrão',
          fa: 'ماشین، ماکارونی.',
          pron: 'کاهو، ماکاهائو',
          note: 'RR در برزیل غالباً مانند «هـ» گلویی تلفظ می‌شود.',
        },
        {
          pt: 'QU: queijo, aquele',
          fa: 'پنیر، آن (مذکر).',
          pron: 'کِیژو، آکِلی',
        },
        {
          pt: 'GU: águia, guerra',
          fa: 'عقاب، جنگ.',
          pron: 'آگیا، گِها',
        },
        {
          pt: 'SS: pássaro, pessoa',
          fa: 'پرنده، شخص.',
          pron: 'پاسارو، پِسوا',
          note: 'SS همیشه صدای /s/ می‌دهد (نه /z/).',
        },
        {
          pt: 'SC: nascimento, crescer',
          fa: 'تولد/زایش، رشد کردن.',
          pron: 'ناسیمِنتو، کرِسِر',
        },
        {
          pt: 'SÇ: cresça, nasço',
          fa: '(او) رشد کند، (من) متولد می‌شوم.',
          pron: 'کرِسا، ناسو',
        },
        {
          pt: 'XC: exceção, excelência',
          fa: 'استثنا، برتری/عالی‌جناب.',
          pron: 'اِسِسائو، اِسِلِنسیا',
        },
      ],
    },
    {
      headingFa: '۹. نکتهٔ مهم: GU و QU پیش از E و I',
      bodyFa:
        'دیگرافوهای «GU» و «QU» همیشه پیش از واکه‌های «E» و «I» ظاهر می‌شوند و در این حالت حرف U تلفظ نمی‌شود.',
      examples: [
        {
          pt: 'guitarra',
          fa: 'گیتار.',
          pron: 'گیتاها',
        },
        {
          pt: 'alguém',
          fa: 'کسی/شخصی.',
          pron: 'آلگِین',
        },
        {
          pt: 'queijo',
          fa: 'پنیر.',
          pron: 'کِیژو',
        },
        {
          pt: 'máquina',
          fa: 'ماشین/دستگاه.',
          pron: 'ماکینا',
        },
      ],
    },
    {
      headingFa: '۱۰. مواردی که GU و QU دیگراف نیستند',
      bodyFa:
        'وقتی GU/QU پیش از A بیایند، یا وقتی پیش از E/I بیایند اما حرف U تلفظ شود، دیگر دیگرافو نیستند (چون U صدای خودش را دارد).',
      examples: [
        {
          pt: 'água',
          fa: 'آب.',
          pron: 'آگوا',
          note: 'پیش از A است و U تلفظ می‌شود → دیگراف نیست.',
        },
        {
          pt: 'bilíngue',
          fa: 'دوزبانه.',
          pron: 'بیلینگوی',
          note: 'اینجا U تلفظ می‌شود → دیگراف نیست.',
        },
        {
          pt: 'líquido',
          fa: 'مایع.',
          pron: 'لیکویدو',
          note: 'U تلفظ می‌شود → دیگراف نیست.',
        },
        {
          pt: 'qual',
          fa: 'کدام.',
          pron: 'کوآل',
          note: 'پیش از A → دیگراف نیست.',
        },
        {
          pt: 'tranquilo',
          fa: 'آرام/بی‌خیال.',
          pron: 'ترانکویلو',
          note: 'U تلفظ می‌شود → دیگراف نیست.',
        },
      ],
    },
    {
      headingFa: '۱۱. دیگرافوهای واکه‌ای (خیشومی)',
      bodyFa:
        'دیگرافوهای واکه‌ای زمانی ساخته می‌شوند که پس از یک واکه، همخوان «n» یا «m» بیاید و با هم یک واکهٔ خیشومی‌شده (تودماغی) بسازند. اینها عبارت‌اند از: am, em, im, om, um و an, en, in, on, un.\n\nقاعدهٔ املایی مهم: پیش از حروف B و P از M استفاده می‌کنیم (نه N).',
      examples: [
        {
          pt: 'AM: ambulância, campeão',
          fa: 'آمبولانس، قهرمان.',
          pron: 'آمبولانسیا، کامپِئائو',
          note: 'پیش از B و P حرف M می‌آید.',
        },
        {
          pt: 'EM: lembrança, sempre',
          fa: 'خاطره/یادگاری، همیشه.',
          pron: 'لِمبرانسا، سِمپری',
        },
        {
          pt: 'IM: símbolo, limpo',
          fa: 'نماد، تمیز.',
          pron: 'سیمبولو، لیمپو',
        },
        {
          pt: 'OM: ombro, sombra',
          fa: 'شانه، سایه.',
          pron: 'اُمبرو، سُمبرا',
        },
        {
          pt: 'UM: cumprimento, chumbo',
          fa: 'سلام/تعارف، سُرب.',
          pron: 'کومپریمِنتو، شومبو',
        },
        {
          pt: 'AN: sangue, antes',
          fa: 'خون، قبل.',
          pron: 'سانگی، آنتیس',
        },
        {
          pt: 'EN: pente, entrada',
          fa: 'شانه (وسیله)، ورودی.',
          pron: 'پِنتی، اِنترادا',
        },
        {
          pt: 'IN: introdução, lindo',
          fa: 'مقدمه، زیبا.',
          pron: 'اینترودوسائو، لیندو',
        },
        {
          pt: 'ON: ponte, contar',
          fa: 'پل، شمردن/تعریف کردن.',
          pron: 'پُنتی، کُنتار',
        },
        {
          pt: 'UN: mundo, juntar',
          fa: 'جهان، جمع کردن/به هم پیوستن.',
          pron: 'موندو، ژونتار',
        },
      ],
    },
  ],
  keyPointsFa: [
    'الفبا ۲۶ حرف دارد: ۲۱ همخوان و ۵ واکه (A, E, I, O, U).',
    'ترکیب‌های خارج از الفبا (دیگرافوها): ch, nh, lh, ss, rr, sc, xc, gu, qu.',
    'سدیلها (Ç) هرگز اول واژه نمی‌آید؛ پیش از A/O/U برای صدای /s/ به‌کار می‌رود.',
    'پیش از E و I فقط C می‌آید (بدون سدیلها) و همان صدای /s/ را می‌دهد: CE، CI.',
    'دیگرافو = دو حرف، یک صدا. دو نوع: همخوانی و واکه‌ای (خیشومی).',
    'GU و QU فقط وقتی دیگراف‌اند که پیش از E/I باشند و U تلفظ نشود (queijo، guerra)؛ در água یا qual دیگراف نیستند.',
    'پیش از B و P همیشه M می‌نویسیم، نه N (campeão، sempre، ombro).',
  ],
  quiz: [
    {
      id: 'course-aula-1-q1',
      type: 'fill-blank',
      prompt: 'FUMA___ (dica: som de /s/ antes de A)',
      promptFa: 'جای خالی را با CE/CI یا ÇA/ÇO/ÇU کامل کنید.',
      options: [],
      answer: 'FUMAÇA',
      explanationFa:
        'پیش از A برای صدای /s/ از سدیلها استفاده می‌کنیم: FUMAÇA (دود).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q2',
      type: 'fill-blank',
      prompt: 'RE___ITA (dica: som de /s/ antes de I)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'RECEITA',
      explanationFa:
        'پیش از I فقط C می‌آید (بدون سدیلها): RECEITA (نسخه / دستور پخت).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q3',
      type: 'fill-blank',
      prompt: 'ALMO___ (dica: som de /s/ antes de O)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'ALMOÇO',
      explanationFa: 'پیش از O از سدیلها استفاده می‌کنیم: ALMOÇO (ناهار).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q4',
      type: 'fill-blank',
      prompt: 'A___CAR (dica: som de /s/ antes de Ú)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'AÇÚCAR',
      explanationFa: 'پیش از U از سدیلها استفاده می‌کنیم: AÇÚCAR (شکر).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q5',
      type: 'fill-blank',
      prompt: 'CARO___ (dica: som de /s/ antes de O)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'CAROÇO',
      explanationFa: 'پیش از O از سدیلها استفاده می‌کنیم: CAROÇO (هسته).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q6',
      type: 'fill-blank',
      prompt: '___BOLA (dica: som de /s/ antes de E)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'CEBOLA',
      explanationFa: 'پیش از E فقط C می‌آید (بدون سدیلها): CEBOLA (پیاز).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q7',
      type: 'fill-blank',
      prompt: 'AVAN___R (dica: som de /s/ antes de A)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'AVANÇAR',
      explanationFa:
        'پیش از A از سدیلها استفاده می‌کنیم: AVANÇAR (پیشروی کردن).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q8',
      type: 'fill-blank',
      prompt: 'CA___LA (dica: som de /s/ antes de U)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'CAÇULA',
      explanationFa:
        'پیش از U از سدیلها استفاده می‌کنیم: CAÇULA (کوچک‌ترین فرزند خانواده).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q9',
      type: 'fill-blank',
      prompt: 'CRIAN___ (dica: som de /s/ antes de A)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'CRIANÇA',
      explanationFa: 'پیش از A از سدیلها استفاده می‌کنیم: CRIANÇA (کودک).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q10',
      type: 'fill-blank',
      prompt: 'DIFEREN___ (dica: som de /s/ antes de A)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'DIFERENÇA',
      explanationFa: 'پیش از A از سدیلها استفاده می‌کنیم: DIFERENÇA (تفاوت).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q11',
      type: 'fill-blank',
      prompt: '___NEMA (dica: som de /s/ antes de I)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'CINEMA',
      explanationFa: 'پیش از I فقط C می‌آید (بدون سدیلها): CINEMA (سینما).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q12',
      type: 'fill-blank',
      prompt: 'ENDERE___ (dica: som de /s/ antes de O)',
      promptFa: 'جای خالی را کامل کنید.',
      options: [],
      answer: 'ENDEREÇO',
      explanationFa:
        'پیش از O از سدیلها استفاده می‌کنیم: ENDEREÇO (نشانی / آدرس).',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q13',
      type: 'mcq',
      prompt: 'Quantas letras, consoantes e vogais tem o alfabeto português?',
      promptFa: 'الفبای پرتغالی چند حرف، چند همخوان و چند واکه دارد؟',
      options: [
        '26 letras: 21 consoantes e 5 vogais',
        '24 letras: 20 consoantes e 4 vogais',
        '26 letras: 20 consoantes e 6 vogais',
        '28 letras: 22 consoantes e 6 vogais',
      ],
      answer: '26 letras: 21 consoantes e 5 vogais',
      explanationFa: 'الفبا ۲۶ حرف دارد: ۲۱ همخوان و ۵ واکه (A, E, I, O, U).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-1-q14',
      type: 'mcq',
      prompt: 'Em qual palavra "QU" NÃO é um dígrafo?',
      promptFa: 'در کدام واژه ترکیب «QU» دیگرافو نیست؟',
      options: ['queijo', 'aquele', 'máquina', 'tranquilo'],
      answer: 'tranquilo',
      explanationFa:
        'در tranquilo حرف U تلفظ می‌شود، پس QU دیگرافو نیست. اما در queijo، aquele و máquina حرف U تلفظ نمی‌شود و QU دیگرافو است.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-1-q15',
      type: 'mcq',
      prompt: 'Complete corretamente: ca___peão / se___pre (antes de B e P).',
      promptFa: 'کدام حرف پیش از B و P درست است؟ (campeão / sempre)',
      options: ['M (campeão, sempre)', 'N (canpeão, senpre)'],
      answer: 'M (campeão, sempre)',
      explanationFa:
        'قاعده: پیش از B و P همیشه M می‌نویسیم، نه N. پس: campeão، sempre.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-1-q16',
      type: 'mcq',
      prompt: 'Qual som representa o dígrafo "CH" em "chuva"?',
      promptFa: 'دیگرافو «CH» در واژهٔ chuva چه صدایی دارد؟',
      options: [
        'som de "ش" (sh)',
        'som de "ک" (k)',
        'som de "چ" (tch)',
        'som de "س" (s)',
      ],
      answer: 'som de "ش" (sh)',
      explanationFa: 'در پرتغالی CH صدای «ش» می‌دهد: chuva (شووا) یعنی باران.',
      cefr: 'A1',
      skill: 'reading',
    },
    {
      id: 'course-aula-1-q17',
      type: 'translate-pt-fa',
      prompt: 'Traduza para o persa: "Saudade".',
      promptFa: 'این واژهٔ نمادین برزیلی را به فارسی توضیح دهید.',
      options: [],
      answer: 'دلتنگی؛ احساس مالیخولیایی ناشی از دوری از یک شخص، چیز یا مکان.',
      explanationFa:
        'Saudade واژه‌ای کاملاً برزیلی/پرتغالی است و معادل دقیقِ تک‌کلمه‌ای در بسیاری زبان‌ها ندارد؛ به معنای دلتنگی و حسِ فقدان است.',
      cefr: 'A1',
      skill: 'vocab',
    },
  ],
  estimatedMinutes: 25,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 1 (کامل).',
};
