import type { CourseLesson } from '@/domain/content/schema';

export const aula9: CourseLesson = {
  id: 'course-aula-9',
  order: 9,
  aula: 'Aula 9',
  titleFa: 'افعال ۳ — تمرین (افعال باقاعده و بی‌قاعده)',
  titlePt: 'Verbos 3 — Prática (Regulares e Irregulares)',
  cefr: 'A2',
  summaryFa:
    'این درس یک درسِ تمرینی است: هرچه در درس‌های افعال یاد گرفته‌اید را در چهار زمان اصلی به‌کار می‌بندید — زمان حال (Presente do Indicativo)، گذشتهٔ کامل (Pretérito Perfeito)، گذشتهٔ استمراری (Pretérito Imperfeito) و آینده (Futuro). ابتدا جدول‌های صرفِ افعال باقاعدهٔ سه گروه (-AR, -ER, -IR) و مهم‌ترین افعال بی‌قاعده (SER, IR, FAZER, ESTAR) را مرور می‌کنید، سپس ده‌ها جملهٔ واقعی را کامل می‌کنید. جمله‌ها در بافت‌های کاربردی مهاجران هستند: گرفتن مدارک (CPF، RNE، Carteira de Trabalho)، مرکز CRAI، قانون کار و حقوق کارگر، و زندگی روزمره.',
  objectivesFa: [
    'افعال باقاعدهٔ سه گروه (-AR, -ER, -IR) را در زمان حال درست صرف کنید.',
    'افعال بی‌قاعدهٔ پرکاربرد SER، IR، FAZER و ESTAR را در زمان حال به‌کار ببرید.',
    'گذشتهٔ کامل (Pretérito Perfeito) را برای بیان کارهای تمام‌شده به‌کار ببرید.',
    'گذشتهٔ استمراری (Pretérito Imperfeito) را برای عادت‌ها و توصیف گذشته بشناسید.',
    'زمان آینده را هم با صرف ساده و هم با ساختار «ir + مصدر» بسازید.',
    'واژگان مربوط به مدارک و قانون کار در برزیل را در جمله به‌کار ببرید.',
  ],
  sections: [
    {
      headingFa: '۱. مرور کلی درس',
      bodyFa:
        'این درس بیشتر تمرین است تا نظریه. هدف این است که صرفِ افعال را در چهار زمانِ اصلی «به‌صورت خودکار» تمرین کنید. جزوهٔ اصلی از شما می‌خواهد افعال را در این زمان‌ها صرف کنید:\n\n۱) PRESENTE DO INDICATIVO — زمان حال ساده (کارهای همیشگی، عادت‌ها، حقایق)\n۲) PRETÉRITO PERFEITO — گذشتهٔ کامل (کاری که در گذشته تمام شده است)\n۳) PRETÉRITO IMPERFEITO — گذشتهٔ استمراری (عادت یا حالتِ ادامه‌دار در گذشته)\n۴) FUTURO — آینده\n\nبرای هر زمان چهار «شخص» را صرف می‌کنیم:\nEU (من)\nVOCÊ / ELE / ELA / A GENTE (تو-شما / او / او / ما ـ غیررسمی) → همگی سوم‌شخص مفرد\nNÓS (ما)\nVOCÊS / ELES / ELAS (شما / آن‌ها) → همگی سوم‌شخص جمع\n\nنکته: در پرتغالی برزیلی «a gente» با فعلِ سوم‌شخص مفرد می‌آید (مثل ele/ela)، هرچند معنی «ما» می‌دهد.',
      examples: [
        {
          pt: 'EU / VOCÊ, ELE, ELA, A GENTE / NÓS / VOCÊS, ELES, ELAS',
          fa: 'من / تو-او-ما(غیررسمی) / ما / شما-آن‌ها',
          pron: 'اِئو / وُسه، اِلی، اِلا، آ جِنتی / نُس / وُسِس، اِلیس، اِلاس',
          note: 'این چهار ردیف در همهٔ جدول‌های صرف تکرار می‌شوند.',
        },
      ],
    },
    {
      headingFa: '۲. زمان حال ـ افعال باقاعدهٔ گروه ‑AR',
      bodyFa:
        'برای صرف، ابتدا پایانهٔ مصدر (-ar) را برمی‌داریم و پایانهٔ مناسبِ هر شخص را می‌افزاییم. الگوی گروه ‑AR (مثال: FALAR = حرف زدن، TRABALHAR = کار کردن، ACORDAR = بیدار شدن، MORAR = زندگی کردن):\n\nEU            → -o        (falo)\nVOCÊ/ELE/ELA/A GENTE → -a  (fala)\nNÓS           → -amos     (falamos)\nVOCÊS/ELES/ELAS → -am     (falam)\n\nمثال کامل با TRABALHAR:\neu trabalho / você trabalha / nós trabalhamos / eles trabalham',
      examples: [
        {
          pt: 'Eu acordo cedo durante a semana.',
          fa: 'من در طول هفته زود بیدار می‌شوم.',
          pron: 'اِئو آکوردو سِدو دورانتی آ سِمانا',
          note: 'acordar گروه ‑AR: اول‌شخص مفرد acordo.',
        },
        {
          pt: 'Meus pais acordam mais tarde no fim de semana.',
          fa: 'پدر و مادرم آخر هفته دیرتر بیدار می‌شوند.',
          pron: 'مِئوس پایس آکوردام مایس تارجی',
          note: 'سوم‌شخص جمع: acordam.',
        },
        {
          pt: 'Nós moramos em São Paulo.',
          fa: 'ما در سائوپائولو زندگی می‌کنیم.',
          pron: 'نُس موراموس اِین سائو پائولو',
        },
      ],
    },
    {
      headingFa: '۳. زمان حال ـ افعال باقاعدهٔ گروه ‑ER',
      bodyFa:
        'الگوی گروه ‑ER (مثال: COMER = خوردن، ESCREVER = نوشتن، ESCOLHER = انتخاب کردن، RECEBER = دریافت کردن):\n\nEU            → -o        (como)\nVOCÊ/ELE/ELA/A GENTE → -e  (come)\nNÓS           → -emos     (comemos)\nVOCÊS/ELES/ELAS → -em     (comem)\n\nمثال کامل با COMER:\neu como / você come / nós comemos / eles comem',
      examples: [
        {
          pt: 'Eu como pouco durante o verão.',
          fa: 'من در تابستان کم می‌خورم.',
          pron: 'اِئو کُمو پُوکو دورانتی او وِرائو',
          note: 'اول‌شخص مفرد گروه ‑ER: como.',
        },
        {
          pt: 'Os seus tios comem arroz com feijão?',
          fa: 'عمو/دایی‌های شما برنج با لوبیا می‌خورند؟',
          pron: 'اوس سِئوس تیوس کُمِین آخوس کُن فِیژائو',
          note: 'arroz com feijão غذای پایهٔ برزیلی است.',
        },
      ],
    },
    {
      headingFa: '۴. زمان حال ـ افعال باقاعدهٔ گروه ‑IR',
      bodyFa:
        'الگوی گروه ‑IR (مثال: PARTIR = عزیمت کردن/رفتن، DIVIDIR = تقسیم کردن، DIRIGIR = رانندگی کردن). توجه: در زمان حال، تنها تفاوتِ ‑IR با ‑ER در شخص «nós» است (‑imos به‌جای ‑emos):\n\nEU            → -o        (parto)\nVOCÊ/ELE/ELA/A GENTE → -e  (parte)\nNÓS           → -imos     (partimos)\nVOCÊS/ELES/ELAS → -em     (partem)\n\nمثال کامل با PARTIR:\neu parto / você parte / nós partimos / eles partem',
      examples: [
        {
          pt: 'Eu parto cedo de casa.',
          fa: 'من زود از خانه بیرون می‌روم.',
          pron: 'اِئو پارتو سِدو جی کازا',
          note: 'اول‌شخص مفرد: parto.',
        },
        {
          pt: 'Nós não partimos de casa sozinhos sem nossos pais.',
          fa: 'ما بدون پدر و مادرمان تنها از خانه بیرون نمی‌رویم.',
          pron: 'نُس نائو پارتیموس جی کازا سوزینیوس',
          note: 'شخص nós در گروه ‑IR: partimos.',
        },
      ],
    },
    {
      headingFa: '۵. زمان حال ـ افعال بی‌قاعدهٔ پرکاربرد',
      bodyFa:
        'چهار فعلِ بی‌قاعده که در این درس زیاد می‌آیند را باید حفظ کنید:\n\nSER (بودن ـ ثابت/هویت):\neu sou / você-ele-ela é / nós somos / vocês-eles são\n\nIR (رفتن):\neu vou / você-ele-ela vai / nós vamos / vocês-eles vão\n\nFAZER (انجام دادن/ساختن):\neu faço / você-ele-ela faz / nós fazemos / vocês-eles fazem\n\nESTAR (بودن ـ موقتی/مکان):\neu estou / você-ele-ela está / nós estamos / vocês-eles estão\n\nنکته: فعل IR اغلب با حرف اضافهٔ مقصد می‌آید: ir a (ao/à) = رفتن به، ir para = رفتن به‌سویِ.',
      examples: [
        {
          pt: 'Eu vou ao parque. Maria vai ao cinema.',
          fa: 'من به پارک می‌روم. ماریا به سینما می‌رود.',
          pron: 'اِئو وُو آئو پارکی. ماریا وای آئو سینِما',
          note: 'ao = a + o (مذکر). vou اول‌شخص، vai سوم‌شخص.',
        },
        {
          pt: 'Eu e Luciana vamos para uma festa.',
          fa: 'من و لوسیانا به یک مهمانی می‌رویم.',
          pron: 'اِئو ای لوسیانا واموس پارا اوما فِستا',
          note: '«من و …» = nós → vamos.',
        },
        {
          pt: 'Vocês nunca vão para a piscina com a gente.',
          fa: 'شما هیچ‌وقت با ما به استخر نمی‌آیید.',
          pron: 'وُسِس نونکا وائو پارا آ پیسینا کُن آ جِنتی',
          note: 'سوم‌شخص جمع IR: vão.',
        },
      ],
    },
    {
      headingFa: '۶. گذشتهٔ کامل (Pretérito Perfeito) ـ افعال باقاعده',
      bodyFa:
        'گذشتهٔ کامل برای کاری است که در گذشته شروع و تمام شده است (معادل گذشتهٔ سادهٔ فارسی: «کردم، خوردم، رفتم»). پایانه‌های باقاعده:\n\nگروه ‑AR (trabalhar):\neu trabalhei / ele trabalhou / nós trabalhamos / eles trabalharam\n\nگروه ‑ER (comer):\neu comi / ele comeu / nós comemos / eles comeram\n\nگروه ‑IR (partir):\neu parti / ele partiu / nós partimos / eles partiram\n\nنکته: در گروه ‑AR شخص nós در گذشتهٔ کامل و زمان حال یکسان است (trabalhamos)؛ بافت جمله معنا را روشن می‌کند. کلماتِ «ontem» (دیروز)، «no ano passado» (سال گذشته)، «já» (قبلاً) نشانهٔ گذشتهٔ کامل هستند.',
      examples: [
        {
          pt: 'Eu já tirei a minha Carteira de Trabalho.',
          fa: 'من قبلاً کارت کارم را گرفته‌ام.',
          pron: 'اِئو ژا تیرِی آ مینیا کارتِیرا جی ترابالیو',
          note: 'tirar (‑AR) اول‌شخص گذشته: tirei.',
        },
        {
          pt: 'A empresa me contratou por 90 dias.',
          fa: 'شرکت مرا برای ۹۰ روز استخدام کرد.',
          pron: 'آ اِمپرِزا می کُنتراتُو پور نوونتا دیاس',
          note: 'سوم‌شخص گذشتهٔ ‑AR: contratou.',
        },
        {
          pt: 'Karen tomou leite com mel ontem à noite.',
          fa: 'کارِن دیشب شیر با عسل خورد (نوشید).',
          pron: 'کارِن تُمُو لِیتی کُن مِل اُنتِین آ نُیتی',
          note: 'tomar (‑AR) سوم‌شخص گذشته: tomou.',
        },
      ],
    },
    {
      headingFa: '۷. گذشتهٔ کامل ـ افعال بی‌قاعده (FAZER, IR/SER)',
      bodyFa:
        'برخی افعالِ پرکاربرد در گذشتهٔ کامل بی‌قاعده‌اند و باید حفظ شوند:\n\nFAZER (انجام دادن):\neu fiz / ele fez / nós fizemos / eles fizeram\n\nIR و SER در گذشته شکل یکسان دارند:\neu fui / ele foi / nós fomos / eles foram\n\nمثال: «Eu fiz duas horas extras» (من دو ساعت اضافه‌کاری کردم). بافت جمله تعیین می‌کند fui یعنی «رفتم» (IR) یا «بودم» (SER).',
      examples: [
        {
          pt: 'Eu fiz duas horas extras no meu trabalho.',
          fa: 'من در محل کارم دو ساعت اضافه‌کاری کردم.',
          pron: 'اِئو فیز دواس اُراس اِستراس',
          note: 'fazer گذشته اول‌شخص: fiz.',
        },
      ],
    },
    {
      headingFa: '۸. گذشتهٔ استمراری (Pretérito Imperfeito)',
      bodyFa:
        'این زمان برای عادت‌ها، توصیف‌ها و حالت‌های ادامه‌دار در گذشته است (معادل «می‌کردم، می‌خوردم، زندگی می‌کردم» در فارسی). پایانه‌ها:\n\nگروه ‑AR (morar, trabalhar, tomar, gostar):\neu morava / ele morava / nós morávamos / eles moravam\n\nگروه ‑ER و ‑IR (comer, dividir) ـ پایانه یکسان است:\neu comia / ele comia / nós comíamos / eles comiam\neu dividia / nós dividíamos / eles dividiam\n\nکاربرد رایج: توصیف زندگی در کشورِ قبلی — «No meu país, eu trabalhava como…» (در کشورم به‌عنوان … کار می‌کردم).',
      examples: [
        {
          pt: 'No meu país, eu trabalhava como professor.',
          fa: 'در کشورم به‌عنوان معلم کار می‌کردم.',
          pron: 'نو مِئو پایس، اِئو ترابالیاوا کُمو پروفِسور',
          note: 'trabalhar گذشتهٔ استمراری اول‌شخص: trabalhava.',
        },
        {
          pt: 'No meu país, eu comia arroz todos os dias.',
          fa: 'در کشورم هر روز برنج می‌خوردم.',
          pron: 'نو مِئو پایس، اِئو کُمیا آخوس تودوس اوس دیاس',
          note: 'comer گذشتهٔ استمراری: comia.',
        },
        {
          pt: 'Eu morava em outro país no passado.',
          fa: 'من در گذشته در کشور دیگری زندگی می‌کردم.',
          pron: 'اِئو موراوا اِین اُترو پایس نو پاسادو',
          note: '«no passado» نشانهٔ گذشته است.',
        },
      ],
    },
    {
      headingFa: '۹. زمان آینده (Futuro)',
      bodyFa:
        'برای آینده دو راه وجود دارد:\n\n۱) آیندهٔ ساده (Futuro do Presente): پایانه‌ها به مصدرِ کامل افزوده می‌شوند و برای هر سه گروه یکسان‌اند:\neu -ei / ele -á / nós -emos / eles -ão\nمثال (comprar): comprarei / comprará / compraremos / comprarão\nمثال (comer): comerei / comerá / comeremos / comerão\n\nافعال بی‌قاعدهٔ آینده: fazer → farei/fará/faremos/farão؛ ser → serei/será/seremos/serão.\n\n۲) آیندهٔ نزدیک (رایج‌تر در گفتار): ir (در زمان حال) + مصدر:\neu vou comprar / nós vamos comer / eles vão beber\n\nهر دو درست‌اند؛ در گفتار روزمرهٔ برزیل، «vou + مصدر» بسیار رایج‌تر است. فعل ir به‌تنهایی هم برای بیان آیندهٔ حرکت به‌کار می‌رود: «Amanhã eu vou à praia» (فردا به ساحل می‌روم).',
      examples: [
        {
          pt: 'Amanhã eu vou à praia e depois nós vamos ao cinema.',
          fa: 'فردا من به ساحل می‌روم و بعد با هم به سینما می‌رویم.',
          pron: 'آمانیا اِئو وُو آ پرایا ای دِپُیس نُس واموس آئو سینِما',
          note: 'در اینجا خودِ ir معنای آینده و حرکت را می‌رساند.',
        },
        {
          pt: 'Tenho certeza que amanhã será um grande dia para você!',
          fa: 'مطمئنم که فردا روزِ بزرگی برای تو خواهد بود!',
          pron: 'تِنیو سِرتِزا کی آمانیا سِرا اوم گرانجی جیا',
          note: 'ser آیندهٔ سوم‌شخص: será (یا vai ser).',
        },
        {
          pt: 'Domingo nós vamos fazer um grande almoço em família.',
          fa: 'یکشنبه ما یک ناهار بزرگ خانوادگی خواهیم داشت.',
          pron: 'دومینگو نُس واموس فازِر اوم گرانجی آلمُسو',
          note: 'آیندهٔ نزدیک: vamos fazer (یا faremos).',
        },
      ],
    },
    {
      headingFa: '۱۰. بافت کاربردی: مدارک (CPF، RNE، Carteira de Trabalho، CRAI)',
      bodyFa:
        'بخشی از تمرین‌ها در بافتِ گرفتن مدارک قانونی در برزیل است. واژگان کلیدی:\n\nCPF = Cadastro da Pessoa Física — شمارهٔ مالیاتی/شناسایی افراد، برای فعالیت‌های تجاری لازم است؛ در «Receita Federal» (ادارهٔ مالیات فدرال) گرفته می‌شود.\nRNE = Registro Nacional de Estrangeiro — سند شناسایی خارجیان در برزیل؛ در «Polícia Federal» گرفته می‌شود.\nCarteira de Trabalho — کارت کار؛ در «Superintendência Regional do Trabalho e Emprego» گرفته می‌شود.\nCRAI = Centro de Referência e Acolhida para Imigrantes — مرکز مرجع و پذیرش مهاجران؛ اطلاعات و مشاورهٔ حقوقی برای پناهندگان و مهاجران می‌دهد.\n\nافعال پرکاربرد این بخش (زمان حال): precisar (نیاز داشتن)، significar (معنی دادن)، existir (وجود داشتن)، encontrar (یافتن)، ficar (واقع بودن)، atender (پاسخ‌گویی کردن).',
      examples: [
        {
          pt: 'Eu preciso tirar CPF, RNE e Carteira de Trabalho.',
          fa: 'من باید CPF، RNE و کارت کار بگیرم.',
          pron: 'اِئو پرِسیزو تیرار سِپِاِفی، اِخِنی ای کارتِیرا جی ترابالیو',
          note: 'precisar + مصدر = لازم بودن که کاری انجام شود.',
        },
        {
          pt: 'O CRAI fica na Rua Japurá, 212 – Bela Vista.',
          fa: 'مرکز CRAI در خیابان ژاپورا، شمارهٔ ۲۱۲ – بلا ویستا واقع است.',
          pron: 'او کِرای فیکا نا خوا ژاپورا',
          note: 'ficar برای مکانِ ثابتِ یک ساختمان به‌کار می‌رود.',
        },
        {
          pt: 'CPF significa Cadastro da Pessoa Física.',
          fa: 'CPF یعنی «ثبتِ شخص حقیقی».',
          pron: 'سِپِاِفی سیگنیفیکا کاداسترو دا پِسوآ فیزیکا',
          note: 'significar (‑AR): سوم‌شخص significa.',
        },
      ],
    },
    {
      headingFa: '۱۱. بافت کاربردی: کار و قانون کار',
      bodyFa:
        'بخش دیگری از تمرین‌ها دربارهٔ حقوق کارگر است. نکات و واژگان:\n\n• با مدارک منظم می‌توانید «Contrato de Trabalho» (قرارداد کار) تا ۹۰ روز داشته باشید؛ پس از آن شرکت می‌تواند قرارداد را به‌صورت نامعین تمدید کند.\n• کارِ شایسته حداکثر ۸ ساعت در روز است؛ بیش از آن «hora extra» (اضافه‌کاری) محسوب می‌شود و ۵۰٪ بیشتر از ساعتِ عادی پرداخت می‌شود. اضافه‌کاری نباید از ۲ ساعت در روز بیشتر شود.\n• کارگر حق یک روز «folga» (مرخصی/تعطیلی) در هفته دارد.\n• کارِ شبانه (مثلاً از ۲۲ تا ۵) «adicional noturno» (فوق‌العادهٔ شب) ۲۰٪ دارد.\n• از حقوقِ ثبت‌شده کسوراتی برداشته می‌شود: INSS، Taxas Sindicais (حق سندیکا)، Imposto de Renda (مالیات بر درآمد) و Vale Transporte (کمک‌هزینهٔ ایاب‌وذهاب).\n\nافعال این بخش بیشتر در گذشتهٔ کامل می‌آیند: assinar (امضا کردن)، contratar (استخدام کردن)، descobrir (کشف/پی بردن)، passar (گذشتن/رد شدن)، explicar (توضیح دادن)، receber (دریافت کردن)، conseguir (موفق شدن/به‌دست آوردن)، regularizar (قانونی کردن)، folgar (مرخصی داشتن).',
      examples: [
        {
          pt: 'Eu trabalhei 12 horas por dia, mas depois descobri que o trabalho decente é de no máximo 8 horas.',
          fa: 'من روزی ۱۲ ساعت کار کردم، اما بعد فهمیدم که کارِ شایسته حداکثر ۸ ساعت است.',
          pron: 'اِئو ترابالیِی دوزی اُراس ... مَس دِپُیس دِسکوبری',
          note: 'trabalhei (‑AR) و descobri (‑IR) هر دو گذشتهٔ اول‌شخص.',
        },
        {
          pt: 'Ontem eu recebi o meu salário com o adicional noturno de 20%.',
          fa: 'دیروز حقوقم را با فوق‌العادهٔ شبِ ۲۰ درصدی دریافت کردم.',
          pron: 'اُنتِین اِئو خِسِبی او مِئو سالاریو',
          note: 'receber (‑ER) گذشتهٔ اول‌شخص: recebi.',
        },
      ],
    },
    {
      headingFa: '۱۲. گفت‌وگوی معرفی با فعل SER',
      bodyFa:
        'یکی از تمرین‌ها یک گفت‌وگوی کوتاهِ آشنایی است که با فعل SER در زمان حال کامل می‌شود. کل گفت‌وگو:\n\nAndreia: Como é seu nome? (اسمت چیست؟)\nCarol: Meu nome é Carol. E você, qual é seu nome? (اسم من کارول است. تو، اسمت چیست؟)\nAndreia: Eu sou a Andreia. Você é estudante? (من آندریا هستم. تو دانشجویی؟)\nCarol: Sou, sim. E você também é estudante? (بله، هستم. تو هم دانشجویی؟)\nAndreia: Não, eu sou professora. (نه، من معلم هستم.)\n\nنکته: «Como é seu nome?» و «Qual é seu nome?» هر دو یعنی «اسمت چیست؟».',
      examples: [
        {
          pt: 'Eu sou a Andreia. Você é estudante?',
          fa: 'من آندریا هستم. تو دانشجویی؟',
          pron: 'اِئو سُ آ آندرِیا. وُسه اِ اِستودانتی؟',
          note: 'sou اول‌شخص، é سوم‌شخص/دوم‌شخص (você).',
        },
      ],
    },
  ],
  keyPointsFa: [
    'زمان حالِ باقاعده: ‑AR (o/a/amos/am)، ‑ER (o/e/emos/em)، ‑IR (o/e/imos/em).',
    'گذشتهٔ کامل باقاعده: ‑AR (ei/ou/amos/aram)، ‑ER (i/eu/emos/eram)، ‑IR (i/iu/imos/iram).',
    'گذشتهٔ استمراری: ‑AR (ava/ava/ávamos/avam)؛ ‑ER و ‑IR (ia/ia/íamos/iam).',
    'آینده: پایانهٔ ثابت روی مصدر (ei/á/emos/ão) یا ساختار رایجِ «ir + مصدر».',
    'افعال بی‌قاعدهٔ کلیدی: SER (sou/é/somos/são)، IR (vou/vai/vamos/vão)، FAZER (faço/faz/fazemos/fazem, گذشته fiz/fez).',
    'در گذشته، IR و SER شکل یکسان دارند: fui/foi/fomos/foram.',
    '«a gente» با فعل سوم‌شخص مفرد می‌آید هرچند معنی «ما» می‌دهد.',
    'واژگان مدارک: CPF (Receita Federal)، RNE (Polícia Federal)، Carteira de Trabalho، و مرکز CRAI برای مهاجران.',
  ],
  quiz: [
    {
      id: 'course-aula-9-q1',
      type: 'fill-blank',
      prompt:
        'Complete o diálogo com SER (presente): Andreia: Como ___ seu nome? Carol: Meu nome ___ Carol. E você, qual ___ seu nome? Andreia: Eu ___ a Andreia. Você ___ estudante? Carol: ___, sim. E você também ___ estudante? Andreia: Não, eu ___ professora.',
      promptFa: 'جای خالی‌ها را با فعل SER در زمان حال کامل کنید (به ترتیب).',
      options: [],
      answer: 'é / é / é / sou / é / Sou / é / sou',
      explanationFa:
        'SER زمان حال: eu sou، você/ele/ela é. پس همهٔ جاهای سوم‌شخص «é» و اول‌شخص (Eu) «sou» می‌شود.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q2',
      type: 'fill-blank',
      prompt: 'Maria ___ ao cinema. (IR, presente)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'vai',
      explanationFa: 'IR سوم‌شخص مفرد: vai. «ao» = a + o.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q3',
      type: 'fill-blank',
      prompt: 'Eu ___ ao parque. (IR, presente)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (اول‌شخص مفرد).',
      options: [],
      answer: 'vou',
      explanationFa: 'IR اول‌شخص مفرد: vou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q4',
      type: 'fill-blank',
      prompt: 'Mário ___ para a escola. (IR, presente)',
      promptFa: 'با فعل IR در زمان حال کامل کنید.',
      options: [],
      answer: 'vai',
      explanationFa: 'IR سوم‌شخص مفرد: vai. «ir para» = رفتن به‌سوی.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q5',
      type: 'fill-blank',
      prompt: 'Eu e Luciana ___ para uma festa. (IR, presente)',
      promptFa: 'با فعل IR در زمان حال کامل کنید («من و …» = nós).',
      options: [],
      answer: 'vamos',
      explanationFa: '«Eu e Luciana» = nós → vamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q6',
      type: 'fill-blank',
      prompt: 'João e Tatiana ___ para o trabalho. (IR, presente)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'vão',
      explanationFa: 'دو نفر (سوم‌شخص جمع) → vão.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q7',
      type: 'fill-blank',
      prompt: 'Vocês nunca ___ para a piscina com a gente. (IR, presente)',
      promptFa: 'با فعل IR در زمان حال کامل کنید (vocês).',
      options: [],
      answer: 'vão',
      explanationFa: 'vocês با شکل سوم‌شخص جمع می‌آید → vão.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q8',
      type: 'fill-blank',
      prompt: 'Eu ___ cedo durante a semana. (acordar, presente)',
      promptFa: 'با فعل acordar در زمان حال کامل کنید.',
      options: [],
      answer: 'acordo',
      explanationFa: 'acordar (‑AR) اول‌شخص: acordo.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q9',
      type: 'fill-blank',
      prompt: 'Meus pais ___ mais tarde durante o fim de semana. (acordar, presente)',
      promptFa: 'با فعل acordar در زمان حال کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'acordam',
      explanationFa: 'acordar (‑AR) سوم‌شخص جمع: acordam.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q10',
      type: 'fill-blank',
      prompt: 'Minha irmã não ___ cedo aos domingos. (acordar, presente)',
      promptFa: 'با فعل acordar در زمان حال کامل کنید (سوم‌شخص مفرد).',
      options: [],
      answer: 'acorda',
      explanationFa: 'acordar (‑AR) سوم‌شخص مفرد: acorda.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q11',
      type: 'fill-blank',
      prompt: 'Minha avó ___ bastante aos sábados. (comer, presente)',
      promptFa: 'با فعل comer در زمان حال کامل کنید.',
      options: [],
      answer: 'come',
      explanationFa: 'comer (‑ER) سوم‌شخص مفرد: come.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q12',
      type: 'fill-blank',
      prompt: 'Eu ___ pouco durante o verão. (comer, presente)',
      promptFa: 'با فعل comer در زمان حال کامل کنید (اول‌شخص).',
      options: [],
      answer: 'como',
      explanationFa: 'comer (‑ER) اول‌شخص: como.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q13',
      type: 'fill-blank',
      prompt: 'Os seus tios ___ arroz com feijão? (comer, presente)',
      promptFa: 'با فعل comer در زمان حال کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'comem',
      explanationFa: 'comer (‑ER) سوم‌شخص جمع: comem.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q14',
      type: 'fill-blank',
      prompt: 'Meu primo ___ na segunda-feira para São Paulo. (partir, presente)',
      promptFa: 'با فعل partir در زمان حال کامل کنید.',
      options: [],
      answer: 'parte',
      explanationFa: 'partir (‑IR) سوم‌شخص مفرد: parte.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q15',
      type: 'fill-blank',
      prompt: 'Eu ___ cedo de casa. (partir, presente)',
      promptFa: 'با فعل partir در زمان حال کامل کنید (اول‌شخص).',
      options: [],
      answer: 'parto',
      explanationFa: 'partir (‑IR) اول‌شخص: parto.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q16',
      type: 'fill-blank',
      prompt: 'Nós não ___ de casa sozinhos sem nossos pais. (partir, presente)',
      promptFa: 'با فعل partir در زمان حال کامل کنید (nós).',
      options: [],
      answer: 'partimos',
      explanationFa: 'partir (‑IR) شخص nós: partimos (توجه: ‑imos نه ‑emos).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q17',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ como professor. (trabalhar, pretérito imperfeito)',
      promptFa: 'با فعل trabalhar در گذشتهٔ استمراری کامل کنید (بخش شغل آزاد است).',
      options: [],
      answer: 'trabalhava',
      explanationFa: 'trabalhar (‑AR) گذشتهٔ استمراری اول‌شخص: trabalhava (عادتِ گذشته).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q18',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ arroz todos os dias. (comer, pretérito imperfeito)',
      promptFa: 'با فعل comer در گذشتهٔ استمراری کامل کنید.',
      options: [],
      answer: 'comia',
      explanationFa: 'comer (‑ER) گذشتهٔ استمراری اول‌شخص: comia.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q19',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ a minha casa com a família. (dividir, pretérito imperfeito)',
      promptFa: 'با فعل dividir در گذشتهٔ استمراری کامل کنید.',
      options: [],
      answer: 'dividia',
      explanationFa: 'dividir (‑IR) گذشتهٔ استمراری اول‌شخص: dividia.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q20',
      type: 'fill-blank',
      prompt: 'No meu país, eu ___ chá no café da manhã. (tomar, pretérito imperfeito)',
      promptFa: 'با فعل tomar در گذشتهٔ استمراری کامل کنید.',
      options: [],
      answer: 'tomava',
      explanationFa: 'tomar (‑AR) گذشتهٔ استمراری اول‌شخص: tomava.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q21',
      type: 'fill-blank',
      prompt: 'Na minha cidade, eu ___ de caminhar no parque. (gostar, pretérito imperfeito)',
      promptFa: 'با فعل gostar در گذشتهٔ استمراری کامل کنید.',
      options: [],
      answer: 'gostava',
      explanationFa: 'gostar (‑AR) گذشتهٔ استمراری اول‌شخص: gostava. «gostar de» + چیز/کار.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q22',
      type: 'fill-blank',
      prompt: 'Eu ___ tirar CPF, RNE e Carteira de Trabalho. (precisar, presente)',
      promptFa: 'با فعل precisar در زمان حال کامل کنید.',
      options: [],
      answer: 'preciso',
      explanationFa: 'precisar (‑AR) اول‌شخص: preciso. «precisar + مصدر» = لازم بودن.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q23',
      type: 'fill-blank',
      prompt: 'CPF ___ Cadastro da Pessoa Física. (significar, presente)',
      promptFa: 'با فعل significar در زمان حال کامل کنید.',
      options: [],
      answer: 'significa',
      explanationFa: 'significar (‑AR) سوم‌شخص مفرد: significa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q24',
      type: 'fill-blank',
      prompt: 'Você ___ ir até a Receita Federal para tirar o CPF. (precisar, presente)',
      promptFa: 'با فعل precisar در زمان حال کامل کنید (você).',
      options: [],
      answer: 'precisa',
      explanationFa: 'precisar سوم‌شخص/você: precisa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q25',
      type: 'fill-blank',
      prompt: 'RNE ___ Registro Nacional de Estrangeiro. (significar, presente)',
      promptFa: 'با فعل significar در زمان حال کامل کنید.',
      options: [],
      answer: 'significa',
      explanationFa: 'significar سوم‌شخص مفرد: significa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q26',
      type: 'fill-blank',
      prompt: 'Você ___ ir até a Polícia Federal para tirar o RNE. (precisar, presente)',
      promptFa: 'با فعل precisar در زمان حال کامل کنید (você).',
      options: [],
      answer: 'precisa',
      explanationFa: 'precisar سوم‌شخص/você: precisa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q27',
      type: 'fill-blank',
      prompt:
        'Você ___ ir até a Superintendência Regional do Trabalho e Emprego para tirar a Carteira de Trabalho. (precisar, presente)',
      promptFa: 'با فعل precisar در زمان حال کامل کنید (você).',
      options: [],
      answer: 'precisa',
      explanationFa: 'precisar سوم‌شخص/você: precisa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q28',
      type: 'fill-blank',
      prompt: 'Eu ___ e ___ trabalho todos os dias. (acordar / procurar, presente)',
      promptFa: 'با دو فعل acordar و procurar در زمان حال کامل کنید (اول‌شخص).',
      options: [],
      answer: 'acordo / procuro',
      explanationFa: 'هر دو ‑AR اول‌شخص: acordo، procuro.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q29',
      type: 'fill-blank',
      prompt: 'Para informações e apoio geral ___ o CRAI. (existir, presente)',
      promptFa: 'با فعل existir در زمان حال کامل کنید.',
      options: [],
      answer: 'existe',
      explanationFa: 'existir (‑IR) سوم‌شخص مفرد: existe.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q30',
      type: 'fill-blank',
      prompt:
        'No CRAI você ___ informações e orientações jurídicas para refugiados e imigrantes. (encontrar, presente)',
      promptFa: 'با فعل encontrar در زمان حال کامل کنید (você).',
      options: [],
      answer: 'encontra',
      explanationFa: 'encontrar (‑AR) سوم‌شخص/você: encontra.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q31',
      type: 'fill-blank',
      prompt: 'O CRAI ___ na Rua Japurá, 212 – Bela Vista. (ficar, presente)',
      promptFa: 'با فعل ficar در زمان حال کامل کنید.',
      options: [],
      answer: 'fica',
      explanationFa: 'ficar (‑AR) سوم‌شخص مفرد: fica؛ برای مکانِ ساختمان.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q32',
      type: 'fill-blank',
      prompt: 'O CRAI ___ pelo telefone 3598-7200. (atender, presente)',
      promptFa: 'با فعل atender در زمان حال کامل کنید.',
      options: [],
      answer: 'atende',
      explanationFa: 'atender (‑ER) سوم‌شخص مفرد: atende.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q33',
      type: 'fill-blank',
      prompt: 'Eu já ___ a minha Carteira de Trabalho. (tirar, pretérito perfeito)',
      promptFa: 'با فعل tirar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'tirei',
      explanationFa: 'tirar (‑AR) گذشتهٔ کامل اول‌شخص: tirei. «já» نشانهٔ گذشته.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q34',
      type: 'fill-blank',
      prompt:
        'Se você ainda não ___ a sua Carteira de Trabalho, precisa ir até a Superintendência. (tirar, pretérito perfeito)',
      promptFa: 'با فعل tirar در گذشتهٔ کامل کامل کنید (você).',
      options: [],
      answer: 'tirou',
      explanationFa: 'tirar گذشتهٔ کامل سوم‌شخص/você: tirou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q35',
      type: 'fill-blank',
      prompt:
        'Se você já ___ a sua documentação de trabalho, você pode ter um Contrato de Trabalho de até 90 dias. (regularizar, pretérito perfeito)',
      promptFa: 'با فعل regularizar در گذشتهٔ کامل کامل کنید (você).',
      options: [],
      answer: 'regularizou',
      explanationFa: 'regularizar (‑AR) گذشتهٔ کامل você: regularizou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q36',
      type: 'fill-blank',
      prompt: 'Eu já ___ meu Contrato de Trabalho. (assinar, pretérito perfeito)',
      promptFa: 'با فعل assinar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'assinei',
      explanationFa: 'assinar (‑AR) گذشتهٔ کامل اول‌شخص: assinei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q37',
      type: 'fill-blank',
      prompt: 'A empresa me ___ por 90 dias. (contratar, pretérito perfeito)',
      promptFa: 'با فعل contratar در گذشتهٔ کامل کامل کنید (سوم‌شخص).',
      options: [],
      answer: 'contratou',
      explanationFa: 'contratar (‑AR) گذشتهٔ کامل سوم‌شخص: contratou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q38',
      type: 'fill-blank',
      prompt:
        'Eu já ___ 12 horas por dia em uma confecção, mas depois ___ que o trabalho decente é de no máximo 8 horas. (trabalhar / descobrir, pretérito perfeito)',
      promptFa: 'با دو فعل trabalhar و descobrir در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'trabalhei / descobri',
      explanationFa: 'trabalhar (‑AR)→ trabalhei؛ descobrir (‑IR)→ descobri. هر دو اول‌شخص گذشته.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q39',
      type: 'fill-blank',
      prompt:
        'Se você trabalhou e ___ de 8 horas por dia, deve receber hora extra. (passar, pretérito perfeito)',
      promptFa: 'با فعل passar در گذشتهٔ کامل کامل کنید (você).',
      options: [],
      answer: 'passou',
      explanationFa: 'passar (‑AR) گذشتهٔ کامل você: passou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q40',
      type: 'fill-blank',
      prompt:
        'Meu chefe me ___ que a hora extra não pode passar de duas horas por dia. (explicar, pretérito perfeito)',
      promptFa: 'با فعل explicar در گذشتهٔ کامل کامل کنید (سوم‌شخص).',
      options: [],
      answer: 'explicou',
      explanationFa: 'explicar (‑AR) گذشتهٔ کامل سوم‌شخص: explicou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q41',
      type: 'fill-blank',
      prompt: 'Eu fiz duas horas extras e ___ 50% a mais que a hora normal. (receber, pretérito perfeito)',
      promptFa: 'با فعل receber در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'recebi',
      explanationFa: 'receber (‑ER) گذشتهٔ کامل اول‌شخص: recebi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q42',
      type: 'fill-blank',
      prompt:
        'Se você ___ de segunda a segunda e não ___, tem direito a um dia de folga por semana. (trabalhar / folgar, pretérito perfeito)',
      promptFa: 'با دو فعل trabalhar و folgar در گذشتهٔ کامل کامل کنید (você).',
      options: [],
      answer: 'trabalhou / folgou',
      explanationFa: 'هر دو ‑AR گذشتهٔ کامل você: trabalhou، folgou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q43',
      type: 'fill-blank',
      prompt:
        'Trabalho das 22h às 5h como segurança. Ontem eu ___ o meu salário com o adicional noturno de 20%. (receber, pretérito perfeito)',
      promptFa: 'با فعل receber در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'recebi',
      explanationFa: 'receber گذشتهٔ کامل اول‌شخص: recebi. «Ontem» نشانهٔ گذشته.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q44',
      type: 'fill-blank',
      prompt:
        'Meu amigo ___ R$ 600,00 de salário, então eu ___ que não está dentro da Lei. (receber / explicar, pretérito perfeito)',
      promptFa: 'با دو فعل receber و explicar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'recebeu / expliquei',
      explanationFa: 'receber سوم‌شخص گذشته: recebeu؛ explicar اول‌شخص گذشته: expliquei (c→qu پیش از e).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q45',
      type: 'fill-blank',
      prompt:
        'Eu ___ um trabalho registrado e dentro da Lei, então tenho muitos descontos no salário. (conseguir, pretérito perfeito)',
      promptFa: 'با فعل conseguir در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'consegui',
      explanationFa: 'conseguir (‑IR) گذشتهٔ کامل اول‌شخص: consegui.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q46',
      type: 'fill-blank',
      prompt: 'Eu ___ em outro país no passado. (morar, pretérito imperfeito)',
      promptFa: 'با فعل morar متناسب با «no passado» کامل کنید.',
      options: [],
      answer: 'morava',
      explanationFa: '«no passado» + عادت/حالت گذشته → گذشتهٔ استمراری: morava.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q47',
      type: 'fill-blank',
      prompt: 'Eu e meus pais ___ em outro continente. (morar, pretérito imperfeito)',
      promptFa: 'با فعل morar در گذشتهٔ استمراری کامل کنید (nós).',
      options: [],
      answer: 'morávamos',
      explanationFa: 'morar گذشتهٔ استمراری nós: morávamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q48',
      type: 'fill-blank',
      prompt: 'Minha irmã gosta de ___ no Brasil. (morar)',
      promptFa: 'شکل درست فعل morar را بگذارید (بعد از «gosta de»).',
      options: [],
      answer: 'morar',
      explanationFa: 'بعد از «gostar de» فعل به‌صورت مصدر می‌آید: morar.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q49',
      type: 'fill-blank',
      prompt: 'Minha avó ___ o Brasil como país de refúgio. (escolher, pretérito perfeito)',
      promptFa: 'با فعل escolher در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'escolheu',
      explanationFa: 'escolher (‑ER) گذشتهٔ کامل سوم‌شخص: escolheu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q50',
      type: 'fill-blank',
      prompt: 'Eu ___ aprender português. (escolher, pretérito perfeito)',
      promptFa: 'با فعل escolher در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'escolhi',
      explanationFa: 'escolher (‑ER) گذشتهٔ کامل اول‌شخص: escolhi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q51',
      type: 'fill-blank',
      prompt: 'Elas ___ os móveis da casa. (escolher, pretérito perfeito)',
      promptFa: 'با فعل escolher در گذشتهٔ کامل کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'escolheram',
      explanationFa: 'escolher گذشتهٔ کامل سوم‌شخص جمع: escolheram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q52',
      type: 'fill-blank',
      prompt: 'Meu primo ___ roupas quentes porque estava frio ontem. (vestir, pretérito perfeito)',
      promptFa: 'با فعل vestir در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'vestiu',
      explanationFa: 'vestir (‑IR) گذشتهٔ کامل سوم‌شخص: vestiu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q53',
      type: 'fill-blank',
      prompt: 'Eu ___ roupas leves porque semana passada estava quente. (vestir, pretérito perfeito)',
      promptFa: 'با فعل vestir در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'vesti',
      explanationFa: 'vestir (‑IR) گذشتهٔ کامل اول‌شخص: vesti.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q54',
      type: 'fill-blank',
      prompt: 'Nós não ___ calças ontem porque fez calor. (vestir, pretérito perfeito)',
      promptFa: 'با فعل vestir در گذشتهٔ کامل کامل کنید (nós).',
      options: [],
      answer: 'vestimos',
      explanationFa: 'vestir (‑IR) گذشتهٔ کامل nós: vestimos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q55',
      type: 'fill-blank',
      prompt: 'Eu ___ como motorista no ano passado. (trabalhar, pretérito perfeito)',
      promptFa: 'با فعل trabalhar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'trabalhei',
      explanationFa: 'trabalhar گذشتهٔ کامل اول‌شخص: trabalhei. «no ano passado» نشانهٔ گذشته.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q56',
      type: 'fill-blank',
      prompt: 'Os meus amigos ___ muito durante o verão passado. (trabalhar, pretérito perfeito)',
      promptFa: 'با فعل trabalhar در گذشتهٔ کامل کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'trabalharam',
      explanationFa: 'trabalhar گذشتهٔ کامل سوم‌شخص جمع: trabalharam.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q57',
      type: 'fill-blank',
      prompt: 'Meu pai ___ muitos anos na mesma empresa. (trabalhar, pretérito perfeito)',
      promptFa: 'با فعل trabalhar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'trabalhou',
      explanationFa: 'trabalhar گذشتهٔ کامل سوم‌شخص: trabalhou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q58',
      type: 'fill-blank',
      prompt: 'Eu ___ um texto sobre profissões na escola. (escrever, pretérito perfeito)',
      promptFa: 'با فعل escrever در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'escrevi',
      explanationFa: 'escrever (‑ER) گذشتهٔ کامل اول‌شخص: escrevi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q59',
      type: 'fill-blank',
      prompt: 'O carteiro ___ cartas para mim semana passada. (entregar, pretérito perfeito)',
      promptFa: 'با فعل entregar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'entregou',
      explanationFa: 'entregar (‑AR) گذشتهٔ کامل سوم‌شخص: entregou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q60',
      type: 'fill-blank',
      prompt: 'A professora ___ as lições no caderno ontem. (escrever, pretérito perfeito)',
      promptFa: 'با فعل escrever در گذشتهٔ کامل کامل کنید (سوم‌شخص).',
      options: [],
      answer: 'escreveu',
      explanationFa: 'escrever گذشتهٔ کامل سوم‌شخص: escreveu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q61',
      type: 'fill-blank',
      prompt: 'O motorista ___ cuidadosamente o ônibus no trajeto para casa ontem. (dirigir, pretérito perfeito)',
      promptFa: 'با فعل dirigir در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'dirigiu',
      explanationFa: 'dirigir (‑IR) گذشتهٔ کامل سوم‌شخص: dirigiu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q62',
      type: 'fill-blank',
      prompt: 'A taxista e o motorista ___ a dirigir quando eram jovens. (aprender, pretérito perfeito)',
      promptFa: 'با فعل aprender در گذشتهٔ کامل کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'aprenderam',
      explanationFa: 'aprender (‑ER) گذشتهٔ کامل سوم‌شخص جمع: aprenderam.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q63',
      type: 'fill-blank',
      prompt: 'Eu não ___ o carro depois da festa porque eu tinha bebido. (dirigir, pretérito perfeito)',
      promptFa: 'با فعل dirigir در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'dirigi',
      explanationFa: 'dirigir (‑IR) گذشتهٔ کامل اول‌شخص: dirigi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q64',
      type: 'fill-blank',
      prompt: 'Karen ___ leite com mel ontem à noite. (tomar, pretérito perfeito)',
      promptFa: 'با فعل tomar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'tomou',
      explanationFa: 'tomar (‑AR) گذشتهٔ کامل سوم‌شخص: tomou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q65',
      type: 'fill-blank',
      prompt: 'Eu ___ toda a água do filtro. (tomar, pretérito perfeito)',
      promptFa: 'با فعل tomar در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'tomei',
      explanationFa: 'tomar گذشتهٔ کامل اول‌شخص: tomei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q66',
      type: 'fill-blank',
      prompt: 'Por que você não ___ o suco? (tomar, pretérito perfeito)',
      promptFa: 'با فعل tomar در گذشتهٔ کامل کامل کنید (você).',
      options: [],
      answer: 'tomou',
      explanationFa: 'tomar گذشتهٔ کامل você: tomou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q67',
      type: 'fill-blank',
      prompt: 'Ele ___ apenas refrigerante. (tomar, pretérito perfeito)',
      promptFa: 'با فعل tomar در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'tomou',
      explanationFa: 'tomar گذشتهٔ کامل سوم‌شخص: tomou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q68',
      type: 'fill-blank',
      prompt: 'Eu não ___ quando cheguei porque estava com muito sono. (comer, pretérito perfeito)',
      promptFa: 'با فعل comer در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'comi',
      explanationFa: 'comer (‑ER) گذشتهٔ کامل اول‌شخص: comi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q69',
      type: 'fill-blank',
      prompt: 'Rogério ___ frango assado, arroz e batatas fritas. (comer, pretérito perfeito)',
      promptFa: 'با فعل comer در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'comeu',
      explanationFa: 'comer گذشتهٔ کامل سوم‌شخص: comeu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q70',
      type: 'fill-blank',
      prompt: 'Você já ___, agora já pode ir dormir. (comer, pretérito perfeito)',
      promptFa: 'با فعل comer در گذشتهٔ کامل کامل کنید (você).',
      options: [],
      answer: 'comeu',
      explanationFa: 'comer گذشتهٔ کامل você: comeu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q71',
      type: 'fill-blank',
      prompt: 'Ela ___ na casa dos vizinhos. (comer, pretérito perfeito)',
      promptFa: 'با فعل comer در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'comeu',
      explanationFa: 'comer گذشتهٔ کامل سوم‌شخص: comeu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q72',
      type: 'fill-blank',
      prompt:
        'Eu não me lembro se ___ pastel de carne ou de queijo na última vez em que estive aqui. (pedir, pretérito perfeito)',
      promptFa: 'با فعل pedir در گذشتهٔ کامل کامل کنید (اول‌شخص).',
      options: [],
      answer: 'pedi',
      explanationFa: 'pedir (‑IR) گذشتهٔ کامل اول‌شخص: pedi.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q73',
      type: 'fill-blank',
      prompt: 'Você ___ o café para mim? (pedir, pretérito perfeito)',
      promptFa: 'با فعل pedir در گذشتهٔ کامل کامل کنید (você).',
      options: [],
      answer: 'pediu',
      explanationFa: 'pedir گذشتهٔ کامل você: pediu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q74',
      type: 'fill-blank',
      prompt: 'Ana e Estevam ___ um bolo na padaria. (pedir, pretérito perfeito)',
      promptFa: 'با فعل pedir در گذشتهٔ کامل کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'pediram',
      explanationFa: 'pedir گذشتهٔ کامل سوم‌شخص جمع: pediram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q75',
      type: 'fill-blank',
      prompt: 'Ele ___ brigadeiro de sobremesa de novo. (pedir, pretérito perfeito)',
      promptFa: 'با فعل pedir در گذشتهٔ کامل کامل کنید.',
      options: [],
      answer: 'pediu',
      explanationFa: 'pedir گذشتهٔ کامل سوم‌شخص: pediu. (brigadeiro یک شیرینی برزیلی است.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q76',
      type: 'fill-blank',
      prompt: 'Amanhã eu ___ à praia com os meus amigos e depois nós ___ ao cinema juntos! (ir, futuro)',
      promptFa: 'با فعل ir در آینده کامل کنید (اول‌شخص مفرد سپس nós).',
      options: [],
      answer: 'vou / vamos',
      explanationFa: 'آیندهٔ نزدیک با ir: eu vou، nós vamos. (شکل ساده: irei / iremos.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q77',
      type: 'fill-blank',
      prompt:
        'Domingo nós ___ (fazer) um grande almoço em família e, depois, nós ___ (ir) ao parque com eles. (futuro)',
      promptFa: 'با فعل‌های fazer و ir در آینده کامل کنید (nós).',
      options: [],
      answer: 'vamos fazer / vamos',
      explanationFa: 'آیندهٔ نزدیک nós: vamos fazer، vamos (ao parque). شکل ساده: faremos / iremos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q78',
      type: 'fill-blank',
      prompt: 'Hoje eu ___ (comprar) algumas frutas no mercado para fazer uma salada de frutas. (futuro)',
      promptFa: 'با فعل comprar در آینده کامل کنید (اول‌شخص).',
      options: [],
      answer: 'vou comprar',
      explanationFa: 'آیندهٔ نزدیک: vou comprar (شکل ساده: comprarei).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q79',
      type: 'fill-blank',
      prompt: 'Tenho certeza que amanhã ___ (ser) um grande dia para você! (futuro)',
      promptFa: 'با فعل ser در آینده کامل کنید (سوم‌شخص).',
      options: [],
      answer: 'será',
      explanationFa: 'ser آیندهٔ سوم‌شخص: será (شکل نزدیک: vai ser).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q80',
      type: 'fill-blank',
      prompt: 'Hoje, mais tarde, nós ___ (estar) todos juntos para a festa de casamento. (futuro)',
      promptFa: 'با فعل estar در آینده کامل کنید (nós).',
      options: [],
      answer: 'estaremos',
      explanationFa: 'estar آیندهٔ nós: estaremos (شکل نزدیک: vamos estar).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q81',
      type: 'fill-blank',
      prompt: 'Terça-feira ___ (falar) com o meu professor de português sobre as minhas dúvidas. (futuro, eu)',
      promptFa: 'با فعل falar در آینده کامل کنید (اول‌شخص).',
      options: [],
      answer: 'vou falar',
      explanationFa: 'آیندهٔ نزدیک اول‌شخص: vou falar (شکل ساده: falarei).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q82',
      type: 'fill-blank',
      prompt: 'Hoje eles ___ (comer) um lanche no intervalo da aula. (futuro)',
      promptFa: 'با فعل comer در آینده کامل کنید (سوم‌شخص جمع).',
      options: [],
      answer: 'vão comer',
      explanationFa: 'آیندهٔ نزدیک سوم‌شخص جمع: vão comer (شکل ساده: comerão).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q83',
      type: 'fill-blank',
      prompt:
        'Segunda-feira vocês ___ (arrumar) a casa toda porque nós ___ (receber) os nossos visitantes do Brasil! (futuro)',
      promptFa: 'با فعل‌های arrumar و receber در آینده کامل کنید (vocês، سپس nós).',
      options: [],
      answer: 'vão arrumar / vamos receber',
      explanationFa:
        'آیندهٔ نزدیک: vocês vão arrumar، nós vamos receber. (شکل ساده: arrumarão / receberemos.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q84',
      type: 'fill-blank',
      prompt: 'Hoje nós ___ (beber) muito na festa do Diogo e, depois, nós ___ (ir) para casa dormir. (futuro)',
      promptFa: 'با فعل‌های beber و ir در آینده کامل کنید (nós).',
      options: [],
      answer: 'vamos beber / vamos',
      explanationFa: 'آیندهٔ نزدیک nós: vamos beber، vamos (para casa). (شکل ساده: beberemos / iremos.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q85',
      type: 'fill-blank',
      prompt: 'Quarta-feira ela ___ (comprar) um computador novo. (futuro)',
      promptFa: 'با فعل comprar در آینده کامل کنید (سوم‌شخص).',
      options: [],
      answer: 'vai comprar',
      explanationFa: 'آیندهٔ نزدیک سوم‌شخص: vai comprar (شکل ساده: comprará).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q86',
      type: 'mcq',
      prompt: 'Qual é a forma correta no pretérito perfeito? "Eu ___ o carro." (dirigir)',
      promptFa: 'شکل درست گذشتهٔ کامل فعل dirigir برای «eu» کدام است؟',
      options: ['dirigi', 'dirigiu', 'dirijo', 'dirigia'],
      answer: 'dirigi',
      explanationFa: 'dirigir (‑IR) گذشتهٔ کامل اول‌شخص: dirigi. dirijo زمان حال و dirigia گذشتهٔ استمراری است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-9-q87',
      type: 'mcq',
      prompt: 'Onde se tira o CPF?',
      promptFa: 'CPF را کجا می‌گیرند؟',
      options: [
        'Na Receita Federal',
        'Na Polícia Federal',
        'Na Superintendência do Trabalho',
        'No CRAI',
      ],
      answer: 'Na Receita Federal',
      explanationFa: 'CPF (شمارهٔ مالیاتی) در Receita Federal گرفته می‌شود؛ RNE در Polícia Federal.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-9-q88',
      type: 'translate-fa-pt',
      prompt: '«دیروز من دو ساعت اضافه‌کاری کردم.» را به پرتغالی بنویسید.',
      promptFa: 'این جمله را با گذشتهٔ کامل به پرتغالی برزیلی ترجمه کنید.',
      options: [],
      answer: 'Ontem eu fiz duas horas extras.',
      explanationFa: 'fazer در گذشتهٔ کامل بی‌قاعده است: fiz. «hora extra» = اضافه‌کاری.',
      cefr: 'A2',
      skill: 'writing',
    },
    {
      id: 'course-aula-9-q89',
      type: 'translate-fa-pt',
      prompt: '«فردا من به ساحل می‌روم و بعد به سینما می‌رویم.» را به پرتغالی بنویسید.',
      promptFa: 'این جمله را با آیندهٔ نزدیک (ir) به پرتغالی برزیلی ترجمه کنید.',
      options: [],
      answer: 'Amanhã eu vou à praia e depois nós vamos ao cinema.',
      explanationFa: 'آیندهٔ نزدیک با ir: vou / vamos. à = a + a (praia مؤنث)، ao = a + o (cinema مذکر).',
      cefr: 'A2',
      skill: 'writing',
    },
  ],
  estimatedMinutes: 30,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 9 (کامل).',
};
