import type { CourseLesson } from '@/domain/content/schema';

export const aula8: CourseLesson = {
  id: 'course-aula-8',
  order: 8,
  aula: 'Aula 8',
  titleFa: 'فعل‌ها ۲ — وجه اخباری (فعل‌های بی‌قاعده)',
  titlePt: 'Verbos 2 — Indicativo (Irregulares)',
  cefr: 'A2',
  summaryFa:
    'در این درس با فعل‌های بی‌قاعدهٔ پرکاربرد پرتغالی برزیلی آشنا می‌شوید؛ یعنی فعل‌هایی که هنگام صرف، ریشه یا پایانهٔ عادی خود را تغییر می‌دهند. صرف کامل مهم‌ترین فعل‌های بی‌قاعده (SER، ESTAR، DAR، FAZER، IR) را در چهار زمانِ اصلی وجه اخباری یاد می‌گیرید: زمان حال (Presente)، گذشتهٔ کامل (Pretérito Perfeito)، گذشتهٔ ناتمام/استمراری (Pretérito Imperfeito) و آینده (Futuro). تفاوت SER و ESTAR را دوره می‌کنید، نکتهٔ جالبِ یکی‌بودن گذشتهٔ SER و IR را می‌بینید، جدول اول‌شخصِ گذشتهٔ چند فعل دیگر (ter، ver، ler، dizer، poder، vir و…) را مرور می‌کنید و در پایان با ده‌ها تمرینِ حال، گذشته و آینده همه‌چیز را تثبیت می‌کنید.',
  objectivesFa: [
    'تعریف فعل بی‌قاعده را بدانید و بفهمید چرا ریشه و پایانهٔ آن تغییر می‌کند.',
    'صرف کامل SER و ESTAR را در چهار زمان اخباری به‌کار ببرید و تفاوت آن‌ها را تشخیص دهید.',
    'صرف کامل DAR، FAZER و IR را در چهار زمان اخباری بشناسید.',
    'بدانید که گذشتهٔ کامل فعل SER و فعل IR کاملاً یکسان است (fui، foi، fomos، foram).',
    'شکل گذشتهٔ اول‌شخص چند فعل بی‌قاعدهٔ دیگر (ter، ver، ler، dizer، poder، vir، vestir، sair و…) را یاد بگیرید.',
    'جمله‌های زمان حال، گذشته و آینده را با فعل‌های بی‌قاعده بسازید.',
  ],
  sections: [
    {
      headingFa: '۱. فعل بی‌قاعده (Verbos Irregulares) چیست؟',
      bodyFa:
        'فعل‌های بی‌قاعده فعل‌هایی هستند که هنگام صرف در ریشهٔ خود تغییر می‌کنند و پایانه‌های معمولِ گروه خود را نمی‌پذیرند. به بیان ساده، در این فعل‌ها هر دو بخش — ریشه (radical) و پایانه (desinência) — می‌توانند تغییر کنند. برای همین باید صرف آن‌ها را جداگانه حفظ کرد و نمی‌توان مثل فعل‌های باقاعده الگوی ثابت را روی‌شان پیاده کرد.\n\nمثال (زمان حال) برای دو فعل IR (رفتن) و PODER (توانستن):\n\nضمیر            | IR    | PODER\nEU              | VOU   | POSSO\nELE/ELA/VOCÊ    | VAI   | PODE\nA GENTE         | VAI   | PODE\nNÓS             | VAMOS | PODEMOS\nELES/ELAS/VOCÊS | VÃO   | PODEM\n\nمی‌بینید که «ir» در اول‌شخص می‌شود «vou» (ریشه کاملاً عوض شده) و «poder» می‌شود «posso». این‌ها بی‌قاعده‌اند.',
      examples: [
        {
          pt: 'Eu vou ao mercado.',
          fa: 'من به بازار می‌روم.',
          pron: 'اِئو وُ آئو مِرکادو',
          note: 'اول‌شخصِ ir بی‌قاعده است: «vou».',
        },
        {
          pt: 'Eu posso ajudar você.',
          fa: 'من می‌توانم به تو کمک کنم.',
          pron: 'اِئو پُسو آژودار وُسه',
          note: 'اول‌شخصِ poder بی‌قاعده است: «posso».',
        },
        {
          pt: 'Nós vamos e eles vão.',
          fa: 'ما می‌رویم و آن‌ها می‌روند.',
          pron: 'نُس واموس ای اِلیس وائو',
        },
      ],
    },
    {
      headingFa: '۲. فعل SER (بودن ـ ثابت/هویت) — جدول کامل',
      bodyFa:
        'فعل SER برای ویژگی‌های ثابت و همیشگی به‌کار می‌رود (هویت، ملیت، شغل، صفت ذاتی). صرف کامل آن در چهار زمان وجه اخباری:\n\nضمیر            | حال (Presente) | گذشتهٔ کامل (Perfeito) | گذشتهٔ ناتمام (Imperfeito) | آینده (Futuro)\nEU              | SOU            | FUI                    | ERA                        | SEREI\nELE/ELA/VOCÊ    | É              | FOI                    | ERA                        | SERÁ\nA GENTE         | É              | FOI                    | ERA                        | SERÁ\nNÓS             | SOMOS          | FOMOS                  | ÉRAMOS                     | SEREMOS\nELES/ELAS/VOCÊS | SÃO            | FORAM                  | ERAM                       | SERÃO\n\nنکته: گذشتهٔ ناتمام (era، éramos، eram) برای توصیف وضعیت یا عادتِ گذشته است («قبلاً … بود»).',
      examples: [
        {
          pt: 'Eu sou estudante.',
          fa: 'من دانشجو هستم.',
          pron: 'اِئو سُ اِستودانتی',
          note: 'حال ـ نقش/هویت ثابت.',
        },
        {
          pt: 'Ele foi presidente do Brasil.',
          fa: 'او رئیس‌جمهور برزیل بود.',
          pron: 'اِلی فُی پرِزیدِنتی دو برازیل',
          note: 'گذشتهٔ کامل ـ اتفاقی که تمام شده است.',
        },
        {
          pt: 'Quando eu era criança, eu era muito tímido.',
          fa: 'وقتی بچه بودم، خیلی خجالتی بودم.',
          pron: 'کواندو اِئو اِرا کریانسا',
          note: 'گذشتهٔ ناتمام ـ وضعیتِ ادامه‌دار در گذشته.',
        },
        {
          pt: 'No futuro eu serei médica.',
          fa: 'در آینده من پزشک خواهم شد.',
          pron: 'نو فوتورو اِئو سِرِی مِجیکا',
          note: 'آینده.',
        },
      ],
    },
    {
      headingFa: '۳. فعل ESTAR (بودن ـ موقتی/حالت/مکان) — جدول کامل',
      bodyFa:
        'فعل ESTAR برای حالت‌های موقتی، احساس لحظه‌ای، مکان و کارِ در جریان است. صرف کامل آن در چهار زمان اخباری:\n\nضمیر            | حال (Presente) | گذشتهٔ کامل (Perfeito) | گذشتهٔ ناتمام (Imperfeito) | آینده (Futuro)\nEU              | ESTOU          | ESTIVE                 | ESTAVA                     | ESTAREI\nELE/ELA/VOCÊ    | ESTÁ           | ESTEVE                 | ESTAVA                     | ESTARÁ\nA GENTE         | ESTÁ           | ESTEVE                 | ESTAVA                     | ESTARÁ\nNÓS             | ESTAMOS        | ESTIVEMOS              | ESTÁVAMOS                  | ESTAREMOS\nELES/ELAS/VOCÊS | ESTÃO          | ESTIVERAM              | ESTAVAM                    | ESTARÃO\n\nاشتباه رایج فارسی‌زبانان: چون در فارسی فقط یک فعل «بودن» داریم، SER و ESTAR را قاطی می‌کنند. اگر ویژگی همیشگی است SER، اگر حالِ لحظه‌ای/مکان/موقتی است ESTAR.',
      examples: [
        {
          pt: 'Eu estou cansado hoje.',
          fa: 'من امروز خسته‌ام.',
          pron: 'اِئو اِستُ کانسادو اُژی',
          note: 'حالت موقتی → ESTAR.',
        },
        {
          pt: 'Ontem eu estive em casa o dia todo.',
          fa: 'دیروز تمام روز خانه بودم.',
          pron: 'اُنتِین اِئو اِستیوی اِین کازا',
          note: 'گذشتهٔ کامل ـ estive.',
        },
        {
          pt: 'Quando você ligou, eu estava dormindo.',
          fa: 'وقتی تو زنگ زدی، من خواب بودم.',
          pron: 'کواندو وُسه لیگُو، اِئو اِستاوا دورمیندو',
          note: 'گذشتهٔ ناتمام ـ کاری که در حال انجام بود.',
        },
        {
          pt: 'Amanhã nós estaremos no aeroporto às 8h.',
          fa: 'فردا ما ساعت ۸ در فرودگاه خواهیم بود.',
          pron: 'آمانیا نُس اِستارِموس نو آئروپورتو',
          note: 'آینده.',
        },
      ],
    },
    {
      headingFa: '۴. SER یا ESTAR در زمان حال؟ (تمرین کلاسی)',
      bodyFa:
        'در این تمرینِ درس باید بین SER (ثابت/ویژگی) و ESTAR (موقتی/حالت/کارِ در جریان) انتخاب کنید. کلیدهای مهم: اگر بعد از جای خالی فعلِ «-ndo» (gerúndio) آمده باشد حتماً ESTAR است؛ اگر صفتِ همیشگی مثل «trabalhador» (زحمتکش) باشد SER؛ و کلمهٔ «agora» (الان) نشانهٔ ESTAR است. جمله‌های تمرین:\n\n۱) EU ___ cansado de trabalhar. (خسته از کار)\n۲) VOCÊ ___ vendendo seu celular? (در حال فروختن)\n۳) ELE ___ muito trabalhador. (خیلی زحمتکش)\n۴) ELA ___ fazendo um bolo de uva. (در حال درست‌کردن کیک)\n۵) NÓS ___ fazendo um curso de português. (در حال گذراندن دوره)\n۶) VOCÊS ___ muito estudiosos. (agora)\n۷) ELES ___ contentes com a casa nova. (راضی از خانهٔ نو)\n۸) ELAS ___ bem-sucedidas. (agora)',
      examples: [
        {
          pt: 'Eu estou cansado de trabalhar.',
          fa: 'من از کار خسته‌ام.',
          pron: 'اِئو اِستُ کانسادو جی ترابایار',
          note: 'خستگی موقتی → ESTAR.',
        },
        {
          pt: 'Ele é muito trabalhador.',
          fa: 'او خیلی زحمتکش است.',
          pron: 'اِلی اِ مویتو ترابایادور',
          note: 'صفت ذاتی/همیشگی → SER.',
        },
        {
          pt: 'Ela está fazendo um bolo de uva.',
          fa: 'او در حال درست‌کردن کیک انگور است.',
          pron: 'اِلا اِستا فازِندو اون بولو جی اووا',
          note: 'کارِ در جریان (estar + gerúndio) → ESTAR.',
        },
      ],
    },
    {
      headingFa: '۵. فعل DAR (دادن) — جدول کامل',
      bodyFa:
        'DAR یعنی «دادن» و از فعل‌های بی‌قاعدهٔ پرکاربرد است. صرف کامل آن در چهار زمان اخباری:\n\nضمیر            | حال (Presente) | گذشتهٔ کامل (Perfeito) | گذشتهٔ ناتمام (Imperfeito) | آینده (Futuro)\nEU              | DOU            | DEI                    | DAVA                       | DAREI\nELE/ELA/VOCÊ    | DÁ             | DEU                    | DAVA                       | DARÁ\nA GENTE         | DÁ             | DEU                    | DAVA                       | DARÁ\nNÓS             | DAMOS          | DEMOS                  | DÁVAMOS                    | DAREMOS\nELES/ELAS/VOCÊS | DÃO            | DERAM                  | DAVAM                      | DARÃO\n\nنکته: «dar» در اصطلاح‌های زیادی به‌کار می‌رود: «dar um abraço» (بغل کردن)، «dar uma festa» (مهمانی گرفتن)، «dar um show» (اجرای درخشان).',
      examples: [
        {
          pt: 'Eu dou um presente para ela.',
          fa: 'من به او یک هدیه می‌دهم.',
          pron: 'اِئو دُ اون پرِزِنتی پارا اِلا',
          note: 'حال ـ اول‌شخص «dou».',
        },
        {
          pt: 'A gente deu um abraço.',
          fa: 'ما همدیگر را بغل کردیم.',
          pron: 'آ جِنتی دِئو اون آبراسو',
          note: 'گذشتهٔ کامل ـ «a gente» سوم‌شخص مفرد «deu».',
        },
        {
          pt: 'Eles deram um show.',
          fa: 'آن‌ها یک اجرای فوق‌العاده داشتند.',
          pron: 'اِلیس دِرام اون شُو',
          note: 'گذشتهٔ کامل جمع «deram».',
        },
      ],
    },
    {
      headingFa: '۶. فعل FAZER (انجام دادن/ساختن) — جدول کامل',
      bodyFa:
        'FAZER یعنی «کردن، انجام دادن، ساختن». صرف کامل آن در چهار زمان اخباری:\n\nضمیر            | حال (Presente) | گذشتهٔ کامل (Perfeito) | گذشتهٔ ناتمام (Imperfeito) | آینده (Futuro)\nEU              | FAÇO           | FIZ                    | FAZIA                      | FAREI\nELE/ELA/VOCÊ    | FAZ            | FEZ                    | FAZIA                      | FARÁ\nA GENTE         | FAZ            | FEZ                    | FAZIA                      | FARÁ\nNÓS             | FAZEMOS        | FIZEMOS                | FAZÍAMOS                   | FAREMOS\nELES/ELAS/VOCÊS | FAZEM          | FIZERAM                | FAZIAM                     | FARÃO\n\nنکته: «fazer» برای سن و تولد هم به‌کار می‌رود: «fazer aniversário» (تولد گرفتن/تولدش بودن)، «Ele fez 18 anos» (او ۱۸ ساله شد). برای آب‌وهوا هم: «fez frio» (هوا سرد بود).',
      examples: [
        {
          pt: 'Eu faço o jantar todos os dias.',
          fa: 'من هر روز شام درست می‌کنم.',
          pron: 'اِئو فاسو او ژانتار',
          note: 'حال ـ اول‌شخص «faço».',
        },
        {
          pt: 'Ele fez 18 anos.',
          fa: 'او ۱۸ ساله شد.',
          pron: 'اِلی فِس دِزوئیتو آنوس',
          note: 'گذشتهٔ کامل سوم‌شخص «fez».',
        },
        {
          pt: 'Amanhã eu farei minha lição de casa.',
          fa: 'فردا تکلیفم را انجام خواهم داد.',
          pron: 'آمانیا اِئو فارِی مینیا لیسائو جی کازا',
          note: 'آینده «farei».',
        },
      ],
    },
    {
      headingFa: '۷. فعل IR (رفتن) — جدول کامل',
      bodyFa:
        'IR یعنی «رفتن» و یکی از بی‌قاعده‌ترین فعل‌هاست. صرف کامل آن در چهار زمان اخباری:\n\nضمیر            | حال (Presente) | گذشتهٔ کامل (Perfeito) | گذشتهٔ ناتمام (Imperfeito) | آینده (Futuro)\nEU              | VOU            | FUI                    | IA                         | IREI\nELE/ELA/VOCÊ    | VAI            | FOI                    | IA                         | IRÁ\nA GENTE         | VAI            | FOI                    | IA                         | IRÁ\nNÓS             | VAMOS          | FOMOS                  | ÍAMOS                      | IREMOS\nELES/ELAS/VOCÊS | VÃO            | FORAM                  | IAM                        | IRÃO\n\nنکته مهم: در برزیل به‌جای آیندهٔ ساده (irei) خیلی بیشتر از ساختار «vou + مصدر» استفاده می‌شود: «Vou viajar amanhã» (فردا سفر خواهم کرد).',
      examples: [
        {
          pt: 'Todos os domingos nós vamos à igreja.',
          fa: 'هر یکشنبه ما به کلیسا می‌رویم.',
          pron: 'تودوس اوس دومینگوس نُس واموس آ ایگرِژا',
          note: 'حال ـ عادت.',
        },
        {
          pt: 'Você já foi ao Maracanã?',
          fa: 'تا حالا به ماراکانا رفته‌ای؟',
          pron: 'وُسه ژا فُی آئو ماراکانا',
          note: 'گذشتهٔ کامل «foi».',
        },
        {
          pt: 'Quando éramos crianças, a gente ia à casa deles.',
          fa: 'وقتی بچه بودیم، به خانهٔ آن‌ها می‌رفتیم.',
          pron: 'کواندو اِراموس کریانساس، آ جِنتی ایا',
          note: 'گذشتهٔ ناتمام «ia» ـ عادتِ گذشته.',
        },
      ],
    },
    {
      headingFa: '۸. نمونه جمله‌ها با DAR، FAZER و IR (گذشتهٔ کامل)',
      bodyFa:
        'این نمونه‌ها نشان می‌دهند چطور گذشتهٔ کاملِ سه فعل با ضمیرهای مختلف صرف می‌شود. دقت کنید که «a gente» همیشه مثل سوم‌شخص مفرد (deu، fez، foi) صرف می‌شود.',
      examples: [
        {
          pt: 'Eu dei a nota.',
          fa: 'من نمره را دادم.',
          pron: 'اِئو دِی آ نُتا',
        },
        {
          pt: 'Você deu um presente.',
          fa: 'تو یک هدیه دادی.',
          pron: 'وُسه دِئو اون پرِزِنتی',
        },
        {
          pt: 'Ela deu uma ajuda.',
          fa: 'او کمکی کرد.',
          pron: 'اِلا دِئو اوما آژودا',
        },
        {
          pt: 'Nós demos o nosso melhor.',
          fa: 'ما بهترین تلاش‌مان را کردیم.',
          pron: 'نُس دِموس او نُسو مِلیور',
        },
        {
          pt: 'A gente deu um abraço.',
          fa: 'ما همدیگر را بغل کردیم.',
          pron: 'آ جِنتی دِئو اون آبراسو',
          note: '«a gente» = سوم‌شخص مفرد → deu.',
        },
        {
          pt: 'Eles deram um show.',
          fa: 'آن‌ها اجرای درخشانی داشتند.',
          pron: 'اِلیس دِرام اون شُو',
        },
        {
          pt: 'Eu fiz o jantar.',
          fa: 'من شام را درست کردم.',
          pron: 'اِئو فیس او ژانتار',
        },
        {
          pt: 'Você fez uma boa prova.',
          fa: 'تو امتحان خوبی دادی.',
          pron: 'وُسه فِس اوما بُووا پرُوا',
        },
        {
          pt: 'Ele fez 18 anos.',
          fa: 'او ۱۸ ساله شد.',
          pron: 'اِلی فِس دِزوئیتو آنوس',
        },
        {
          pt: 'Nós fizemos um bolo.',
          fa: 'ما یک کیک درست کردیم.',
          pron: 'نُس فیزِموس اون بولو',
        },
        {
          pt: 'A gente fez a lição.',
          fa: 'ما تکلیف را انجام دادیم.',
          pron: 'آ جِنتی فِس آ لیسائو',
        },
        {
          pt: 'Eles fizeram o trabalho.',
          fa: 'آن‌ها کار را انجام دادند.',
          pron: 'اِلیس فیزِرام او ترابالیو',
        },
        {
          pt: 'Eu fui ao parque.',
          fa: 'من به پارک رفتم.',
          pron: 'اِئو فُی آئو پارکی',
        },
        {
          pt: 'Você foi ao shopping.',
          fa: 'تو به مرکز خرید رفتی.',
          pron: 'وُسه فُی آئو شُپینگ',
        },
        {
          pt: 'Ela foi passear.',
          fa: 'او به گردش رفت.',
          pron: 'اِلا فُی پاسِیار',
        },
        {
          pt: 'Nós fomos ao cinema.',
          fa: 'ما به سینما رفتیم.',
          pron: 'نُس فُموس آئو سینِما',
        },
        {
          pt: 'A gente foi trabalhar.',
          fa: 'ما سرِ کار رفتیم.',
          pron: 'آ جِنتی فُی ترابایار',
        },
        {
          pt: 'Elas foram brincar.',
          fa: 'آن‌ها (زنان) رفتند بازی کنند.',
          pron: 'اِلاس فُرام برینکار',
        },
      ],
    },
    {
      headingFa: '۹. نکتهٔ جالب: گذشتهٔ SER و IR یکی است!',
      bodyFa:
        'یک ویژگی جالب و مهم: فعل SER (بودن) و فعل IR (رفتن) در گذشتهٔ کامل کاملاً یک‌شکل صرف می‌شوند. یعنی «fui»، «foi»، «fomos» و «foram» هم می‌تواند «بودم/رفتم» معنی بدهد و فقط از روی جمله می‌فهمیم کدام است.\n\nSER — گذشتهٔ کامل: EU FUI | ELE/ELA/VOCÊ FOI | A GENTE FOI | NÓS FOMOS | ELES/ELAS/VOCÊS FORAM\nIR  — گذشتهٔ کامل: EU FUI | ELE/ELA/VOCÊ FOI | A GENTE FOI | NÓS FOMOS | ELES/ELAS/VOCÊS FORAM\n\nراهنما: اگر بعد از فعل حرف اضافهٔ مکان (ao، à، para) بیاید معمولاً IR است («fui ao Rio» = به ریو رفتم)؛ اگر صفت یا شغل بیاید معمولاً SER است («fui professora» = معلم بودم).',
      examples: [
        {
          pt: 'O livro foi interessante.',
          fa: 'کتاب جالب بود.',
          pron: 'او لیورو فُی اینترِسانتی',
          note: 'اینجا «foi» = بود (SER).',
        },
        {
          pt: 'A explicação do professor foi muito boa.',
          fa: 'توضیح معلم خیلی خوب بود.',
          pron: 'آ اِکسپلیکاسائو دو پروفِسور فُی مویتو بُووا',
          note: 'SER.',
        },
        {
          pt: 'Eu nunca fui assaltado.',
          fa: 'من هرگز موردِ سرقت قرار نگرفتم.',
          pron: 'اِئو نونکا فُی آسالتادو',
          note: 'SER (مجهول).',
        },
        {
          pt: 'Nós fomos bons amigos na escola.',
          fa: 'ما در مدرسه دوستان خوبی بودیم.',
          pron: 'نُس فُموس بُنس آمیگوس نا اِسکولا',
          note: 'SER.',
        },
        {
          pt: 'Eles foram para a Europa no ano passado.',
          fa: 'آن‌ها سال گذشته به اروپا رفتند.',
          pron: 'اِلیس فُرام پارا آ اِئوروپا',
          note: 'IR (حرکت به مکان).',
        },
        {
          pt: 'Ele foi para a Bahia de férias.',
          fa: 'او برای تعطیلات به باهیا رفت.',
          pron: 'اِلی فُی پارا آ باییا جی فِریاس',
          note: 'IR.',
        },
        {
          pt: 'Elas já foram a São Paulo três vezes.',
          fa: 'آن‌ها (زنان) تا حالا سه بار به سائوپائولو رفته‌اند.',
          pron: 'اِلاس ژا فُرام آ سائو پائولو ترِس وِزِس',
          note: 'IR.',
        },
        {
          pt: 'Eu fui para a Argentina no ano passado.',
          fa: 'من سال گذشته به آرژانتین رفتم.',
          pron: 'اِئو فُی پارا آ آرژِنتینا',
          note: 'IR.',
        },
      ],
    },
    {
      headingFa: '۱۰. گذشتهٔ اول‌شخص چند فعل بی‌قاعدهٔ دیگر',
      bodyFa:
        'این جدول شکلِ اول‌شخص مفرد (EU) چند فعل دیگر را در گذشتهٔ کامل (Perfeito) و گذشتهٔ ناتمام (Imperfeito) نشان می‌دهد. این‌ها را حفظ کنید چون خیلی پرکاربردند:\n\nمصدر     | معنی        | گذشتهٔ کامل (EU) | گذشتهٔ ناتمام (EU)\nSortear   | قرعه‌کشی کردن | Sorteei          | Sorteava\nEnxaguar  | آب کشیدن     | Enxaguei         | Enxaguava\nOdiar     | متنفر بودن   | Odiei            | Odiava\nTer       | داشتن        | Tive             | Tinha\nVer       | دیدن         | Vi               | Via\nLer       | خواندن       | Li               | Lia\nDizer     | گفتن         | Disse            | Dizia\nPoder     | توانستن      | Pude             | Podia\nVir       | آمدن         | Vim              | Vinha\nVestir    | پوشیدن       | Vesti            | Vestia\nSair      | بیرون رفتن   | Saí              | Saía\n\nتوجه: «tive/tinha» (ter) و «pude/podia» (poder) و «vim/vinha» (vir) کاملاً بی‌قاعده‌اند و باید حفظ شوند.',
      examples: [
        {
          pt: 'Ontem eu tive uma boa ideia.',
          fa: 'دیروز فکر خوبی داشتم.',
          pron: 'اُنتِین اِئو تیوی اوما بُووا ایدِیا',
          note: 'ter → tive (گذشتهٔ کامل).',
        },
        {
          pt: 'Eu vi um filme ótimo.',
          fa: 'من یک فیلم عالی دیدم.',
          pron: 'اِئو وی اون فیلمی اُتیمو',
          note: 'ver → vi.',
        },
        {
          pt: 'Eu não pude ir à festa.',
          fa: 'من نتوانستم به مهمانی بروم.',
          pron: 'اِئو نائو پودی ایر آ فِستا',
          note: 'poder → pude.',
        },
        {
          pt: 'Eu vim de ônibus.',
          fa: 'من با اتوبوس آمدم.',
          pron: 'اِئو وین جی اُنیبوس',
          note: 'vir → vim.',
        },
      ],
    },
    {
      headingFa: '۱۱. جمع‌بندی: تمرین‌های حال، گذشته و آینده',
      bodyFa:
        'در بخش پایانی درس سه دسته تمرین می‌آید تا صرف فعل‌های بی‌قاعده را در هر سه زمان تثبیت کنید:\n\n۱) Frases no Presente — جمله‌هایی در زمان حال (مثلاً «Eu gosto de frutas»).\n۲) Frases no Passado — جمله‌هایی در زمان گذشته (مثلاً «Ontem fez muito frio»).\n۳) Frases no Futuro — جمله‌هایی در زمان آینده (مثلاً «Amanhã eu farei minha lição»).\n\nنکته: بعضی جای خالی‌ها بیش از یک پاسخِ درست دارند؛ در بخش کوئیز برای هرکدام پاسخِ طبیعی و رایج انتخاب شده و در توضیح، گزینه‌های دیگر هم اشاره شده است. هنگام تمرین به قرینه‌های زمان توجه کنید: «hoje/agora» → حال، «ontem/no ano passado» → گذشته، «amanhã/ano que vem/mês que vem» → آینده.',
      examples: [
        {
          pt: 'Hoje / Ontem / Amanhã',
          fa: 'امروز / دیروز / فردا',
          pron: 'اُژی / اُنتِین / آمانیا',
          note: 'قیدهای زمانی که زمانِ فعل را مشخص می‌کنند.',
        },
        {
          pt: 'No ano passado / No ano que vem',
          fa: 'سال گذشته / سالِ آینده',
          pron: 'نو آنو پاسادو / نو آنو کی وِین',
        },
      ],
    },
  ],
  keyPointsFa: [
    'فعل بی‌قاعده در ریشه و/یا پایانه تغییر می‌کند و باید حفظ شود (مثل vou، posso، faço).',
    'SER = ویژگیِ ثابت/هویت؛ ESTAR = حالتِ موقتی/مکان/کارِ در جریان. «-ndo» و «agora» نشانهٔ ESTAR است.',
    'گذشتهٔ کامل SER و IR کاملاً یکسان است: fui، foi، fomos، foram.',
    'اگر بعد از foi/fui حرف اضافهٔ مکان (ao/à/para) بیاید معمولاً IR است؛ اگر صفت/شغل بیاید معمولاً SER.',
    '«a gente» با فعل سوم‌شخص مفرد صرف می‌شود (a gente foi، a gente deu، a gente faz).',
    'در برزیل آینده را بیشتر با «vou + مصدر» می‌سازند تا با شکل ساده (irei).',
    'گذشتهٔ ناتمام (era، ia، fazia، dava…) برای عادت یا وضعیتِ ادامه‌دار در گذشته است.',
  ],
  quiz: [
    {
      id: 'course-aula-8-q1',
      type: 'mcq',
      prompt: 'EU ___ cansado de trabalhar.',
      promptFa: 'خستگی حالتی موقتی است؛ کدام فعل درست است؟',
      options: ['estou', 'sou', 'é', 'estava'],
      answer: 'estou',
      explanationFa:
        'خستگی حالِ موقتی است → ESTAR اول‌شخص مفرد: «Eu estou cansado».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q2',
      type: 'mcq',
      prompt: 'VOCÊ ___ vendendo seu celular?',
      promptFa: 'کارِ در جریان (vendendo)؛ کدام فعل؟',
      options: ['está', 'é', 'sou', 'estão'],
      answer: 'está',
      explanationFa:
        'وجود «-ndo» یعنی کارِ در جریان → ESTAR: «Você está vendendo».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q3',
      type: 'mcq',
      prompt: 'ELE ___ muito trabalhador.',
      promptFa: '«زحمتکش» صفتی ذاتی است؛ کدام فعل؟',
      options: ['é', 'está', 'estou', 'são'],
      answer: 'é',
      explanationFa: 'صفت ذاتی/همیشگی → SER: «Ele é muito trabalhador».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q4',
      type: 'mcq',
      prompt: 'ELA ___ fazendo um bolo de uva.',
      promptFa: 'کارِ در جریان (fazendo)؛ کدام فعل؟',
      options: ['está', 'é', 'estava', 'são'],
      answer: 'está',
      explanationFa: 'کارِ در جریان → ESTAR: «Ela está fazendo um bolo».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q5',
      type: 'fill-blank',
      prompt: 'NÓS ___ fazendo um curso de português.',
      promptFa: 'با فعل درست کامل کنید (اول‌شخص جمع، کارِ در جریان).',
      options: [],
      answer: 'estamos',
      explanationFa:
        'کارِ در جریان → ESTAR اول‌شخص جمع: «Nós estamos fazendo».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q6',
      type: 'mcq',
      prompt: 'VOCÊS ___ muito estudiosos. (agora)',
      promptFa: 'قید «agora» (الان) نشانهٔ حالتِ موقتی است؛ کدام فعل؟',
      options: ['estão', 'são', 'é', 'estamos'],
      answer: 'estão',
      explanationFa:
        'با «agora» حالت موقتی است → ESTAR جمع: «Vocês estão... agora».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q7',
      type: 'mcq',
      prompt: 'ELES ___ contentes com a casa nova.',
      promptFa: 'رضایتِ لحظه‌ای/موقتی؛ کدام فعل؟',
      options: ['estão', 'são', 'é', 'somos'],
      answer: 'estão',
      explanationFa: 'حالِ عاطفیِ موقتی → ESTAR جمع: «Eles estão contentes».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q8',
      type: 'fill-blank',
      prompt: 'ELAS ___ bem-sucedidas. (agora)',
      promptFa: 'با فعل درست کامل کنید (توجه به «agora»).',
      options: [],
      answer: 'estão',
      explanationFa:
        'با «agora» موقتی است → ESTAR: «Elas estão bem-sucedidas».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q9',
      type: 'fill-blank',
      prompt: 'Eu ___ um presente para ela.',
      promptFa: 'فعل DAR در زمان حال، اول‌شخص مفرد.',
      options: [],
      answer: 'dou',
      explanationFa: 'حالِ اول‌شخصِ dar → «dou»: «Eu dou um presente».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q10',
      type: 'mcq',
      prompt: 'Mês que vem a gente ___ uma festa.',
      promptFa: '«mês que vem» یعنی ماه آینده؛ کدام شکل درست است؟',
      options: ['vai dar', 'demos', 'davam', 'dou'],
      answer: 'vai dar',
      explanationFa:
        'آینده با «a gente» → «vai dar» (یا شکل ساده «dará»). «a gente» سوم‌شخص مفرد است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q11',
      type: 'fill-blank',
      prompt: 'A enfermeira ___ o remédio ao paciente.',
      promptFa: 'فعل DAR در زمان حال، سوم‌شخص مفرد.',
      options: [],
      answer: 'dá',
      explanationFa:
        'حالِ سوم‌شخص مفردِ dar → «dá»: «A enfermeira dá o remédio».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q12',
      type: 'fill-blank',
      prompt:
        'Nas décadas de 80 e 90 os artistas ___ autógrafos, hoje tiram selfies com os fãs.',
      promptFa:
        'عادتِ گذشته (دهه‌های ۸۰ و ۹۰)؛ فعل DAR در گذشتهٔ ناتمام، سوم‌شخص جمع.',
      options: [],
      answer: 'davam',
      explanationFa:
        'عادتِ گذشته → گذشتهٔ ناتمام: «os artistas davam autógrafos».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q13',
      type: 'fill-blank',
      prompt: 'Nós ___ nossa lição de casa depois da aula.',
      promptFa: 'فعل FAZER در زمان حال، اول‌شخص جمع.',
      options: [],
      answer: 'fazemos',
      explanationFa: 'حالِ اول‌شخص جمعِ fazer → «fazemos».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q14',
      type: 'fill-blank',
      prompt: 'Eu ___ aniversário no dia 21 de julho.',
      promptFa: 'فعل FAZER در زمان حال، اول‌شخص مفرد (fazer aniversário).',
      options: [],
      answer: 'faço',
      explanationFa: 'حالِ اول‌شخصِ fazer → «faço»: «Eu faço aniversário...».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q15',
      type: 'mcq',
      prompt: 'O que vocês ___ no domingo passado?',
      promptFa:
        '«domingo passado» یعنی یکشنبهٔ گذشته؛ کدام شکل FAZER درست است؟',
      options: ['fizeram', 'fazem', 'faziam', 'farão'],
      answer: 'fizeram',
      explanationFa: 'گذشتهٔ کاملِ سوم‌شخص جمعِ fazer → «fizeram».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q16',
      type: 'fill-blank',
      prompt: 'O que vocês ___ no país de vocês? (habitualmente)',
      promptFa: 'عادت/کارِ معمول در زمان حال؛ فعل FAZER سوم‌شخص جمع.',
      options: [],
      answer: 'fazem',
      explanationFa:
        'کارِ معمول/همیشگی → حال: «O que vocês fazem no país de vocês?».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q17',
      type: 'fill-blank',
      prompt: 'Todos os domingos nós ___ à igreja.',
      promptFa: 'عادتِ هر یکشنبه؛ فعل IR در زمان حال، اول‌شخص جمع.',
      options: [],
      answer: 'vamos',
      explanationFa: 'حالِ اول‌شخص جمعِ ir → «vamos».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q18',
      type: 'fill-blank',
      prompt: 'Eles ___ todo ano para o Rio de Janeiro.',
      promptFa: 'عادتِ هر سال؛ فعل IR در زمان حال، سوم‌شخص جمع.',
      options: [],
      answer: 'vão',
      explanationFa: 'حالِ سوم‌شخص جمعِ ir → «vão».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q19',
      type: 'mcq',
      prompt: 'Você já ___ ao Maracanã?',
      promptFa: '«já» (تا حالا) نشانهٔ گذشته است؛ کدام شکل IR درست است؟',
      options: ['foi', 'vai', 'ia', 'irá'],
      answer: 'foi',
      explanationFa:
        'گذشتهٔ کاملِ سوم‌شخص مفردِ ir → «foi»: «Você já foi ao Maracanã?».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q20',
      type: 'fill-blank',
      prompt: 'Elas ___ sempre naquele restaurante novo.',
      promptFa: 'عادتِ فعلی (sempre = همیشه)؛ فعل IR در زمان حال، سوم‌شخص جمع.',
      options: [],
      answer: 'vão',
      explanationFa: 'حالِ سوم‌شخص جمعِ ir → «vão».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q21',
      type: 'fill-blank',
      prompt: 'A gente sempre ___ na casa deles quando éramos crianças.',
      promptFa:
        'عادتِ گذشته (quando éramos crianças)؛ فعل IR در گذشتهٔ ناتمام، «a gente».',
      options: [],
      answer: 'ia',
      explanationFa:
        'عادتِ گذشته → گذشتهٔ ناتمام؛ «a gente» سوم‌شخص مفرد → «ia».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q22',
      type: 'mcq',
      prompt: 'Ele ___ presidente do Brasil.',
      promptFa: '«رئیس‌جمهور بودن» در گذشته؛ کدام فعل (SER)؟',
      options: ['foi', 'fui', 'era', 'vai'],
      answer: 'foi',
      explanationFa:
        'گذشتهٔ کاملِ SER سوم‌شخص مفرد → «foi». (شکلِ SER و IR یکی است.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q23',
      type: 'fill-blank',
      prompt: 'Eu nunca ___ ao Rio.',
      promptFa: 'حرکت به مکان در گذشته؛ فعل IR اول‌شخص مفرد.',
      options: [],
      answer: 'fui',
      explanationFa:
        'گذشتهٔ کاملِ IR اول‌شخص مفرد → «fui»: «Eu nunca fui ao Rio».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q24',
      type: 'fill-blank',
      prompt: 'Eles ___ estudar em Portugal por um ano.',
      promptFa: 'حرکت/رفتن در گذشته؛ فعل IR سوم‌شخص جمع.',
      options: [],
      answer: 'foram',
      explanationFa:
        'گذشتهٔ کاملِ IR سوم‌شخص جمع → «foram»: «Eles foram estudar...».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q25',
      type: 'fill-blank',
      prompt: 'Em 2015 nós ___ à Índia.',
      promptFa: 'حرکت به مکان در گذشته؛ فعل IR اول‌شخص جمع.',
      options: [],
      answer: 'fomos',
      explanationFa:
        'گذشتهٔ کاملِ IR اول‌شخص جمع → «fomos»: «Nós fomos à Índia».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q26',
      type: 'mcq',
      prompt: 'Ela ___ professora no curso de italiano.',
      promptFa: 'در اینجا بعد از فعل «شغل» آمده؛ کدام فعل (SER در گذشته)؟',
      options: ['foi', 'vai', 'está', 'ia'],
      answer: 'foi',
      explanationFa:
        'چون بعدش شغل آمده، این SER است: «Ela foi professora» (معلم بود).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q27',
      type: 'fill-blank',
      prompt: 'Ele já ___ loiro, mas agora é ruivo.',
      promptFa:
        'ویژگیِ گذشته (قبلاً بلوند بود)؛ فعل SER گذشتهٔ کامل، سوم‌شخص مفرد.',
      options: [],
      answer: 'foi',
      explanationFa:
        'گذشتهٔ کاملِ SER → «foi»: «Ele já foi loiro» (قبلاً بلوند بود).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q28',
      type: 'fill-blank',
      prompt: 'Eu ___ à padaria e ao supermercado ontem de manhã.',
      promptFa: 'حرکت به مکان دیروز؛ فعل IR اول‌شخص مفرد.',
      options: [],
      answer: 'fui',
      explanationFa: 'گذشتهٔ کاملِ IR → «fui»: «Eu fui à padaria...».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q29',
      type: 'mcq',
      prompt: 'Qual é o pretérito perfeito de "ter" (EU)?',
      promptFa: 'گذشتهٔ کاملِ اول‌شخصِ فعل ter کدام است؟',
      options: ['Tive', 'Tinha', 'Tenho', 'Terei'],
      answer: 'Tive',
      explanationFa: 'گذشتهٔ کاملِ ter → «Tive»؛ گذشتهٔ ناتمام آن «Tinha» است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q30',
      type: 'mcq',
      prompt: 'Qual é o pretérito perfeito de "poder" (EU)?',
      promptFa: 'گذشتهٔ کاملِ اول‌شخصِ فعل poder کدام است؟',
      options: ['Pude', 'Podia', 'Posso', 'Poderei'],
      answer: 'Pude',
      explanationFa:
        'گذشتهٔ کاملِ poder → «Pude»؛ گذشتهٔ ناتمام آن «Podia» است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q31',
      type: 'mcq',
      prompt: 'Qual é o pretérito perfeito de "vir" (EU)?',
      promptFa: 'گذشتهٔ کاملِ اول‌شخصِ فعل vir کدام است؟',
      options: ['Vim', 'Vinha', 'Venho', 'Virei'],
      answer: 'Vim',
      explanationFa: 'گذشتهٔ کاملِ vir → «Vim»؛ گذشتهٔ ناتمام آن «Vinha» است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q32',
      type: 'fill-blank',
      prompt: 'Pretérito perfeito (EU) de "dizer": Ontem eu ___ a verdade.',
      promptFa: 'گذشتهٔ کاملِ اول‌شخصِ فعل dizer را بگذارید.',
      options: [],
      answer: 'disse',
      explanationFa:
        'گذشتهٔ کاملِ dizer اول‌شخص → «disse»: «Eu disse a verdade».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q33',
      type: 'fill-blank',
      prompt: 'Hoje eu ___ com muito frio. (estar)',
      promptFa: 'زمان حال؛ حالتِ موقتی بدن با فعل estar.',
      options: [],
      answer: 'estou',
      explanationFa: 'سرما حالتِ موقتی است → «Hoje eu estou com muito frio».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q34',
      type: 'fill-blank',
      prompt: 'Eu sempre ___ muitos livros. (ler)',
      promptFa: 'زمان حال؛ فعل ler اول‌شخص مفرد.',
      options: [],
      answer: 'leio',
      explanationFa:
        'حالِ اول‌شخصِ ler → «leio»: «Eu sempre leio muitos livros».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q35',
      type: 'fill-blank',
      prompt: 'Ela ___ um carro. (ter)',
      promptFa: 'زمان حال؛ فعل ter سوم‌شخص مفرد (مالکیت).',
      options: [],
      answer: 'tem',
      explanationFa: 'حالِ سوم‌شخصِ ter → «tem»: «Ela tem um carro».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q36',
      type: 'mcq',
      prompt: 'Eu ___ muito feliz. (característica permanente)',
      promptFa: 'اگر شادی ویژگیِ همیشگی باشد؛ کدام فعل؟',
      options: ['sou', 'estou', 'é', 'era'],
      answer: 'sou',
      explanationFa:
        'ویژگی همیشگی → SER: «Eu sou muito feliz». (اگر لحظه‌ای بود → estou.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q37',
      type: 'fill-blank',
      prompt: 'Ela ___ muito. (sair — hábito no presente)',
      promptFa: 'زمان حال؛ فعل sair سوم‌شخص مفرد (بیرون می‌رود/زیاد).',
      options: [],
      answer: 'sai',
      explanationFa: 'حالِ سوم‌شخصِ sair → «sai»: «Ela sai muito».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q38',
      type: 'fill-blank',
      prompt: 'Eu ___ banho todos os dias. (tomar)',
      promptFa: 'زمان حال؛ اصطلاح tomar banho، اول‌شخص مفرد.',
      options: [],
      answer: 'tomo',
      explanationFa:
        'حمام‌کردن → «tomar banho»: «Eu tomo banho todos os dias».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q39',
      type: 'fill-blank',
      prompt: 'Eu ___ de frutas. (gostar)',
      promptFa: 'زمان حال؛ فعل gostar de، اول‌شخص مفرد.',
      options: [],
      answer: 'gosto',
      explanationFa: 'دوست داشتن → «gostar de»: «Eu gosto de frutas».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q40',
      type: 'fill-blank',
      prompt: '___ muitos amigos. (ter — EU)',
      promptFa: 'زمان حال؛ فعل ter اول‌شخص مفرد (دوستانِ زیاد دارم).',
      options: [],
      answer: 'Tenho',
      explanationFa: 'حالِ اول‌شخصِ ter → «Tenho»: «Tenho muitos amigos».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q41',
      type: 'fill-blank',
      prompt: 'A gente ___ bem português. (falar)',
      promptFa: 'زمان حال؛ فعل falar با «a gente» (سوم‌شخص مفرد).',
      options: [],
      answer: 'fala',
      explanationFa:
        '«a gente» سوم‌شخص مفرد است → «A gente fala bem português».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q42',
      type: 'fill-blank',
      prompt: 'Nós sempre ___ as respostas. (saber)',
      promptFa: 'زمان حال؛ فعل saber اول‌شخص جمع (جواب‌ها را می‌دانیم).',
      options: [],
      answer: 'sabemos',
      explanationFa:
        'حالِ اول‌شخص جمعِ saber → «sabemos»: «Nós sempre sabemos as respostas».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q43',
      type: 'fill-blank',
      prompt: 'No ano passado eu ___ ao Rio de Janeiro. (ir)',
      promptFa: 'گذشته (سال گذشته)؛ فعل IR اول‌شخص مفرد.',
      options: [],
      answer: 'fui',
      explanationFa: 'گذشتهٔ کاملِ IR → «fui»: «No ano passado eu fui ao Rio».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q44',
      type: 'fill-blank',
      prompt: 'Eu ___ com muita fome. (estar — passado)',
      promptFa: 'گذشته؛ حالتِ موقتیِ گرسنگی با فعل estar، گذشتهٔ ناتمام.',
      options: [],
      answer: 'estava',
      explanationFa:
        'حالتِ گذشته → گذشتهٔ ناتمامِ estar: «Eu estava com muita fome».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q45',
      type: 'fill-blank',
      prompt: 'Eu ___ muito feliz com sua pergunta. (ficar — passado)',
      promptFa: 'گذشته؛ فعل ficar (خوشحال شدم)، اول‌شخص گذشتهٔ کامل.',
      options: [],
      answer: 'fiquei',
      explanationFa:
        'گذشتهٔ کاملِ ficar → «fiquei»: «Eu fiquei muito feliz». (یا «estava» با معنای وضعیت.)',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q46',
      type: 'mcq',
      prompt: 'Ontem ___ muito frio. (fazer — clima)',
      promptFa: 'برای هوا از فعل بی‌شخصِ fazer استفاده می‌شود؛ کدام شکل گذشته؟',
      options: ['fez', 'fazia', 'faz', 'fará'],
      answer: 'fez',
      explanationFa:
        'آب‌وهوا با fazer بی‌شخص: گذشتهٔ کامل → «Ontem fez muito frio».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q47',
      type: 'fill-blank',
      prompt: 'Ontem ___ muita chuva. (ter — passado)',
      promptFa: 'گذشته؛ فعل بی‌شخصِ ter (باران بود)، گذشتهٔ کامل سوم‌شخص مفرد.',
      options: [],
      answer: 'teve',
      explanationFa:
        'گذشتهٔ کاملِ ter بی‌شخص → «teve»: «Ontem teve muita chuva» (یا «houve»).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q48',
      type: 'fill-blank',
      prompt: 'Ontem eu ___ muito. (comer — passado)',
      promptFa: 'گذشته؛ فعل comer اول‌شخص گذشتهٔ کامل.',
      options: [],
      answer: 'comi',
      explanationFa: 'گذشتهٔ کاملِ comer → «comi»: «Ontem eu comi muito».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q49',
      type: 'fill-blank',
      prompt: 'Ontem eu ___ só um pouquinho. (dormir — passado)',
      promptFa: 'گذشته؛ فعل dormir اول‌شخص گذشتهٔ کامل.',
      options: [],
      answer: 'dormi',
      explanationFa:
        'گذشتهٔ کاملِ dormir → «dormi»: «Ontem eu dormi só um pouquinho».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q50',
      type: 'fill-blank',
      prompt: 'Ontem eu ___ muito. (estudar — passado)',
      promptFa: 'گذشته؛ فعل estudar اول‌شخص گذشتهٔ کامل.',
      options: [],
      answer: 'estudei',
      explanationFa:
        'گذشتهٔ کاملِ estudar → «estudei»: «Ontem eu estudei muito».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q51',
      type: 'fill-blank',
      prompt: 'Ontem eu ___ muitas pessoas. (ver — passado)',
      promptFa: 'گذشته؛ فعل ver اول‌شخص گذشتهٔ کامل.',
      options: [],
      answer: 'vi',
      explanationFa: 'گذشتهٔ کاملِ ver → «vi»: «Ontem eu vi muitas pessoas».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q52',
      type: 'fill-blank',
      prompt: 'Ontem eu ___ muito na empresa. (trabalhar — passado)',
      promptFa: 'گذشته؛ فعل trabalhar اول‌شخص گذشتهٔ کامل.',
      options: [],
      answer: 'trabalhei',
      explanationFa:
        'گذشتهٔ کاملِ trabalhar → «trabalhei»: «Ontem eu trabalhei muito na empresa».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q53',
      type: 'fill-blank',
      prompt: 'No ano que vem eu ___ ao Rio de Janeiro. (ir — futuro)',
      promptFa: 'آینده؛ فعل IR اول‌شخص مفرد.',
      options: [],
      answer: 'irei',
      explanationFa:
        'آیندهٔ IR → «irei» (یا رایج‌تر «vou»): «No ano que vem eu irei ao Rio».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q54',
      type: 'fill-blank',
      prompt: 'Nós ___ bem na prova. (ir — futuro)',
      promptFa: 'آینده؛ فعل IR اول‌شخص جمع (خوب پیش خواهیم رفت).',
      options: [],
      answer: 'iremos',
      explanationFa:
        'آیندهٔ IR اول‌شخص جمع → «iremos»: «Nós iremos bem na prova» (یا «vamos bem»).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q55',
      type: 'fill-blank',
      prompt: 'No mês que vem eu ___ um carro. (comprar — futuro)',
      promptFa: 'آینده؛ فعل comprar اول‌شخص مفرد.',
      options: [],
      answer: 'comprarei',
      explanationFa:
        'آیندهٔ comprar → «comprarei» (یا «vou comprar»): «...eu comprarei um carro».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q56',
      type: 'fill-blank',
      prompt: 'Ela ___ uma casa para a família dela. (comprar — futuro)',
      promptFa: 'آینده؛ فعل comprar سوم‌شخص مفرد.',
      options: [],
      answer: 'comprará',
      explanationFa: 'آیندهٔ comprar سوم‌شخص → «comprará» (یا «vai comprar»).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q57',
      type: 'fill-blank',
      prompt: 'Domingo que vem eu ___ ao parque. (ir — futuro)',
      promptFa: 'آینده؛ فعل IR اول‌شخص مفرد.',
      options: [],
      answer: 'irei',
      explanationFa:
        'آیندهٔ IR → «irei» (یا «vou»): «Domingo que vem eu irei ao parque».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q58',
      type: 'fill-blank',
      prompt: 'Amanhã eu ___ minha lição de casa. (fazer — futuro)',
      promptFa: 'آینده؛ فعل FAZER اول‌شخص مفرد.',
      options: [],
      answer: 'farei',
      explanationFa:
        'آیندهٔ fazer → «farei»: «Amanhã eu farei minha lição de casa».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q59',
      type: 'fill-blank',
      prompt: 'No mês que vem eu ___ mais uma dose da vacina. (tomar — futuro)',
      promptFa: 'آینده؛ فعل tomar اول‌شخص مفرد (واکسن زدن).',
      options: [],
      answer: 'tomarei',
      explanationFa:
        'آیندهٔ tomar → «tomarei»: «...eu tomarei mais uma dose da vacina».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q60',
      type: 'fill-blank',
      prompt: 'Eles ___ mais tarde. (vir — futuro)',
      promptFa: 'آینده؛ فعل vir سوم‌شخص جمع (دیرتر خواهند آمد).',
      options: [],
      answer: 'virão',
      explanationFa:
        'آیندهٔ vir سوم‌شخص جمع → «virão»: «Eles virão mais tarde» (یا «vão vir»).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q61',
      type: 'fill-blank',
      prompt: 'Amanhã eu ___ alguma coisa. (dizer — futuro)',
      promptFa: 'آینده؛ فعل dizer اول‌شخص مفرد.',
      options: [],
      answer: 'direi',
      explanationFa: 'آیندهٔ dizer → «direi»: «Amanhã eu direi alguma coisa».',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q62',
      type: 'mcq',
      prompt: 'A gente ___ muito feliz no Brasil. (ser — futuro)',
      promptFa: 'آینده با «a gente» (سوم‌شخص مفرد)؛ کدام شکل SER؟',
      options: ['será', 'serão', 'seremos', 'foi'],
      answer: 'será',
      explanationFa:
        '«a gente» سوم‌شخص مفرد است → آیندهٔ SER «será»: «A gente será muito feliz no Brasil» (یا «vai ser»).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-8-q63',
      type: 'translate-fa-pt',
      prompt:
        '«دیروز من به سینما رفتم و یک فیلم عالی دیدم.» را به پرتغالی بنویسید.',
      promptFa: 'با گذشتهٔ کاملِ ir و ver ترجمه کنید.',
      options: [],
      answer: 'Ontem eu fui ao cinema e vi um filme ótimo.',
      explanationFa:
        'ir → «fui»، ver → «vi». حرف اضافهٔ مکان بعد از fui نشان می‌دهد این IR است، نه SER.',
      cefr: 'A2',
      skill: 'writing',
    },
    {
      id: 'course-aula-8-q64',
      type: 'translate-pt-fa',
      prompt:
        'Traduza para o persa: "Quando eu era criança, a gente ia à praia todo verão."',
      promptFa: 'این جمله را به فارسی ترجمه کنید (گذشتهٔ ناتمام).',
      options: [],
      answer: 'وقتی بچه بودم، هر تابستان به ساحل می‌رفتیم.',
      explanationFa:
        'گذشتهٔ ناتمام (era، ia) عادت و وضعیتِ ادامه‌دار در گذشته را نشان می‌دهد.',
      cefr: 'A2',
      skill: 'reading',
    },
  ],
  estimatedMinutes: 30,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 8 (کامل).',
};
