import type { CourseLesson } from '@/domain/content/schema';

export const aula10: CourseLesson = {
  id: 'course-aula-10',
  order: 10,
  aula: 'Aula 10',
  titleFa: 'آزمون آزمایشی — نمونهٔ آزمون با پاسخ تشریحی',
  titlePt: 'Simulado — Prova Comentada',
  cefr: 'A2',
  summaryFa:
    'این درس یک آزمون آزمایشی (Simulado) از آزمون حضوری «مهارت زبان پرتغالی» است که کامل و با پاسخ تشریحی مرور می‌شود. ابتدا راهنمای برگزاری آزمون را می‌بینید، سپس تک‌تک ۹ سؤال آزمون را حل می‌کنیم: صرف افعال در زمان حال (Presente)، کامل‌کردن جمله‌ها با فعل دلخواه، زمان گذشتهٔ ساده (Pretérito Perfeito)، تبدیل جمله‌ها به آینده (Futuro)، جدول صرف گذشته/حال/آینده، پیداکردن افعال در جمله، مطابقت اسمی و فعلی (Concordância Nominal e Verbal)، صرف درست فعل بر پایهٔ زمان جمله، و درک مطلب (Interpretação de Texto). در پایان دستورالعمل نگارش انشا (Redação) آمده است. هدف این است که با ساختار و نوع سؤال‌های آزمون واقعی آشنا شوید و بتوانید افعال را در سه زمان اصلی درست به‌کار ببرید.',
  objectivesFa: [
    'با ساختار آزمون حضوری و قوانین آن (تعداد سؤال، رنگ خودکار، حداقل خطوط انشا) آشنا شوید.',
    'افعال باقاعده و بی‌قاعده را در زمان حال (Presente) درست صرف کنید.',
    'زمان گذشتهٔ ساده (Pretérito Perfeito) را برای روایت رویدادهای تمام‌شده به‌کار ببرید.',
    'جمله‌های زمان حال و گذشته را به زمان آینده (Futuro) تبدیل کنید.',
    'مطابقت فاعل و فعل (Concordância Verbal) و مطابقت اسم و صفت (Concordância Nominal) را رعایت کنید.',
    'افعال را در جمله تشخیص دهید و زمان آن‌ها را بشناسید.',
    'یک متن کوتاه را بخوانید و به پرسش‌های درک مطلب پاسخ دهید.',
  ],
  sections: [
    {
      headingFa: '۱. راهنمای آزمون (Orientações)',
      bodyFa:
        'این آزمون یک «آزمون حضوری» (Prova Presencial) برای ارزیابی «مهارت در زبان پرتغالی» (Avaliação de Proficiência em Língua Portuguesa) است. پیش از شروع، این قوانین را بخوانید:\n\n۱) به همهٔ سؤال‌ها پاسخ دهید (Responder todas as questões).\n۲) با خودکار آبی یا مشکی بنویسید (Escrever com caneta Azul ou Preta).\n۳) انشا (Redação) باید دست‌کم ۲۰ خط باشد (precisa ter 20 linhas).\n۴) آزمون‌های یکسان (تقلبی/کپی) باطل می‌شوند (Provas iguais serão canceladas).\n۵) از زمان تعیین‌شده فراتر نروید (Não ultrapassar o tempo determinado).',
      examples: [
        {
          pt: 'Responder todas as questões.',
          fa: 'به همهٔ سؤال‌ها پاسخ دهید.',
          pron: 'رِسپُندِر تودَس اَس کِستوئِس',
        },
        {
          pt: 'Escrever com caneta azul ou preta.',
          fa: 'با خودکار آبی یا مشکی بنویسید.',
          pron: 'اِسکرِوِر کُن کانِتا آزول اُ پرِتا',
        },
        {
          pt: 'A redação precisa ter 20 linhas.',
          fa: 'انشا باید ۲۰ خط داشته باشد.',
          pron: 'آ رِداسائو پرِسیزا تِر وینتی لینیاس',
        },
      ],
    },
    {
      headingFa: '۲. سؤال ۱ — صرف در زمان حال (Presente): متن «João»',
      bodyFa:
        'صورت سؤال: متن زیر را با صرف افعال داخل پرانتز در زمان حال کامل کنید. یادآوری صرف زمان حال برای سه گروه فعل:\n\nگروه ‎-AR‎ (voltar): eu volto · você/ele volta · nós voltamos · eles voltam\nگروه ‎-ER‎ (fazer، بی‌قاعده): eu faço · ele faz · nós fazemos · eles fazem\nگروه ‎-IR‎ (assistir/sorrir): eu assisto · ele assiste · eles assistem؛ sorrir: ele sorri · eles sorriem\n\nمتن کامل با پاسخ‌ها:\n«Após um dia de muito trabalho, João VOLTA para casa muito cansado, ENTRA em casa e DÁ um beijo carinhoso em sua esposa. BRINCA com seu cachorro e vai tomar seu banho. ASSISTE o jornal da noite e FAZ comentários sobre as notícias. Enquanto eles JANTAM, PROCURAM conversar sobre o dia de trabalho deles, SORRIEM bastante para não deixar a tristeza entrar em casa. O nome de sua esposa É Graziela e ela TEM 35 anos e eles ESTÃO casados desde jovens. Ela TRABALHA em uma casa com uma senhora empresária no ramo de festas. Todos os anos ela REÚNE seus funcionários e FAZ uma grande festa para eles.»',
      examples: [
        {
          pt: 'João volta para casa e entra em casa.',
          fa: 'ژوائو به خانه برمی‌گردد و وارد خانه می‌شود.',
          pron: 'ژوائو وُلتا پارا کازا ای اِنترا اِن کازا',
          note: 'voltar و entrar از گروه ‎-AR‎ هستند: سوم‌شخص مفرد → volta, entra.',
        },
        {
          pt: 'Ele dá um beijo e faz comentários.',
          fa: 'او یک بوسه می‌دهد و اظهارنظر می‌کند.',
          pron: 'اِلی دا اون بِیژو ای فَس کُمِنتاریوس',
          note: 'dar و fazer بی‌قاعده‌اند: ele dá, ele faz.',
        },
        {
          pt: 'Eles jantam e sorriem bastante.',
          fa: 'آن‌ها شام می‌خورند و زیاد لبخند می‌زنند.',
          pron: 'اِلیس ژانتام ای سُریِم باستانتی',
          note: 'sorrir در سوم‌شخص جمع → sorriem؛ اشتباه رایج نوشتن «sorrem» است.',
        },
        {
          pt: 'Eles estão casados e ela tem 35 anos.',
          fa: 'آن‌ها متأهل‌اند و او ۳۵ سال دارد.',
          pron: 'اِلیس اِستائو کازادوس ای اِلا تِین ترینتا ای سینکو آنوس',
          note: 'برای سن از ter استفاده می‌شود (tem 35 anos)، نه ser.',
        },
      ],
    },
    {
      headingFa: '۳. سؤال ۲ — کامل‌کردن با فعل دلخواه',
      bodyFa:
        'صورت سؤال: جمله‌ها را با یک فعل به انتخاب خودتان کامل کنید. فعل باید با فاعل مطابقت داشته باشد و از نظر معنایی منطقی باشد. نمونهٔ پاسخ‌های درست (پاسخ‌های دیگر هم اگر مطابقت درست باشد پذیرفته‌اند):\n\n۱) Nós CONVIDAMOS nossos amigos para um jantar. (ما دوستانمان را برای شام دعوت می‌کنیم)\n۲) Meus irmãos JOGAM futebol juntos. (برادرانم با هم فوتبال بازی می‌کنند)\n۳) Elas VIAJAM durante as férias. (آن‌ها در تعطیلات سفر می‌کنند)\n۴) O que você FAZ sábado à noite? (شنبه شب چه می‌کنی؟)\n۵) Não sei se a gasolina É suficiente para toda a viagem. (نمی‌دانم بنزین برای کل سفر کافی هست یا نه)',
      examples: [
        {
          pt: 'Nós convidamos nossos amigos para um jantar.',
          fa: 'ما دوستانمان را برای یک شام دعوت می‌کنیم.',
          pron: 'نُس کُنویدامُس نُسوس آمیگوس پارا اون ژانتار',
          note: 'فاعل «Nós» → فعل اول‌شخص جمع (پایانهٔ ‎-amos‎).',
        },
        {
          pt: 'O que você faz sábado à noite?',
          fa: 'شنبه شب چه‌کار می‌کنی؟',
          pron: 'او کی وُسه فَس سابادو آ نُیتی',
          note: '«você» با فعل سوم‌شخص مفرد می‌آید: faz.',
        },
      ],
    },
    {
      headingFa: '۴. سؤال ۳ — گذشتهٔ ساده (Pretérito Perfeito): متن «Rafaella»',
      bodyFa:
        'صورت سؤال: متن را با افعال در زمان گذشتهٔ ساده (Pretérito Perfeito) کامل کنید. این زمان برای رویدادهای تمام‌شده در گذشته است. پایانه‌های سوم‌شخص مفرد: گروه ‎-AR‎ → ‎-ou‎ · گروه ‎-ER‎ → ‎-eu‎ · گروه ‎-IR‎ → ‎-iu‎.\n\nمتن کامل با پاسخ‌ها:\n«No ano passado, Rafaella REALIZOU o grande sonho da vida dela, VIAJOU para a Europa. CONHECEU a torre Eiffel e o arco do triunfo. VISITOU também o museu do Louvre. Depois da França, PEGOU um voo até Londres e se ENCONTROU com sua amiga Julianna. À noite, as duas SAÍRAM para jantar em um restaurante e não PAGARAM muito caro na refeição. Elas VOLTARAM para a casa após a janta e COLOCARAM um filme para assistir. Na manhã seguinte, Rafaella ACORDOU cedo para andar e ACABOU se apaixonando pela cidade.»',
      examples: [
        {
          pt: 'Rafaella viajou para a Europa e conheceu a torre Eiffel.',
          fa: 'رافائلا به اروپا سفر کرد و برج ایفل را دید.',
          pron: 'رافائلا ویاژُ پارا آ اِئوروپا ای کُنیِسِئو آ تُری اِیفِل',
          note: 'viajar (‎-AR‎) → viajou؛ conhecer (‎-ER‎) → conheceu.',
        },
        {
          pt: 'As duas saíram e não pagaram muito caro.',
          fa: 'آن دو بیرون رفتند و خیلی گران نپرداختند.',
          pron: 'اَس دواس سائیرام ای نائو پاگارام مویتو کارو',
          note: 'سوم‌شخص جمعِ گذشته: sair → saíram, pagar → pagaram.',
        },
        {
          pt: 'Ela acordou cedo e acabou se apaixonando pela cidade.',
          fa: 'او زود بیدار شد و عاقبت عاشق شهر شد.',
          pron: 'اِلا آکُردُ سِدو ای آکابُ سی آپایشونَندو پِلا سیدادی',
        },
      ],
    },
    {
      headingFa: '۵. سؤال ۴ — تبدیل به آینده (Futuro)',
      bodyFa:
        'صورت سؤال: جمله‌ها را به زمان آینده تبدیل کنید. آیندهٔ ساده با افزودن پایانه به مصدر ساخته می‌شود: ‎-ei / -á / -emos / -ão‎ (falarei, falará…). برای فعل در حال استمرار می‌توان از «estar در آینده + gerúndio» استفاده کرد.\n\nپاسخ‌ها:\nA) Estamos correndo no parque → ESTAREMOS correndo no parque. (یا: Correremos no parque)\nB) Mamãe comprou um carro novo → Mamãe COMPRARÁ um carro novo.\nC) Busquei meu irmão no aeroporto → BUSCAREI meu irmão no aeroporto.\nD) O pintor terminou de pintar a casa no domingo → O pintor TERMINARÁ de pintar a casa no domingo.\nE) O papa rezou a missa do galo no Natal → O papa REZARÁ a missa do galo no Natal.\nF) Meu irmão chegou domingo da Europa → Meu irmão CHEGARÁ domingo da Europa.',
      examples: [
        {
          pt: 'Mamãe comprará um carro novo.',
          fa: 'مامان یک ماشین نو خواهد خرید.',
          pron: 'مامائِه کُمپرارا اون کارو نُوو',
          note: 'comprar → comprará (سوم‌شخص مفرد آینده).',
        },
        {
          pt: 'Buscarei meu irmão no aeroporto.',
          fa: 'برادرم را در فرودگاه خواهم برد/دنبال خواهم کرد.',
          pron: 'بوسکارِی مِئو ایرمائو نو آئروپُرتو',
          note: 'اول‌شخص مفرد آینده → پایانهٔ ‎-ei‎ روی مصدر.',
        },
      ],
    },
    {
      headingFa: '۶. سؤال ۵ — جدول صرف: گذشته / حال / آینده',
      bodyFa:
        'صورت سؤال: افعالِ زمان حال (شکل «eu») را در زمان گذشته و آینده صرف کنید. جدول کامل (اول‌شخص مفرد):\n\nPRETÉRITO PERFEITO (PASSADO) | PRESENTE | FUTURO\nFalei | Falo | Falarei\nPensei | Penso | Pensarei\nGostei | Gosto | Gostarei\nCheguei | Chego | Chegarei\nBebi | Bebo | Beberei\n\nنکته‌ها: در «chegar» برای حفظ صدای «گ» در گذشته یک «u» اضافه می‌شود → cheguei. فعل «beber» از گروه ‎-ER‎ است، پس گذشته‌اش «bebi» و آینده‌اش «beberei» می‌شود.',
      examples: [
        {
          pt: 'Falo · Falei · Falarei',
          fa: 'حرف می‌زنم · حرف زدم · حرف خواهم زد',
          pron: 'فالو · فالِی · فالارِی',
        },
        {
          pt: 'Chego · Cheguei · Chegarei',
          fa: 'می‌رسم · رسیدم · خواهم رسید',
          pron: 'شِگو · شِگِی · شِگارِی',
          note: 'در گذشته «u» می‌آید تا صدای سختِ «گ» حفظ شود: cheguei.',
        },
        {
          pt: 'Bebo · Bebi · Beberei',
          fa: 'می‌نوشم · نوشیدم · خواهم نوشید',
          pron: 'بِبو · بِبی · بِبِرِی',
        },
      ],
    },
    {
      headingFa: '۷. سؤال ۶ — پیداکردن افعال در جمله',
      bodyFa:
        'صورت سؤال: افعال جمله‌های زیر را پیدا کنید. فعل کلمه‌ای است که کار یا حالت را نشان می‌دهد و زمان دارد.\n\na) Minha mãe COZINHARÁ feijoada. → cozinhará (آینده)\nb) FUI visitar minha vó e logo VOLTEI. → fui، visitar، voltei (fui و voltei گذشته؛ visitar مصدر)\nc) ANDAREI de bicicleta no domingo. → andarei (آینده)\nd) SENTI muita dor no joelho ao JOGAR futebol. → senti (گذشته)، jogar (مصدر)\ne) Não ESPERAREI o ônibus. → esperarei (آینده)\nf) OLHEI a hora no relógio. → olhei (گذشته)',
      examples: [
        {
          pt: 'Minha mãe cozinhará feijoada.',
          fa: 'مادرم فِیژوآدا خواهد پخت.',
          pron: 'مینیا مائِه کوزینیارا فِیژوآدا',
          note: 'فعل: cozinhará (آیندهٔ cozinhar).',
        },
        {
          pt: 'Fui visitar minha vó e logo voltei.',
          fa: 'رفتم مادربزرگم را ببینم و زود برگشتم.',
          pron: 'فویی ویزیتار مینیا وُ ای لوگو وُلتِی',
          note: 'سه فعل: fui، visitar، voltei.',
        },
        {
          pt: 'Não esperarei o ônibus.',
          fa: 'منتظر اتوبوس نخواهم ماند.',
          pron: 'نائو اِسپِرارِی او اُنیبوس',
          note: 'فعل: esperarei (آیندهٔ esperar).',
        },
      ],
    },
    {
      headingFa: '۸. سؤال ۷ — مطابقت اسمی و فعلی (Concordância)',
      bodyFa:
        'صورت سؤال: مطابقت اسمی و فعلی جمله‌ها را درست کنید. فعل باید با فاعل و صفت/اسم با شمار مطابقت داشته باشد.\n\nجمله‌های اشتباه ← درست:\n۱) Nós quer ir para festa ← Nós QUEREMOS ir para A festa. («Nós» → queremos)\n۲) A gente precisamos sair mais cedo ← A gente PRECISA sair mais cedo. («a gente» سوم‌شخص مفرد → precisa)\n۳) Ele queremos buscar a máquina ← Ele QUER buscar a máquina. («Ele» → quer)\n۴) Elas busca seu filhos na escola ← Elas BUSCAM SEUS filhos na escola. (فعل جمع + مطابقت seus/filhos)\n۵) Nós não pagou a conta ← Nós não PAGAMOS a conta. («Nós» → pagamos)',
      examples: [
        {
          pt: 'Nós queremos ir para a festa.',
          fa: 'ما می‌خواهیم به جشن برویم.',
          pron: 'نُس کِرِموس ایر پارا آ فِستا',
          note: 'فاعل «Nós» فعل اول‌شخص جمع می‌خواهد: queremos.',
        },
        {
          pt: 'A gente precisa sair mais cedo.',
          fa: 'ما باید زودتر برویم.',
          pron: 'آ جِنتی پرِسیزا سائیر مایس سِدو',
          note: '«a gente» با فعل سوم‌شخص مفرد می‌آید (precisa)، هرچند معنی «ما» می‌دهد.',
        },
        {
          pt: 'Elas buscam seus filhos na escola.',
          fa: 'آن‌ها فرزندانشان را از مدرسه می‌آورند.',
          pron: 'اِلاس بوسکام سِئوس فیلیوس نا اِسکولا',
          note: 'هم فعل جمع (buscam) و هم مطابقت اسمی (seus filhos) لازم است.',
        },
      ],
    },
    {
      headingFa: '۹. سؤال ۸ — صرف درست بر پایهٔ زمان جمله',
      bodyFa:
        'صورت سؤال: جمله‌ها را با صرف درستِ فعل داخل پرانتز کامل کنید. به قید زمان توجه کنید تا زمان درست را انتخاب کنید (گذشته، حال یا آینده).\n\n۱) Semana passada eu JANTEI nesse restaurante (jantar). → گذشته\n۲) Mais tarde ele ENCONTRARÁ a namorada (encontrar). → آینده\n۳) O jogo de ontem ESTEVE bem difícil (estar). → گذشته (estar → esteve)\n۴) Amanhã, não ESTAREI em casa (estar). → آینده\n۵) Mês que vem COMPRAREI aquela calça jeans (comprar). → آینده\n۶) Me perdoe, mas não QUERO fazer isso (querer). → حال\n۷) No mês passado, os alunos ESTUDARAM geografia (estudar). → گذشته',
      examples: [
        {
          pt: 'Semana passada eu jantei nesse restaurante.',
          fa: 'هفتهٔ گذشته من در آن رستوران شام خوردم.',
          pron: 'سِمانا پاسادا اِئو ژانتِی نِسی رِستائورانتی',
          note: '«Semana passada» نشانهٔ گذشته است → jantei.',
        },
        {
          pt: 'Amanhã, não estarei em casa.',
          fa: 'فردا خانه نخواهم بود.',
          pron: 'آمانیا، نائو اِستارِی اِن کازا',
          note: '«Amanhã» نشانهٔ آینده است → estarei (آیندهٔ estar).',
        },
        {
          pt: 'No mês passado, os alunos estudaram geografia.',
          fa: 'ماه گذشته دانش‌آموزان جغرافیا خواندند.',
          pron: 'نو مِس پاسادو، اوس آلونوس اِستودارام ژِئوگرافیا',
          note: 'فاعل جمع + گذشته → estudaram.',
        },
      ],
    },
    {
      headingFa: '۱۰. سؤال ۹ — درک مطلب (Interpretação de Texto): «Cristina»',
      bodyFa:
        'متن: «Cristina é uma catadora de material reciclável em uma pequena cidade no interior de São Paulo. Com seu trabalho, ela consegue pagar seu curso de cabeleireira e ajudar nas despesas da casa. Cristina tem 32 anos, é casada com Júnior, que é motorista de ônibus. Eles são casados há 5 anos e pensam em breve fazer uma viagem para conhecer o nordeste do Brasil. O casal sonha que em aproximadamente dois anos poderão ter seu primeiro filho.»\n\nترجمهٔ فارسی: کریستینا در شهری کوچک در داخل ایالت سائوپائولو جمع‌کنندهٔ مواد بازیافتی است. با کارش می‌تواند شهریهٔ کلاس آرایشگری‌اش را بپردازد و در هزینه‌های خانه کمک کند. او ۳۲ سال دارد و با ژونیور که رانندهٔ اتوبوس است ازدواج کرده. آن‌ها ۵ سال است ازدواج کرده‌اند و به‌زودی می‌خواهند سفری به شمال‌شرقِ برزیل بروند. آرزوی این زوج این است که تقریباً تا دو سال دیگر اولین فرزندشان را داشته باشند.\n\nپاسخ پرسش‌ها:\n۱) Quem é Cristina? → Cristina é uma catadora de material reciclável; tem 32 anos e é casada.\n۲) Quem é seu esposo e para onde pretendem viajar? → Seu esposo é o Júnior, motorista de ônibus; pretendem viajar para o nordeste do Brasil.\n۳) Qual o sonho do casal? → Ter o primeiro filho em aproximadamente dois anos.',
      examples: [
        {
          pt: 'Cristina é uma catadora de material reciclável.',
          fa: 'کریستینا جمع‌کنندهٔ مواد بازیافتی است.',
          pron: 'کریستینا اِ اوما کاتادورا جی ماتِریال رِسیکلاوِل',
        },
        {
          pt: 'Seu esposo, Júnior, é motorista de ônibus.',
          fa: 'همسرش، ژونیور، رانندهٔ اتوبوس است.',
          pron: 'سِئو اِسپُزو، ژونیور، اِ مُتوریستا جی اُنیبوس',
        },
        {
          pt: 'O casal sonha em ter o primeiro filho.',
          fa: 'این زوج آرزوی داشتنِ اولین فرزند را دارند.',
          pron: 'او کازال سُنیا اِین تِر او پریمِیرو فیلیو',
        },
      ],
    },
    {
      headingFa: '۱۱. انشا (Redação)',
      bodyFa:
        'بخش پایانی آزمون نگارش انشا است. قوانین انشا:\n\n• انشا باید دست‌کم ۲۰ خط باشد (no mínimo 20 linhas).\n• باید با موضوع (tema) هماهنگ باشد (Precisa estar de acordo com o tema).\n• با خودکار مشکی یا آبی نوشته شود (Escrever com caneta preta ou azul).\n\nموضوع (TEMA) در برگهٔ آزمون مشخص می‌شود. برای نمرهٔ خوب: مقدمه، بدنه و نتیجه‌گیری بنویسید، از زمان‌های فعلی درست استفاده کنید و مطابقت فاعل و فعل را رعایت کنید.',
      examples: [
        {
          pt: 'A redação deve conter no mínimo 20 linhas.',
          fa: 'انشا باید دست‌کم ۲۰ خط داشته باشد.',
          pron: 'آ رِداسائو دِوی کُنتِر نو مینیمو وینتی لینیاس',
        },
        {
          pt: 'A redação precisa estar de acordo com o tema.',
          fa: 'انشا باید با موضوع هماهنگ باشد.',
          pron: 'آ رِداسائو پرِسیزا اِستار جی آکُردو کُن او تِما',
        },
      ],
    },
  ],
  keyPointsFa: [
    'زمان حال (Presente): پایانه‌های سوم‌شخص مفرد ‎-a‎ (‎-AR‎)، ‎-e‎ (‎-ER/-IR‎)؛ برای سن از ter استفاده کنید (tem 35 anos).',
    'گذشتهٔ ساده (Pretérito Perfeito) سوم‌شخص مفرد: ‎-ou‎ / ‎-eu‎ / ‎-iu‎؛ جمع: ‎-aram‎ / ‎-eram‎ / ‎-iram‎.',
    'آیندهٔ ساده (Futuro): پایانه‌های ‎-ei / -á / -emos / -ão‎ روی مصدر (falarei, comprará).',
    'در «chegar» گذشته «u» می‌گیرد تا صدای «گ» حفظ شود: cheguei.',
    'مطابقت فعلی: Nós → ‎-mos‎؛ «a gente» با فعل سوم‌شخص مفرد می‌آید هرچند یعنی «ما».',
    'مطابقت اسمی: صفت/ضمیر ملکی با اسم مطابقت شمار می‌گیرد (seus filhos).',
    'به قید زمان جمله (ontem, amanhã, semana passada) توجه کنید تا زمان فعل را درست انتخاب کنید.',
  ],
  quiz: [
    {
      id: 'course-aula-10-q1',
      type: 'fill-blank',
      prompt:
        'Presente: Após o trabalho, João ____ (voltar) para casa cansado.',
      promptFa: 'فعل voltar را در زمان حال برای «João» صرف کنید.',
      options: [],
      answer: 'volta',
      explanationFa: 'voltar از گروه ‎-AR‎ است؛ سوم‌شخص مفرد زمان حال → volta.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q2',
      type: 'fill-blank',
      prompt: 'Presente: Ele ____ (dar) um beijo carinhoso na esposa.',
      promptFa: 'فعل بی‌قاعدهٔ dar را در زمان حال برای «ele» بگذارید.',
      options: [],
      answer: 'dá',
      explanationFa: 'dar بی‌قاعده است؛ سوم‌شخص مفرد → dá (با علامت تشدید).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q3',
      type: 'fill-blank',
      prompt: 'Presente: Ele ____ (fazer) comentários sobre as notícias.',
      promptFa: 'فعل بی‌قاعدهٔ fazer را در زمان حال برای «ele» بگذارید.',
      options: [],
      answer: 'faz',
      explanationFa: 'fazer بی‌قاعده است؛ سوم‌شخص مفرد → faz.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q4',
      type: 'fill-blank',
      prompt: 'Presente: Enquanto eles ____ (jantar), ____ (sorrir) bastante.',
      promptFa: 'دو فعل را در زمان حال برای «eles» بگذارید.',
      options: [],
      answer: 'jantam / sorriem',
      explanationFa:
        'سوم‌شخص جمع: jantar → jantam؛ sorrir → sorriem (نه «sorrem»).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q5',
      type: 'mcq',
      prompt: 'Presente: A esposa ____ 35 anos.',
      promptFa: 'برای گفتن سن کدام فعل درست است؟',
      options: ['tem', 'é', 'está', 'faz'],
      answer: 'tem',
      explanationFa: 'برای سن از ter استفاده می‌شود: «tem 35 anos»، نه ser.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q6',
      type: 'fill-blank',
      prompt: 'Presente: Eles ____ (estar) casados desde jovens.',
      promptFa: 'فعل estar را در زمان حال برای «eles» بگذارید.',
      options: [],
      answer: 'estão',
      explanationFa: 'estar سوم‌شخص جمع زمان حال → estão.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q7',
      type: 'fill-blank',
      prompt: 'Complete com um verbo: Meus irmãos ____ futebol juntos.',
      promptFa: 'با یک فعل مناسب و صرف‌شده برای «meus irmãos» کامل کنید.',
      options: [],
      answer: 'jogam',
      explanationFa: 'فاعل جمع → فعل سوم‌شخص جمع: jogam (بازی می‌کنند).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q8',
      type: 'mcq',
      prompt: 'Complete com um verbo: O que você ____ sábado à noite?',
      promptFa: 'کدام صرف با فاعل «você» درست است؟',
      options: ['faz', 'faço', 'fazem', 'fazemos'],
      answer: 'faz',
      explanationFa: '«você» با فعل سوم‌شخص مفرد می‌آید → faz.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q9',
      type: 'fill-blank',
      prompt:
        'Pretérito Perfeito: No ano passado, Rafaella ____ (viajar) para a Europa.',
      promptFa: 'فعل viajar را در گذشتهٔ ساده برای «Rafaella» بگذارید.',
      options: [],
      answer: 'viajou',
      explanationFa: 'گروه ‎-AR‎ در گذشتهٔ ساده سوم‌شخص مفرد → ‎-ou‎: viajou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q10',
      type: 'fill-blank',
      prompt: 'Pretérito Perfeito: Ela ____ (conhecer) a torre Eiffel.',
      promptFa: 'فعل conhecer را در گذشتهٔ ساده بگذارید.',
      options: [],
      answer: 'conheceu',
      explanationFa:
        'گروه ‎-ER‎ در گذشتهٔ ساده سوم‌شخص مفرد → ‎-eu‎: conheceu.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q11',
      type: 'fill-blank',
      prompt:
        'Pretérito Perfeito: As duas ____ (sair) e não ____ (pagar) muito caro.',
      promptFa: 'دو فعل را در گذشتهٔ ساده برای «as duas» بگذارید.',
      options: [],
      answer: 'saíram / pagaram',
      explanationFa: 'سوم‌شخص جمعِ گذشته: sair → saíram؛ pagar → pagaram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q12',
      type: 'fill-blank',
      prompt:
        'Pretérito Perfeito: Rafaella ____ (acordar) cedo e ____ (acabar) se apaixonando pela cidade.',
      promptFa: 'دو فعل را در گذشتهٔ ساده بگذارید.',
      options: [],
      answer: 'acordou / acabou',
      explanationFa: 'هر دو گروه ‎-AR‎ هستند → acordou, acabou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q13',
      type: 'translate-pt-fa',
      prompt: 'Passe para o Futuro: "Mamãe comprou um carro novo."',
      promptFa:
        'این جمله را به زمان آینده تبدیل کنید (فقط جملهٔ پرتغالی آینده را بنویسید).',
      options: [],
      answer: 'Mamãe comprará um carro novo.',
      explanationFa: 'comprar در آیندهٔ سوم‌شخص مفرد → comprará.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q14',
      type: 'mcq',
      prompt: 'Passe para o Futuro: "Busquei meu irmão no aeroporto." →',
      promptFa: 'کدام شکل آیندهٔ درست برای «busquei» است؟',
      options: [
        'Buscarei meu irmão no aeroporto.',
        'Busco meu irmão no aeroporto.',
        'Buscava meu irmão no aeroporto.',
        'Busquei meu irmão no aeroporto.',
      ],
      answer: 'Buscarei meu irmão no aeroporto.',
      explanationFa: 'اول‌شخص مفرد آینده → پایانهٔ ‎-ei‎ روی مصدر: buscarei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q15',
      type: 'translate-pt-fa',
      prompt: 'Passe para o Futuro: "Meu irmão chegou domingo da Europa."',
      promptFa: 'این جمله را به آینده تبدیل کنید (جملهٔ پرتغالی آینده).',
      options: [],
      answer: 'Meu irmão chegará domingo da Europa.',
      explanationFa: 'chegar در آیندهٔ سوم‌شخص مفرد → chegará.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q16',
      type: 'fill-blank',
      prompt: 'Conjugue: PASSADO ____ · PRESENTE Chego · FUTURO ____.',
      promptFa: 'گذشته و آیندهٔ «Chego» را بنویسید.',
      options: [],
      answer: 'Cheguei / Chegarei',
      explanationFa:
        'در گذشته «u» می‌آید تا صدای «گ» حفظ شود: cheguei؛ آینده: chegarei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q17',
      type: 'fill-blank',
      prompt: 'Conjugue: PASSADO ____ · PRESENTE Bebo · FUTURO ____.',
      promptFa: 'گذشته و آیندهٔ «Bebo» را بنویسید.',
      options: [],
      answer: 'Bebi / Beberei',
      explanationFa: 'beber از گروه ‎-ER‎ است: گذشته bebi، آینده beberei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q18',
      type: 'mcq',
      prompt: 'Qual é o verbo em: "Minha mãe cozinhará feijoada."?',
      promptFa: 'فعل جمله کدام است؟',
      options: ['cozinhará', 'feijoada', 'mãe', 'minha'],
      answer: 'cozinhará',
      explanationFa: 'فعل جمله «cozinhará» است (آیندهٔ cozinhar).',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q19',
      type: 'mcq',
      prompt: 'Quantos verbos há em: "Fui visitar minha vó e logo voltei."?',
      promptFa: 'چند فعل در این جمله هست؟',
      options: [
        'Três (fui, visitar, voltei)',
        'Um (fui)',
        'Dois (fui, voltei)',
        'Nenhum',
      ],
      answer: 'Três (fui, visitar, voltei)',
      explanationFa: 'سه فعل: fui و voltei (گذشته) و visitar (مصدر).',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q20',
      type: 'mcq',
      prompt: 'Faça a concordância: "Nós quer ir para festa." →',
      promptFa: 'کدام تصحیحِ مطابقت درست است؟',
      options: [
        'Nós queremos ir para a festa.',
        'Nós quer ir para a festa.',
        'Nós quero ir para festa.',
        'Nós querem ir para festa.',
      ],
      answer: 'Nós queremos ir para a festa.',
      explanationFa: 'فاعل «Nós» فعل اول‌شخص جمع می‌خواهد → queremos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q21',
      type: 'mcq',
      prompt: 'Faça a concordância: "A gente precisamos sair mais cedo." →',
      promptFa: 'کدام تصحیحِ درست است؟',
      options: [
        'A gente precisa sair mais cedo.',
        'A gente precisamos sair mais cedo.',
        'A gente precisam sair mais cedo.',
        'A gente preciso sair mais cedo.',
      ],
      answer: 'A gente precisa sair mais cedo.',
      explanationFa: '«a gente» با فعل سوم‌شخص مفرد می‌آید → precisa.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q22',
      type: 'fill-blank',
      prompt:
        'Faça a concordância: "Elas busca seu filhos na escola." → Elas ____ ____ filhos na escola.',
      promptFa: 'فعل و ضمیر ملکی را برای مطابقت درست کنید.',
      options: [],
      answer: 'buscam seus',
      explanationFa:
        'فعل جمع (buscam) و مطابقت اسمی (seus filhos) هر دو لازم است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q23',
      type: 'fill-blank',
      prompt:
        'Faça a concordância: "Nós não pagou a conta." → Nós não ____ a conta.',
      promptFa: 'فعل را با فاعل «Nós» درست کنید.',
      options: [],
      answer: 'pagamos',
      explanationFa: '«Nós» فعل اول‌شخص جمع می‌خواهد → pagamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q24',
      type: 'fill-blank',
      prompt:
        'Verbo correto: Semana passada eu ____ (jantar) nesse restaurante.',
      promptFa: 'با توجه به «semana passada» فعل را صرف کنید.',
      options: [],
      answer: 'jantei',
      explanationFa:
        '«Semana passada» گذشته است → jantei (اول‌شخص مفرد گذشته).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q25',
      type: 'fill-blank',
      prompt: 'Verbo correto: Mais tarde ele ____ (encontrar) a namorada.',
      promptFa: 'با توجه به «mais tarde» فعل را صرف کنید.',
      options: [],
      answer: 'encontrará',
      explanationFa: '«Mais tarde» به آینده اشاره دارد → encontrará.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q26',
      type: 'fill-blank',
      prompt: 'Verbo correto: Amanhã, não ____ (estar) em casa.',
      promptFa: 'با توجه به «amanhã» فعل estar را صرف کنید.',
      options: [],
      answer: 'estarei',
      explanationFa:
        '«Amanhã» آینده است → estarei (آیندهٔ estar، اول‌شخص مفرد).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q27',
      type: 'mcq',
      prompt: 'Verbo correto: Me perdoe, mas não ____ (querer) fazer isso.',
      promptFa: 'کدام صرفِ querer در زمان حال (اول‌شخص) درست است؟',
      options: ['quero', 'quis', 'quererei', 'queremos'],
      answer: 'quero',
      explanationFa: 'زمان حال اول‌شخص مفرد فعل بی‌قاعدهٔ querer → quero.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q28',
      type: 'fill-blank',
      prompt:
        'Verbo correto: No mês passado, os alunos ____ (estudar) geografia.',
      promptFa: 'با توجه به «mês passado» فعل را برای «os alunos» صرف کنید.',
      options: [],
      answer: 'estudaram',
      explanationFa: 'گذشتهٔ سوم‌شخص جمع گروه ‎-AR‎ → estudaram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q29',
      type: 'translate-pt-fa',
      prompt: 'Interpretação: "Quem é Cristina?" Responda em português.',
      promptFa: 'بر اساس متن به پرتغالی پاسخ دهید: کریستینا کیست؟',
      options: [],
      answer:
        'Cristina é uma catadora de material reciclável; tem 32 anos e é casada.',
      explanationFa:
        'پاسخ از متن استخراج می‌شود: شغل، سن و وضعیت تأهل کریستینا.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q30',
      type: 'mcq',
      prompt: 'Interpretação: Para onde o casal pretende viajar?',
      promptFa: 'زوج قصد دارند به کجا سفر کنند؟',
      options: [
        'Para o nordeste do Brasil',
        'Para a Europa',
        'Para São Paulo',
        'Para Londres',
      ],
      answer: 'Para o nordeste do Brasil',
      explanationFa:
        'متن می‌گوید آن‌ها می‌خواهند شمال‌شرقِ برزیل (nordeste do Brasil) را ببینند.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q31',
      type: 'mcq',
      prompt: 'Interpretação: Qual é o sonho do casal?',
      promptFa: 'آرزوی این زوج چیست؟',
      options: [
        'Ter o primeiro filho em cerca de dois anos',
        'Comprar uma casa nova',
        'Abrir um salão de beleza',
        'Comprar um ônibus',
      ],
      answer: 'Ter o primeiro filho em cerca de dois anos',
      explanationFa:
        'متن می‌گوید آرزوی زوج داشتنِ اولین فرزند تقریباً تا دو سال دیگر است.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q32',
      type: 'mcq',
      prompt:
        'Orientações da prova: quantas linhas, no mínimo, a redação precisa ter?',
      promptFa: 'بر اساس راهنما، انشا دست‌کم چند خط باید باشد؟',
      options: ['20 linhas', '10 linhas', '30 linhas', '15 linhas'],
      answer: '20 linhas',
      explanationFa: 'طبق قوانین آزمون، انشا باید دست‌کم ۲۰ خط باشد.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q33',
      type: 'translate-fa-pt',
      prompt: '«فردا خانه نخواهم بود.» را به پرتغالی بنویسید.',
      promptFa: 'این جمله را با زمان آیندهٔ فعل estar به پرتغالی بنویسید.',
      options: [],
      answer: 'Amanhã, não estarei em casa.',
      explanationFa: 'قید «amanhã» آینده می‌خواهد؛ estar در آینده → estarei.',
      cefr: 'A2',
      skill: 'writing',
    },
  ],
  estimatedMinutes: 28,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 10 (کامل).',
};
