import type { CourseLesson } from '@/domain/content/schema';

export const aula10: CourseLesson = {
  id: 'course-aula-10',
  order: 10,
  aula: 'Aula 10',
  titleFa: 'آزمون آزمایشی — نمونه‌سؤالِ تشریح‌شده',
  titlePt: 'Simulado — Prova Comentada',
  cefr: 'A2',
  summaryFa:
    'این درس یک «آزمون آزمایشیِ تشریح‌شده» (Simulado / Prova Comentada) است؛ یعنی نمونهٔ کاملِ آزمون حضوریِ سنجش مهارت زبان پرتغالی به‌همراه پاسخ و توضیح. ابتدا دستورالعمل‌های برگزاری آزمون را می‌بینید، سپس ۹ تمرین بزرگ را کار می‌کنید: صرف افعال در زمان حال (Presente)، تکمیل جمله با فعل دلخواه، صرف در گذشتهٔ کامل (Pretérito Perfeito)، تبدیل جمله به آیندهٔ (Futuro)، صرفِ همزمانِ گذشته/حال/آینده، پیدا کردن افعال درون جمله، تطابق فعل و اسم (Concordância Verbal e Nominal)، تکمیل جمله با زمانِ درست بر اساس قید زمان، و در پایان درک مطلب (Interpretação de Texto) و انشا (Redação). هر بخش با پاسخ و توضیح فارسی همراه است.',
  objectivesFa: [
    'دستورالعمل‌های آزمون حضوریِ سنجش مهارت زبان پرتغالی را بفهمید.',
    'افعال باقاعده و بی‌قاعده را در زمان حال (Presente) درست صرف کنید.',
    'افعال را در گذشتهٔ کامل (Pretérito Perfeito) و آینده (Futuro) صرف کنید.',
    'جمله‌ها را از یک زمان به زمان دیگر (حال ← گذشته ← آینده) تبدیل کنید.',
    'تطابق فعل با فاعل و تطابق اسم/صفت (Concordância Verbal e Nominal) را رعایت کنید.',
    'قیدهای زمان (ontem, amanhã, mês passado, mês que vem …) را برای انتخاب زمانِ درست فعل به‌کار ببرید.',
    'یک متن ساده را بخوانید و به پرسش‌های درک مطلب پاسخ دهید.',
  ],
  sections: [
    {
      headingFa: '۱. معرفی آزمون و دستورالعمل‌ها (Orientações)',
      bodyFa:
        'این یک «آزمون حضوریِ سنجش مهارت زبان پرتغالی» (Avaliação de Proficiência em Língua Portuguesa — Prova Presencial) است. پیش از شروع، این ۵ قانون را بخوانید:\n\n1) به همهٔ سؤال‌ها پاسخ دهید (Responder todas as questões).\n2) با خودکار آبی یا مشکی بنویسید (Escrever com caneta azul ou preta).\n3) انشا (Redação) باید دست‌کم ۲۰ خط باشد (A redação precisa ter 20 linhas).\n4) برگه‌های یکسان (تقلبی) باطل می‌شوند (Provas iguais serão canceladas).\n5) از زمانِ تعیین‌شده فراتر نروید (Não ultrapassar o tempo determinado).',
      examples: [
        {
          pt: 'Responder todas as questões.',
          fa: 'به همهٔ سؤال‌ها پاسخ دهید.',
          pron: 'رِسپُندِر تودَس اَس کِستوئِس',
        },
        {
          pt: 'Escrever com caneta azul ou preta.',
          fa: 'با خودکار آبی یا مشکی بنویسید.',
          pron: 'اِسکرِوِر کُن کانِتا آزول اُ پرِتا',
          note: 'caneta = خودکار؛ lápis = مداد (که مجاز نیست).',
        },
        {
          pt: 'A redação precisa ter 20 linhas.',
          fa: 'انشا باید ۲۰ خط داشته باشد.',
          pron: 'آ رِداسائو پرِسیزا تِر وینتی لینیاس',
        },
        {
          pt: 'Não ultrapassar o tempo determinado.',
          fa: 'از زمان تعیین‌شده فراتر نروید.',
          pron: 'نائو اولتراپاسار او تِمپو دِتِرمینادو',
        },
      ],
    },
    {
      headingFa: '۲. تمرین ۱ — صرف افعال در زمان حال (Presente)',
      bodyFa:
        'صورت‌سؤال: متن زیر را با صرف افعالِ داخل پرانتز در «زمان حال» کامل کنید. تمام جمله‌ها دربارهٔ ژوائو (João) و همسرش گراسیِلا (Graziela) و روزمرهٔ آن‌هاست، پس فاعلِ بیشتر افعال سوم‌شخص مفرد است. متن کاملِ پاسخ:\n\n«Após um dia de muito trabalho, João VOLTA para casa muito cansado, ENTRA em casa e DÁ um beijo carinhoso em sua esposa. BRINCA com seu cachorro e vai tomar seu banho. ASSISTE o jornal da noite e FAZ comentários sobre as notícias. Enquanto eles JANTAM, PROCURAM conversar sobre o dia de trabalho deles, SORRIEM bastante para não deixar a tristeza entrar em casa. O nome de sua esposa É Graziela e ela TEM 35 anos e eles ESTÃO casados desde jovens. Ela TRABALHA em uma casa com uma senhora empresária no ramo de festas. Todos os anos ela REÚNE seus funcionários e FAZ uma grande festa para eles.»\n\nترجمه: پس از یک روزِ پرکار، ژوائو خیلی خسته به خانه برمی‌گردد، وارد خانه می‌شود و بوسه‌ای مهربانانه به همسرش می‌دهد. با سگش بازی می‌کند و می‌رود دوش بگیرد. اخبار شب را تماشا می‌کند و دربارهٔ خبرها نظر می‌دهد. وقتی شام می‌خورند، سعی می‌کنند دربارهٔ روزِ کاری‌شان گفت‌وگو کنند و زیاد لبخند می‌زنند تا نگذارند غم وارد خانه شود. نامِ همسرش گراسیِلاست و او ۳۵ سال دارد و آن‌ها از جوانی ازدواج کرده‌اند. او در خانه‌ای نزد بانویی کارآفرین در حوزهٔ برگزاری جشن کار می‌کند. هر سال او کارکنانش را گرد هم می‌آورد و جشن بزرگی برایشان برپا می‌کند.',
      examples: [
        {
          pt: 'João volta para casa muito cansado.',
          fa: 'ژوائو خیلی خسته به خانه برمی‌گردد.',
          pron: 'ژوائو وُلتا پارا کازا',
          note: 'voltar (باقاعده -ar): ele/ela → volta.',
        },
        {
          pt: 'Ele entra em casa e dá um beijo na esposa.',
          fa: 'وارد خانه می‌شود و همسرش را می‌بوسد.',
          pron: 'اِلی اِنترا اِین کازا اِ دا اوم بِیژو',
          note: 'dar بی‌قاعده است: ele → dá (با accent).',
        },
        {
          pt: 'Ele assiste o jornal e faz comentários.',
          fa: 'اخبار را تماشا می‌کند و نظر می‌دهد.',
          pron: 'اِلی آسیستی او ژورنال اِ فَس',
          note: 'assistir (-ir): ele → assiste؛ fazer بی‌قاعده: ele → faz.',
        },
        {
          pt: 'Enquanto eles jantam, sorriem bastante.',
          fa: 'وقتی شام می‌خورند، زیاد لبخند می‌زنند.',
          pron: 'اِنکوانتو اِلِس ژانتام، سُرییِم',
          note: 'sorrir بی‌قاعده: eles → sorriem.',
        },
        {
          pt: 'Ela tem 35 anos e eles estão casados.',
          fa: 'او ۳۵ سال دارد و آن‌ها متأهل‌اند.',
          pron: 'اِلا تِین ترینتا اِ سینکو آنوس',
          note: 'ter: ela → tem؛ estar: eles → estão. برای سن از ter استفاده می‌شود.',
        },
        {
          pt: 'Todos os anos ela reúne seus funcionários.',
          fa: 'هر سال کارکنانش را گرد هم می‌آورد.',
          pron: 'تودوس اوس آنوس اِلا رِئونی',
          note: 'reunir: ela → reúne.',
        },
      ],
    },
    {
      headingFa: '۳. تمرین ۲ — تکمیل جمله با فعلِ دلخواه',
      bodyFa:
        'صورت‌سؤال: جمله‌ها را با یک فعلِ دلخواه (به‌شکلِ درستِ صرف‌شده) کامل کنید. در اینجا پاسخ یکتا نیست؛ مهم آن است که فعل با فاعل تطابق داشته باشد و جمله معنا بدهد. نمونهٔ پاسخ‌های درست:\n\n1. Nós CONVIDAMOS nossos amigos para um jantar. (ما دوستانمان را برای شام دعوت می‌کنیم.)\n2. Meus irmãos JOGAM futebol juntos. (برادرانم با هم فوتبال بازی می‌کنند.)\n3. Elas VIAJAM durante as férias. (آن‌ها در تعطیلات سفر می‌کنند.)\n4. O que você FAZ sábado à noite? (شنبه‌شب چه کار می‌کنی؟)\n5. Não sei se a gasolina É suficiente para toda a viagem. (نمی‌دانم بنزین برای کلِ سفر کافی است یا نه.)',
      examples: [
        {
          pt: 'Nós convidamos nossos amigos para um jantar.',
          fa: 'ما دوستانمان را برای شام دعوت می‌کنیم.',
          pron: 'نُس کُنویدامُس نُسوس آمیگوس',
          note: 'فعل با «Nós» باید به -amos ختم شود.',
        },
        {
          pt: 'Meus irmãos jogam futebol juntos.',
          fa: 'برادرانم با هم فوتبال بازی می‌کنند.',
          pron: 'مِئوس ایرمائوس ژُگام فوتِبول ژونتوس',
          note: 'فاعل جمع (irmãos) → فعل سوم‌شخص جمع (jogam).',
        },
        {
          pt: 'O que você faz sábado à noite?',
          fa: 'شنبه‌شب چه کار می‌کنی؟',
          pron: 'او کی وُسه فَس سابادو آ نُیتی',
        },
      ],
    },
    {
      headingFa: '۴. تمرین ۳ — گذشتهٔ کامل (Pretérito Perfeito)',
      bodyFa:
        'صورت‌سؤال: متن زیر را با افعال در «گذشتهٔ کامل» (Pretérito Perfeito = گذشتهٔ سادهٔ روایی) کامل کنید. داستان دربارهٔ سفرِ رافائلا (Rafaella) به اروپاست. متن کاملِ پاسخ:\n\n«No ano passado, Rafaella REALIZOU o grande sonho da vida dela, VIAJOU para a Europa. CONHECEU a torre Eiffel e o arco do triunfo. VISITOU também o museu do Louvre. Depois da França, PEGOU um voo até Londres e se ENCONTROU com sua amiga Julianna. À noite, as duas SAÍRAM para jantar em um restaurante e não PAGARAM muito caro na refeição. Elas VOLTARAM para a casa após a janta e COLOCARAM um filme para assistir. Na manhã seguinte, Rafaella ACORDOU cedo para andar e ACABOU se apaixonando pela cidade.»\n\nترجمه: سال گذشته، رافائلا بزرگ‌ترین آرزوی زندگی‌اش را برآورده کرد و به اروپا سفر کرد. برجِ ایفل و طاق نصرت را دید. موزهٔ لوور را هم بازدید کرد. پس از فرانسه، پروازی به لندن گرفت و با دوستش جولیانا دیدار کرد. شب، آن دو برای شام به رستورانی رفتند و بابت غذا خیلی گران نپرداختند. پس از شام به خانه برگشتند و فیلمی گذاشتند تا تماشا کنند. صبح روز بعد، رافائلا زود بیدار شد تا قدم بزند و کارش به عاشق‌شدنِ آن شهر کشید.',
      examples: [
        {
          pt: 'Rafaella realizou o grande sonho e viajou para a Europa.',
          fa: 'رافائلا آرزوی بزرگش را برآورده کرد و به اروپا سفر کرد.',
          pron: 'رافائلا رِآلیزُ ... ویاژُ',
          note: 'افعال -ar در گذشته سوم‌شخص مفرد → -ou: realizou, viajou.',
        },
        {
          pt: 'Conheceu a torre Eiffel e visitou o museu do Louvre.',
          fa: 'برج ایفل را دید و موزهٔ لوور را بازدید کرد.',
          pron: 'کُنیِسِئو ... ویزیتُ',
          note: 'conhecer (-er) → conheceu.',
        },
        {
          pt: 'As duas saíram para jantar e não pagaram caro.',
          fa: 'آن دو برای شام بیرون رفتند و گران نپرداختند.',
          pron: 'اَس دوآس سائیرام ... نائو پاگارام',
          note: 'فاعل جمع (as duas) → سوم‌شخص جمع: saíram, pagaram.',
        },
        {
          pt: 'Rafaella acordou cedo e acabou se apaixonando pela cidade.',
          fa: 'رافائلا زود بیدار شد و کارش به عاشق آن شهر شدن کشید.',
          pron: 'آکُردُ سِدو ... آکابُ',
        },
      ],
    },
    {
      headingFa: '۵. تمرین ۴ — تبدیل جمله به آینده (Futuro)',
      bodyFa:
        'صورت‌سؤال: جمله‌های زیر را به «زمان آینده» تبدیل کنید. آیندهٔ ساده در پرتغالی معمولاً با افزودنِ پایانه به مصدر ساخته می‌شود (falarei, comprará …) یا به‌شکلِ رایج‌ترِ گفتاری با «ir + مصدر» (vou falar). پاسخ‌ها:\n\nA) Estamos correndo no parque → CORREREMOS no parque. / VAMOS CORRER no parque. (در پارک خواهیم دوید.)\nB) Mamãe comprou um carro novo → Mamãe COMPRARÁ um carro novo. (مامان ماشین نو خواهد خرید.)\nC) Busquei meu irmão no aeroporto → BUSCAREI meu irmão no aeroporto. (برادرم را در فرودگاه خواهم آورد.)\nD) O pintor terminou de pintar a casa no domingo → O pintor TERMINARÁ de pintar a casa no domingo. (نقاش یکشنبه کارِ نقاشیِ خانه را تمام خواهد کرد.)\nE) O papa rezou a missa do galo no Natal → O papa REZARÁ a missa do galo no Natal. (پاپ در کریسمس عشای نیمه‌شب را خواهد خواند.)\nF) Meu irmão chegou domingo da Europa → Meu irmão CHEGARÁ domingo da Europa. (برادرم یکشنبه از اروپا خواهد رسید.)',
      examples: [
        {
          pt: 'Mamãe comprará um carro novo.',
          fa: 'مامان ماشین نو خواهد خرید.',
          pron: 'مامای کُمپرارا اوم کارو نُوو',
          note: 'comprar → ela comprará (آیندهٔ ساده).',
        },
        {
          pt: 'Buscarei meu irmão no aeroporto.',
          fa: 'برادرم را از فرودگاه خواهم آورد.',
          pron: 'بوسکارِی مِئو ایرمائو نو آئِروپُرتو',
          note: 'buscar → eu buscarei.',
        },
        {
          pt: 'Meu irmão chegará domingo da Europa.',
          fa: 'برادرم یکشنبه از اروپا خواهد رسید.',
          pron: 'مِئو ایرمائو شِگارا دُمینگو',
          note: 'chegar → ele chegará.',
        },
      ],
    },
    {
      headingFa: '۶. تمرین ۵ — صرف همزمان در گذشته و آینده',
      bodyFa:
        'صورت‌سؤال: افعالِ زمان حال (ستون وسط) را در «گذشتهٔ کامل» و «آینده» صرف کنید. همهٔ افعال اول‌شخص مفرد (eu) هستند. جدولِ کاملِ پاسخ:\n\nPRETÉRITO PERFEITO | PRESENTE | FUTURO\nFalei              | Falo     | Falarei\nPensei             | Penso    | Pensarei\nGostei             | Gosto    | Gostarei\nCheguei            | Chego    | Chegarei\nBebi               | Bebo     | Beberei\n\nنکته: فعل chegar در گذشته «cheguei» می‌شود (افزودنِ u برای حفظِ صدای «گ» پیش از e). فعل beber چون -er است در گذشته «bebi» و در آینده «beberei» می‌شود.',
      examples: [
        {
          pt: 'Falo → Falei → Falarei',
          fa: 'حرف می‌زنم ← حرف زدم ← حرف خواهم زد',
          pron: 'فالو ← فالِی ← فالارِی',
        },
        {
          pt: 'Chego → Cheguei → Chegarei',
          fa: 'می‌رسم ← رسیدم ← خواهم رسید',
          pron: 'شِگو ← شِگِی ← شِگارِی',
          note: 'در گذشته «u» اضافه می‌شود (cheguei) تا صدای «گ» حفظ شود.',
        },
        {
          pt: 'Penso → Pensei → Pensarei',
          fa: 'فکر می‌کنم ← فکر کردم ← فکر خواهم کرد',
          pron: 'پِنسو ← پِنسِی ← پِنسارِی',
          note: 'pensar باقاعدهٔ -ar است.',
        },
        {
          pt: 'Gosto → Gostei → Gostarei',
          fa: 'دوست دارم ← دوست داشتم ← دوست خواهم داشت',
          pron: 'گُستو ← گُستِی ← گُستارِی',
          note: 'gostar باقاعدهٔ -ar است.',
        },
        {
          pt: 'Bebo → Bebi → Beberei',
          fa: 'می‌نوشم ← نوشیدم ← خواهم نوشید',
          pron: 'بِبو ← بِبی ← بِبِرِی',
          note: 'beber از گروه -er است، پس الگوی صرفش با -ar فرق دارد.',
        },
      ],
    },
    {
      headingFa: '۷. تمرین ۶ — پیدا کردنِ افعال درون جمله',
      bodyFa:
        'صورت‌سؤال: افعالِ به‌کاررفته در جمله‌های زیر را مشخص کنید. توجه کنید که یک جمله می‌تواند بیش از یک فعل داشته باشد (فعلِ اصلی + مصدر). پاسخ‌ها:\n\na) Minha mãe COZINHARÁ feijoada. → cozinhará (آینده)\nb) FUI VISITAR minha vó e logo VOLTEI. → fui, visitar, voltei\nc) ANDAREI de bicicleta no domingo. → andarei (آینده)\nd) SENTI muita dor no joelho ao JOGAR futebol. → senti, jogar\ne) Não ESPERAREI o ônibus. → esperarei (آینده)\nf) OLHEI a hora no relógio. → olhei (گذشته)',
      examples: [
        {
          pt: 'Minha mãe cozinhará feijoada.',
          fa: 'مادرم فِیژوآدا خواهد پخت.',
          pron: 'مینیا مای کُزینیارا فِیژوآدا',
          note: 'فعل: cozinhará (آیندهٔ فعل cozinhar).',
        },
        {
          pt: 'Fui visitar minha vó e logo voltei.',
          fa: 'رفتم به دیدنِ مادربزرگم و زود برگشتم.',
          pron: 'فویی ویزیتار مینیا وُ اِ لُگو وُلتِی',
          note: 'سه فعل: fui، visitar (مصدر)، voltei.',
        },
        {
          pt: 'Senti muita dor no joelho ao jogar futebol.',
          fa: 'هنگام فوتبال‌بازی درد شدیدی در زانو حس کردم.',
          pron: 'سِنتی مویتا دُر نو ژوئِلیو آئو ژُگار',
          note: 'دو فعل: senti (گذشته)، jogar (مصدر).',
        },
      ],
    },
    {
      headingFa: '۸. تمرین ۷ — تطابق فعل و اسم (Concordância Verbal e Nominal)',
      bodyFa:
        'صورت‌سؤال: تطابقِ فعل با فاعل و تطابقِ اسم/صفت را در جمله‌های زیر درست کنید. خطای رایج این است که فعل با فاعل هماهنگ نیست. پاسخ‌های اصلاح‌شده:\n\n1. «Nós quer ir para festa» → Nós QUEREMOS ir para A festa. (ما می‌خواهیم به جشن برویم.)\n2. «A gente precisamos sair mais cedo» → A gente PRECISA sair mais cedo. («a gente» سوم‌شخص مفرد است.)\n3. «Ele queremos buscar a máquina» → Ele QUER buscar a máquina. (او می‌خواهد ماشین را بیاورد.)\n4. «Elas busca seu filhos na escola» → Elas BUSCAM SEUS filhos na escola. (آن‌ها فرزندانشان را از مدرسه می‌آورند.)\n5. «Nós não pagou a conta» → Nós não PAGAMOS a conta. (ما صورت‌حساب را نپرداختیم.)\n\nنکتهٔ مهم برای فارسی‌زبانان: «a gente» با اینکه معنای «ما» می‌دهد، فعلش سوم‌شخص مفرد است (a gente precisa)، نه اول‌شخص جمع (a gente precisamos ✗).',
      examples: [
        {
          pt: 'Nós queremos ir para a festa.',
          fa: 'ما می‌خواهیم به جشن برویم.',
          pron: 'نُس کِرِموس ایر پارا آ فِستا',
          note: 'Nós → queremos (اول‌شخص جمع). «para a festa» با حرف تعریف.',
        },
        {
          pt: 'A gente precisa sair mais cedo.',
          fa: 'ما باید زودتر برویم.',
          pron: 'آ جِنتی پرِسیزا سائیر مایس سِدو',
          note: '«a gente» با فعل سوم‌شخص مفرد می‌آید (precisa)، نه precisamos.',
        },
        {
          pt: 'Elas buscam seus filhos na escola.',
          fa: 'آن‌ها فرزندانشان را از مدرسه می‌آورند.',
          pron: 'اِلاس بوسکام سِئوس فیلیوس نا اِسکولا',
          note: 'هم فعل (buscam) و هم صفت ملکی/اسم (seus filhos) باید جمع باشند.',
        },
      ],
    },
    {
      headingFa: '۹. تمرین ۸ — انتخاب زمانِ درست بر اساس قیدِ زمان',
      bodyFa:
        'صورت‌سؤال: جمله‌ها را با فعلِ داخل پرانتز، در صرفِ درست، کامل کنید. کلید حل، قیدِ زمانِ هر جمله است (semana passada = گذشته، amanhã = آینده، …). پاسخ‌ها:\n\n1. Semana passada eu JANTEI nesse restaurante. (jantar → گذشته) — هفتهٔ پیش در این رستوران شام خوردم.\n2. Mais tarde ele ENCONTRARÁ a namorada. (encontrar → آینده) — بعداً او نامزدش را خواهد دید.\n3. O jogo de ontem ESTAVA bem difícil. (estar → گذشته) — بازیِ دیروز خیلی سخت بود.\n4. Amanhã, não ESTAREI em casa. (estar → آینده) — فردا خانه نخواهم بود.\n5. Mês que vem COMPRAREI aquela calça jeans. (comprar → آینده) — ماهِ آینده آن شلوار جین را خواهم خرید.\n6. Me perdoe, mas não QUERO fazer isso. (querer → حال) — ببخشید، اما نمی‌خواهم این کار را بکنم.\n7. No mês passado, os alunos ESTUDARAM geografia. (estudar → گذشته) — ماهِ گذشته دانش‌آموزان جغرافیا خواندند.',
      examples: [
        {
          pt: 'Semana passada eu jantei nesse restaurante.',
          fa: 'هفتهٔ پیش در این رستوران شام خوردم.',
          pron: 'سِمانا پاسادا اِئو ژانتِی',
          note: '«semana passada» → گذشته (jantei).',
        },
        {
          pt: 'Amanhã, não estarei em casa.',
          fa: 'فردا خانه نخواهم بود.',
          pron: 'آمانیا، نائو اِستارِی اِین کازا',
          note: '«amanhã» → آینده (estarei).',
        },
        {
          pt: 'Mês que vem comprarei aquela calça jeans.',
          fa: 'ماهِ آینده آن شلوار جین را خواهم خرید.',
          pron: 'مِس کی وِین کُمپرارِی',
          note: '«mês que vem» = ماهِ آینده → آینده (comprarei).',
        },
      ],
    },
    {
      headingFa: '۱۰. تمرین ۹ — درک مطلب (Interpretação de Texto)',
      bodyFa:
        'متن را بخوانید و به پرسش‌ها پاسخ دهید.\n\nمتن: «Cristina é uma catadora de material reciclável em uma pequena cidade no interior de São Paulo. Com seu trabalho, ela consegue pagar seu curso de cabeleireira e ajudar nas despesas da casa. Cristina tem 32 anos, é casada com Júnior, que é motorista de ônibus. Eles são casados há 5 anos e pensam em breve fazer uma viagem para conhecer o nordeste do Brasil. O casal sonha que em aproximadamente dois anos poderão ter seu primeiro filho.»\n\nترجمه: کریستینا در شهرِ کوچکی در حومهٔ سائوپائولو جمع‌آورندهٔ موادِ بازیافتی است. با کارش می‌تواند شهریهٔ کلاسِ آرایشگری‌اش را بپردازد و در هزینه‌های خانه کمک کند. کریستینا ۳۲ سال دارد و با ژونیور که رانندهٔ اتوبوس است ازدواج کرده. آن‌ها ۵ سال است که ازدواج کرده‌اند و به‌زودی فکر سفری برای دیدنِ شمال‌شرقِ برزیل دارند. این زوج آرزو دارند تقریباً دو سال دیگر بتوانند اولین فرزندشان را داشته باشند.\n\nپاسخِ پرسش‌ها:\n1) Quem é Cristina? → É uma catadora de material reciclável no interior de São Paulo; tem 32 anos e é casada. (کریستینا کیست؟ جمع‌آورندهٔ موادِ بازیافتی در حومهٔ سائوپائولو، ۳۲ ساله و متأهل.)\n2) Quem é seu esposo e para onde pretendem viajar? → Seu esposo é Júnior, motorista de ônibus; pretendem viajar para o nordeste do Brasil. (همسرش ژونیور، رانندهٔ اتوبوس؛ می‌خواهند به شمال‌شرقِ برزیل سفر کنند.)\n3) Qual o sonho do casal? → Ter o primeiro filho em aproximadamente dois anos. (رؤیای زوج: داشتنِ اولین فرزند در حدودِ دو سال دیگر.)',
      examples: [
        {
          pt: 'Cristina é catadora de material reciclável.',
          fa: 'کریستینا جمع‌آورندهٔ موادِ بازیافتی است.',
          pron: 'کریستینا اِ کاتادورا جی ماتِریال رِسیکلاوِل',
        },
        {
          pt: 'Seu esposo é Júnior, motorista de ônibus.',
          fa: 'همسرش ژونیور، رانندهٔ اتوبوس است.',
          pron: 'سِئو اِسپوزو اِ ژونیور، مُتوریستا جی اُنیبوس',
        },
        {
          pt: 'O casal sonha em ter o primeiro filho em dois anos.',
          fa: 'زوج آرزو دارند دو سال دیگر اولین فرزندشان را داشته باشند.',
          pron: 'او کازال سُنیا اِین تِر او پریمِیرو فیلیو',
        },
      ],
    },
    {
      headingFa: '۱۱. انشا (Redação)',
      bodyFa:
        'بخش آخرِ آزمون یک انشا (Redação) است. قوانین آن:\n\n• انشا باید دست‌کم ۲۰ خط داشته باشد (no mínimo 20 linhas).\n• باید با موضوعِ داده‌شده (TEMA) مطابقت داشته باشد (estar de acordo com o tema).\n• باید با خودکار مشکی یا آبی نوشته شود (escrever com caneta preta ou azul).\n\nنکته برای زبان‌آموز: در انشا، زمان‌ها و تطابق فعل‌ها (که در تمرین‌های ۱ تا ۸ کار کردید) را رعایت کنید، جمله‌ها را با نقطه و ویرگولِ درست بنویسید و از موضوع خارج نشوید.',
      examples: [
        {
          pt: 'A redação deve conter no mínimo 20 linhas.',
          fa: 'انشا باید دست‌کم ۲۰ خط داشته باشد.',
          pron: 'آ رِداسائو دِوی کُنتِر نو مینیمو وینتی لینیاس',
        },
        {
          pt: 'Precisa estar de acordo com o tema.',
          fa: 'باید با موضوع مطابقت داشته باشد.',
          pron: 'پرِسیزا اِستار جی آکُردو کُن او تِما',
        },
      ],
    },
  ],
  keyPointsFa: [
    'زمان حال (Presente): افعال باقاعده الگوهای -a/-e (سوم‌شخص) دارند؛ اما dar→dá, fazer→faz, ter→tem, ser→é, estar→estão بی‌قاعده‌اند.',
    'گذشتهٔ کامل (Pretérito Perfeito): -ar → -ou (viajou)، جمع → -aram (pagaram)؛ -er/-ir الگوی دیگری دارند (conheceu, saíram, bebi).',
    'آینده (Futuro): مصدر + پایانه (comprarei, chegará) یا شکلِ گفتاریِ «ir + مصدر» (vou comprar).',
    'chegar در گذشته «cheguei» می‌شود (افزودنِ u برای حفظِ صدای گ).',
    'تطابق فعل با فاعل الزامی است: Nós → -mos، Ele → مفرد، Elas → جمع.',
    '«a gente» معنای «ما» می‌دهد اما فعلش سوم‌شخص مفرد است (a gente precisa، نه precisamos).',
    'قید زمان زمانِ فعل را تعیین می‌کند: semana passada/ontem/mês passado → گذشته؛ amanhã/mês que vem → آینده.',
    'در درک مطلب پاسخ را از خودِ متن استخراج کنید و در انشا از موضوع خارج نشوید و دست‌کم ۲۰ خط بنویسید.',
  ],
  quiz: [
    {
      id: 'course-aula-10-q1',
      type: 'fill-blank',
      prompt: 'Presente: Após um dia de trabalho, João ____ (voltar) para casa.',
      promptFa: 'فعل voltar را در زمان حال برای «João» صرف کنید.',
      options: [],
      answer: 'volta',
      explanationFa: 'voltar فعلِ باقاعدهٔ -ar است؛ سوم‌شخص مفرد → volta.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q2',
      type: 'fill-blank',
      prompt: 'Presente: Ele entra em casa e ____ (dar) um beijo na esposa.',
      promptFa: 'فعل dar را در زمان حال برای «ele» صرف کنید.',
      options: [],
      answer: 'dá',
      explanationFa: 'dar بی‌قاعده است؛ سوم‌شخص مفرد → dá.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q3',
      type: 'mcq',
      prompt: 'Presente: Ele ____ o jornal da noite e ____ comentários.',
      promptFa: 'کدام گزینه assistir و fazer را درست در زمان حال صرف کرده است؟',
      options: [
        'assiste / faz',
        'assisti / fez',
        'assistir / fazer',
        'assiste / faço',
      ],
      answer: 'assiste / faz',
      explanationFa: 'assistir (-ir) → assiste؛ fazer بی‌قاعده → faz.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q4',
      type: 'fill-blank',
      prompt: 'Presente: Enquanto eles ____ (jantar), ____ (sorrir) bastante.',
      promptFa: 'دو فعل jantar و sorrir را در زمان حال برای «eles» صرف کنید.',
      options: [],
      answer: 'jantam / sorriem',
      explanationFa: 'سوم‌شخص جمع: jantar → jantam؛ sorrir (بی‌قاعده) → sorriem.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q5',
      type: 'fill-blank',
      prompt: 'Presente: O nome da esposa ____ (ser) Graziela e ela ____ (ter) 35 anos.',
      promptFa: 'افعال ser و ter را در زمان حال صرف کنید.',
      options: [],
      answer: 'é / tem',
      explanationFa: 'ser → é؛ ter → tem. برای سن همیشه از ter استفاده می‌شود.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q6',
      type: 'mcq',
      prompt: 'Presente: Eles ____ casados desde jovens.',
      promptFa: 'کدام صرفِ estar برای «eles» درست است؟',
      options: ['estão', 'está', 'estamos', 'estou'],
      answer: 'estão',
      explanationFa: 'estar سوم‌شخص جمع → estão.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q7',
      type: 'fill-blank',
      prompt: 'Presente: Todos os anos ela ____ (reunir) seus funcionários.',
      promptFa: 'فعل reunir را در زمان حال برای «ela» صرف کنید.',
      options: [],
      answer: 'reúne',
      explanationFa: 'reunir سوم‌شخص مفرد → reúne (با accent روی u).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q8',
      type: 'fill-blank',
      prompt: 'Complete com um verbo: Meus irmãos ____ futebol juntos.',
      promptFa: 'با یک فعلِ دلخواهِ درست‌صرف‌شده کامل کنید (فاعل جمع).',
      options: [],
      answer: 'jogam',
      explanationFa: 'فاعل «meus irmãos» جمع است؛ فعل باید سوم‌شخص جمع باشد، مثل jogam.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q9',
      type: 'fill-blank',
      prompt: 'Complete com um verbo: Nós ____ nossos amigos para um jantar.',
      promptFa: 'با فعلِ دلخواهِ درست‌صرف‌شده برای «Nós» کامل کنید.',
      options: [],
      answer: 'convidamos',
      explanationFa: 'فاعل Nós → پایانهٔ -amos؛ مثلاً convidamos (دعوت می‌کنیم).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q10',
      type: 'fill-blank',
      prompt: 'Pretérito Perfeito: No ano passado, Rafaella ____ (realizar) um sonho e ____ (viajar) para a Europa.',
      promptFa: 'افعال realizar و viajar را در گذشتهٔ کامل صرف کنید.',
      options: [],
      answer: 'realizou / viajou',
      explanationFa: 'افعال -ar در گذشتهٔ کامل سوم‌شخص مفرد → -ou: realizou, viajou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q11',
      type: 'mcq',
      prompt: 'Pretérito Perfeito: Ela ____ a torre Eiffel e ____ o museu do Louvre.',
      promptFa: 'کدام گزینه conhecer و visitar را درست در گذشته صرف کرده است؟',
      options: [
        'conheceu / visitou',
        'conhece / visita',
        'conheceu / visita',
        'conhecerá / visitará',
      ],
      answer: 'conheceu / visitou',
      explanationFa: 'conhecer (-er) → conheceu؛ visitar (-ar) → visitou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q12',
      type: 'fill-blank',
      prompt: 'Pretérito Perfeito: À noite, as duas ____ (sair) para jantar e não ____ (pagar) caro.',
      promptFa: 'افعال sair و pagar را در گذشته برای فاعلِ جمع صرف کنید.',
      options: [],
      answer: 'saíram / pagaram',
      explanationFa: 'فاعل «as duas» جمع است: sair → saíram؛ pagar → pagaram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q13',
      type: 'fill-blank',
      prompt: 'Pretérito Perfeito: Na manhã seguinte, Rafaella ____ (acordar) cedo e ____ (acabar) se apaixonando.',
      promptFa: 'افعال acordar و acabar را در گذشته برای «Rafaella» صرف کنید.',
      options: [],
      answer: 'acordou / acabou',
      explanationFa: 'هر دو -ar و سوم‌شخص مفرد → acordou, acabou.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q14',
      type: 'translate-pt-fa',
      prompt: 'Passe para o Futuro: "Mamãe comprou um carro novo."',
      promptFa: 'این جمله را به آینده تبدیل کنید (به پرتغالی بنویسید).',
      options: [],
      answer: 'Mamãe comprará um carro novo.',
      explanationFa: 'comprar در آیندهٔ ساده سوم‌شخص مفرد → comprará.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q15',
      type: 'translate-pt-fa',
      prompt: 'Passe para o Futuro: "Busquei meu irmão no aeroporto."',
      promptFa: 'این جمله را به آینده تبدیل کنید (به پرتغالی بنویسید).',
      options: [],
      answer: 'Buscarei meu irmão no aeroporto.',
      explanationFa: 'buscar در آیندهٔ ساده اول‌شخص مفرد → buscarei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q16',
      type: 'translate-pt-fa',
      prompt: 'Passe para o Futuro: "Meu irmão chegou domingo da Europa."',
      promptFa: 'این جمله را به آینده تبدیل کنید (به پرتغالی بنویسید).',
      options: [],
      answer: 'Meu irmão chegará domingo da Europa.',
      explanationFa: 'chegar در آیندهٔ ساده سوم‌شخص مفرد → chegará.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q17',
      type: 'fill-blank',
      prompt: 'Conjugue no Passado e no Futuro (eu): Falo → ____ / ____.',
      promptFa: 'فعل falar را در گذشته و آینده (اول‌شخص) صرف کنید.',
      options: [],
      answer: 'falei / falarei',
      explanationFa: 'falar: گذشته → falei؛ آینده → falarei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q18',
      type: 'fill-blank',
      prompt: 'Conjugue no Passado e no Futuro (eu): Chego → ____ / ____.',
      promptFa: 'فعل chegar را در گذشته و آینده (اول‌شخص) صرف کنید.',
      options: [],
      answer: 'cheguei / chegarei',
      explanationFa: 'در گذشته «u» اضافه می‌شود تا صدای گ حفظ شود: cheguei؛ آینده → chegarei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q19',
      type: 'fill-blank',
      prompt: 'Conjugue no Passado e no Futuro (eu): Bebo → ____ / ____.',
      promptFa: 'فعل beber را در گذشته و آینده (اول‌شخص) صرف کنید.',
      options: [],
      answer: 'bebi / beberei',
      explanationFa: 'beber از گروه -er است: گذشته → bebi؛ آینده → beberei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q20',
      type: 'mcq',
      prompt: 'Localize o verbo: "Andarei de bicicleta no domingo."',
      promptFa: 'فعلِ این جمله کدام است و در چه زمانی است؟',
      options: [
        'Andarei (Futuro)',
        'bicicleta (substantivo)',
        'domingo (advérbio)',
        'de (preposição)',
      ],
      answer: 'Andarei (Futuro)',
      explanationFa: 'فعل جمله «Andarei» است که آیندهٔ فعل andar می‌باشد.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q21',
      type: 'mcq',
      prompt: 'Quantos verbos há em: "Fui visitar minha vó e logo voltei."?',
      promptFa: 'در این جمله چند فعل وجود دارد؟',
      options: [
        'Três: fui, visitar, voltei',
        'Um: voltei',
        'Dois: fui, voltei',
        'Nenhum',
      ],
      answer: 'Três: fui, visitar, voltei',
      explanationFa: 'سه فعل: fui و voltei (صرف‌شده) و visitar (مصدر).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q22',
      type: 'translate-pt-fa',
      prompt: 'Corrija a concordância: "Nós quer ir para festa."',
      promptFa: 'تطابق فعل و اسم را درست کنید (به پرتغالی بنویسید).',
      options: [],
      answer: 'Nós queremos ir para a festa.',
      explanationFa: 'Nós → queremos؛ و «para a festa» با حرف تعریف درست است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q23',
      type: 'mcq',
      prompt: 'Corrija: "A gente precisamos sair mais cedo."',
      promptFa: 'شکلِ درستِ فعل برای «a gente» کدام است؟',
      options: [
        'A gente precisa sair mais cedo.',
        'A gente precisamos sair mais cedo.',
        'A gente precisam sair mais cedo.',
        'A gente preciso sair mais cedo.',
      ],
      answer: 'A gente precisa sair mais cedo.',
      explanationFa: '«a gente» با فعل سوم‌شخص مفرد می‌آید → precisa، نه precisamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q24',
      type: 'translate-pt-fa',
      prompt: 'Corrija a concordância: "Elas busca seu filhos na escola."',
      promptFa: 'تطابق فعل و اسم را درست کنید (به پرتغالی بنویسید).',
      options: [],
      answer: 'Elas buscam seus filhos na escola.',
      explanationFa: 'Elas → buscam؛ و «seus filhos» (صفت ملکی و اسم هر دو جمع).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q25',
      type: 'fill-blank',
      prompt: 'Corrija: "Nós não pagou a conta." → Nós não ____ a conta.',
      promptFa: 'فعل pagar را برای «Nós» در گذشته درست کنید.',
      options: [],
      answer: 'pagamos',
      explanationFa: 'Nós در گذشتهٔ فعل pagar → pagamos.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q26',
      type: 'fill-blank',
      prompt: 'Semana passada eu ____ (jantar) nesse restaurante.',
      promptFa: 'با توجه به «semana passada» فعل jantar را صرف کنید.',
      options: [],
      answer: 'jantei',
      explanationFa: '«semana passada» = گذشته → jantei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q27',
      type: 'fill-blank',
      prompt: 'Mais tarde ele ____ (encontrar) a namorada.',
      promptFa: 'با توجه به «mais tarde» فعل encontrar را صرف کنید.',
      options: [],
      answer: 'encontrará',
      explanationFa: '«mais tarde» به آینده اشاره دارد → encontrará (یا vai encontrar).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q28',
      type: 'mcq',
      prompt: 'O jogo de ontem ____ bem difícil. (estar)',
      promptFa: 'با توجه به «ontem» کدام صرفِ estar درست است؟',
      options: ['estava', 'estará', 'está', 'estou'],
      answer: 'estava',
      explanationFa: '«ontem» = دیروز → گذشته؛ estar در توصیفِ گذشته → estava (یا esteve).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q29',
      type: 'fill-blank',
      prompt: 'Amanhã, não ____ (estar) em casa.',
      promptFa: 'با توجه به «amanhã» فعل estar را صرف کنید.',
      options: [],
      answer: 'estarei',
      explanationFa: '«amanhã» = فردا → آینده → estarei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q30',
      type: 'fill-blank',
      prompt: 'Mês que vem ____ (comprar) aquela calça jeans.',
      promptFa: 'با توجه به «mês que vem» فعل comprar را صرف کنید.',
      options: [],
      answer: 'comprarei',
      explanationFa: '«mês que vem» = ماهِ آینده → آینده → comprarei.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q31',
      type: 'fill-blank',
      prompt: 'Me perdoe, mas não ____ (querer) fazer isso.',
      promptFa: 'فعل querer را در زمانِ درست (حالِ کنونی) صرف کنید.',
      options: [],
      answer: 'quero',
      explanationFa: 'اشاره به تمایلِ همین حالا → زمان حال، اول‌شخص → quero.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q32',
      type: 'fill-blank',
      prompt: 'No mês passado, os alunos ____ (estudar) geografia.',
      promptFa: 'با توجه به «no mês passado» فعل estudar را برای «os alunos» صرف کنید.',
      options: [],
      answer: 'estudaram',
      explanationFa: '«mês passado» = گذشته؛ فاعل جمع → estudaram.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-10-q33',
      type: 'translate-pt-fa',
      prompt: 'Interpretação: "Quem é Cristina?" (responda em português com base no texto)',
      promptFa: 'بر اساس متن، به این پرسشِ درک مطلب پاسخ دهید.',
      options: [],
      answer: 'Cristina é uma catadora de material reciclável no interior de São Paulo; tem 32 anos e é casada.',
      explanationFa: 'پاسخ باید از خودِ متن استخراج شود: شغل، سن و وضعیت تأهل کریستینا.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q34',
      type: 'translate-pt-fa',
      prompt: 'Interpretação: "Quem é seu esposo e para onde pretendem viajar?"',
      promptFa: 'بر اساس متن، به این پرسشِ درک مطلب پاسخ دهید.',
      options: [],
      answer: 'Seu esposo é Júnior, motorista de ônibus; pretendem viajar para o nordeste do Brasil.',
      explanationFa: 'همسر = ژونیورِ رانندهٔ اتوبوس؛ مقصدِ سفر = شمال‌شرقِ برزیل.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q35',
      type: 'translate-pt-fa',
      prompt: 'Interpretação: "Qual o sonho do casal?"',
      promptFa: 'بر اساس متن، به این پرسشِ درک مطلب پاسخ دهید.',
      options: [],
      answer: 'O sonho do casal é ter o primeiro filho em aproximadamente dois anos.',
      explanationFa: 'رؤیای زوج: داشتنِ اولین فرزند در حدودِ دو سالِ دیگر.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-10-q36',
      type: 'mcq',
      prompt: 'Segundo as orientações, a redação precisa ter no mínimo:',
      promptFa: 'طبق دستورالعمل‌ها، انشا دست‌کم چند خط باید داشته باشد؟',
      options: ['20 linhas', '10 linhas', '5 linhas', '40 linhas'],
      answer: '20 linhas',
      explanationFa: 'قانونِ سوم آزمون: انشا باید دست‌کم ۲۰ خط باشد.',
      cefr: 'A2',
      skill: 'reading',
    },
  ],
  estimatedMinutes: 30,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 10 (کامل).',
};
