import type { CourseLesson } from '@/domain/content/schema';

export const aula15: CourseLesson = {
  id: 'course-aula-15',
  order: 15,
  aula: 'Aula 15',
  titleFa: 'زبان و ارتباط؛ وابستگی اسمی و وابستگی فعلی',
  titlePt: 'Linguagem e Comunicação; Regência Nominal e Verbal',
  cefr: 'B1',
  summaryFa:
    'این درس دو بخش دارد. بخش نخست دربارهٔ «زبان و ارتباط» است: عناصر لازم برای برقراری ارتباط (فرستنده، گیرنده، پیام، کانال و رمز)، انواع زبان (زبان کلامی و غیرکلامی)، تفاوت زبان گفتاری و نوشتاری، و عوامل تغییر زبان (منطقه‌ای، فرهنگی و بافتی) و مفهوم «گفتار» به‌عنوان کنشی فردی. بخش دوم دربارهٔ «وابستگی» (Regência) است: وابستگی اسمی یعنی رابطهٔ میان اسم‌ها/صفت‌ها/قیدها و متمم‌هایشان به کمک حرف اضافه (مثل interessado em، ansioso para)، و وابستگی فعلی یعنی رابطهٔ میان فعل‌ها و متمم‌هایشان به کمک حرف اضافه (مثل morar em، ir a/para). فهرست کامل اسم‌ها و فعل‌هایی که به حرف اضافه نیاز دارند به‌همراه مثال آورده شده و در پایان تمرین کامل کردن جمله‌ها را انجام می‌دهید.',
  objectivesFa: [
    'عناصر شش‌گانهٔ فرایند ارتباط را بشناسید و نقش هرکدام را توضیح دهید.',
    'زبان کلامی و غیرکلامی را از هم تشخیص دهید و برای هرکدام مثال بزنید.',
    'تفاوت میان زبان گفتاری و زبان نوشتاری را درک کنید.',
    'عوامل تغییر زبان (منطقه‌ای، فرهنگی، بافتی) و مفهوم «گفتار» فردی را بشناسید.',
    'مفهوم «وابستگی اسمی» (Regência Nominal) و حرف اضافهٔ درست پس از هر اسم/صفت را به‌کار ببرید.',
    'مفهوم «وابستگی فعلی» (Regência Verbal) و حرف اضافهٔ درست پس از هر فعل را به‌کار ببرید.',
    'با فهرست پرکاربردترین اسم‌ها و فعل‌هایی که به حرف اضافه نیاز دارند آشنا شوید.',
  ],
  sections: [
    {
      headingFa: '۱. زبان و ارتباط ـ عناصر لازم برای ارتباط',
      bodyFa:
        'برای اینکه ارتباط (comunicação) شکل بگیرد، عناصر زیر لازم‌اند:\n\nا) فرستنده (emissor / destinador / remetente): شخص یا گروهی که پیام را تولید می‌کند.\nب) گیرنده (receptor / destinatário): شخص یا گروهی که پیام را دریافت می‌کند.\nج) خودِ پیام (a mensagem): که حاوی اطلاعاتِ منتقل‌شده است.\nد) کانال ارتباط یا تماس (o canal de comunicação / de contato): وسیله‌ای که برای انتقال پیام به‌کار می‌رود.\nه) رمز/کد (o código): در پیام نوشتاری یا گفتاری، رمز همان «زبان» است. علاوه بر زبان، رمزهای دیگری هم می‌توان به‌کار برد، مانند رنگ‌ها، حرکت‌ها (اشاره‌ها)، شکل‌ها و علائم.\n\nبرای اینکه ارتباط با کارایی برقرار شود، فرستنده و گیرنده باید از یک رمزِ یکسان استفاده کنند.',
      examples: [
        {
          pt: 'O emissor produz a mensagem.',
          fa: 'فرستنده پیام را تولید می‌کند.',
          pron: 'او اِمیسور پرودوز آ مِنساژِن',
        },
        {
          pt: 'O receptor recebe a mensagem.',
          fa: 'گیرنده پیام را دریافت می‌کند.',
          pron: 'او رِسِپتور رِسِبی آ مِنساژِن',
        },
        {
          pt: 'O emissor e o receptor devem utilizar o mesmo código.',
          fa: 'فرستنده و گیرنده باید از یک رمز یکسان استفاده کنند.',
          pron: 'او اِمیسور ای او رِسِپتور دِوِن اوتیلیزار او مِزمو کُدیگو',
          note: 'اگر رمز مشترک نباشد ارتباط برقرار نمی‌شود.',
        },
      ],
    },
    {
      headingFa: '۲. زبان (Linguagem) ـ کلامی و غیرکلامی',
      bodyFa:
        'زبان (linguagem) فرایندی برای ارتباط و بیان است که در انتقال پیام میان طرف‌های گفت‌وگو (interlocutores) به‌کار می‌رود. زبان در موقعیت‌های گوناگون حضور دارد و برای بیان احساسات، دستورها، خواسته‌ها، اعلام نظرها و مانند این‌ها به‌کار می‌رود. زبان می‌تواند دو نوع باشد:\n\nالف) زبان غیرکلامی (Linguagem não-verbal): از واژه استفاده نمی‌کند. مثال‌ها: تابلوهای علائم راهنمایی و رانندگی، سوت کارخانه هنگام ناهار، سوت داور فوتبال که به نقطهٔ پنالتی اشاره می‌کند. در زبان غیرکلامی، رنگ‌ها، صداها، حرکت‌ها و طرح‌ها بی‌درنگ معنا را می‌رسانند.\n\nب) زبان کلامی یا «língua» (Linguagem verbal): از واژه‌ها استفاده می‌کند، چه نوشتاری چه گفتاری. مثال‌ها: کتاب‌ها، روزنامه‌ها و مجله‌ها، آگهی‌ها، ایمیل‌ها، پیام‌های متنی، تابلوهای علائم، گفت‌وگوی مردم، کلاس‌ها، سخنرانی‌ها و فیلم‌ها.',
      examples: [
        {
          pt: 'As placas de sinalização de trânsito são linguagem não-verbal.',
          fa: 'تابلوهای علائم رانندگی زبانِ غیرکلامی هستند.',
          pron: 'آس پلاکاس جی سینالیزاسائو جی ترانزیتو سائو لینگواژِن نائو-وِربال',
        },
        {
          pt: 'O apito do juiz aponta para a marca do pênalti.',
          fa: 'سوت داور به نقطهٔ پنالتی اشاره می‌کند.',
          pron: 'او آپیتو دو ژوئیز آپونتا پارا آ مارکا دو پِنالتی',
          note: 'نمونه‌ای از ارتباط غیرکلامی با صدا.',
        },
        {
          pt: 'Livros, jornais e revistas usam linguagem verbal.',
          fa: 'کتاب‌ها، روزنامه‌ها و مجله‌ها از زبان کلامی استفاده می‌کنند.',
          pron: 'لیوروس، ژورنایس ای رِویستاس اوزَن لینگواژِن وِربال',
        },
      ],
    },
    {
      headingFa: '۳. زبان گفتاری و زبان نوشتاری',
      bodyFa:
        'نباید زبان گفتاری (língua falada) را با زبان نوشتاری (língua escrita) اشتباه گرفت، زیرا این‌ها دو وسیلهٔ ارتباطیِ متفاوت‌اند. نوشتار مرحله‌ای متأخرتر از یک زبان را نشان می‌دهد.\n\nزبان گفتاری خودانگیخته‌تر است و با لحن صدا، و گاهی با ادا و اشاره همراه می‌شود.\n\nزبان نوشتاری صرفاً بازنمایی زبان گفتاری نیست، بلکه سیستمی همراه با قاعده است. در زبان نوشتاری نسبت به قواعد دستور زبان معیار (gramática normativa) سخت‌گیری بیشتری وجود دارد.\n\nدلیلش این است که هنگام صحبت، آدم‌ها می‌توانند به ابزارهای دیگری هم برای برقراری ارتباط متوسل شوند ـ می‌توان خواست حرف تکرار شود، اشاره‌ها هست و غیره. اما در زبان نوشتاری، تعامل پیچیده‌تر است و همین باعث می‌شود لازم باشد مطمئن شویم متنِ نوشته‌شده به‌تنهایی از پس ارتباط برمی‌آید.',
      examples: [
        {
          pt: 'A língua falada é mais espontânea.',
          fa: 'زبان گفتاری خودانگیخته‌تر است.',
          pron: 'آ لینگوا فالادا اِ مایس اِسپونتانِئا',
        },
        {
          pt: 'Na língua escrita há mais exigências gramaticais.',
          fa: 'در زبان نوشتاری سخت‌گیری‌های دستوری بیشتری هست.',
          pron: 'نا لینگوا اِسکریتا آ مایس اِزیژِنسیاس گراماتیکایس',
        },
      ],
    },
    {
      headingFa: '۴. تفاوت گفتار و نوشتار و عوامل تغییر زبان',
      bodyFa:
        'گفتار و نوشتار به دانش‌های متفاوتی نیاز دارند. در همهٔ زبان‌ها، مردم به یک شکل حرف می‌زنند و به شکل دیگری می‌نویسند. برای مثال بیشتر ما برزیلی‌ها می‌گوییم «Eli mi ensinô»، اما پرتغالیِ گونهٔ معیار می‌خواهد که این‌طور نوشته شود: «Ele me ensinou» (او به من یاد داد).\n\nعوامل تغییر (Fatores de variação): در برزیل همه به زبان پرتغالی حرف می‌زنند، اما به‌دلیل عوامل گوناگون کاربردهای متفاوتی از زبان وجود دارد. مهم‌ترین‌ها:\n\n• عوامل منطقه‌ای (Fatores regionais): می‌توان تفاوت پرتغالیِ ساکن منطقهٔ شمال‌شرق (nordeste) و ساکن منطقهٔ جنوب‌شرق (sudeste) برزیل را دید. حتی درون یک منطقهٔ واحد هم تفاوت‌هایی در کاربرد زبان هست.\n\n• عوامل فرهنگی (Fatores culturais): میزان تحصیلات و پیشینهٔ فرهنگی فرد هم از عوامل مؤثر بر کاربردهای گوناگون زبان است. فرد تحصیل‌کرده زبان را به‌شکلی متفاوت از کسی که به مدرسه دسترسی نداشته به‌کار می‌برد.',
      examples: [
        {
          pt: 'Falado: "Eli mi ensinô." → Escrito: "Ele me ensinou."',
          fa: 'گفتاری: «اِلی می اِنسینو.» ← نوشتاری: «او به من یاد داد.»',
          pron: 'اِلی می اِنسینو ← اِلی می اِنسینوو',
          note: 'نمونهٔ تفاوت تلفظ عامیانه با نوشتار معیار.',
        },
        {
          pt: 'O português do nordeste é diferente do português do sudeste.',
          fa: 'پرتغالیِ شمال‌شرق با پرتغالیِ جنوب‌شرق فرق دارد.',
          pron: 'او پُرتوگِس دو نُردِستی اِ دیفِرِنتی دو پُرتوگِس دو سودِستی',
          note: 'نمونهٔ عامل منطقه‌ای.',
        },
      ],
    },
    {
      headingFa: '۵. عوامل بافتی و مفهوم «گفتار» (Fala)',
      bodyFa:
        'عوامل بافتی (Fatores contextuais): شیوهٔ حرف‌زدن ما بسته به موقعیتی که در آن قرار داریم تغییر می‌کند؛ وقتی با دوستانمان صحبت می‌کنیم از واژه‌هایی استفاده نمی‌کنیم که اگر با کسانی که با آن‌ها صمیمی نیستیم حرف می‌زدیم به‌کار می‌بردیم.\n\nگفتار (Fala): همان کاربرد شفاهی زبان توسط فرد است. گفتار کنشی فردی است، زیرا هر فرد برای بیان گفتار می‌تواند عناصری از زبان را انتخاب کند که برایش مناسب است، بر پایهٔ سلیقه و نیازش، متناسب با موقعیت، بافت، شخصیت و محیط اجتماعی‌ـ‌فرهنگی‌ای که در آن زندگی می‌کند.',
      examples: [
        {
          pt: 'Com os amigos não usamos os termos formais.',
          fa: 'با دوستان از اصطلاح‌های رسمی استفاده نمی‌کنیم.',
          pron: 'کُن اوس آمیگوس نائو اوزاموس اوس تِرموس فُرمایس',
        },
        {
          pt: 'A fala é um ato individual.',
          fa: 'گفتار یک کنشِ فردی است.',
          pron: 'آ فالا اِ اوم آتو ایندیویدوال',
        },
      ],
    },
    {
      headingFa: '۶. وابستگی اسمی + حرف اضافه (Regência Nominal)',
      bodyFa:
        'وابستگی اسمی (Regência Nominal) نامی است که به رابطهٔ میان «نام‌ها» (اسم، صفت یا قید) و متمم‌هایشان می‌دهیم. بسیاری از این نام‌ها برای اتصال به متمم به یک حرف اضافهٔ مشخص نیاز دارند.\n\nبه دو مثال زیر توجه کنید؛ در هر دو از صفت interessado (علاقه‌مند) استفاده شده و پس از آن باید حرف اضافهٔ em بیاید:\n• Ela está interessada em aprender novas línguas.\n• Eles estão interessados em estudar português no Brasil.\n\nحالا صفت ansioso (بی‌تاب/مشتاق) که پس از آن باید حرف اضافهٔ para بیاید:\n• Ele está ansioso para te ver.\n• Nós estamos ansiosos para pegar nosso certificado.\n\nنکته برای فارسی‌زبانان: حرف اضافهٔ درست بخشی از خودِ صفت است و باید حفظ شود؛ نمی‌توان آن را حدس زد یا از فارسی ترجمه کرد.',
      examples: [
        {
          pt: 'Ela está interessada em aprender novas línguas.',
          fa: 'او (زن) به یادگیری زبان‌های تازه علاقه‌مند است.',
          pron: 'اِلا اِستا اینتِرِسادا اِین آپرِندِر نُواس لینگواس',
          note: 'interessado همیشه با em می‌آید.',
        },
        {
          pt: 'Eles estão interessados em estudar português no Brasil.',
          fa: 'آن‌ها به تحصیل پرتغالی در برزیل علاقه‌مندند.',
          pron: 'اِلیس اِستائو اینتِرِسادوس اِین اِستودار پُرتوگِس نو برازیل',
        },
        {
          pt: 'Ele está ansioso para te ver.',
          fa: 'او (مرد) برای دیدن تو بی‌تاب است.',
          pron: 'اِلی اِستا آنسیوزو پارا تی وِر',
          note: 'ansioso با para می‌آید (نه با em).',
        },
        {
          pt: 'Nós estamos ansiosos para pegar nosso certificado.',
          fa: 'ما برای گرفتن گواهی‌مان بی‌تابیم.',
          pron: 'نُس اِستاموس آنسیوزوس پارا پِگار نُسو سِرتیفیکادو',
        },
      ],
    },
    {
      headingFa: '۷. اسم‌ها/صفت‌هایی که به حرف اضافه نیاز دارند ـ مثال‌ها',
      bodyFa:
        'در ادامه فهرستی از «نام‌ها»یی که هرکدام حرف اضافهٔ خاص خود را می‌طلبند و جمله‌های نمونه آورده شده است. حرف اضافه را همراه با خودِ صفت به‌خاطر بسپارید:\n\nfácil de (آسان برای)\nperto de (نزدیک به)\ncontente em (خوشحال از)\nagradável de (دلپذیر برای)\nigual a (مانندِ / برابر با)\ntriste por (غمگین از/به‌خاطرِ)\nadmiração por (تحسین نسبت به)',
      examples: [
        {
          pt: 'Isso não é muito fácil de fazer.',
          fa: 'این خیلی آسان برای انجام‌دادن نیست.',
          pron: 'ایسو نائو اِ مویتو فاسیل جی فازِر',
          note: 'صفت fácil + de.',
        },
        {
          pt: 'Eu queria estar mais perto de você.',
          fa: 'دلم می‌خواست به تو نزدیک‌تر باشم.',
          pron: 'اِئو کِریا اِستار مایس پِرتو جی وُسه',
          note: 'قید perto + de.',
        },
        {
          pt: 'Estamos contentes em te receber.',
          fa: 'از پذیرفتنِ تو خوشحالیم.',
          pron: 'اِستاموس کونتِنتِس اِین تی رِسِبِر',
          note: 'صفت contente + em.',
        },
        {
          pt: 'Essa vista é agradável de se ver!',
          fa: 'این منظره دیدنش دلپذیر است!',
          pron: 'اِسا ویستا اِ آگرادّاوِل جی سی وِر',
          note: 'صفت agradável + de.',
        },
        {
          pt: 'Eu sou igual a você!',
          fa: 'من مثل تو هستم!',
          pron: 'اِئو سُ ایگوال آ وُسه',
          note: 'صفت igual + a.',
        },
        {
          pt: 'Estamos tristes por ir embora.',
          fa: 'از رفتن غمگینیم.',
          pron: 'اِستاموس تریستِس پور ایر اِمبورا',
          note: 'صفت triste + por.',
        },
        {
          pt: 'Eu tenho admiração por você.',
          fa: 'من نسبت به تو تحسین دارم.',
          pron: 'اِئو تِنیو آدمیراسائو پور وُسه',
          note: 'اسم admiração + por.',
        },
      ],
    },
    {
      headingFa: '۸. وابستگی فعلی + حرف اضافه (Regência Verbal)',
      bodyFa:
        'وابستگی فعلی (Regência Verbal) پیوند و رابطهٔ میان فعل‌ها و متمم‌هایشان است. بسیاری از فعل‌ها برای کامل‌شدن معنا به حرف اضافهٔ مشخصی نیاز دارند.\n\nمثال: «Eu moro no Rio de Janeiro» (من در ریودوژانیرو زندگی می‌کنم). فعل morar (زندگی‌کردن) در پرتغالی به حرف اضافهٔ em نیاز دارد؛ پس همیشه می‌گوییم در جایی زندگی می‌کنیم (morar em). اگر حرف اضافهٔ درست را به‌کار نبریم، جمله معنای کاملش را نخواهد داشت یا ممکن است معنای دیگری پیدا کند.\n\nمثالی دیگر: «Ele vai para a praia» (او به ساحل می‌رود). با فعل ir (رفتن) هم به حرف اضافه نیاز داریم، چون در پرتغالی همیشه به سمتِ جایی می‌رویم. در پرتغالی دو حرف اضافه هست که این‌جا یک‌جور عمل می‌کنند: a و para؛ پس در این حالت می‌توان هر دو را به‌کار برد.',
      examples: [
        {
          pt: 'Eu moro no Rio de Janeiro.',
          fa: 'من در ریودوژانیرو زندگی می‌کنم.',
          pron: 'اِئو مُرو نو ریو جی ژانِیرو',
          note: 'morar + em؛ «no» = em + o.',
        },
        {
          pt: 'Ele vai para a praia. / Ele vai à praia.',
          fa: 'او به ساحل می‌رود.',
          pron: 'اِلی وای پارا آ پرایا / اِلی وای آ پرایا',
          note: 'با فعل ir هر دو حرف اضافهٔ a و para درست‌اند.',
        },
      ],
    },
    {
      headingFa: '۹. فعل‌هایی که به حرف اضافه نیاز دارند ـ فهرست',
      bodyFa:
        'فهرست پرکاربردترین فعل‌ها همراه با حرف اضافه‌شان. حرف اضافه بخشی جدانشدنی از کاربرد فعل است:\n\nAjudar a — کمک‌کردن به\nComeçar a — شروع‌کردن به\nContinuar a — ادامه‌دادن به\nEnsinar a — یاد دادن\nIr a/para — رفتن به\nGostar de — دوست‌داشتن\nLembrar-se de — به‌یاد آوردن / به‌خاطر داشتن\nTerminar de — تمام‌کردن\nConcordar em/com — موافقت‌کردن (با)\nPensar em — فکر کردن به\nSonhar em/com — رؤیای چیزی را داشتن / خواب چیزی را دیدن',
      examples: [
        {
          pt: 'Eu gosto de você.',
          fa: 'من تو را دوست دارم.',
          pron: 'اِئو گُستو جی وُسه',
          note: 'gostar همیشه با de.',
        },
        {
          pt: 'Eles começaram a estudar português.',
          fa: 'آن‌ها شروع کردند به خواندن پرتغالی.',
          pron: 'اِلیس کومِسارام آ اِستودار پُرتوگِس',
          note: 'começar + a.',
        },
        {
          pt: 'Nós concordamos em chegar cedo.',
          fa: 'ما توافق کردیم که زود برسیم.',
          pron: 'نُس کونکورداموس اِین شِگار سِدو',
          note: 'concordar + em (یا com).',
        },
        {
          pt: 'Eu terminei de cozinhar cedo.',
          fa: 'من زود آشپزی را تمام کردم.',
          pron: 'اِئو تِرمینِی جی کوزینیار سِدو',
          note: 'terminar + de.',
        },
        {
          pt: 'A professora me ensinou a ler.',
          fa: 'معلم (زن) به من خواندن یاد داد.',
          pron: 'آ پروفِسورا می اِنسینو آ لِر',
          note: 'ensinar + a.',
        },
        {
          pt: 'Elas pensam em comprar uma casa grande.',
          fa: 'آن‌ها (زنان) به خریدِ یک خانهٔ بزرگ فکر می‌کنند.',
          pron: 'اِلاس پِنسام اِین کومپرار اوما کازا گراندی',
          note: 'pensar + em.',
        },
      ],
    },
    {
      headingFa: '۱۰. تمرین ـ کامل کردن جمله‌ها',
      bodyFa:
        'جمله‌های زیر را با گزینه‌های مناسب کامل کنید. گزینه‌ها:\n\ngosto de  /  acabamos de  /  boas em  /  preciso  /  começaram a  /  precisa\n\nالف) Ele ____ acordar mais cedo para não chegar atrasado no trabalho.\nب) Eu ____ dormir até as 8:00 da manhã, mas às vezes ____ acordar às 5:00.\nج) Elas são ____ matemática.\nد) Nós ____ jantar e já estamos com fome.\nه) Vocês já ____ fazer o novo curso de português.\n\nپاسخ‌ها در بخش تمرین (Quiz) با توضیح آورده شده‌اند. توجه: acabar de یعنی «تازه کاری را تمام کردن»، precisar (+ مصدر) یعنی «نیاز داشتن»، و «boas em» یعنی «خوب بودن در (کاری)».',
      examples: [
        {
          pt: 'Nós acabamos de jantar.',
          fa: 'ما همین الان شام خوردیم (تازه تمام کردیم).',
          pron: 'نُس آکاباموس جی ژانتار',
          note: 'acabar de + مصدر = «تازه انجام دادن».',
        },
        {
          pt: 'Elas são boas em matemática.',
          fa: 'آن‌ها (زنان) در ریاضی خوب‌اند.',
          pron: 'اِلاس سائو بوآس اِین ماتِماتیکا',
          note: 'ser bom/boa + em.',
        },
      ],
    },
  ],
  keyPointsFa: [
    'برای برقراری ارتباط شش عنصر لازم است: فرستنده، گیرنده، پیام، کانال و رمز؛ فرستنده و گیرنده باید رمزِ مشترک داشته باشند.',
    'زبان غیرکلامی از واژه استفاده نمی‌کند (تابلوها، سوت، اشاره)؛ زبان کلامی از واژهٔ گفتاری یا نوشتاری استفاده می‌کند.',
    'زبان گفتاری خودانگیخته و همراه با لحن و اشاره است؛ زبان نوشتاری سیستمی با قاعده و سخت‌گیریِ دستوری بیشتر است.',
    'کاربرد زبان بر اثر عوامل منطقه‌ای، فرهنگی و بافتی تغییر می‌کند؛ «گفتار» کنشی فردی است.',
    'وابستگی اسمی: صفت/اسم حرف اضافهٔ خودش را دارد ـ interessado em، ansioso para، fácil de، igual a، triste por، admiração por.',
    'وابستگی فعلی: فعل حرف اضافهٔ خودش را دارد ـ morar em، gostar de، começar a، terminar de، pensar em، ensinar a.',
    'با فعل ir هر دو حرف اضافهٔ a و para درست است؛ حرف اضافه را همراه با خودِ کلمه حفظ کنید و از فارسی ترجمه نکنید.',
  ],
  quiz: [
    {
      id: 'course-aula-15-q1',
      type: 'mcq',
      prompt: 'Quem produz a mensagem na comunicação?',
      promptFa: 'در فرایند ارتباط چه کسی پیام را تولید می‌کند؟',
      options: ['O emissor', 'O receptor', 'O canal', 'O código'],
      answer: 'O emissor',
      explanationFa: 'فرستنده (emissor / remetente) کسی است که پیام را تولید می‌کند؛ گیرنده آن را دریافت می‌کند.',
      cefr: 'B1',
      skill: 'reading',
    },
    {
      id: 'course-aula-15-q2',
      type: 'mcq',
      prompt: 'No caso de uma mensagem escrita ou falada, o código é:',
      promptFa: 'در پیام نوشتاری یا گفتاری، «رمز» (código) چیست؟',
      options: ['a língua', 'o canal', 'o emissor', 'a mímica'],
      answer: 'a língua',
      explanationFa: 'در پیام نوشتاری یا گفتاری، رمز همان زبان (língua) است؛ البته رنگ‌ها، اشاره‌ها و علائم هم می‌توانند رمز باشند.',
      cefr: 'B1',
      skill: 'reading',
    },
    {
      id: 'course-aula-15-q3',
      type: 'mcq',
      prompt: 'Qual destes é um exemplo de linguagem não-verbal?',
      promptFa: 'کدام‌یک نمونهٔ زبان غیرکلامی است؟',
      options: [
        'O apito do juiz de futebol',
        'Um e-mail',
        'Uma palestra',
        'Uma conversa entre amigos',
      ],
      answer: 'O apito do juiz de futebol',
      explanationFa: 'سوت داور بدون واژه معنا را می‌رساند، پس زبان غیرکلامی است؛ ایمیل، سخنرانی و گفت‌وگو کلامی‌اند.',
      cefr: 'B1',
      skill: 'reading',
    },
    {
      id: 'course-aula-15-q4',
      type: 'mcq',
      prompt: 'A língua falada, em comparação com a escrita, é:',
      promptFa: 'زبان گفتاری در مقایسه با نوشتاری چگونه است؟',
      options: [
        'mais espontânea',
        'mais exigente com a gramática',
        'um sistema mais rígido de regras',
        'um estágio posterior da língua',
      ],
      answer: 'mais espontânea',
      explanationFa: 'زبان گفتاری خودانگیخته‌تر است؛ زبان نوشتاری قواعد سخت‌گیرانه‌تر و مرحله‌ای متأخرتر از زبان است.',
      cefr: 'B1',
      skill: 'reading',
    },
    {
      id: 'course-aula-15-q5',
      type: 'mcq',
      prompt: 'A diferença entre o português do nordeste e do sudeste é um exemplo de:',
      promptFa: 'تفاوت پرتغالیِ شمال‌شرق و جنوب‌شرق نمونهٔ کدام عامل است؟',
      options: [
        'fatores regionais',
        'fatores culturais',
        'fatores contextuais',
        'linguagem não-verbal',
      ],
      answer: 'fatores regionais',
      explanationFa: 'تفاوت بین مناطق جغرافیایی به عوامل منطقه‌ای (fatores regionais) مربوط است.',
      cefr: 'B1',
      skill: 'reading',
    },
    {
      id: 'course-aula-15-q6',
      type: 'fill-blank',
      prompt: 'Ela está interessada ___ aprender novas línguas.',
      promptFa: 'حرف اضافهٔ درست پس از صفت interessado را بگذارید.',
      options: [],
      answer: 'em',
      explanationFa: 'صفت interessado همیشه با حرف اضافهٔ em می‌آید: interessado em.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q7',
      type: 'fill-blank',
      prompt: 'Ele está ansioso ___ te ver.',
      promptFa: 'حرف اضافهٔ درست پس از صفت ansioso را بگذارید.',
      options: [],
      answer: 'para',
      explanationFa: 'صفت ansioso با حرف اضافهٔ para می‌آید: ansioso para.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q8',
      type: 'mcq',
      prompt: 'Complete: "Eu sou igual ___ você!"',
      promptFa: 'حرف اضافهٔ درست پس از igual کدام است؟',
      options: ['a', 'de', 'em', 'por'],
      answer: 'a',
      explanationFa: 'صفت igual با حرف اضافهٔ a می‌آید: igual a você.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q9',
      type: 'mcq',
      prompt: 'Complete: "Estamos tristes ___ ir embora."',
      promptFa: 'حرف اضافهٔ درست پس از triste کدام است؟',
      options: ['por', 'em', 'a', 'de'],
      answer: 'por',
      explanationFa: 'صفت triste در این کاربرد با por می‌آید: triste por.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q10',
      type: 'fill-blank',
      prompt: 'Eu moro ___ Rio de Janeiro. (em + o)',
      promptFa: 'فعل morar به حرف اضافهٔ em نیاز دارد؛ شکل ادغام‌شده با «o» را بگذارید.',
      options: [],
      answer: 'no',
      explanationFa: 'morar + em؛ em + o = no. پس «moro no Rio de Janeiro».',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q11',
      type: 'mcq',
      prompt: 'Com o verbo "ir", quais preposições funcionam da mesma forma?',
      promptFa: 'با فعل ir کدام دو حرف اضافه یکسان عمل می‌کنند؟',
      options: ['a e para', 'de e em', 'em e por', 'de e a'],
      answer: 'a e para',
      explanationFa: 'با فعل ir هر دو حرف اضافهٔ a و para درست‌اند: «ir a / ir para».',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q12',
      type: 'fill-blank',
      prompt: 'Eu gosto ___ você.',
      promptFa: 'حرف اضافهٔ درست پس از فعل gostar را بگذارید.',
      options: [],
      answer: 'de',
      explanationFa: 'فعل gostar همیشه با de می‌آید: gostar de.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q13',
      type: 'mcq',
      prompt: 'Complete: "Eles começaram ___ estudar português."',
      promptFa: 'حرف اضافهٔ درست پس از começar کدام است؟',
      options: ['a', 'de', 'em', 'com'],
      answer: 'a',
      explanationFa: 'فعل começar با a می‌آید: começar a + مصدر.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q14',
      type: 'fill-blank',
      prompt: 'A professora me ensinou ___ ler.',
      promptFa: 'حرف اضافهٔ درست پس از ensinar را بگذارید.',
      options: [],
      answer: 'a',
      explanationFa: 'فعل ensinar با a می‌آید: ensinar a + مصدر.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q15',
      type: 'fill-blank',
      prompt: 'Ele ___ acordar mais cedo para não chegar atrasado no trabalho.',
      promptFa: 'تمرین (الف): با گزینهٔ مناسب کامل کنید (precisa / preciso / gosto de …).',
      options: [],
      answer: 'precisa',
      explanationFa: 'فاعل «ele» سوم‌شخص مفرد است، پس «precisa»: او لازم است زودتر بیدار شود.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q16',
      type: 'fill-blank',
      prompt: 'Eu ___ dormir até as 8:00, mas às vezes ___ acordar às 5:00.',
      promptFa: 'تمرین (ب): دو جای خالی را کامل کنید (gosto de / preciso).',
      options: [],
      answer: 'gosto de / preciso',
      explanationFa: 'اولی سلیقه است → «gosto de dormir»؛ دومی نیاز است → «preciso acordar».',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q17',
      type: 'fill-blank',
      prompt: 'Elas são ___ matemática.',
      promptFa: 'تمرین (ج): با گزینهٔ مناسب کامل کنید.',
      options: [],
      answer: 'boas em',
      explanationFa: '«ser boa em» یعنی در چیزی خوب بودن؛ برای «elas» جمع مؤنث → «boas em matemática».',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q18',
      type: 'fill-blank',
      prompt: 'Nós ___ jantar e já estamos com fome.',
      promptFa: 'تمرین (د): با گزینهٔ مناسب کامل کنید.',
      options: [],
      answer: 'acabamos de',
      explanationFa: '«acabar de + مصدر» یعنی تازه کاری را تمام کردن → «acabamos de jantar».',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q19',
      type: 'fill-blank',
      prompt: 'Vocês já ___ fazer o novo curso de português.',
      promptFa: 'تمرین (ه): با گزینهٔ مناسب کامل کنید.',
      options: [],
      answer: 'começaram a',
      explanationFa: 'فعل começar با a و برای «vocês» → «começaram a fazer».',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-15-q20',
      type: 'translate-fa-pt',
      prompt: '«ما توافق کردیم که زود برسیم.» را به پرتغالی بنویسید.',
      promptFa: 'با فعل concordar (که با em می‌آید) ترجمه کنید.',
      options: [],
      answer: 'Nós concordamos em chegar cedo.',
      explanationFa: 'concordar + em؛ «concordamos em chegar cedo».',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-15-q21',
      type: 'translate-pt-fa',
      prompt: 'Traduza para o persa: "Elas pensam em comprar uma casa grande."',
      promptFa: 'این جمله را به فارسی ترجمه کنید.',
      options: [],
      answer: 'آن‌ها (زنان) به خریدِ یک خانهٔ بزرگ فکر می‌کنند.',
      explanationFa: 'فعل pensar با em می‌آید: pensar em (فکر کردن به).',
      cefr: 'B1',
      skill: 'reading',
    },
    {
      id: 'course-aula-15-q22',
      type: 'order-words',
      prompt: 'Ordene: [de / Eu / cozinhar / terminei / cedo]',
      promptFa: 'واژه‌ها را مرتب کنید تا جملهٔ درست ساخته شود.',
      options: [],
      answer: 'Eu terminei de cozinhar cedo.',
      explanationFa: 'فعل terminar با de می‌آید: «terminei de cozinhar».',
      cefr: 'B1',
      skill: 'grammar',
    },
  ],
  estimatedMinutes: 26,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 15 (کامل).',
};
