import type { CourseLesson } from '@/domain/content/schema';

export const aula3: CourseLesson = {
  id: 'course-aula-3',
  order: 3,
  aula: 'Aula 3',
  titleFa: 'ضمایر ملکی و صفت‌ها',
  titlePt: 'Pronomes Possessivos e Adjetivos',
  cefr: 'A1',
  summaryFa:
    'این درس دو بخش اصلی دارد. بخش نخست ضمایر ملکی (Pronomes Possessivos) پرتغالی برزیلی است: meu/minha, seu/sua, nosso/nossa و شکل‌های مالکیت سوم‌شخص dele/dela/deles/delas؛ در اینجا یاد می‌گیرید که ضمیر ملکی نه با صاحبِ چیز، بلکه با خودِ چیزِ داشته‌شده (جنسیت و شمار آن) هماهنگ می‌شود — نکته‌ای که فارسی‌زبانان زیاد اشتباه می‌کنند. بخش دوم صفت (Adjetivo) است: تعریف صفت، هماهنگی صفت با اسم در جنس (مذکر/مؤنث) و شمار (مفرد/جمع)، و ساختن صفت از یک عبارت. در میانهٔ درس با شعر معروف «Retrato» از سیسیلیا میرِلیس کاربرد ضمیر ملکی «minha» را در متنی ادبی می‌بینید. تمرین‌های فراوانی برای پر کردن جای خالی و تبدیل عبارت به صفت آورده شده است.',
  objectivesFa: [
    'جدول کامل ضمایر ملکی را برای هر شخص در دو جنس و دو شمار بشناسید.',
    'بدانید ضمیر ملکی با چیزِ داشته‌شده هماهنگ می‌شود، نه با صاحبِ آن.',
    'شکل‌های مالکیت سوم‌شخص (dele, dela, deles, delas, de vocês) را درست به‌کار ببرید.',
    'تعریف صفت را بدانید و بفهمید صفت ویژگیِ یک اسم را بیان می‌کند.',
    'صفت را با اسم در جنس (مذکر/مؤنث) و شمار (مفرد/جمع) هماهنگ کنید.',
    'از یک عبارت (مثلاً «که شجاعت دارد») صفت متناظر آن («شجاع») را بسازید.',
  ],
  sections: [
    {
      headingFa: '۱. ضمیر ملکی چیست؟',
      bodyFa:
        'ضمیر ملکی (Pronome Possessivo) نشان می‌دهد چیزی به چه کسی تعلق دارد. در فارسی این کار را با «ـ َم، ـ َت، ـ َش» یا «مالِ من» انجام می‌دهیم (کتابِ من = کتابم). نکتهٔ کلیدی و مهم‌ترین تفاوت با فارسی: در پرتغالی ضمیر ملکی با «چیزِ داشته‌شده» هماهنگ می‌شود، نه با صاحبِ آن. یعنی جنسیت (مذکر/مؤنث) و شمار (مفرد/جمع) ضمیر ملکی از روی همان اسمی گرفته می‌شود که پس از آن می‌آید:\n\nmeu carro (ماشینِ من ـ carro مذکر مفرد) → meu\nminha casa (خانهٔ من ـ casa مؤنث مفرد) → minha\nmeus carros (ماشین‌های من ـ جمع مذکر) → meus\nminhas casas (خانه‌های من ـ جمع مؤنث) → minhas\n\nپس حتی اگر گوینده مرد باشد، وقتی دربارهٔ «casa» (مؤنث) حرف می‌زند می‌گوید «minha casa».',
      examples: [
        {
          pt: 'meu carro',
          fa: 'ماشینِ من',
          pron: 'مِئو کارو',
          note: 'carro مذکر مفرد → meu.',
        },
        {
          pt: 'minha casa',
          fa: 'خانهٔ من',
          pron: 'مینیا کازا',
          note: 'casa مؤنث مفرد → minha.',
        },
        {
          pt: 'meus livros / minhas irmãs',
          fa: 'کتاب‌های من / خواهرهای من',
          pron: 'مِئوس لیوروس / مینیاس ایرمانس',
          note: 'جمع مذکر → meus؛ جمع مؤنث → minhas.',
        },
      ],
    },
    {
      headingFa: '۲. جدول کامل ضمایر ملکی',
      bodyFa:
        'برای هر شخص، ضمیر ملکی دو شکل مذکر و مؤنث دارد و هرکدام مفرد و جمع می‌شوند. جدول کامل (شکل مؤنث و سپس مذکر):\n\nشخص | مؤنث (مفرد ـ جمع) | مذکر (مفرد ـ جمع)\nEU (من) | minha ـ minhas | meu ـ meus\nVOCÊ (تو/شما) | sua ـ suas | seu ـ seus\nELE / ELA (او) | sua ـ suas ـ dela | seu ـ seus ـ dele\nA GENTE (ما، غیررسمی) | nossa ـ nossas | nosso ـ nossos\nNÓS (ما) | nossa ـ nossas | nosso ـ nossos\nVOCÊS (شما جمع) | sua ـ suas ـ de vocês | seu ـ seus ـ de vocês\nELES / ELAS (آن‌ها) | sua ـ suas ـ delas | seu ـ seus ـ deles\n\nتوجه: برای «a gente» و «nós» هر دو از nosso/nossa استفاده می‌شود، چون هر دو معنی «ما» می‌دهند.',
      examples: [
        {
          pt: 'meu / minha / meus / minhas',
          fa: 'مالِ من (مذکر مفرد / مؤنث مفرد / مذکر جمع / مؤنث جمع)',
          pron: 'مِئو / مینیا / مِئوس / مینیاس',
        },
        {
          pt: 'seu / sua / seus / suas',
          fa: 'مالِ تو/شما یا او',
          pron: 'سِئو / سوا / سِئوس / سواس',
        },
        {
          pt: 'nosso / nossa / nossos / nossas',
          fa: 'مالِ ما',
          pron: 'نُسو / نُسا / نُسوس / نُساس',
        },
      ],
    },
    {
      headingFa: '۳. رفع ابهام سوم‌شخص: dele / dela / deles / delas',
      bodyFa:
        'واژهٔ «seu/sua» هم می‌تواند «مالِ تو/شما» باشد و هم «مالِ او». برای اینکه معلوم شود منظور «مالِ او (مرد)»، «مالِ او (زن)» یا «مالِ آن‌ها» است، برزیلی‌ها اغلب از شکل‌های dele/dela/deles/delas استفاده می‌کنند که بعد از اسم می‌آیند:\n\ndele = مالِ او (مرد) — از de + ele\ndela = مالِ او (زن) — از de + ela\ndeles = مالِ آن‌ها (مردانه/مختلط) — از de + eles\ndelas = مالِ آن‌ها (زنانه) — از de + elas\nde vocês = مالِ شما (جمع)\n\nمثال: «o carro dele» (ماشینِ او ـ مرد) روشن‌تر از «o seu carro» است. توجه کنید که dele/dela با جنسیتِ صاحبِ چیز مشخص می‌شود، اما پیش از آن حرف تعریف با خودِ چیز هماهنگ است: «a casa dele» (خانهٔ او ـ مرد).',
      examples: [
        {
          pt: 'o carro dele / o carro dela',
          fa: 'ماشینِ او (مرد) / ماشینِ او (زن)',
          pron: 'او کارو دِلی / او کارو دِلا',
          note: 'dele وقتی صاحب مرد است، dela وقتی صاحب زن است.',
        },
        {
          pt: 'a casa deles / a casa delas',
          fa: 'خانهٔ آن‌ها (مردانه/مختلط) / خانهٔ آن‌ها (زنانه)',
          pron: 'آ کازا دِلِس / آ کازا دِلاس',
        },
        {
          pt: 'Vi uma foto e perguntei se era dela ou de sua irmã.',
          fa: 'یک عکس دیدم و پرسیدم مالِ او (زن) بود یا مالِ خواهرش.',
          pron: 'وی اوما فُتو ای پِرگونتِی سی اِرا دِلا اُ جی سوا ایرما',
        },
      ],
    },
    {
      headingFa: '۴. تمرین کلیدی: هماهنگی با چیزِ داشته‌شده',
      bodyFa:
        'در این جمله‌ها ببینید چطور ضمیر ملکی از روی اسمِ بعد از خود جنسیت و شمار می‌گیرد. جای خالی‌های اصلیِ جزوه:\n«O carro é ___» (ماشین مذکر مفرد است → meu/seu…)؛ «___ filho é pequeno» (filho مذکر مفرد)؛ «___ irmã virá nos visitar» (irmã مؤنث مفرد)؛ «___ casa é grande» (casa مؤنث مفرد)؛ «___ vozes serão ouvidas» (vozes مؤنث جمع)؛ «Este lanche é ___» (lanche مذکر مفرد)؛ «Quero ouvir o parecer ___» (parecer مذکر مفرد)؛ «___ pais são muito educados» (pais مذکر جمع).',
      examples: [
        {
          pt: 'Meu filho é pequeno.',
          fa: 'پسرِ من کوچک است.',
          pron: 'مِئو فیلیو اِ پِکِنو',
          note: 'filho مذکر مفرد → meu.',
        },
        {
          pt: 'Minha irmã virá nos visitar.',
          fa: 'خواهرم به دیدن ما خواهد آمد.',
          pron: 'مینیا ایرما ویرا نوس ویزیتار',
          note: 'irmã مؤنث مفرد → minha.',
        },
        {
          pt: 'Nossas vozes serão ouvidas.',
          fa: 'صداهای ما شنیده خواهد شد.',
          pron: 'نُساس وُزِس سِرائو اُویداس',
          note: 'vozes مؤنث جمع → nossas.',
        },
        {
          pt: 'Meus pais são muito educados.',
          fa: 'پدر و مادرِ من بسیار مؤدب هستند.',
          pron: 'مِئوس پایس سائو مویتو اِدوکادوس',
          note: 'pais مذکر جمع → meus.',
        },
      ],
    },
    {
      headingFa: '۵. تمرین: پر کردن با ضمیر ملکیِ درست (بخش اول جزوه)',
      bodyFa:
        'در این تمرین‌ها فعلِ جمله (tenho, temos, tem…) نشان می‌دهد صاحب چه کسی است و اسمِ ملک جنس/شمار را تعیین می‌کند. پاسخ‌های درستِ جزوه:\n\nNós temos uma boa casa. Ela é nossa casa. (صاحب: ما؛ casa مؤنث → nossa)\nEle tem uma amiga simpática. Ela é sua amiga / amiga dele. (سوم‌شخص → sua یا dele)\nEu tenho um livro de fotografia. Ele é meu livro. (صاحب: من؛ livro مذکر → meu)\nVocê carrega a mochila. Ela é sua mochila. (صاحب: você؛ mochila مؤنث → sua)\n\nو در بخش «Esse … é ___»:\nEsse gato é meu — Essa moto é minha — Essa casa é sua — Esse livro é meu — Essa bicicleta é minha — Esse apartamento é nosso — Essa loja é nossa.',
      examples: [
        {
          pt: 'Nós temos uma boa casa. Ela é nossa casa.',
          fa: 'ما خانهٔ خوبی داریم. آن خانهٔ ماست.',
          pron: 'نُس تِموس اوما بوآ کازا. اِلا اِ نُسا کازا',
          note: 'صاحب «nós» و casa مؤنث → nossa.',
        },
        {
          pt: 'A gente tem uma loja. Essa loja é nossa.',
          fa: 'ما یک مغازه داریم. این مغازه مالِ ماست.',
          pron: 'آ جِنتی تِین اوما لُژا. اِسا لُژا اِ نُسا',
          note: '«a gente» یعنی «ما» و از nosso/nossa استفاده می‌کند؛ loja مؤنث → nossa.',
        },
      ],
    },
    {
      headingFa: '۶. تمرین: MEU/MINHA/NOSSO/NOSSA و SEU/SUA/DELE/DELA',
      bodyFa:
        'دستهٔ اول (فقط با MEU, MINHA, NOSSO, NOSSA):\na) Ontem à noite, eu liguei para meu irmão. (irmão مذکر، صاحب eu → meu)\nb) Encontramos nosso apartamento ideal. (encontramos = ما، apartamento مذکر → nosso)\nc) Queremos melhorar nossa comunicação. (queremos = ما، comunicação مؤنث → nossa)\nd) Preparei minha mochila com roupa de ginástica. (preparei = من، mochila مؤنث → minha)\n\nدستهٔ دوم (با SEU, SUA, DELE, DELA):\na) Eu falei com você e pedi emprestado o seu celular e também a sua senha do Wi-Fi. (celular مذکر → seu؛ senha مؤنث → sua)\nb) Eu falei com o Márcio e pedi emprestado o celular e a senha do Wi-Fi dele. (صاحب مرد → dele)\nc) Vi uma foto na casa da Marisa e perguntei se era dela ou de sua irmã. (مالِ خودش → dela / خواهرش → sua irmã)',
      examples: [
        {
          pt: 'Eu liguei para meu irmão que mora em outro país.',
          fa: 'به برادرم که در کشوری دیگر زندگی می‌کند زنگ زدم.',
          pron: 'اِئو لیگِی پارا مِئو ایرمائو کی مُرا اِین اُترو پاییس',
          note: 'irmão مذکر و صاحب «eu» → meu.',
        },
        {
          pt: 'Pedi emprestado o seu celular e a sua senha.',
          fa: 'گوشیِ تو و رمزِ تو را قرض گرفتم.',
          pron: 'پِدی اِمپرِستادو او سِئو سِلولار ای آ سوا سِنیا',
          note: 'celular مذکر → seu؛ senha مؤنث → sua.',
        },
        {
          pt: 'Pedi emprestado o celular e a senha do Wi-Fi dele.',
          fa: 'گوشی و رمز وای‌فایِ او (مرد) را قرض گرفتم.',
          pron: 'پِدی اِمپرِستادو او سِلولار ای آ سِنیا دو وای-فای دِلی',
          note: 'صاحب مرد (Márcio) → dele.',
        },
      ],
    },
    {
      headingFa: '۷. شعر «Retrato» (پرتره) از Cecília Meireles',
      bodyFa:
        'این شعر معروف کاربرد ضمیر ملکی «minha» را در متنی ادبی نشان می‌دهد (minha face = چهرهٔ من). متن کامل شعر:\n\n«Eu não tinha este rosto de hoje,\nassim calmo, assim triste, assim magro,\nnem estes olhos tão vazios, nem o lábio amargo.\nEu não tinha estas mãos sem força,\ntão paradas e frias e mortas;\neu não tinha este coração que nem se mostra.\nEu não dei por esta mudança,\ntão simples, tão certa, tão fácil:\nEm que espelho ficou perdida a minha face?»\n— Cecília Meireles',
      examples: [
        {
          pt: 'Em que espelho ficou perdida a minha face?',
          fa: 'در کدام آینه چهرهٔ من گم شد؟',
          pron: 'اِین کی اِسپِلیو فیکو پِردیدا آ مینیا فاسی',
          note: 'face مؤنث مفرد → minha.',
        },
        {
          pt: 'Eu não tinha este rosto de hoje.',
          fa: 'من این چهرهٔ امروز را نداشتم.',
          pron: 'اِئو نائو تینیا اِستی رُستو جی اُژی',
          note: 'este = این (مذکر مفرد)، اشارهٔ نزدیک.',
        },
      ],
    },
    {
      headingFa: '۸. صفت (Adjetivo) چیست؟',
      bodyFa:
        'صفت واژه‌ای است که ویژگیِ یک موجود یا چیز را بیان می‌کند. مثلاً واژهٔ «bondoso» (مهربان) هم یک کیفیت را نشان می‌دهد و هم می‌تواند مستقیماً کنار یک اسم بنشیند: homem bondoso (مردِ مهربان)، moça bondosa (دخترِ مهربان)، pessoa bondosa (شخصِ مهربان). نکتهٔ اصلی: صفت در جنس و شمار تغییر می‌کند (varia em gênero e número) و همیشه باید با اسمی که توصیف می‌کند هماهنگ باشد.',
      examples: [
        {
          pt: 'homem bondoso / moça bondosa',
          fa: 'مردِ مهربان / دخترِ مهربان',
          pron: 'اُمِن بُندوزو / مُسا بُندوزا',
          note: 'صفت با جنسِ اسم هماهنگ می‌شود: -o مذکر، -a مؤنث.',
        },
        {
          pt: 'pessoa bondosa',
          fa: 'شخصِ مهربان',
          pron: 'پِسوا بُندوزا',
          note: 'pessoa همیشه مؤنث است، حتی برای مرد → bondosa.',
        },
      ],
    },
    {
      headingFa: '۹. صرف صفت‌ها: جنس و شمار (Flexão dos Adjetivos)',
      bodyFa:
        'صفت‌ها بر اساس دو چیز تغییر می‌کنند:\n\nجنس (Gênero): صفت با اسمی که به آن اشاره می‌کند در مذکر یا مؤنث بودن هماهنگ می‌شود. بسیاری از صفت‌ها پایانهٔ -o مذکر و -a مؤنث دارند (bonito/bonita). برخی صفت‌ها یک شکل برای هر دو جنس دارند (مثل inteligente, feliz, fácil).\n\nشمار (Número): صفت‌ها جمع را با همان قاعده‌های اسم می‌سازند (معمولاً افزودن -s: bonito → bonitos؛ یا -es برای برخی پایانه‌ها). صفت باید با شمارِ اسم هماهنگ باشد.\n\nمثال‌های جزوه:\n- um lugar bonito (یک مکانِ زیبا)\n- uma menina educada (یک دخترِ بافرهنگ)\n- umas flores perfumadas (چند گلِ خوشبو)\n- uns livros interessantes (چند کتابِ جالب)',
      examples: [
        {
          pt: 'um lugar bonito',
          fa: 'یک مکانِ زیبا',
          pron: 'اون لوگار بونیتو',
          note: 'مذکر مفرد → bonito.',
        },
        {
          pt: 'uma menina educada',
          fa: 'یک دخترِ بافرهنگ',
          pron: 'اوما مِنینا اِدوکادا',
          note: 'مؤنث مفرد → educada.',
        },
        {
          pt: 'umas flores perfumadas',
          fa: 'چند گلِ خوشبو',
          pron: 'اوماس فلورِس پِرفوماداس',
          note: 'مؤنث جمع → perfumadas.',
        },
        {
          pt: 'uns livros interessantes',
          fa: 'چند کتابِ جالب',
          pron: 'اونس لیوروس اینتِرِسانتِس',
          note: 'interessante یک شکل برای هر دو جنس دارد؛ جمع → interessantes.',
        },
      ],
    },
    {
      headingFa: '۱۰. تمرین: تکمیل پایانهٔ صفت‌ها (هماهنگی)',
      bodyFa:
        'در این نمونه‌ها باید پایانهٔ صفت را با جنس و شمارِ اسم هماهنگ کنید. پاسخ‌های درستِ جزوه:\n\nAVIÕES RÁPIDOS (هواپیماهای سریع ـ مذکر جمع)\nBLUSA VELHA (بلوزِ کهنه ـ مؤنث مفرد)\nCAMAS MACIAS (تخت‌های نرم ـ مؤنث جمع)\nCANTOR FAMOSO (خوانندهٔ مشهور ـ مذکر مفرد)\nCARROS LENTOS (ماشین‌های کند ـ مذکر جمع)\nCHUVA GELADA (بارانِ سرد/یخ ـ مؤنث مفرد)\nCOPO VAZIO (لیوانِ خالی ـ مذکر مفرد)\nDIA FRIO (روزِ سرد ـ مذکر مفرد)',
      examples: [
        {
          pt: 'aviões rápidos',
          fa: 'هواپیماهای سریع',
          pron: 'آویُنس هاپیدوس',
          note: 'avião مذکر، جمع → rápidos.',
        },
        {
          pt: 'camas macias',
          fa: 'تخت‌های نرم',
          pron: 'کاماس ماسیاس',
          note: 'cama مؤنث، جمع → macias.',
        },
        {
          pt: 'chuva gelada',
          fa: 'بارانِ سرد',
          pron: 'شووا ژِلادا',
          note: 'chuva مؤنث مفرد → gelada.',
        },
        {
          pt: 'dia frio',
          fa: 'روزِ سرد',
          pron: 'جیا فریو',
          note: 'واژهٔ dia با اینکه به -a ختم می‌شود مذکر است → frio.',
        },
      ],
    },
    {
      headingFa: '۱۱. تمرین: تکمیل جمله‌ها با صفتِ مناسب',
      bodyFa:
        'در این تمرین باید با توجه به معنا صفتی مناسب انتخاب کنید (پاسخ‌ها می‌توانند کمی متفاوت باشند، اما باید در جنس و شمار هماهنگ باشند). نمونهٔ پاسخ‌های مناسب:\n\na) Tenho DVDs novos em casa. (چند دی‌وی‌دیِ نو)\nb) Mamãe precisa de uma roupa elegante para ir ao casamento. (لباسِ شیک)\nc) Não assisti ao filme porque ele é longo demais. (بیش از حد طولانی)\nd) Todos ficaram muito surpresos com o e-mail. (خیلی شگفت‌زده)\ne) O filme era triste, por isso fiquei triste. (غمگین → غمگین شدم)\nf) A partida estava difícil, mesmo assim eles ganharam. (بازیِ سخت)\ng) Camila ganhou um caderno novo de seu pai. (دفترِ نو)\nh) Janaina escreveu uma carta muito carinhosa para seu tio. (نامهٔ محبت‌آمیز)\ni) O menino é muito inteligente, sempre acerta as questões. (بسیار باهوش)',
      examples: [
        {
          pt: 'Todos ficaram muito surpresos com o e-mail.',
          fa: 'همه با آن ایمیل خیلی شگفت‌زده شدند.',
          pron: 'تُدوس فیکارام مویتو سورپرِزوس کُن او ایمِیل',
          note: 'todos مذکر جمع → surpresos.',
        },
        {
          pt: 'O menino é muito inteligente, sempre acerta as questões.',
          fa: 'پسر خیلی باهوش است، همیشه سؤال‌ها را درست جواب می‌دهد.',
          pron: 'او مِنینو اِ مویتو اینتِلیجِنتی',
          note: 'inteligente یک شکل برای هر دو جنس دارد.',
        },
      ],
    },
    {
      headingFa: '۱۲. تمرین: ساختن صفت از یک عبارت',
      bodyFa:
        'گاهی یک عبارتِ توصیفی را می‌توان با یک صفتِ کوتاه جایگزین کرد. پاسخ‌های درستِ جزوه:\n\nMenino que tem coragem = menino corajoso (پسری که شجاعت دارد = پسرِ شجاع)\nBoletim da escola = boletim escolar (کارنامهٔ مدرسه = کارنامهٔ آموزشی)\nFilme que assusta = filme assustador (فیلمی که می‌ترساند = فیلمِ ترسناک)\nPessoa que tem preguiça = pessoa preguiçosa (شخصی که تنبلی دارد = شخصِ تنبل)\nRevista da semana = revista semanal (مجلهٔ هفته = مجلهٔ هفتگی)\nFesta no mês de junho = festa junina (جشنِ ماه ژوئن = جشنِ ژونینا)\nQueijo de Minas = queijo mineiro (پنیرِ میناس = پنیرِ میناسی)\nPagamento feito por mês = pagamento mensal (پرداختِ ماهانه = پرداختِ ماهیانه)',
      examples: [
        {
          pt: 'menino corajoso',
          fa: 'پسرِ شجاع',
          pron: 'مِنینو کوراژوزو',
          note: '«que tem coragem» → corajoso.',
        },
        {
          pt: 'festa junina',
          fa: 'جشنِ ژونینا (جشن سنتی ماه ژوئن در برزیل)',
          pron: 'فِستا ژونینا',
          note: '«no mês de junho» → junina.',
        },
        {
          pt: 'pagamento mensal',
          fa: 'پرداختِ ماهیانه',
          pron: 'پاگامِنتو مِنسال',
          note: '«feito por mês» → mensal.',
        },
      ],
    },
  ],
  keyPointsFa: [
    'ضمیر ملکی با چیزِ داشته‌شده هماهنگ می‌شود، نه با صاحبِ آن (minha casa حتی اگر گوینده مرد باشد).',
    'meu/minha/meus/minhas برای «من»؛ seu/sua… برای «تو/شما و او»؛ nosso/nossa… برای «ما».',
    'برای روشن‌شدن مالکیتِ سوم‌شخص از dele (مرد)، dela (زن)، deles/delas (آن‌ها) استفاده کن.',
    '«a gente» و «nós» هر دو از nosso/nossa استفاده می‌کنند.',
    'صفت در جنس (مذکر/مؤنث) و شمار (مفرد/جمع) با اسم هماهنگ می‌شود.',
    'برخی صفت‌ها (inteligente, feliz, fácil) یک شکل برای هر دو جنس دارند.',
    'می‌توان عبارتِ توصیفی را با یک صفت جایگزین کرد: «que tem coragem» → corajoso.',
  ],
  quiz: [
    {
      id: 'course-aula-3-q1',
      type: 'mcq',
      prompt: 'Complete: ___ casa é grande.',
      promptFa: 'کدام ضمیر ملکی با «casa» (مؤنث مفرد) هماهنگ است؟',
      options: ['Minha', 'Meu', 'Meus', 'Minhas'],
      answer: 'Minha',
      explanationFa:
        'casa مؤنث مفرد است؛ ضمیر ملکی هم باید مؤنث مفرد باشد → minha.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q2',
      type: 'mcq',
      prompt: 'Complete: ___ filho é pequeno.',
      promptFa: 'کدام ضمیر ملکی با «filho» (مذکر مفرد) هماهنگ است؟',
      options: ['Meu', 'Minha', 'Meus', 'Minhas'],
      answer: 'Meu',
      explanationFa: 'filho مذکر مفرد است → meu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q3',
      type: 'fill-blank',
      prompt: '___ pais são muito educados.',
      promptFa: 'با «pais» (مذکر جمع) کامل کنید.',
      options: [],
      answer: 'Meus',
      explanationFa: 'pais مذکر جمع است → meus.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q4',
      type: 'mcq',
      prompt: 'Complete: ___ vozes serão ouvidas.',
      promptFa: 'با «vozes» (مؤنث جمع) و منظور «ما» کامل کنید.',
      options: ['Nossas', 'Nosso', 'Nossos', 'Nossa'],
      answer: 'Nossas',
      explanationFa: 'vozes مؤنث جمع است و معنی «مالِ ما» → nossas.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q5',
      type: 'fill-blank',
      prompt: 'Nós temos uma boa casa. Ela é ___ casa.',
      promptFa: 'با ضمیر ملکیِ «ما» و اسمِ مؤنث مفرد کامل کنید.',
      options: [],
      answer: 'nossa',
      explanationFa: 'صاحب «nós» و casa مؤنث مفرد → nossa.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q6',
      type: 'fill-blank',
      prompt: 'Ele tem uma amiga muito simpática. Ela é ___ amiga.',
      promptFa: 'با ضمیر ملکیِ سوم‌شخص کامل کنید (amiga مؤنث مفرد).',
      options: [],
      answer: 'sua',
      explanationFa:
        'صاحب سوم‌شخص و amiga مؤنث مفرد → sua (یا «amiga dele» برای رفع ابهام).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q7',
      type: 'fill-blank',
      prompt: 'Eu tenho um livro de fotografia. Ele é ___ livro.',
      promptFa: 'با ضمیر ملکیِ «من» و اسمِ مذکر مفرد کامل کنید.',
      options: [],
      answer: 'meu',
      explanationFa: 'صاحب «eu» و livro مذکر مفرد → meu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q8',
      type: 'fill-blank',
      prompt: 'Você carrega a mochila todos os dias. Ela é ___ mochila.',
      promptFa: 'با ضمیر ملکیِ «você» و اسمِ مؤنث مفرد کامل کنید.',
      options: [],
      answer: 'sua',
      explanationFa: 'صاحب «você» و mochila مؤنث مفرد → sua.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q9',
      type: 'fill-blank',
      prompt: 'Eu tenho um gato. Esse gato é ___.',
      promptFa: 'با ضمیر ملکیِ «من» (gato مذکر) کامل کنید.',
      options: [],
      answer: 'meu',
      explanationFa: 'gato مذکر مفرد و صاحب «eu» → meu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q10',
      type: 'fill-blank',
      prompt: 'Eu tenho uma moto. Essa moto é ___.',
      promptFa: 'با ضمیر ملکیِ «من» (moto مؤنث) کامل کنید.',
      options: [],
      answer: 'minha',
      explanationFa:
        'moto مؤنث مفرد و صاحب «eu» → minha؛ اشتباه رایج «meu moto» است.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q11',
      type: 'fill-blank',
      prompt: 'Você tem uma casa. Essa casa é ___.',
      promptFa: 'با ضمیر ملکیِ «você» (casa مؤنث) کامل کنید.',
      options: [],
      answer: 'sua',
      explanationFa: 'casa مؤنث مفرد و صاحب «você» → sua.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q12',
      type: 'fill-blank',
      prompt: 'Eu tenho uma bicicleta. Essa bicicleta é ___.',
      promptFa: 'با ضمیر ملکیِ «من» (bicicleta مؤنث) کامل کنید.',
      options: [],
      answer: 'minha',
      explanationFa: 'bicicleta مؤنث مفرد و صاحب «eu» → minha.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q13',
      type: 'fill-blank',
      prompt: 'Nós temos um apartamento. Esse apartamento é ___.',
      promptFa: 'با ضمیر ملکیِ «ما» (apartamento مذکر) کامل کنید.',
      options: [],
      answer: 'nosso',
      explanationFa: 'apartamento مذکر مفرد و صاحب «nós» → nosso.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q14',
      type: 'fill-blank',
      prompt: 'A gente tem uma loja. Essa loja é ___.',
      promptFa: 'با ضمیر ملکیِ «a gente» (= ما) و loja مؤنث کامل کنید.',
      options: [],
      answer: 'nossa',
      explanationFa:
        '«a gente» معنی «ما» می‌دهد و از nosso/nossa استفاده می‌کند؛ loja مؤنث → nossa.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q15',
      type: 'fill-blank',
      prompt:
        'Ontem à noite, eu liguei para ___ irmão que mora em outro país. (MEU/MINHA/NOSSO/NOSSA)',
      promptFa:
        'با یکی از MEU/MINHA/NOSSO/NOSSA کامل کنید (irmão مذکر، صاحب «eu»).',
      options: [],
      answer: 'meu',
      explanationFa: 'irmão مذکر مفرد و صاحب «eu» → meu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q16',
      type: 'fill-blank',
      prompt: 'Encontramos ___ apartamento ideal. (MEU/MINHA/NOSSO/NOSSA)',
      promptFa:
        'با یکی از MEU/MINHA/NOSSO/NOSSA کامل کنید (فعل encontramos = ما، apartamento مذکر).',
      options: [],
      answer: 'nosso',
      explanationFa:
        '«encontramos» اول‌شخص جمع است → ما؛ apartamento مذکر → nosso.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q17',
      type: 'fill-blank',
      prompt:
        'Queremos melhorar ___ comunicação com as pessoas. (MEU/MINHA/NOSSO/NOSSA)',
      promptFa:
        'با یکی از MEU/MINHA/NOSSO/NOSSA کامل کنید (queremos = ما، comunicação مؤنث).',
      options: [],
      answer: 'nossa',
      explanationFa: '«queremos» اول‌شخص جمع → ما؛ comunicação مؤنث → nossa.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q18',
      type: 'fill-blank',
      prompt:
        'Ontem preparei ___ mochila com roupa de ginástica. (MEU/MINHA/NOSSO/NOSSA)',
      promptFa:
        'با یکی از MEU/MINHA/NOSSO/NOSSA کامل کنید (preparei = من، mochila مؤنث).',
      options: [],
      answer: 'minha',
      explanationFa: '«preparei» اول‌شخص مفرد → من؛ mochila مؤنث → minha.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q19',
      type: 'fill-blank',
      prompt:
        'Eu falei com você e pedi emprestado o ___ celular e também a ___ senha do Wi-Fi. (SEU/SUA)',
      promptFa:
        'دو جای خالی را با SEU/SUA پر کنید (celular مذکر، senha مؤنث؛ صاحب «você»).',
      options: [],
      answer: 'seu / sua',
      explanationFa: 'celular مذکر → seu؛ senha مؤنث → sua؛ صاحب «você».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q20',
      type: 'mcq',
      prompt:
        'Eu falei com o Márcio e pedi emprestado o celular e a senha do Wi-Fi ___.',
      promptFa: 'برای «مالِ مارسیو» (یک مرد) کدام درست است؟',
      options: ['dele', 'dela', 'deles', 'seu'],
      answer: 'dele',
      explanationFa: 'Márcio یک مرد است → dele (= de + ele).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q21',
      type: 'mcq',
      prompt:
        'Vi uma foto na casa da Marisa e perguntei se era dela ou de ___ irmã.',
      promptFa:
        'کدام ضمیر ملکی جای خالی را کامل می‌کند (irmã مؤنث، اشاره به خواهرِ خودِ ماریسا)؟',
      options: ['sua', 'seu', 'dele', 'suas'],
      answer: 'sua',
      explanationFa: 'irmã مؤنث مفرد → sua (خواهرش).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q22',
      type: 'mcq',
      prompt: 'Qual forma indica posse de UMA mulher (ela)?',
      promptFa: 'کدام شکل مالکیتِ «او (زن)» را نشان می‌دهد؟',
      options: ['dela', 'dele', 'deles', 'de vocês'],
      answer: 'dela',
      explanationFa: 'dela = de + ela → مالِ او (زن).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q23',
      type: 'mcq',
      prompt: 'O adjetivo em português...',
      promptFa: 'صفت در پرتغالی چگونه رفتار می‌کند؟',
      options: [
        'varia em gênero e número',
        'nunca muda',
        'só muda no plural',
        'só muda no feminino',
      ],
      answer: 'varia em gênero e número',
      explanationFa:
        'صفت هم در جنس (مذکر/مؤنث) و هم در شمار (مفرد/جمع) تغییر می‌کند.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q24',
      type: 'fill-blank',
      prompt: 'AVIÕES RÁPID___',
      promptFa: 'پایانهٔ صفت را برای «aviões» (مذکر جمع) کامل کنید.',
      options: [],
      answer: 'rápidos',
      explanationFa: 'avião مذکر و جمع است → rápidos.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q25',
      type: 'fill-blank',
      prompt: 'BLUSA VELH___',
      promptFa: 'پایانهٔ صفت را برای «blusa» (مؤنث مفرد) کامل کنید.',
      options: [],
      answer: 'velha',
      explanationFa: 'blusa مؤنث مفرد → velha.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q26',
      type: 'fill-blank',
      prompt: 'CAMAS MACI__',
      promptFa: 'پایانهٔ صفت را برای «camas» (مؤنث جمع) کامل کنید.',
      options: [],
      answer: 'macias',
      explanationFa: 'cama مؤنث و جمع → macias.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q27',
      type: 'fill-blank',
      prompt: 'CANTOR FAMOS___',
      promptFa: 'پایانهٔ صفت را برای «cantor» (مذکر مفرد) کامل کنید.',
      options: [],
      answer: 'famoso',
      explanationFa: 'cantor مذکر مفرد → famoso.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q28',
      type: 'fill-blank',
      prompt: 'CARROS LENT____',
      promptFa: 'پایانهٔ صفت را برای «carros» (مذکر جمع) کامل کنید.',
      options: [],
      answer: 'lentos',
      explanationFa: 'carro مذکر و جمع → lentos.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q29',
      type: 'fill-blank',
      prompt: 'CHUVA GELAD___',
      promptFa: 'پایانهٔ صفت را برای «chuva» (مؤنث مفرد) کامل کنید.',
      options: [],
      answer: 'gelada',
      explanationFa: 'chuva مؤنث مفرد → gelada.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q30',
      type: 'fill-blank',
      prompt: 'COPO VAZI___',
      promptFa: 'پایانهٔ صفت را برای «copo» (مذکر مفرد) کامل کنید.',
      options: [],
      answer: 'vazio',
      explanationFa: 'copo مذکر مفرد → vazio.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q31',
      type: 'fill-blank',
      prompt: 'DIA FRI____',
      promptFa: 'پایانهٔ صفت را برای «dia» (مذکر مفرد) کامل کنید.',
      options: [],
      answer: 'frio',
      explanationFa: 'واژهٔ dia با اینکه به -a ختم می‌شود مذکر است → frio.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q32',
      type: 'mcq',
      prompt:
        'Complete com adjetivo adequado: O menino é muito ___, sempre acerta as questões.',
      promptFa: 'کدام صفت مناسب است (پسری که همیشه درست جواب می‌دهد)؟',
      options: ['inteligente', 'preguiçoso', 'triste', 'lento'],
      answer: 'inteligente',
      explanationFa: 'کسی که همیشه درست جواب می‌دهد → باهوش (inteligente).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q33',
      type: 'mcq',
      prompt:
        'Complete com adjetivo adequado: Mamãe precisa de uma roupa ___ para ir ao casamento.',
      promptFa: 'کدام صفت برای «لباسِ عروسی» مناسب است؟',
      options: ['elegante', 'suja', 'velha', 'rasgada'],
      answer: 'elegante',
      explanationFa: 'برای عروسی لباسِ شیک/مجلسی مناسب است → elegante.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q34',
      type: 'mcq',
      prompt:
        'Complete com adjetivo adequado: Não assisti ao filme porque ele é ___ demais.',
      promptFa: 'کدام صفت مناسب است (دلیلِ ندیدنِ فیلم)؟',
      options: ['longo', 'curto', 'bonito', 'novo'],
      answer: 'longo',
      explanationFa:
        'اگر فیلم را ندیدیم چون بیش از حد … بود، «longo demais» (خیلی طولانی) منطقی است.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q35',
      type: 'translate-pt-fa',
      prompt:
        'Menino que tem coragem = menino ___. Traduza o adjetivo para o persa.',
      promptFa: 'صفتِ متناظرِ «menino corajoso» را به فارسی بنویسید.',
      options: [],
      answer: 'شجاع',
      explanationFa: '«que tem coragem» → corajoso (شجاع).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q36',
      type: 'fill-blank',
      prompt: 'Filme que assusta = filme ___.',
      promptFa: 'عبارت را با صفتِ درست جایگزین کنید.',
      options: [],
      answer: 'assustador',
      explanationFa: '«que assusta» → assustador (ترسناک).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q37',
      type: 'fill-blank',
      prompt: 'Pessoa que tem preguiça = pessoa ___.',
      promptFa:
        'عبارت را با صفتِ درست (مؤنث، چون pessoa مؤنث است) جایگزین کنید.',
      options: [],
      answer: 'preguiçosa',
      explanationFa: 'pessoa مؤنث است → preguiçosa (تنبل).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q38',
      type: 'fill-blank',
      prompt: 'Revista da semana = revista ___.',
      promptFa: 'عبارت را با صفتِ درست جایگزین کنید.',
      options: [],
      answer: 'semanal',
      explanationFa: '«da semana» → semanal (هفتگی).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q39',
      type: 'fill-blank',
      prompt: 'Festa no mês de junho = festa ___.',
      promptFa: 'عبارت را با صفتِ درست جایگزین کنید.',
      options: [],
      answer: 'junina',
      explanationFa: '«no mês de junho» → junina (جشن سنتی ماه ژوئن).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q40',
      type: 'fill-blank',
      prompt: 'Queijo de Minas = queijo ___.',
      promptFa: 'عبارت را با صفتِ درست جایگزین کنید.',
      options: [],
      answer: 'mineiro',
      explanationFa: '«de Minas» → mineiro (میناسی).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q41',
      type: 'fill-blank',
      prompt: 'Pagamento feito por mês = pagamento ___.',
      promptFa: 'عبارت را با صفتِ درست جایگزین کنید.',
      options: [],
      answer: 'mensal',
      explanationFa: '«feito por mês» → mensal (ماهیانه).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q42',
      type: 'translate-fa-pt',
      prompt: '«خانهٔ من بزرگ است.» را به پرتغالی بنویسید.',
      promptFa: 'با ضمیر ملکیِ درست به پرتغالی ترجمه کنید.',
      options: [],
      answer: 'Minha casa é grande.',
      explanationFa: 'casa مؤنث مفرد → minha؛ اشتباه رایج «meu casa» است.',
      cefr: 'A1',
      skill: 'writing',
    },
    {
      id: 'course-aula-3-q43',
      type: 'order-words',
      prompt: 'Ordene: [dele / o / é / carro]',
      promptFa:
        'واژه‌ها را مرتب کنید تا جملهٔ «ماشین مالِ اوست (مرد)» ساخته شود.',
      options: ['dele', 'o', 'é', 'carro'],
      answer: 'o carro é dele',
      explanationFa: 'ساختار: حرف تعریف + اسم + فعل + dele → «o carro é dele».',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q44',
      type: 'translate-pt-fa',
      prompt:
        'Traduza para o persa: "Em que espelho ficou perdida a minha face?"',
      promptFa: 'این مصرع از شعر Retrato را به فارسی ترجمه کنید.',
      options: [],
      answer: 'در کدام آینه چهرهٔ من گم شد؟',
      explanationFa: 'minha face = چهرهٔ من (face مؤنث → minha).',
      cefr: 'A1',
      skill: 'reading',
    },
    {
      id: 'course-aula-3-q45',
      type: 'fill-blank',
      prompt: 'O carro é ___.',
      promptFa: 'با ضمیر ملکی کامل کنید (carro مذکر مفرد؛ مثلاً «مالِ من»).',
      options: [],
      answer: 'meu',
      explanationFa:
        'carro مذکر مفرد است؛ شکل مذکر مفرد لازم است → meu (یا seu/dele بسته به صاحب).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q46',
      type: 'fill-blank',
      prompt: '___ irmã virá nos visitar.',
      promptFa: 'با ضمیر ملکی کامل کنید (irmã مؤنث مفرد).',
      options: [],
      answer: 'minha',
      explanationFa: 'irmã مؤنث مفرد است → minha (یا sua بسته به صاحب).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q47',
      type: 'fill-blank',
      prompt: 'Este lanche é ___.',
      promptFa: 'با ضمیر ملکی کامل کنید (lanche مذکر مفرد).',
      options: [],
      answer: 'meu',
      explanationFa: 'lanche مذکر مفرد است → meu (یا seu/dele بسته به صاحب).',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q48',
      type: 'fill-blank',
      prompt: 'Quero ouvir o parecer ___.',
      promptFa: 'با ضمیر ملکی کامل کنید (parecer مذکر مفرد؛ نظرِ کسی).',
      options: [],
      answer: 'seu',
      explanationFa:
        'parecer مذکر مفرد است → seu (نظرِ تو/شما/او)؛ برای رفع ابهام dele/dela هم ممکن است.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q49',
      type: 'fill-blank',
      prompt: 'Eu tenho um livro. Esse livro é ___.',
      promptFa: 'با ضمیر ملکیِ «من» کامل کنید (livro مذکر مفرد).',
      options: [],
      answer: 'meu',
      explanationFa: 'livro مذکر مفرد و صاحب «eu» → meu.',
      cefr: 'A1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-3-q50',
      type: 'fill-blank',
      prompt: 'Tenho DVDs ___ em casa. (adjetivo adequado)',
      promptFa:
        'با صفتی مناسب کامل کنید (DVDs مذکر جمع؛ صفت باید مذکر جمع باشد).',
      options: [],
      answer: 'novos',
      explanationFa:
        'DVDs مذکر جمع است؛ نمونهٔ صفتِ مناسب → novos (نو). صفت در جنس و شمار هماهنگ می‌شود.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q51',
      type: 'fill-blank',
      prompt: 'Todos ficaram muito ___ com o e-mail. (adjetivo adequado)',
      promptFa: 'با صفتی مناسب کامل کنید (todos مذکر جمع).',
      options: [],
      answer: 'surpresos',
      explanationFa:
        'todos مذکر جمع → صفت هم مذکر جمع؛ نمونهٔ مناسب surpresos (شگفت‌زده).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q52',
      type: 'fill-blank',
      prompt: 'O filme era ___, por isso fiquei ___. (adjetivo adequado)',
      promptFa:
        'با صفتی مناسب هر دو جای خالی را کامل کنید (فیلم و حالِ گوینده).',
      options: [],
      answer: 'triste',
      explanationFa:
        'یک انتخابِ منطقی: «O filme era triste, por isso fiquei triste» (فیلم غمگین بود، پس غمگین شدم). triste یک شکل برای هر دو جنس دارد.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q53',
      type: 'fill-blank',
      prompt:
        'A partida estava ___, mesmo assim eles ganharam. (adjetivo adequado)',
      promptFa: 'با صفتی مناسب کامل کنید (partida مؤنث مفرد).',
      options: [],
      answer: 'difícil',
      explanationFa:
        'نمونهٔ مناسب: partida (بازی) difícil (سخت)؛ difícil یک شکل برای هر دو جنس دارد.',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q54',
      type: 'fill-blank',
      prompt: 'Camila ganhou um caderno ___ de seu pai. (adjetivo adequado)',
      promptFa: 'با صفتی مناسب کامل کنید (caderno مذکر مفرد).',
      options: [],
      answer: 'novo',
      explanationFa:
        'caderno مذکر مفرد → صفت مذکر مفرد؛ نمونهٔ مناسب novo (نو).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q55',
      type: 'fill-blank',
      prompt:
        'Janaina escreveu uma carta muito ___ para seu tio. (adjetivo adequado)',
      promptFa: 'با صفتی مناسب کامل کنید (carta مؤنث مفرد).',
      options: [],
      answer: 'carinhosa',
      explanationFa:
        'carta مؤنث مفرد → صفت مؤنث مفرد؛ نمونهٔ مناسب carinhosa (محبت‌آمیز).',
      cefr: 'A1',
      skill: 'vocab',
    },
    {
      id: 'course-aula-3-q56',
      type: 'fill-blank',
      prompt: 'Boletim da escola = boletim ___.',
      promptFa: 'عبارت را با صفتِ درست جایگزین کنید.',
      options: [],
      answer: 'escolar',
      explanationFa: '«da escola» → escolar (آموزشی/مدرسه‌ای).',
      cefr: 'A1',
      skill: 'vocab',
    },
  ],
  estimatedMinutes: 28,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 3 (کامل).',
};
