import type { CourseLesson } from '@/domain/content/schema';

export const aula13: CourseLesson = {
  id: 'course-aula-13',
  order: 13,
  aula: 'Aula 13',
  titleFa: 'قیدها (Advérbios)',
  titlePt: 'Advérbios',
  cefr: 'A2',
  summaryFa:
    'در این درس با «قید» (advérbio) در پرتغالی برزیلی آشنا می‌شوید؛ کلمه‌ای که معنای فعل، صفت یا قیدِ دیگر را تغییر می‌دهد و جمله را غنی‌تر می‌کند. قیدها کلماتی تغییرناپذیرند (شکلشان با جنس و شمار عوض نمی‌شود). ابتدا تعریف و طبقه‌بندی هفت‌گانهٔ قیدها را می‌بینید، سپس هر گروه را جداگانه یاد می‌گیرید: قید مکان (به‌همراه تفاوت مهم aqui/lá/aí/ali)، قید زمان، قید حالت (که بیشترشان به «-mente» ختم می‌شوند)، قید تأکید، قید نفی، قید شدت و قید تردید. هر بخش با مثال‌های واقعی و تمرین‌های جای‌خالی همراه است.',
  objectivesFa: [
    'تعریف قید و نقش آن در تغییر معنای فعل، صفت و قیدِ دیگر را بدانید.',
    'هفت گروه معناییِ قید را تشخیص دهید: مکان، زمان، حالت، تأکید، نفی، شدت و تردید.',
    'تفاوت چهار قید مکان aqui / lá / aí / ali را درست به‌کار ببرید.',
    'قیدهای پرکاربرد هر گروه را بشناسید و در جمله استفاده کنید.',
    'جای خالی جمله‌ها را با قید مناسب پر کنید.',
  ],
  sections: [
    {
      headingFa: '۱. قید چیست؟ (Advérbios)',
      bodyFa:
        'قید (advérbio) دسته‌ای از کلمات است که معنای فعل، صفت یا قیدِ دیگر را تغییر می‌دهد. قید جمله را غنی‌تر می‌کند و معنای بهتری به آن می‌دهد. نکتهٔ مهم: قیدها کلماتی «تغییرناپذیر» (invariáveis) هستند؛ یعنی شکلشان با جنس (مذکر/مؤنث) یا شمار (مفرد/جمع) عوض نمی‌شود. قید می‌تواند سه چیز را تغییر دهد:\n\n- فعل را: Ela dorme pouco. (او کم می‌خوابد)\n- صفت را: Esta aula é muito boa. (این درس خیلی خوب است)\n- قیدِ دیگر را: Ele cantou muito bem. (او خیلی خوب خواند)',
      examples: [
        {
          pt: 'Ela dorme pouco.',
          fa: 'او کم می‌خوابد.',
          pron: 'اِلا دُرمی پُوکو',
          note: 'قید «pouco» فعل «dormir» را تغییر می‌دهد.',
        },
        {
          pt: 'Esta aula é muito boa.',
          fa: 'این درس خیلی خوب است.',
          pron: 'اِستا آئولا اِ مویتو بُووا',
          note: 'قید «muito» صفت «boa» را تشدید می‌کند.',
        },
        {
          pt: 'Ele cantou muito bem.',
          fa: 'او خیلی خوب خواند.',
          pron: 'اِلی کانتُو مویتو بِین',
          note: 'قید «muito» قیدِ دیگر «bem» را تغییر می‌دهد.',
        },
      ],
    },
    {
      headingFa: '۲. طبقه‌بندی قیدها بر اساس معنا',
      bodyFa:
        'قیدها بر اساس معنا به هفت گروه اصلی تقسیم می‌شوند. نمونهٔ هر گروه:\n\n- مکان (Lugar): aqui, antes, dentro...\n- زمان (Tempo): hoje, logo, primeiro, ontem, tarde, outrora...\n- حالت (Modo): bem, mal, assim, melhor, pior, depressa...\n- تأکید (Afirmação): sim, certamente, realmente, decerto...\n- نفی (Negação): não, nem, nunca, jamais, de modo algum, de forma nenhuma...\n- شدت (Intensidade): muito, demais, pouco, tão, em excesso, bastante, mais, menos...\n- تردید (Dúvida): talvez, porventura, quiçá, provavelmente, possivelmente...',
      examples: [
        {
          pt: 'Lugar: aqui / Tempo: hoje / Modo: bem',
          fa: 'مکان: اینجا / زمان: امروز / حالت: خوب',
          pron: 'آکی / اُژی / بِین',
        },
        {
          pt: 'Afirmação: sim / Negação: não / Dúvida: talvez',
          fa: 'تأکید: بله / نفی: نه / تردید: شاید',
          pron: 'سین / نائو / تالوِس',
        },
      ],
    },
    {
      headingFa: '۳. قید مکان (Advérbios de lugar)',
      bodyFa:
        'قیدهای مکان به جمله می‌گویند که کاری «کجا» رخ می‌دهد؛ یعنی به شناسایی مکان یا فضای یک عمل کمک می‌کنند.\n\nقیدهای مکان: aqui (اینجا)، ali (آنجا)، cá (اینجا)، lá (آنجا)، atrás (پشت)، perto (نزدیک)، abaixo (پایین‌تر)، acima (بالاتر)، antes (پیش‌تر)، dentro (داخل)، fora (بیرون)، além (فراتر)، longe (دور) و مانند اینها.',
      examples: [
        {
          pt: 'Meu telefone celular estava embaixo da cama.',
          fa: 'موبایلم زیر تخت بود.',
          pron: 'مِئو تِلِفُنی سِلولار اِستاوا اِمبایشو دا کاما',
        },
        {
          pt: 'Como é a Praia de Ipanema? Eu nunca fui lá.',
          fa: 'ساحل ایپانما چطور است؟ من هرگز آنجا نرفته‌ام.',
          pron: 'کُمو اِ آ پرایا جی ایپانِما؟ اِئو نونکا فویی لا',
        },
        {
          pt: 'O professor mora muito longe da escola.',
          fa: 'معلم خیلی دور از مدرسه زندگی می‌کند.',
          pron: 'او پروفِسور مُرا مویتو لُنژی دا اِسکولا',
        },
        {
          pt: 'Posso ir aí?',
          fa: 'می‌توانم آنجا (پیش تو) بیایم؟',
          pron: 'پُسو ایر آیی؟',
          note: '«aí» یعنی جایی نزدیک مخاطب.',
        },
        {
          pt: 'O sol está bem forte aqui na praia.',
          fa: 'اینجا در ساحل، آفتاب خیلی قوی است.',
          pron: 'او سُل اِستا بِین فُرتی آکی نا پرایا',
        },
        {
          pt: 'A moça deixou sua bolsa ali no canto da sala.',
          fa: 'دختر کیفش را آنجا در گوشهٔ اتاق گذاشت.',
          pron: 'آ مُسا دِیشُو سوا بُلسا آلی نو کانتو دا سالا',
        },
      ],
    },
    {
      headingFa: '۴. تفاوت AQUI / LÁ / AÍ / ALI',
      bodyFa:
        'این چهار قید مکان معنای نزدیکی دارند اما فاصله‌شان فرق می‌کند. این تفاوت برای فارسی‌زبانان کلیدی است چون در فارسی بیشتر با «اینجا/آنجا» بیان می‌شود:\n\n- AQUI = نزدیک کسی که حرف می‌زند (گوینده).\n- LÁ = دور از هر دو نفر (هم گوینده هم مخاطب).\n- AÍ = نزدیک کسی که با او حرف می‌زنیم (مخاطب).\n- ALI = فاصلهٔ نزدیک نسبت به یک نقطهٔ مرجع (آنجا، جای مشخص).',
      examples: [
        {
          pt: 'Aqui na minha cidade chove muito.',
          fa: 'اینجا در شهرِ من زیاد باران می‌بارد.',
          pron: 'آکی نا مینیا سیدادی شُوی مویتو',
          note: 'AQUI = نزدیک گوینده.',
        },
        {
          pt: 'Tenho amigos lá na Alemanha.',
          fa: 'من آنجا در آلمان دوستانی دارم.',
          pron: 'تِنیو آمیگوس لا نا آلِمانیا',
          note: 'LÁ = دور از هر دو نفر.',
        },
        {
          pt: 'Aí no seu bairro tem muitas lojas.',
          fa: 'آنجا در محلهٔ تو مغازه‌های زیادی هست.',
          pron: 'آیی نو سِئو بایرو تِین مویتاس لُژاس',
          note: 'AÍ = نزدیک مخاطب.',
        },
        {
          pt: 'Ali perto do centro tem um metrô.',
          fa: 'آنجا نزدیک مرکز شهر یک مترو هست.',
          pron: 'آلی پِرتو دو سِنترو تِین اون مِترُ',
          note: 'ALI = نزدیک یک نقطهٔ مرجع.',
        },
      ],
    },
    {
      headingFa: '۵. قید زمان (Advérbios de tempo)',
      bodyFa:
        'قیدهای زمان دوره‌ای را که یک رویداد در آن رخ داده مشخص می‌کنند و فعل را توضیح، توصیف یا تغییر می‌دهند.\n\nقیدهای زمان: agora (الان)، já (دیگر/همین حالا)، ainda (هنوز)، logo (به‌زودی)، amanhã (فردا)، primeiro (اول)، hoje (امروز)، ontem (دیروز)، cedo (زود)، tarde (دیر)، sempre (همیشه)، nunca (هرگز)، outrora (در گذشته) و مانند اینها.\n\nمثال توضیحی: «Eu acordei cedo» (من زود بیدار شدم). اگر فقط بگوییم «Eu acordei» معنا کامل است اما اطلاعات اضافی نداریم. وقتی قید «cedo» را اضافه می‌کنیم، اطلاعاتِ زمانِ بیدار شدن را به جمله می‌افزاییم. پس «cedo» معنای فعلِ «acordar» را تغییر می‌دهد.',
      examples: [
        {
          pt: 'Eu acordei cedo.',
          fa: 'من زود بیدار شدم.',
          pron: 'اِئو آکُردِی سِدو',
        },
        {
          pt: 'Volto já para nossa reunião.',
          fa: 'همین حالا برای جلسه‌مان برمی‌گردم.',
          pron: 'وُلتو ژا پارا نُسا رِئونیائو',
        },
        {
          pt: 'Ontem estava chovendo muito.',
          fa: 'دیروز باران زیادی می‌بارید.',
          pron: 'اُنتِین اِستاوا شُوِندو مویتو',
        },
      ],
    },
    {
      headingFa: '۶. قید حالت (Advérbios de modo)',
      bodyFa:
        'قیدهای حالت نشان می‌دهند که کاری «چگونه» یا به «چه شیوه‌ای» انجام می‌شود. خیلی رایج است که قیدهای حالت به پسوند «-mente» ختم شوند (معادل «-انه/-وار» فارسی).\n\nقیدهای حالت: assim (این‌طور)، bem (خوب)، mal (بد)، depressa (تند)، devagar (آهسته)، melhor (بهتر)، pior (بدتر) و بخشی از کلماتِ ختم‌شونده به «-mente»: alegremente (شادمانه)، docemente (به‌نرمی)، tristemente (غمگینانه) و مانند اینها.',
      examples: [
        {
          pt: 'A cantora canta bem.',
          fa: 'خواننده (زن) خوب می‌خواند.',
          pron: 'آ کانتُرا کانتا بِین',
        },
        {
          pt: 'Ela canta mal.',
          fa: 'او (زن) بد می‌خواند.',
          pron: 'اِلا کانتا مال',
        },
        {
          pt: 'Eu nunca fico nervoso em público. Consigo falar naturalmente.',
          fa: 'من هرگز جلوی جمع مضطرب نمی‌شوم. می‌توانم طبیعی صحبت کنم.',
          pron: 'اِئو نونکا فیکو نِروُزو اِین پوبلیکو. کُنسیگو فالار ناتورالمِنتی',
          note: '«naturalmente» قیدِ ختم‌شونده به -mente.',
        },
        {
          pt: 'Eu consigo compreender português facilmente.',
          fa: 'من می‌توانم به‌راحتی پرتغالی را بفهمم.',
          pron: 'اِئو کُنسیگو کُمپرِئِندِر پُرتوگِس فاسیلمِنتی',
        },
        {
          pt: 'O rio secou rapidamente.',
          fa: 'رودخانه به‌سرعت خشک شد.',
          pron: 'او هیو سِکُو هاپیدامِنتی',
        },
        {
          pt: 'Fui calorosamente recebido pela vizinhança.',
          fa: 'همسایه‌ها گرم از من استقبال کردند.',
          pron: 'فویی کالوروزامِنتی هِسِبیدو پِلا ویزینیانسا',
        },
      ],
    },
    {
      headingFa: '۷. قید تأکید (Advérbios de afirmação)',
      bodyFa:
        'این قیدها برای افزودن حسِ «تأیید و اطمینان» به جمله به‌کار می‌روند.\n\nقیدهای تأکید: sim (بله)، certamente (قطعاً)، realmente (واقعاً)، efetivamente (به‌واقع)، decerto (بی‌شک) و مانند اینها. عبارت «com certeza» (با اطمینان) هم پرکاربرد است.',
      examples: [
        {
          pt: 'Eles certamente visitarão o Brasil.',
          fa: 'آن‌ها قطعاً از برزیل دیدن خواهند کرد.',
          pron: 'اِلیس سِرتامِنتی ویزیتارائو او برازیل',
        },
        {
          pt: 'Sim! Eu estou amando aprender português.',
          fa: 'بله! من عاشق یادگیری پرتغالی شده‌ام.',
          pron: 'سین! اِئو اِستُ آماندو آپرِندِر پُرتوگِس',
        },
        {
          pt: 'Nós nos veremos de novo com certeza.',
          fa: 'ما حتماً دوباره همدیگر را خواهیم دید.',
          pron: 'نُس نُس وِرِموس جی نُوو کُن سِرتِزا',
        },
        {
          pt: 'Sim, eu gosto de suco de laranja.',
          fa: 'بله، من آب پرتقال دوست دارم.',
          pron: 'سین، اِئو گُستو جی سوکو جی لارانژا',
        },
        {
          pt: 'Amanhã certamente teremos avaliação.',
          fa: 'فردا قطعاً امتحان خواهیم داشت.',
          pron: 'آمانیا سِرتامِنتی تِرِموس آوالیاسائو',
        },
        {
          pt: 'Realmente eles são inteligentes.',
          fa: 'واقعاً آن‌ها باهوش‌اند.',
          pron: 'هِئالمِنتی اِلیس سائو اینتِلیژِنتِس',
        },
        {
          pt: 'Com certeza eles serão aprovados.',
          fa: 'مطمئناً آن‌ها قبول خواهند شد.',
          pron: 'کُن سِرتِزا اِلیس سِرائو آپروادوس',
        },
      ],
    },
    {
      headingFa: '۸. قید نفی (Advérbios de negação)',
      bodyFa:
        'این قیدها برای نفی کردن چیزی یا دادن اطلاعاتِ منفی به‌کار می‌روند.\n\nقیدهای نفی: não (نه)، nem (نه حتی)، nunca (هرگز)، jamais (هرگز/به‌هیچ‌وجه)، de modo algum (به‌هیچ‌طریق)، de forma nenhuma (به‌هیچ‌وجه)، de jeito nenhum (به‌هیچ‌وجه) و مانند اینها.',
      examples: [
        {
          pt: 'Eu não moro no Rio de Janeiro.',
          fa: 'من در ریو دو ژانیرو زندگی نمی‌کنم.',
          pron: 'اِئو نائو مُرو نو هیو جی ژانِیرو',
        },
        {
          pt: 'Ela nunca vai à praia durante a semana.',
          fa: 'او در طول هفته هرگز به ساحل نمی‌رود.',
          pron: 'اِلا نونکا وای آ پرایا دورانتی آ سِمانا',
        },
        {
          pt: 'De jeito nenhum eu faria isso.',
          fa: 'به‌هیچ‌وجه این کار را نمی‌کردم.',
          pron: 'جی ژِیتو نِنیون اِئو فاریا ایسو',
        },
        {
          pt: 'Eu jamais voltarei a falar com eles.',
          fa: 'من هرگز دوباره با آن‌ها حرف نخواهم زد.',
          pron: 'اِئو ژامایس وُلتارِی آ فالار کُن اِلیس',
        },
        {
          pt: 'Ele nem comeu a sobremesa e já vai embora.',
          fa: 'او حتی دسر را هم نخورد و دارد می‌رود.',
          pron: 'اِلی نِین کُمِئو آ سُبرِمِزا ای ژا وای اِمبُرا',
        },
      ],
    },
    {
      headingFa: '۹. قید شدت (Advérbios de intensidade)',
      bodyFa:
        'این قیدها برای توصیف شدتِ یک جمله و دادن تأکید بیشتر به گفته به‌کار می‌روند. آن‌ها درجه (بالا یا پایین) را نشان می‌دهند و نیرو یا سطحِ یک عمل، ویژگی یا موقعیت را بیان می‌کنند.\n\nقیدهای شدت: muito (خیلی)، pouco (کم)، bastante (به‌قدر کافی/زیاد)، tão (این‌قدر)، quase (تقریباً)، nada (اصلاً)، demais (بیش از حد)، em excesso (به‌افراط)، mais (بیشتر)، menos (کمتر) و مانند اینها.\n\nمثال: «Eu estou muito feliz» (من خیلی خوشحالم). اینجا قید «muito» معنای صفتِ «feliz» را که بعد از آن می‌آید تشدید می‌کند؛ پس من فقط خوشحال نیستم، خیلییی خوشحالم.',
      examples: [
        {
          pt: 'Eu estou muito feliz.',
          fa: 'من خیلی خوشحالم.',
          pron: 'اِئو اِستُ مویتو فِلیس',
        },
        {
          pt: 'Eu estudei pouco.',
          fa: 'من کم درس خواندم.',
          pron: 'اِئو اِستودِی پُوکو',
        },
        {
          pt: 'Eu almocei bastante macarrão.',
          fa: 'من برای ناهار مقدار زیادی ماکارونی خوردم.',
          pron: 'اِئو آلمُسِی باستانتی ماکاهائو',
        },
        {
          pt: 'O rio secou demais.',
          fa: 'رودخانه بیش از حد خشک شد.',
          pron: 'او هیو سِکُو دِمایس',
        },
      ],
    },
    {
      headingFa: '۱۰. قید تردید (Advérbios de dúvida)',
      bodyFa:
        'این قیدها برای نشان دادن عدم‌قطعیت یا تردید در جمله‌ها به‌کار می‌روند.\n\nقیدهای تردید: talvez (شاید)، porventura (احتمالاً/شاید)، quiçá (شاید)، provavelmente (احتمالاً)، possivelmente (به‌احتمال زیاد).',
      examples: [
        {
          pt: 'Amanhã talvez faça sol.',
          fa: 'فردا شاید آفتابی باشد.',
          pron: 'آمانیا تالوِس فاسا سُل',
        },
        {
          pt: 'Possivelmente a empresa entrará em contato.',
          fa: 'به‌احتمال زیاد شرکت تماس خواهد گرفت.',
          pron: 'پُسیوِلمِنتی آ اِمپرِزا اِنترارا اِین کُنتاتو',
        },
        {
          pt: 'São 12:00 horas e ela, provavelmente, irá almoçar.',
          fa: 'ساعت ۱۲:۰۰ است و او احتمالاً می‌رود ناهار بخورد.',
          pron: 'سائو دُزی اُراس ای اِلا، پروواوِلمِنتی، ایرا آلمُسار',
        },
      ],
    },
  ],
  keyPointsFa: [
    'قید معنای فعل، صفت یا قیدِ دیگر را تغییر می‌دهد و «تغییرناپذیر» است (با جنس و شمار عوض نمی‌شود).',
    'هفت گروه قید: مکان، زمان، حالت، تأکید، نفی، شدت و تردید.',
    'AQUI = نزدیک گوینده، AÍ = نزدیک مخاطب، ALI = نزدیک یک مرجع، LÁ = دور از هر دو.',
    'بیشتر قیدهای حالت به «-mente» ختم می‌شوند (naturalmente, facilmente, rapidamente).',
    'muito پرکاربردترین قید شدت است و صفت یا قید بعد از خود را تشدید می‌کند.',
  ],
  quiz: [
    {
      id: 'course-aula-13-q1',
      type: 'mcq',
      prompt: 'O que um advérbio modifica?',
      promptFa: 'قید معنای کدام‌ها را تغییر می‌دهد؟',
      options: [
        'فعل، صفت و قیدِ دیگر',
        'فقط اسم',
        'فقط ضمیر',
        'فقط حرف اضافه',
      ],
      answer: 'فعل، صفت و قیدِ دیگر',
      explanationFa: 'قید معنای فعل، صفت یا قیدِ دیگر را تغییر می‌دهد و کلمه‌ای تغییرناپذیر است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q2',
      type: 'mcq',
      prompt: 'A qual classe pertence "hoje"?',
      promptFa: '«hoje» جزو کدام گروه قید است؟',
      options: ['زمان (Tempo)', 'مکان (Lugar)', 'حالت (Modo)', 'شدت (Intensidade)'],
      answer: 'زمان (Tempo)',
      explanationFa: '«hoje» یعنی امروز و قید زمان است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q3',
      type: 'mcq',
      prompt: 'Qual advérbio indica algo LONGE das duas pessoas?',
      promptFa: 'کدام قید نشان‌دهندهٔ جایی دور از هر دو نفر است؟',
      options: ['lá', 'aqui', 'aí', 'cá'],
      answer: 'lá',
      explanationFa: 'LÁ یعنی دور از هر دو نفر (گوینده و مخاطب).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q4',
      type: 'mcq',
      prompt: '"Aí" refere-se a um lugar próximo de quem?',
      promptFa: '«aí» به مکانی نزدیک چه کسی اشاره دارد؟',
      options: ['مخاطب', 'گوینده', 'شخص سوم', 'هیچ‌کس'],
      answer: 'مخاطب',
      explanationFa: 'AÍ یعنی نزدیک کسی که با او حرف می‌زنیم (مخاطب).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q5',
      type: 'fill-blank',
      prompt: 'Minha bolsa está _____ da mesa. (advérbio de lugar)',
      promptFa: 'با قید مکان کامل کنید: کیف من ___ میز است.',
      options: [],
      answer: 'embaixo',
      explanationFa: '«embaixo da mesa» یعنی زیر میز؛ قید مکان.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q6',
      type: 'fill-blank',
      prompt: 'O gato está _____ do carro. (advérbio de lugar)',
      promptFa: 'با قید مکان کامل کنید: گربه ___ ماشین است.',
      options: [],
      answer: 'embaixo',
      explanationFa: '«embaixo do carro» یعنی زیر ماشین؛ قید مکان.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q7',
      type: 'fill-blank',
      prompt: '_____ no Brasil todos falam português. (advérbio de lugar)',
      promptFa: 'با قید مکان کامل کنید: ___ در برزیل همه پرتغالی حرف می‌زنند.',
      options: [],
      answer: 'Aqui',
      explanationFa: 'اگر گوینده در برزیل باشد «Aqui no Brasil» (اینجا در برزیل) درست است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q8',
      type: 'fill-blank',
      prompt: '_____ de casa é muito quente. (advérbio de lugar)',
      promptFa: 'با قید مکان کامل کنید: ___ خانه خیلی گرم است.',
      options: [],
      answer: 'Dentro',
      explanationFa: '«Dentro de casa» یعنی داخل خانه؛ قید مکان.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q9',
      type: 'fill-blank',
      prompt: '_____ já posso fazer a prova. (advérbio de tempo)',
      promptFa: 'با قید زمان کامل کنید: ___ می‌توانم امتحان بدهم.',
      options: [],
      answer: 'Agora',
      explanationFa: '«Agora já» یعنی همین حالا؛ قید زمان.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q10',
      type: 'fill-blank',
      prompt: '_____ está na hora de ir embora. (advérbio de tempo)',
      promptFa: 'با قید زمان کامل کنید: ___ وقتِ رفتن است.',
      options: [],
      answer: 'Já',
      explanationFa: '«Já está na hora» یعنی دیگر وقتش شده؛ قید زمان.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q11',
      type: 'fill-blank',
      prompt: 'Não sei _____ se quero viajar. (advérbio de tempo)',
      promptFa: 'با قید زمان کامل کنید: هنوز نمی‌دانم می‌خواهم سفر کنم یا نه.',
      options: [],
      answer: 'ainda',
      explanationFa: '«ainda» یعنی هنوز؛ قید زمان.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q12',
      type: 'fill-blank',
      prompt: '_____ voltarei aos meus 10 anos. (advérbio de tempo)',
      promptFa: 'با قید زمان کامل کنید: ___ به ۱۰ سالگی‌ام بازنخواهم گشت.',
      options: [],
      answer: 'Nunca',
      explanationFa: '«Nunca» یعنی هرگز؛ قید زمان (و نفی).',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q13',
      type: 'fill-blank',
      prompt: 'Ele está andando muito _____. (advérbio de modo)',
      promptFa: 'با قید حالت کامل کنید: او خیلی ___ راه می‌رود.',
      options: [],
      answer: 'devagar',
      explanationFa: '«devagar» یعنی آهسته؛ قید حالت.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q14',
      type: 'fill-blank',
      prompt: 'Ele canta _____ do que ela. (advérbio de modo)',
      promptFa: 'با قید حالت کامل کنید: او ___ از او (زن) می‌خواند.',
      options: [],
      answer: 'melhor',
      explanationFa: '«melhor do que» یعنی بهتر از؛ قید حالت در مقایسه.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q15',
      type: 'fill-blank',
      prompt: 'Você foi _____ na prova? (advérbio de modo)',
      promptFa: 'با قید حالت کامل کنید: در امتحان ___ بودی؟',
      options: [],
      answer: 'bem',
      explanationFa: '«ir bem na prova» یعنی در امتحان خوب عمل کردن؛ قید حالت.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q16',
      type: 'fill-blank',
      prompt: '_____ acabei meu curso! (advérbio de modo terminado em -mente)',
      promptFa: 'با قید حالتِ ختم‌شونده به -mente کامل کنید: ___ دوره‌ام را تمام کردم!',
      options: [],
      answer: 'Finalmente',
      explanationFa: '«Finalmente» یعنی بالاخره؛ قید حالتِ ختم‌شونده به -mente.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q17',
      type: 'fill-blank',
      prompt: '_____ eu quero ter a cidadania brasileira. (advérbio de afirmação)',
      promptFa: 'با قید تأکید کامل کنید: ___ می‌خواهم تابعیت برزیل را داشته باشم.',
      options: [],
      answer: 'Certamente',
      explanationFa: '«Certamente» یعنی قطعاً؛ قید تأکید.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q18',
      type: 'fill-blank',
      prompt: '_____ passarei no meu exame. (advérbio de afirmação)',
      promptFa: 'با قید تأکید کامل کنید: ___ در امتحانم قبول می‌شوم.',
      options: [],
      answer: 'Certamente',
      explanationFa: '«Certamente» (یا Com certeza) یعنی قطعاً؛ قید تأکید.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q19',
      type: 'fill-blank',
      prompt: '_____ quero morar aqui. (advérbio de afirmação)',
      promptFa: 'با قید تأکید کامل کنید: ___ می‌خواهم اینجا زندگی کنم.',
      options: [],
      answer: 'Realmente',
      explanationFa: '«Realmente» یعنی واقعاً؛ قید تأکید.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q20',
      type: 'fill-blank',
      prompt: '_____ serei aprovado. (advérbio de afirmação)',
      promptFa: 'با قید تأکید کامل کنید: ___ قبول خواهم شد.',
      options: [],
      answer: 'Decerto',
      explanationFa: '«Decerto» یعنی بی‌شک؛ قید تأکید.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q21',
      type: 'fill-blank',
      prompt: 'Ela _____ viu o que ele fez. (advérbio de negação)',
      promptFa: 'با قید نفی کامل کنید: او ندید که او (مرد) چه کرد.',
      options: [],
      answer: 'não',
      explanationFa: '«não» یعنی نه؛ رایج‌ترین قید نفی.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q22',
      type: 'fill-blank',
      prompt: '_____ entrarei nesse elevador sozinho. (advérbio de negação)',
      promptFa: 'با قید نفی کامل کنید: ___ تنها وارد این آسانسور نمی‌شوم.',
      options: [],
      answer: 'Nunca',
      explanationFa: '«Nunca» یعنی هرگز؛ قید نفی.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q23',
      type: 'fill-blank',
      prompt: '_____ pegarei o que não é meu. (advérbio de negação)',
      promptFa: 'با قید نفی کامل کنید: ___ چیزی را که مالِ من نیست برنمی‌دارم.',
      options: [],
      answer: 'Jamais',
      explanationFa: '«Jamais» یعنی هرگز/به‌هیچ‌وجه؛ قید نفی قوی‌تر از nunca.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q24',
      type: 'fill-blank',
      prompt: 'Eles _____ esperaram a luz verde acender e já atravessaram a rua. (advérbio de negação)',
      promptFa: 'با قید نفی کامل کنید: آن‌ها ___ منتظر سبز شدن چراغ شدند و از خیابان رد شدند.',
      options: [],
      answer: 'nem',
      explanationFa: '«nem» یعنی حتی ... هم نه؛ قید نفی.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q25',
      type: 'fill-blank',
      prompt: 'Hoje estou _____ bem. (advérbio de intensidade)',
      promptFa: 'با قید شدت کامل کنید: امروز ___ خوبم.',
      options: [],
      answer: 'muito',
      explanationFa: '«muito bem» یعنی خیلی خوب؛ قید شدت.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q26',
      type: 'fill-blank',
      prompt: 'Ele tem _____ tempo para ler. (advérbio de intensidade)',
      promptFa: 'با قید شدت کامل کنید: او ___ وقت برای خواندن دارد.',
      options: [],
      answer: 'pouco',
      explanationFa: '«pouco tempo» یعنی وقتِ کم؛ قید شدت.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q27',
      type: 'fill-blank',
      prompt: 'Ele tem _____ tempo para ler do que ela. (advérbio de intensidade)',
      promptFa: 'با قید شدت (مقایسه) کامل کنید: او ___ وقت برای خواندن دارد تا او (زن).',
      options: [],
      answer: 'mais',
      explanationFa: '«mais ... do que» یعنی بیشتر از؛ قید شدت در مقایسه.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q28',
      type: 'fill-blank',
      prompt: 'Eles formam um casal _____ bonito! (advérbio de intensidade)',
      promptFa: 'با قید شدت کامل کنید: آن‌ها زوجِ ___ زیبایی هستند!',
      options: [],
      answer: 'muito',
      explanationFa: '«muito bonito» یعنی خیلی زیبا؛ قید شدت. «tão bonito» هم پذیرفتنی است.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q29',
      type: 'fill-blank',
      prompt: 'Eles estavam cansados _____. (advérbio de intensidade)',
      promptFa: 'با قید شدت کامل کنید: آن‌ها ___ خسته بودند.',
      options: [],
      answer: 'demais',
      explanationFa: '«cansados demais» یعنی بیش از حد خسته؛ قید شدت.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q30',
      type: 'fill-blank',
      prompt: '_____ eu vá viajar para a praia. (advérbio de dúvida)',
      promptFa: 'با قید تردید کامل کنید: ___ به سفرِ ساحل بروم.',
      options: [],
      answer: 'Talvez',
      explanationFa: '«Talvez» یعنی شاید؛ قید تردید.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q31',
      type: 'fill-blank',
      prompt: '_____ serei contratado. (advérbio de dúvida)',
      promptFa: 'با قید تردید کامل کنید: ___ استخدام خواهم شد.',
      options: [],
      answer: 'Provavelmente',
      explanationFa: '«Provavelmente» یعنی احتمالاً؛ قید تردید.',
      cefr: 'A2',
      skill: 'grammar',
    },
    {
      id: 'course-aula-13-q32',
      type: 'translate-pt-fa',
      prompt: 'Traduza para o persa: "Ele cantou muito bem."',
      promptFa: 'این جمله را به فارسی ترجمه کنید.',
      options: [],
      answer: 'او خیلی خوب خواند.',
      explanationFa: 'قید «muito» قیدِ «bem» را تشدید می‌کند و هر دو فعل «cantar» را توصیف می‌کنند.',
      cefr: 'A2',
      skill: 'reading',
    },
    {
      id: 'course-aula-13-q33',
      type: 'translate-fa-pt',
      prompt: '«فردا شاید آفتابی باشد.» را به پرتغالی بنویسید.',
      promptFa: 'با قید تردید به پرتغالی برزیلی ترجمه کنید.',
      options: [],
      answer: 'Amanhã talvez faça sol.',
      explanationFa: '«talvez» قید تردید است و «amanhã» قید زمان.',
      cefr: 'A2',
      skill: 'writing',
    },
  ],
  estimatedMinutes: 25,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 13 (کامل).',
};
