import type { CourseLesson } from '@/domain/content/schema';

export const aula12: CourseLesson = {
  id: 'course-aula-12',
  order: 12,
  aula: 'Aula 12',
  titleFa: 'مطابقت اسمی و فعلی (Concordância Nominal e Verbal)',
  titlePt: 'Concordância Nominal e Verbal',
  cefr: 'B1',
  summaryFa:
    'در این درس دو نوع «مطابقت» (concordância) در پرتغالی برزیلی را کامل یاد می‌گیرید. اول مطابقت اسمی (Concordância Nominal): چطور حرف تعریف، ضمیر، عدد و صفت باید در جنس (مذکر/مؤنث) و شمار (مفرد/جمع) با اسمی که به آن اشاره دارند هماهنگ شوند؛ همراه با قاعدهٔ صفتی که به چند اسم اشاره دارد، تفاوت «muito» به‌عنوان ضمیر و قید، و کاربرد «anexo / em anexo» و واژه‌های پرمشکل مثل «meio»، «menos»، «só» و «quite». سپس مطابقت فعلی (Concordância Verbal): چطور فعل در شخص و شمار با فاعل هماهنگ می‌شود، از جمله فاعل مرکب و کاربرد ویژهٔ «a gente». همهٔ مثال‌ها و همهٔ تمرین‌های جزوه (بیش از سی تمرین: پرکردن جای خالی، یافتن و اصلاح خطا) در این درس بازتولید شده‌اند.',
  objectivesFa: [
    'قاعدهٔ کلی مطابقت اسمی را بشناسید: حرف تعریف، ضمیر، عدد و صفت با اسم در جنس و شمار مطابقت می‌کنند.',
    'وقتی یک صفت به چند اسم اشاره دارد، بدانید چه زمانی مفرد و چه زمانی جمع/مذکر می‌شود.',
    'تفاوت «muito» به‌عنوان ضمیر (متغیر) و قید (ثابت) را به‌کار ببرید.',
    'کاربرد درست «anexo/anexa/anexos/anexas» در برابر «em anexo» (تغییرناپذیر) را بدانید.',
    'واژه‌های پرمشکل «meio»، «menos» (نه «menas»)، «só/sós»، «quite/quites» را درست به‌کار ببرید.',
    'قاعدهٔ مطابقت فعلی را بشناسید: فعل در شخص و شمار با فاعل هماهنگ می‌شود.',
    'با فاعل مرکب (مثلاً «eu e meu amigo») و با «a gente» فعل را درست صرف کنید.',
    'خطاهای رایج مطابقت اسمی و فعلی را در جمله پیدا و اصلاح کنید.',
  ],
  sections: [
    {
      headingFa:
        '۱. مطابقت اسمی ـ قاعدهٔ کلی (Concordância Nominal — Regra Geral)',
      bodyFa:
        'در مطابقت اسمی، حرف تعریف (artigo)، ضمیر (pronome)، عدد (numeral) و صفت (adjetivo) باید در جنس (مذکر/مؤنث) و شمار (مفرد/جمع) با اسمی (substantivo) که به آن اشاره دارند هماهنگ باشند.\n\nمثال کلیدی جزوه:\nOs nossos dois brinquedos preferidos estão quebrados.\n= اسباب‌بازی‌های موردعلاقهٔ ما هر دو شکسته‌اند.\n\nتحلیل: اسمِ مرکزی «brinquedos» مذکر و جمع است. پس همهٔ همراهانش هم مذکرِ جمع‌اند:\n- Os = حرف تعریفِ مذکرِ جمع\n- nossos = ضمیرِ مذکرِ جمع\n- dois = عددِ مذکر\n- preferidos = صفتِ مذکرِ جمع\n\nچون همه به «brinquedos» (مذکر/جمع) اشاره دارند، همگی مذکرِ جمع شده‌اند. نکته برای فارسی‌زبان: در فارسی صفت با جنس و شمار تغییر نمی‌کند، اما در پرتغالی حتماً باید تغییر کند.',
      examples: [
        {
          pt: 'Os nossos dois brinquedos preferidos estão quebrados.',
          fa: 'دو اسباب‌بازیِ موردعلاقهٔ ما شکسته‌اند.',
          pron: 'اوس نُسوس دُیس برینکِدوس پرِفِریدوس اِستائو کِبرادوس',
          note: 'artigo + pronome + numeral + adjetivo همه با اسم مذکرِ جمع «brinquedos» هماهنگ شده‌اند.',
        },
      ],
    },
    {
      headingFa: '۲. نمونه‌های مطابقت اسمی (Exemplos)',
      bodyFa:
        'این نه جملهٔ جزوه مطابقت اسمی را در حالت‌های گوناگون نشان می‌دهند. به‌ویژه جمله‌های ۷، ۸ و ۹ نکتهٔ مهمی دارند: وقتی یک صفت بعد از چند اسم می‌آید، یا می‌تواند فقط با نزدیک‌ترین اسم مطابقت کند (مفرد) یا با همهٔ آن‌ها با هم (جمع/مذکر). هر دو حالت درست‌اند اما معنا کمی فرق می‌کند.',
      examples: [
        {
          pt: 'Os meus vestidos são bem coloridos.',
          fa: 'لباس‌های من خیلی رنگی هستند.',
          pron: 'اوس مِئوس وِستیدوس سائو بِین کُلُریدوس',
          note: 'همه مذکرِ جمع، هماهنگ با «vestidos».',
        },
        {
          pt: 'Eu tenho muitos amigos estrangeiros.',
          fa: 'من دوستان خارجیِ زیادی دارم.',
          pron: 'اِئو تِنیو مویتوس آمیگوس اِسترانژِیروس',
          note: '«muitos» اینجا ضمیر است و با «amigos» جمع شده.',
        },
        {
          pt: 'O relógio está atrasado.',
          fa: 'ساعت عقب است.',
          pron: 'او رِلوژیو اِستا آترازادو',
          note: 'اسم مفرد مذکر → صفت مفرد مذکر.',
        },
        {
          pt: 'As duas canetas amarelas são minhas.',
          fa: 'آن دو خودکارِ زرد مالِ من هستند.',
          pron: 'آس دواس کانِتاس آمارِلاس سائو مینیاس',
          note: 'همه مؤنثِ جمع، هماهنگ با «canetas».',
        },
        {
          pt: 'Eu tenho um gato e um cachorro, os dois são brancos.',
          fa: 'من یک گربه و یک سگ دارم، هر دو سفیدند.',
          pron: 'اِئو تِنیو اون گاتو ای اون کاشُرو، اوس دُیس سائو برانکوس',
          note: 'گروه مختلط (gato + cachorro هر دو مذکر) → «brancos» مذکرِ جمع.',
        },
        {
          pt: 'Os dois meninos estudiosos leram muitas revistas científicas.',
          fa: 'آن دو پسرِ کوشا مجله‌های علمیِ زیادی خواندند.',
          pron: 'اوس دُیس مِنینوس اِستودیوزوس لِرام مویتاس رِویستاس سیِنتیفیکاس',
          note: 'دو گروه اسمی جداگانه، هرکدام با صفت خودش هماهنگ.',
        },
        {
          pt: 'Comprei abacate e melão maduro.',
          fa: 'آووکادو و خربزهٔ رسیده خریدم.',
          pron: 'کُمپرِی آباکاتی ای مِلائو مادورو',
          note: 'صفت فقط با نزدیک‌ترین اسم (melão) مطابقت کرده → مفرد مذکر.',
        },
        {
          pt: 'Comprei abacate e melão maduros.',
          fa: 'آووکادو و خربزهٔ رسیده خریدم (هر دو رسیده).',
          pron: 'کُمپرِی آباکاتی ای مِلائو مادوروس',
          note: 'همان جمله؛ حالا صفت با هر دو اسم مطابقت کرده → جمع مذکر. هر دو حالت درست است.',
        },
        {
          pt: 'Ele só usa roupa e carro novos.',
          fa: 'او فقط لباس و ماشینِ نو استفاده می‌کند.',
          pron: 'اِلی سو اوزا هُپا ای کارو نُووس',
          note: 'صفت «novos» با هر دو اسم (roupa مؤنث + carro مذکر) هماهنگ شده → مذکرِ جمع (گروه مختلط).',
        },
      ],
    },
    {
      headingFa: '۳. «muito» به‌عنوان ضمیر در برابر قید',
      bodyFa:
        'واژهٔ «muito» دو نقش دارد و رفتارش فرق می‌کند:\n\n۱) MUITO به‌عنوان ضمیر = مقدار/کمیت → تغییر می‌کند و با اسم هماهنگ می‌شود (muito، muitos، muita، muitas).\n۲) MUITO به‌عنوان قید = شدت → هرگز تغییر نمی‌کند و همیشه «muito» می‌ماند (چون صفت یا فعل را شدت می‌بخشد، نه اسم را).\n\nراهنما: اگر «muito» قبل از اسم است و معنیِ «زیاد/مقدار» می‌دهد → ضمیر و متغیر. اگر قبل از صفت/قید است و معنیِ «خیلی» می‌دهد → قید و ثابت.',
      examples: [
        {
          pt: 'Eu tenho muitos amigos estrangeiros.',
          fa: 'من دوستان خارجیِ زیادی دارم.',
          pron: 'اِئو تِنیو مویتوس آمیگوس',
          note: 'ضمیر، با amigos (مذکر جمع) → muitos.',
        },
        {
          pt: 'Eu tenho muito dinheiro.',
          fa: 'من پول زیادی دارم.',
          pron: 'اِئو تِنیو مویتو جینیِیرو',
          note: 'ضمیر، با dinheiro (مذکر مفرد) → muito.',
        },
        {
          pt: 'Eu tenho muitas amigas.',
          fa: 'من دوستان (زن) زیادی دارم.',
          pron: 'اِئو تِنیو مویتاس آمیگاس',
          note: 'ضمیر، با amigas (مؤنث جمع) → muitas.',
        },
        {
          pt: 'Eu tenho muita saúde.',
          fa: 'من سلامتیِ زیادی دارم.',
          pron: 'اِئو تِنیو مویتا ساوجی',
          note: 'ضمیر، با saúde (مؤنث مفرد) → muita.',
        },
        {
          pt: 'Minha filha é muito bonita.',
          fa: 'دخترم خیلی زیباست.',
          pron: 'مینیا فیلیا اِ مویتو بونیتا',
          note: 'قید، صفت را شدت می‌دهد → ثابت «muito».',
        },
        {
          pt: 'Minhas filhas são muito bonitas.',
          fa: 'دخترانم خیلی زیبا هستند.',
          pron: 'مینیاس فیلیاس سائو مویتو بونیتاس',
          note: 'قید ثابت است حتی وقتی صفت جمع شود.',
        },
        {
          pt: 'Meu filho é muito bonito.',
          fa: 'پسرم خیلی زیباست.',
          pron: 'مِئو فیلیو اِ مویتو بونیتو',
          note: 'قید ثابت «muito».',
        },
        {
          pt: 'Meus filhos são muito bonitos.',
          fa: 'پسرانم خیلی زیبا هستند.',
          pron: 'مِئوس فیلیوس سائو مویتو بونیتوس',
          note: 'قید همیشه «muito» می‌ماند، هرگز «muitos» نمی‌شود.',
        },
      ],
    },
    {
      headingFa: '۴. «anexo» یا «em anexo»؟',
      bodyFa:
        'وقتی می‌خواهیم بگوییم چیزی «پیوست/ضمیمه» است، دو راه داریم:\n\n۱) ANEXO به‌عنوان صفت → با اسم در جنس و شمار مطابقت می‌کند: anexo (مذکر مفرد)، anexos (مذکر جمع)، anexa (مؤنث مفرد)، anexas (مؤنث جمع).\n۲) EM ANEXO → عبارت قیدیِ تغییرناپذیر است و همیشه ثابت می‌ماند، فرقی نمی‌کند اسم مذکر یا مؤنث، مفرد یا جمع باشد.\n\nپس یا صفت را با اسم هماهنگ کن، یا «em anexo» را بدون تغییر بگذار.',
      examples: [
        {
          pt: 'Segue anexo o documento.',
          fa: 'سند پیوست است.',
          pron: 'سِگی آنِکسو او دوکومِنتو',
          note: 'صفت با documento (مذکر مفرد) → anexo.',
        },
        {
          pt: 'Seguem anexos os documentos.',
          fa: 'اسناد پیوست هستند.',
          pron: 'سِگِین آنِکسوس اوس دوکومِنتوس',
          note: 'صفت با documentos (مذکر جمع) → anexos؛ فعل هم جمع شد (seguem).',
        },
        {
          pt: 'Segue anexa a fotografia.',
          fa: 'عکس پیوست است.',
          pron: 'سِگی آنِکسا آ فُتوگرافیا',
          note: 'صفت با fotografia (مؤنث مفرد) → anexa.',
        },
        {
          pt: 'Seguem anexas as duas vias do documento.',
          fa: 'هر دو نسخهٔ سند پیوست هستند.',
          pron: 'سِگِین آنِکساس آس دواس ویاس',
          note: 'صفت با vias (مؤنث جمع) → anexas.',
        },
        {
          pt: 'O documento segue em anexo.',
          fa: 'سند به‌صورت پیوست فرستاده می‌شود.',
          pron: 'او دوکومِنتو سِگی اِین آنِکسو',
          note: '«em anexo» تغییرناپذیر.',
        },
        {
          pt: 'Os documentos seguem em anexo.',
          fa: 'اسناد به‌صورت پیوست فرستاده می‌شوند.',
          pron: 'اوس دوکومِنتوس سِگِین اِین آنِکسو',
          note: '«em anexo» با اسم جمع هم تغییر نمی‌کند.',
        },
        {
          pt: 'A fotografia segue em anexo. / As fotografias seguem em anexo.',
          fa: 'عکس/عکس‌ها به‌صورت پیوست فرستاده می‌شوند.',
          pron: 'آ فُتوگرافیا سِگی اِین آنِکسو',
          note: '«em anexo» با مؤنث و جمع هم ثابت می‌ماند.',
        },
      ],
    },
    {
      headingFa: '۵. واژه‌های پرمشکل: meio، menos، só، quite',
      bodyFa:
        'چند واژه هستند که فارسی‌زبانان (و حتی خودِ برزیلی‌ها) در آن‌ها خطا می‌کنند:\n\n- MEIO: اگر عدد/کسر باشد (نصف) صفت است و مطابقت می‌کند (meia hora = نیم ساعت). اما اگر قید باشد (کمی/تقریباً)، تغییر نمی‌کند: «Ela é meio engraçada» (او کمی بامزه است) — «meia engraçada» غلط است.\n- MENOS: همیشه ثابت است؛ «menas» اصلاً در پرتغالی وجود ندارد.\n- SÓ: اگر معنی «تنها/به‌تنهایی» بدهد صفت است و جمع می‌شود (sós)؛ اگر معنی «فقط» بدهد قید و ثابت است.\n- QUITE: صفت است و مطابقت می‌کند: «estou quite» (مفرد)، «estamos quites» (جمع) — یعنی بی‌حساب/تسویه‌شده.',
      examples: [
        {
          pt: 'Ela é meio engraçada.',
          fa: 'او کمی بامزه است.',
          pron: 'اِلا اِ مِیو اِنگراسادا',
          note: '«meio» اینجا قید = کمی، پس ثابت؛ «meia» غلط است.',
        },
        {
          pt: 'Comprei meia dúzia de ovos.',
          fa: 'نیم دوجین تخم‌مرغ خریدم.',
          pron: 'کُمپرِی مِیا دوزیا جی اُووس',
          note: 'اینجا «meia» = نصف، صفت است و با dúzia (مؤنث) مطابقت کرده.',
        },
        {
          pt: 'Eu viajei menos que você.',
          fa: 'من کمتر از تو سفر کردم.',
          pron: 'اِئو ویاژِی مِنوس کی وُسه',
          note: '«menos» همیشه ثابت؛ «menas» وجود ندارد.',
        },
        {
          pt: 'Cintia e Angélica vieram sós.',
          fa: 'سینتیا و آنژلیکا تنها آمدند.',
          pron: 'سینتیا ای آنژِلیکا ویِرام سوس',
          note: '«sós» = تنها/بی‌همراه، صفت و جمع؛ فرق دارد با «só» = فقط.',
        },
        {
          pt: 'Eu estou quite com o banco. Vocês estão quites também?',
          fa: 'من با بانک بی‌حساب شده‌ام. شما هم تسویه کرده‌اید؟',
          pron: 'اِئو اِستُ کیتی کُن او بانکو. وُسِس اِستائو کیتیس؟',
          note: '«quite» مفرد، «quites» جمع.',
        },
      ],
    },
    {
      headingFa: '۶. تمرین ۱ ـ پرکردن جای خالی (مطابقت اسمی)',
      bodyFa:
        'گزینهٔ درست را انتخاب کنید. این هفت تمرین از جزوه (بخش EXERCÍCIOS صفحهٔ ۶) روی مطابقت اسمی و واژه‌های پرمشکل تمرکز دارند:\n\na) Todos os meninos e meninas nessa escola são ______. (estrangeiras / estrangeiros)\nb) Seguem ______ as duas vias do documento. (anexo / anexas)\nc) Os quartos e a sala estavam ______. (desarrumada / desarrumados)\nd) Cintia e Angélica vieram ______. (só / sós)\ne) Eu viajei ______ que você. (menos / menas)\nf) As fotografias vão em ______. (anexas / anexo)\ng) Eu estou ____ com o banco. E vocês estão ____ também? (quites / quite)\n\nپاسخ‌ها را در بخش تمرین‌های تعاملی (quiz) این درس ببینید.',
      examples: [],
    },
    {
      headingFa: '۷. تمرین ۲ ـ یافتن و اصلاح خطا (مطابقت اسمی)',
      bodyFa:
        'در جمله‌های زیر خطاهای مطابقت اسمی را پیدا و اصلاح کنید (بخش «Encontre o(s) erro(s)» صفحهٔ ۷):\n\na) O carro tinha uma dos faróis queimados. → O carro tinha um dos faróis queimados.\nb) Com menas flores a jardim ficou tristes. → Com menos flores o jardim ficou triste.\nc) As documentos estão errado. → Os documentos estão errados.\nd) Ele fez apenas um hora extras. → Ele fez apenas uma hora extra.\n\nهر یک از این جمله‌ها چند خطای هماهنگیِ جنس/شمار دارند که در بخش quiz به‌طور کامل توضیح داده شده‌اند.',
      examples: [
        {
          pt: 'O carro tinha um dos faróis queimados.',
          fa: 'ماشین یکی از چراغ‌هایش سوخته بود.',
          pron: 'او کارو تینیا اون دوس فارُیس کِیمادوس',
          note: 'اصلاح‌شده: «um» مذکر (نه «uma») چون به farol مذکر برمی‌گردد.',
        },
        {
          pt: 'Com menos flores o jardim ficou triste.',
          fa: 'با گل‌های کمتر، باغ غمگین شد.',
          pron: 'کُن مِنوس فلورِس او ژاردین فیکو تریستی',
          note: 'اصلاح‌شده: «menos» (نه menas)، «o jardim» مذکر، «triste» مفرد.',
        },
      ],
    },
    {
      headingFa: '۸. مطابقت فعلی ـ قاعدهٔ کلی (Concordância Verbal)',
      bodyFa:
        'مطابقت فعلی یعنی فعل باید در شمار (مفرد/جمع) و شخص (اول/دوم/سوم) با فاعلِ خود هماهنگ شود.\n\nمثال کلیدی جزوه:\nTodos almejam uma vida digna!\n= همه آرزوی زندگیِ شایسته‌ای دارند!\n\nتحلیل: فاعل «Todos» سوم‌شخصِ جمع است، پس فعل هم باید سوم‌شخصِ جمع باشد → «almejam».\n\nنکتهٔ مهم فاعل مرکب: وقتی فاعل از چند بخش تشکیل شده (مثلاً «O fumo e a bebida» یا «Eu e meu amigo»)، فعل جمع می‌شود. اگر یکی از اجزا «eu» باشد، فعل اول‌شخصِ جمع (nós) می‌شود.',
      examples: [
        {
          pt: 'Todos almejam uma vida digna!',
          fa: 'همه آرزوی زندگیِ شایسته‌ای دارند!',
          pron: 'تودوس آلمِژام اوما ویدا دیگنا',
          note: 'فاعل سوم‌شخص جمع → فعل سوم‌شخص جمع.',
        },
      ],
    },
    {
      headingFa: '۹. نمونه‌های مطابقت فعلی (Exemplos)',
      bodyFa:
        'این ده جمله انواع فاعل و صرف فعل را نشان می‌دهند: فاعل مرکب، «eu e...» (→ nós)، «a gente» (فعل سوم‌شخص مفرد)، و فاعل‌های جمع. به هماهنگیِ فعل با فاعل در هر جمله دقت کنید.',
      examples: [
        {
          pt: 'O fumo e a bebida em excesso fazem mal à saúde.',
          fa: 'سیگار و نوشیدنیِ زیاده‌ازحد برای سلامتی مضرند.',
          pron: 'او فومو ای آ بِبیدا اِین اِسِسو فازِین مال آ ساوجی',
          note: 'فاعل مرکب (fumo + bebida) → فعل جمع «fazem».',
        },
        {
          pt: 'Eu e meu amigo iremos ao Shopping amanhã.',
          fa: 'من و دوستم فردا به مرکز خرید خواهیم رفت.',
          pron: 'اِئو ای مِئو آمیگو ایرِموس آئو شُپینگ آمانیا',
          note: '«eu e...» → اول‌شخص جمع «iremos».',
        },
        {
          pt: 'Hoje à tarde eles terão consulta médica.',
          fa: 'امروز بعدازظهر آن‌ها نوبت پزشکی دارند.',
          pron: 'اُژی آ تارجی اِلِس تِرائو کُنسولتا مِجیکا',
          note: 'فاعل سوم‌شخص جمع → «terão».',
        },
        {
          pt: 'Nós estamos sempre preocupados com a saúde.',
          fa: 'ما همیشه نگرانِ سلامتی هستیم.',
          pron: 'نُس اِستاموس سِمپری پرِئوکوپادوس',
          note: 'اول‌شخص جمع → «estamos».',
        },
        {
          pt: 'A gente precisa comprar mais roupas novas.',
          fa: 'ما باید لباس‌های نوِ بیشتری بخریم.',
          pron: 'آ ژِنتی پرِسیزا کُمپرار مایس هُپاس نُواس',
          note: '«a gente» با فعل سوم‌شخص مفرد → «precisa» (نه precisamos).',
        },
        {
          pt: 'Vocês querem prova com consulta?',
          fa: 'شما امتحانِ با کتابِ باز می‌خواهید؟',
          pron: 'وُسِس کِرِین پرووا کُن کُنسولتا',
          note: 'دوم‌شخص جمع → «querem».',
        },
        {
          pt: 'Nós desejamos um bom final de semana.',
          fa: 'ما آخر هفتهٔ خوبی برایتان آرزو می‌کنیم.',
          pron: 'نُس دِزِژاموس اون بُن فینال جی سِمانا',
          note: 'اول‌شخص جمع → «desejamos».',
        },
        {
          pt: 'Nós nos casaremos em novembro.',
          fa: 'ما در نوامبر ازدواج خواهیم کرد.',
          pron: 'نُس نوس کازارِموس اِین نُوِمبرو',
          note: 'فعل انعکاسی، اول‌شخص جمع → «casaremos».',
        },
        {
          pt: 'Eles ainda precisam usar a máscara de proteção.',
          fa: 'آن‌ها هنوز باید ماسک محافظ بزنند.',
          pron: 'اِلِس آیندا پرِسیزام اوزار آ ماسکارا',
          note: 'سوم‌شخص جمع → «precisam».',
        },
        {
          pt: 'As pessoas ainda não chegaram.',
          fa: 'مردم هنوز نرسیده‌اند.',
          pron: 'آس پِسواس آیندا نائو شِگارام',
          note: '«as pessoas» جمع → فعل جمع «chegaram».',
        },
      ],
    },
    {
      headingFa: '۱۰. تمرین ۳ ـ پرکردن جای خالی (مطابقت فعلی)',
      bodyFa:
        'فعل داخل پرانتز را در شکل درست صرف کنید (بخش EXERCÍCIOS صفحهٔ ۱۱):\n\na) Todos _____ de respeito e carinho. (precisar) → precisam\nb) Eu _____ mais aulas de português. (querer) → quero\nc) Nossa TV _____ de conserto. (precisar) → precisa\nd) Eu sempre _____ um dinheiro no bolso. (ter) → tenho\ne) Duas estradas brasileiras _____ em ótimo estado. (estar) → estão\nf) Nós _____ de mais doces e salgados. (precisar) → precisamos\ng) Eu _____ de banho de mar. (gostar) → gosto\nh) Todos nós _____ passar na prova. (ir) → vamos\n\nپاسخ‌ها در بخش quiz به‌همراه توضیح آمده‌اند.',
      examples: [],
    },
    {
      headingFa: '۱۱. تمرین ۴ ـ یافتن و اصلاح خطا (مطابقت فعلی)',
      bodyFa:
        'در جمله‌های زیر فعل با فاعل هماهنگ نیست؛ خطا را پیدا و اصلاح کنید (صفحهٔ ۱۲ و ۱۳):\n\na) O cachorro foram operado na perna. → O cachorro foi operado na perna.\nb) Nós tem muitas bolsas amarelas. → Nós temos muitas bolsas amarelas.\nc) Eles não quer ter filhos. → Eles não querem ter filhos.\nd) A gente trabalhamos o dia todo. → A gente trabalha o dia todo.\ne) Elas sempre chora no filme. → Elas sempre choram no filme.\nf) Eu sempre compra ovos para o almoço. → Eu sempre compro ovos para o almoço.\ng) Nós deseja muita saúde para você. → Nós desejamos muita saúde para você.\n\nنکتهٔ «a gente»: هرچند معنی «ما» می‌دهد، فعلش سوم‌شخصِ مفرد است (trabalha، نه trabalhamos).',
      examples: [
        {
          pt: 'O cachorro foi operado na perna.',
          fa: 'سگ از ناحیهٔ پا عمل شد.',
          pron: 'او کاشورو فُی اُپِرادو نا پِرنا',
          note: 'اصلاح‌شده: فاعل مفرد → «foi» (نه foram).',
        },
        {
          pt: 'A gente trabalha o dia todo.',
          fa: 'ما تمام روز کار می‌کنیم.',
          pron: 'آ ژِنتی ترابایا او جیا تودو',
          note: 'اصلاح‌شده: «a gente» → فعل سوم‌شخص مفرد «trabalha».',
        },
      ],
    },
    {
      headingFa: '۱۲. تمرین ۵ ـ یافتن و اصلاح خطا (مطابقت اسمی، مرور)',
      bodyFa:
        'خطای مطابقت اسمی را پیدا و جمله را اصلاح کنید (صفحهٔ ۱۵):\n\na) As duas amigas americanos visitaram o Brasil. → As duas amigas americanas visitaram o Brasil.\nb) Minha filha é muito bonito. → Minha filha é muito bonita.\nc) Os primeiros candidatas chegaram para a entrevista. → As primeiras candidatas chegaram para a entrevista.\nd) Ela é meia engraçada. → Ela é meio engraçada.\ne) Segue anexo a fatura. → Segue anexa a fatura.\n\nپاسخ‌ها با توضیح کامل در بخش quiz آمده‌اند.',
      examples: [
        {
          pt: 'As duas amigas americanas visitaram o Brasil.',
          fa: 'آن دو دوستِ آمریکایی از برزیل دیدن کردند.',
          pron: 'آس دواس آمیگاس آمِریکاناس ویزیتارام او برازیل',
          note: 'اصلاح‌شده: صفت با «amigas» (مؤنث جمع) → americanas.',
        },
        {
          pt: 'Segue anexa a fatura.',
          fa: 'فاکتور پیوست است.',
          pron: 'سِگی آنِکسا آ فاتورا',
          note: 'اصلاح‌شده: «anexa» با fatura (مؤنث مفرد) هماهنگ می‌شود.',
        },
      ],
    },
    {
      headingFa: '۱۳. تمرین ۶ ـ یافتن و اصلاح خطا (مطابقت فعلی، مرور)',
      bodyFa:
        'خطای مطابقت فعلی را پیدا و جمله را اصلاح کنید (صفحهٔ ۱۶):\n\na) Ele gosto de viajar pelo país. → Ele gosta de viajar pelo país.\nb) Eles está muito bem. → Eles estão muito bem.\nc) Cachorros e gatos é animais muito obedientes. → Cachorros e gatos são animais muito obedientes.\nd) A gente adoramos ver as flores no jardim. → A gente adora ver as flores no jardim.\ne) Eu vai sempre aos parques no domingo. → Eu vou sempre aos parques no domingo.\n\nپاسخ‌ها با توضیح در بخش quiz.',
      examples: [
        {
          pt: 'Cachorros e gatos são animais muito obedientes.',
          fa: 'سگ‌ها و گربه‌ها حیواناتِ بسیار مطیعی هستند.',
          pron: 'کاشوروس ای گاتوس سائو آنیمایس مویتو اُبِدیِنتِس',
          note: 'اصلاح‌شده: فاعل مرکب/جمع → فعل جمع «são».',
        },
        {
          pt: 'Eu vou sempre aos parques no domingo.',
          fa: 'من یکشنبه‌ها همیشه به پارک‌ها می‌روم.',
          pron: 'اِئو وُ سِمپری آئوس پارکِس نو دومینگو',
          note: 'اصلاح‌شده: اول‌شخص مفرد فعل ir → «vou» (نه vai).',
        },
      ],
    },
  ],
  keyPointsFa: [
    'مطابقت اسمی: حرف تعریف، ضمیر، عدد و صفت با اسم در جنس و شمار هماهنگ می‌شوند.',
    'صفتِ بعد از چند اسم می‌تواند فقط با نزدیک‌ترین اسم (مفرد) یا با همه (جمع/مذکر) مطابقت کند؛ هر دو درست است.',
    'در گروه اسمیِ مختلط (مذکر + مؤنث) صفت مذکرِ جمع می‌شود.',
    '«muito» ضمیر (زیاد/مقدار) متغیر است؛ «muito» قید (خیلی) همیشه ثابت است.',
    '«anexo/anexa/anexos/anexas» صفت است و مطابقت می‌کند؛ «em anexo» همیشه تغییرناپذیر است.',
    '«meio» به‌عنوان قید (کمی) ثابت است؛ «menas» وجود ندارد، همیشه «menos».',
    '«só»=فقط (ثابت) اما «sós»=تنها (صفت جمع)؛ «quite/quites» صفت است و مطابقت می‌کند.',
    'مطابقت فعلی: فعل با فاعل در شخص و شمار هماهنگ می‌شود.',
    'فاعل مرکب فعل را جمع می‌کند؛ اگر «eu» جزءِ فاعل باشد فعل اول‌شخص جمع (nós) می‌شود.',
    '«a gente» معنی «ما» می‌دهد اما فعلش سوم‌شخصِ مفرد است (a gente trabalha، نه trabalhamos).',
  ],
  quiz: [
    {
      id: 'course-aula-12-q1',
      type: 'mcq',
      prompt: 'Todos os meninos e meninas nessa escola são ______.',
      promptFa:
        'گزینهٔ درست را برای مطابقت انتخاب کنید (گروه مختلط مذکر+مؤنث).',
      options: ['estrangeiros', 'estrangeiras', 'estrangeiro', 'estrangeira'],
      answer: 'estrangeiros',
      explanationFa:
        'وقتی گروه مختلط باشد (meninos مذکر + meninas مؤنث)، صفت مذکرِ جمع می‌شود → estrangeiros.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q2',
      type: 'mcq',
      prompt: 'Seguem ______ as duas vias do documento.',
      promptFa: 'شکل درست «anexo» را انتخاب کنید.',
      options: ['anexas', 'anexo', 'anexos', 'em anexas'],
      answer: 'anexas',
      explanationFa:
        '«anexo» صفت است و با «vias» (مؤنث جمع) مطابقت می‌کند → anexas.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q3',
      type: 'mcq',
      prompt: 'Os quartos e a sala estavam ______.',
      promptFa: 'گزینهٔ درست را برای مطابقت انتخاب کنید.',
      options: ['desarrumados', 'desarrumada', 'desarrumadas', 'desarrumado'],
      answer: 'desarrumados',
      explanationFa:
        'گروه مختلط (quartos مذکر + sala مؤنث) → صفت مذکرِ جمع «desarrumados».',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q4',
      type: 'mcq',
      prompt: 'Cintia e Angélica vieram ______.',
      promptFa: 'کدام درست است؟ (معنی: تنها آمدند)',
      options: ['sós', 'só', 'soas', 'sozinho'],
      answer: 'sós',
      explanationFa:
        'اینجا «só» معنی «تنها/بی‌همراه» می‌دهد، پس صفت است و جمع می‌شود → sós.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q5',
      type: 'mcq',
      prompt: 'Eu viajei ______ que você.',
      promptFa: 'کدام درست است؟',
      options: ['menos', 'menas', 'menores', 'menor'],
      answer: 'menos',
      explanationFa:
        '«menos» همیشه ثابت است؛ واژهٔ «menas» در پرتغالی وجود ندارد.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q6',
      type: 'mcq',
      prompt: 'As fotografias vão em ______.',
      promptFa: 'کدام درست است؟ (عبارت em anexo)',
      options: ['anexo', 'anexas', 'anexos', 'anexa'],
      answer: 'anexo',
      explanationFa:
        'در عبارت «em anexo» واژه تغییرناپذیر است و حتی با اسم مؤنثِ جمع هم «anexo» می‌ماند.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q7',
      type: 'fill-blank',
      prompt:
        'Eu estou ____ com o banco. E vocês estão ____ também? (quite/quites)',
      promptFa: 'دو شکل درست «quite» را به‌ترتیب بگذارید (مفرد / جمع).',
      options: [],
      answer: 'quite / quites',
      explanationFa:
        '«quite» صفت است: با فاعل مفرد «quite» و با فاعل جمع «quites» → Eu estou quite / vocês estão quites.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q8',
      type: 'fill-blank',
      prompt: 'Corrija: O carro tinha uma dos faróis queimados.',
      promptFa: 'جمله را با اصلاح خطای مطابقت بازنویسی کنید.',
      options: [],
      answer: 'O carro tinha um dos faróis queimados.',
      explanationFa: '«farol» مذکر است، پس «um dos faróis» درست است، نه «uma».',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q9',
      type: 'fill-blank',
      prompt: 'Corrija: Com menas flores a jardim ficou tristes.',
      promptFa: 'همهٔ خطاهای مطابقت را اصلاح کنید.',
      options: [],
      answer: 'Com menos flores o jardim ficou triste.',
      explanationFa:
        'سه خطا: «menas»→«menos» (ثابت)؛ «a jardim»→«o jardim» (مذکر)؛ «tristes»→«triste» (فاعل مفرد).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q10',
      type: 'fill-blank',
      prompt: 'Corrija: As documentos estão errado.',
      promptFa: 'خطاهای جنس و شمار را اصلاح کنید.',
      options: [],
      answer: 'Os documentos estão errados.',
      explanationFa:
        '«documento» مذکر است → «os documentos»؛ صفت هم باید جمع مذکر شود → «errados».',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q11',
      type: 'fill-blank',
      prompt: 'Corrija: Ele fez apenas um hora extras.',
      promptFa: 'خطاهای مطابقت را اصلاح کنید.',
      options: [],
      answer: 'Ele fez apenas uma hora extra.',
      explanationFa:
        '«hora» مؤنث مفرد است → «uma hora»؛ صفت هم باید مفرد مؤنث شود → «extra».',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q12',
      type: 'mcq',
      prompt: 'Eu tenho ______ dinheiro. (muito como pronome)',
      promptFa: 'شکل درست «muito» را انتخاب کنید (اسم مذکر مفرد).',
      options: ['muito', 'muita', 'muitos', 'muitas'],
      answer: 'muito',
      explanationFa:
        'اینجا «muito» ضمیر است و با «dinheiro» (مذکر مفرد) مطابقت می‌کند → muito.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q13',
      type: 'mcq',
      prompt: 'Minhas filhas são ______ bonitas. (muito como advérbio)',
      promptFa: 'شکل درست «muito» را انتخاب کنید (قید شدت).',
      options: ['muito', 'muitas', 'muitos', 'muita'],
      answer: 'muito',
      explanationFa:
        'اینجا «muito» قید است و صفت را شدت می‌دهد، پس هرگز تغییر نمی‌کند → muito.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q14',
      type: 'mcq',
      prompt: 'Escolha a forma correta: Comprei abacate e melão ______.',
      promptFa: 'کدام گزینه درست است؟',
      options: [
        'maduro ou maduros (ambos corretos)',
        'só maduros',
        'só madura',
        'maduras',
      ],
      answer: 'maduro ou maduros (ambos corretos)',
      explanationFa:
        'صفت بعد از دو اسم می‌تواند فقط با نزدیک‌ترین (melão → maduro) یا با هر دو (maduros) مطابقت کند؛ هر دو درست‌اند.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q15',
      type: 'fill-blank',
      prompt: 'Todos ______ de respeito e carinho. (precisar)',
      promptFa: 'فعل را در شکل درست صرف کنید.',
      options: [],
      answer: 'precisam',
      explanationFa: '«Todos» سوم‌شخص جمع است → precisam.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q16',
      type: 'fill-blank',
      prompt: 'Eu ______ mais aulas de português. (querer)',
      promptFa: 'فعل را صرف کنید (اول‌شخص مفرد).',
      options: [],
      answer: 'quero',
      explanationFa: 'اول‌شخص مفرد فعل querer → quero.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q17',
      type: 'fill-blank',
      prompt: 'Nossa TV ______ de conserto. (precisar)',
      promptFa: 'فعل را صرف کنید (فاعل مفرد).',
      options: [],
      answer: 'precisa',
      explanationFa: '«Nossa TV» سوم‌شخص مفرد است → precisa.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q18',
      type: 'fill-blank',
      prompt: 'Eu sempre ______ um dinheiro no bolso. (ter)',
      promptFa: 'فعل را صرف کنید (اول‌شخص مفرد).',
      options: [],
      answer: 'tenho',
      explanationFa: 'اول‌شخص مفرد فعل ter → tenho.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q19',
      type: 'fill-blank',
      prompt: 'Duas estradas brasileiras ______ em ótimo estado. (estar)',
      promptFa: 'فعل را صرف کنید (فاعل جمع).',
      options: [],
      answer: 'estão',
      explanationFa: '«Duas estradas» سوم‌شخص جمع است → estão.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q20',
      type: 'fill-blank',
      prompt: 'Nós ______ de mais doces e salgados. (precisar)',
      promptFa: 'فعل را صرف کنید (اول‌شخص جمع).',
      options: [],
      answer: 'precisamos',
      explanationFa: 'اول‌شخص جمع فعل precisar → precisamos.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q21',
      type: 'fill-blank',
      prompt: 'Eu ______ de banho de mar. (gostar)',
      promptFa: 'فعل را صرف کنید (اول‌شخص مفرد).',
      options: [],
      answer: 'gosto',
      explanationFa: 'اول‌شخص مفرد فعل gostar → gosto.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q22',
      type: 'fill-blank',
      prompt: 'Todos nós ______ passar na prova. (ir)',
      promptFa: 'فعل را صرف کنید (اول‌شخص جمع).',
      options: [],
      answer: 'vamos',
      explanationFa: '«Todos nós» اول‌شخص جمع است → vamos.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q23',
      type: 'fill-blank',
      prompt: 'Corrija: O cachorro foram operado na perna.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'O cachorro foi operado na perna.',
      explanationFa: 'فاعل «O cachorro» مفرد است → فعل مفرد «foi» (نه foram).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q24',
      type: 'fill-blank',
      prompt: 'Corrija: Nós tem muitas bolsas amarelas.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Nós temos muitas bolsas amarelas.',
      explanationFa: 'فاعل «Nós» اول‌شخص جمع است → temos (نه tem).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q25',
      type: 'fill-blank',
      prompt: 'Corrija: Eles não quer ter filhos.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Eles não querem ter filhos.',
      explanationFa: 'فاعل «Eles» سوم‌شخص جمع است → querem (نه quer).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q26',
      type: 'fill-blank',
      prompt: 'Corrija: A gente trabalhamos o dia todo.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید (توجه به a gente).',
      options: [],
      answer: 'A gente trabalha o dia todo.',
      explanationFa:
        '«a gente» با فعل سوم‌شخص مفرد می‌آید → trabalha (نه trabalhamos).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q27',
      type: 'fill-blank',
      prompt: 'Corrija: Elas sempre chora no filme.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Elas sempre choram no filme.',
      explanationFa: 'فاعل «Elas» سوم‌شخص جمع است → choram (نه chora).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q28',
      type: 'fill-blank',
      prompt: 'Corrija: Eu sempre compra ovos para o almoço.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Eu sempre compro ovos para o almoço.',
      explanationFa: 'فاعل «Eu» اول‌شخص مفرد است → compro (نه compra).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q29',
      type: 'fill-blank',
      prompt: 'Corrija: Nós deseja muita saúde para você.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Nós desejamos muita saúde para você.',
      explanationFa: 'فاعل «Nós» اول‌شخص جمع است → desejamos (نه deseja).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q30',
      type: 'fill-blank',
      prompt: 'Corrija: As duas amigas americanos visitaram o Brasil.',
      promptFa: 'خطای مطابقت اسمی را اصلاح کنید.',
      options: [],
      answer: 'As duas amigas americanas visitaram o Brasil.',
      explanationFa: 'صفت باید با «amigas» (مؤنث جمع) هماهنگ شود → americanas.',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q31',
      type: 'fill-blank',
      prompt: 'Corrija: Minha filha é muito bonito.',
      promptFa: 'خطای مطابقت اسمی را اصلاح کنید.',
      options: [],
      answer: 'Minha filha é muito bonita.',
      explanationFa:
        'صفت با «filha» (مؤنث) هماهنگ می‌شود → bonita؛ «muito» قید است و ثابت می‌ماند.',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q32',
      type: 'fill-blank',
      prompt: 'Corrija: Os primeiros candidatas chegaram para a entrevista.',
      promptFa: 'خطای مطابقت اسمی را اصلاح کنید.',
      options: [],
      answer: 'As primeiras candidatas chegaram para a entrevista.',
      explanationFa:
        '«candidatas» مؤنث جمع است، پس حرف تعریف و عدد ترتیبی هم باید مؤنث شوند → As primeiras candidatas.',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q33',
      type: 'mcq',
      prompt: 'Ela é ______ engraçada.',
      promptFa: 'کدام درست است؟ (meio به‌عنوان قید = کمی)',
      options: ['meio', 'meia', 'meios', 'meias'],
      answer: 'meio',
      explanationFa:
        'اینجا «meio» قید است (= کمی) و تغییر نمی‌کند؛ «meia engraçada» غلط است.',
      cefr: 'B1',
      skill: 'grammar',
    },
    {
      id: 'course-aula-12-q34',
      type: 'fill-blank',
      prompt: 'Corrija: Segue anexo a fatura.',
      promptFa: 'خطای مطابقت را اصلاح کنید.',
      options: [],
      answer: 'Segue anexa a fatura.',
      explanationFa:
        '«anexo» صفت است و با «fatura» (مؤنث مفرد) مطابقت می‌کند → anexa.',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q35',
      type: 'fill-blank',
      prompt: 'Corrija: Ele gosto de viajar pelo país.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Ele gosta de viajar pelo país.',
      explanationFa: 'فاعل «Ele» سوم‌شخص مفرد است → gosta (نه gosto).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q36',
      type: 'fill-blank',
      prompt: 'Corrija: Eles está muito bem.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Eles estão muito bem.',
      explanationFa: 'فاعل «Eles» سوم‌شخص جمع است → estão (نه está).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q37',
      type: 'fill-blank',
      prompt: 'Corrija: Cachorros e gatos é animais muito obedientes.',
      promptFa: 'خطای مطابقت فعلی (فاعل مرکب) را اصلاح کنید.',
      options: [],
      answer: 'Cachorros e gatos são animais muito obedientes.',
      explanationFa: 'فاعل مرکب/جمع (Cachorros e gatos) → فعل جمع «são».',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q38',
      type: 'fill-blank',
      prompt: 'Corrija: A gente adoramos ver as flores no jardim.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید (توجه به a gente).',
      options: [],
      answer: 'A gente adora ver as flores no jardim.',
      explanationFa:
        '«a gente» فعل سوم‌شخص مفرد می‌گیرد → adora (نه adoramos).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q39',
      type: 'fill-blank',
      prompt: 'Corrija: Eu vai sempre aos parques no domingo.',
      promptFa: 'خطای مطابقت فعلی را اصلاح کنید.',
      options: [],
      answer: 'Eu vou sempre aos parques no domingo.',
      explanationFa: 'اول‌شخص مفرد فعل ir → vou (نه vai).',
      cefr: 'B1',
      skill: 'writing',
    },
    {
      id: 'course-aula-12-q40',
      type: 'translate-fa-pt',
      prompt:
        '«من و دوستم فردا به مرکز خرید خواهیم رفت.» را به پرتغالی بنویسید.',
      promptFa: 'با توجه به فاعل مرکب با «eu» ترجمه کنید.',
      options: [],
      answer: 'Eu e meu amigo iremos ao Shopping amanhã.',
      explanationFa:
        'وقتی «eu» جزءِ فاعل مرکب باشد، فعل اول‌شخص جمع می‌شود → iremos.',
      cefr: 'B1',
      skill: 'writing',
    },
  ],
  estimatedMinutes: 30,
  sourceNoteFa: 'برگرفته از جزوهٔ آماده‌سازی فدرال — Aula 12 (کامل).',
};
