import { mkPhrase } from './helpers';
import type { Phrase } from '@/domain/content/schema';

/**
 * Seed phrases: Brazilian Portuguese for Persian speakers.
 *
 * ~70 everyday-life phrases + ~60 administrative / bureaucratic phrases
 * (Polícia Federal, cartório, university, documents).
 */
export const phrases: Phrase[] = [
  // ─────────────────────────── greetings ───────────────────────────
  mkPhrase({
    id: 'p-bom-dia',
    pt: 'Bom dia!',
    faLiteral: 'روزِ خوب!',
    faNatural: 'صبح بخیر!',
    pron: 'بُن جیا',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
    notes: 'تا حدود ظهر استفاده می‌شود.',
  }),
  mkPhrase({
    id: 'p-boa-tarde',
    pt: 'Boa tarde!',
    faLiteral: 'بعدازظهرِ خوب!',
    faNatural: 'عصر بخیر!',
    pron: 'بُآ تاردی',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
    notes: 'از ظهر تا غروب استفاده می‌شود.',
  }),
  mkPhrase({
    id: 'p-boa-noite',
    pt: 'Boa noite!',
    faLiteral: 'شبِ خوب!',
    faNatural: 'شب بخیر! / عصر بخیر!',
    pron: 'بُآ نُیتی',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
    notes: 'هم برای سلامِ شب و هم برای خداحافظی شب به کار می‌رود.',
  }),
  mkPhrase({
    id: 'p-oi',
    pt: 'Oi!',
    faLiteral: 'سلام!',
    faNatural: 'سلام!',
    pron: 'اُی',
    cefr: 'A1',
    category: 'greetings',
    formality: 'informal',
  }),
  mkPhrase({
    id: 'p-ola',
    pt: 'Olá!',
    faLiteral: 'سلام!',
    faNatural: 'سلام!',
    pron: 'اُلا',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tudo-bem',
    pt: 'Tudo bem?',
    faLiteral: 'همه‌چیز خوب است؟',
    faNatural: 'خوبی؟ / حالت چطوره؟',
    pron: 'تودو بِین',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
    notes:
      'هم به‌عنوان احوال‌پرسی و هم به‌عنوان پاسخ (تودو بِین = خوبم) به کار می‌رود.',
  }),
  mkPhrase({
    id: 'p-como-vai',
    pt: 'Como vai?',
    faLiteral: 'چطور می‌روی؟',
    faNatural: 'حالت چطوره؟',
    pron: 'کُمو وای',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tudo-otimo',
    pt: 'Tudo ótimo, e você?',
    faLiteral: 'همه‌چیز عالی، و تو؟',
    faNatural: 'عالی‌ام، تو چطوری؟',
    pron: 'تودو اُتیمو، ای وُسه',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-ate-logo',
    pt: 'Até logo!',
    faLiteral: 'تا کمی بعد!',
    faNatural: 'می‌بینمت! / فعلاً!',
    pron: 'آته لُگو',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-ate-amanha',
    pt: 'Até amanhã!',
    faLiteral: 'تا فردا!',
    faNatural: 'تا فردا!',
    pron: 'آته آمانیا',
    cefr: 'A1',
    category: 'greetings',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tchau',
    pt: 'Tchau!',
    faLiteral: 'خداحافظ!',
    faNatural: 'خداحافظ! / بای!',
    pron: 'چاو',
    cefr: 'A1',
    category: 'greetings',
    formality: 'informal',
  }),
  mkPhrase({
    id: 'p-bem-vindo',
    pt: 'Seja bem-vindo!',
    faLiteral: 'خوش‌آمده باش!',
    faNatural: 'خوش آمدید!',
    pron: 'سِژا بِین-ویندو',
    cefr: 'A2',
    category: 'greetings',
    formality: 'formal',
    notes: 'برای زن: bem-vinda (بِین-ویندا).',
  }),

  // ─────────────────────────── introductions ───────────────────────────
  mkPhrase({
    id: 'p-meu-nome-e',
    pt: 'Meu nome é Ali.',
    faLiteral: 'نامِ من علی است.',
    faNatural: 'اسم من علی است.',
    pron: 'مِئو نُمی اِ علی',
    cefr: 'A1',
    category: 'introductions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-como-se-chama',
    pt: 'Como você se chama?',
    faLiteral: 'چطور خودت را صدا می‌زنی؟',
    faNatural: 'اسمت چیه؟',
    pron: 'کُمو وُسه سی شاما',
    cefr: 'A1',
    category: 'introductions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-prazer',
    pt: 'Prazer em conhecê-lo.',
    faLiteral: 'لذت از شناختنِ شما.',
    faNatural: 'از آشنایی با شما خوشوقتم.',
    pron: 'پرازِر اِین کُنیه‌سه‌لو',
    cefr: 'A2',
    category: 'introductions',
    formality: 'formal',
    notes:
      'خطاب به زن: conhecê-la (کُنیه‌سه‌لا). به‌طور غیررسمی فقط "Prazer!" کافی است.',
  }),
  mkPhrase({
    id: 'p-sou-do-ira',
    pt: 'Sou do Irã.',
    faLiteral: 'از ایران هستم.',
    faNatural: 'اهل ایران هستم.',
    pron: 'سُو دو ایرا',
    cefr: 'A1',
    category: 'introductions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-moro-em',
    pt: 'Moro em São Paulo.',
    faLiteral: 'در سائوپائولو زندگی می‌کنم.',
    faNatural: 'ساکن سائوپائولو هستم.',
    pron: 'مُرو اِین سائو پائولو',
    cefr: 'A1',
    category: 'introductions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-nao-falo-bem',
    pt: 'Ainda não falo bem português.',
    faLiteral: 'هنوز پرتغالی را خوب صحبت نمی‌کنم.',
    faNatural: 'هنوز پرتغالی‌ام خوب نیست.',
    pron: 'آیندا نائو فالو بِین پورتوگِس',
    cefr: 'A2',
    category: 'introductions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-quantos-anos',
    pt: 'Quantos anos você tem?',
    faLiteral: 'چند سال داری؟',
    faNatural: 'چند سالته؟',
    pron: 'کوانتوس آنوس وُسه تِین',
    cefr: 'A1',
    category: 'introductions',
    formality: 'neutral',
    notes: 'در پرتغالی سن با فعل ter (داشتن) بیان می‌شود، نه ser (بودن).',
  }),

  // ─────────────────────────── small-talk ───────────────────────────
  mkPhrase({
    id: 'p-de-onde-voce-e',
    pt: 'De onde você é?',
    faLiteral: 'اهل کجایی؟',
    faNatural: 'اهل کجایی؟',
    pron: 'جی اُنجی وُسه اِ',
    cefr: 'A1',
    category: 'small-talk',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-o-que-voce-faz',
    pt: 'O que você faz?',
    faLiteral: 'چه کاری می‌کنی؟',
    faNatural: 'شغلت چیه؟',
    pron: 'او کی وُسه فاس',
    cefr: 'A2',
    category: 'small-talk',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-gosto-daqui',
    pt: 'Estou gostando muito daqui.',
    faLiteral: 'دارم اینجا را خیلی دوست دارم.',
    faNatural: 'اینجا خیلی بهم خوش می‌گذره.',
    pron: 'اِستُو گُستاندو مویتو داکی',
    cefr: 'A2',
    category: 'small-talk',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-que-legal',
    pt: 'Que legal!',
    faLiteral: 'چه باحال!',
    faNatural: 'چه خوب! / عالیه!',
    pron: 'کی لِگاو',
    cefr: 'A1',
    category: 'small-talk',
    formality: 'informal',
  }),
  mkPhrase({
    id: 'p-nossa',
    pt: 'Nossa!',
    faLiteral: 'وای!',
    faNatural: 'وای! / عجب!',
    pron: 'نُسا',
    cefr: 'A2',
    category: 'small-talk',
    formality: 'informal',
    notes: 'اصطلاح رایج برای تعجب؛ کوتاه‌شده‌ی «Nossa Senhora».',
  }),
  mkPhrase({
    id: 'p-vamos-marcar',
    pt: 'Vamos marcar um café?',
    faLiteral: 'بیا یک قهوه قرار بگذاریم؟',
    faNatural: 'بریم یه قهوه بخوریم؟',
    pron: 'واموس مارکار اوم کافه',
    cefr: 'A2',
    category: 'small-talk',
    formality: 'informal',
  }),

  // ─────────────────────────── restaurant ───────────────────────────
  mkPhrase({
    id: 'p-mesa-para-dois',
    pt: 'Uma mesa para dois, por favor.',
    faLiteral: 'یک میز برای دو نفر، لطفاً.',
    faNatural: 'یه میز دو نفره، لطفاً.',
    pron: 'اوما مِزا پارا دُیس، پور فاوُر',
    cefr: 'A1',
    category: 'restaurant',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-cardapio',
    pt: 'Pode me trazer o cardápio?',
    faLiteral: 'می‌توانی منو را برایم بیاوری؟',
    faNatural: 'میشه منو رو بیارید؟',
    pron: 'پُجی می ترازِر او کارداپیو',
    cefr: 'A2',
    category: 'restaurant',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-o-que-recomenda',
    pt: 'O que você recomenda?',
    faLiteral: 'چه چیزی پیشنهاد می‌دهی؟',
    faNatural: 'چی پیشنهاد می‌دید؟',
    pron: 'او کی وُسه رِکومِندا',
    cefr: 'A2',
    category: 'restaurant',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-vou-querer',
    pt: 'Vou querer isto aqui.',
    faLiteral: 'این را خواهم خواست.',
    faNatural: 'این یکی رو می‌خوام.',
    pron: 'وُو کِرِر ایستو آکی',
    cefr: 'A2',
    category: 'restaurant',
    formality: 'neutral',
    notes: '«Vou querer...» شکل رایج و مؤدبانه‌ی سفارش دادن است.',
  }),
  mkPhrase({
    id: 'p-sem-carne',
    pt: 'Eu não como carne.',
    faLiteral: 'من گوشت نمی‌خورم.',
    faNatural: 'من گوشت نمی‌خورم.',
    pron: 'اِئو نائو کُمو کارنی',
    cefr: 'A1',
    category: 'restaurant',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-sou-alergico',
    pt: 'Sou alérgico a amendoim.',
    faLiteral: 'به بادام‌زمینی حساسیت دارم.',
    faNatural: 'به بادام‌زمینی آلرژی دارم.',
    pron: 'سُو آلِرژیکو آ آمِندُاین',
    cefr: 'A2',
    category: 'restaurant',
    formality: 'neutral',
    notes: 'زن: alérgica (آلِرژیکا).',
  }),
  mkPhrase({
    id: 'p-a-conta',
    pt: 'A conta, por favor.',
    faLiteral: 'صورتحساب، لطفاً.',
    faNatural: 'صورتحساب لطفاً.',
    pron: 'آ کُنتا، پور فاوُر',
    cefr: 'A1',
    category: 'restaurant',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-aceita-cartao',
    pt: 'Vocês aceitam cartão?',
    faLiteral: 'کارت قبول می‌کنید؟',
    faNatural: 'کارت قبول می‌کنید؟',
    pron: 'وُسِس آسِیتام کارتائو',
    cefr: 'A2',
    category: 'restaurant',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-esta-delicioso',
    pt: 'Está delicioso!',
    faLiteral: 'خوشمزه است!',
    faNatural: 'خیلی خوشمزه‌ست!',
    pron: 'اِستا دِلیسیوزو',
    cefr: 'A1',
    category: 'restaurant',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-um-copo-de-agua',
    pt: 'Um copo de água, por favor.',
    faLiteral: 'یک لیوان آب، لطفاً.',
    faNatural: 'یه لیوان آب لطفاً.',
    pron: 'اوم کُپو جی آگوا، پور فاوُر',
    cefr: 'A1',
    category: 'restaurant',
    formality: 'neutral',
  }),

  // ─────────────────────────── supermarket ───────────────────────────
  mkPhrase({
    id: 'p-onde-fica-o-arroz',
    pt: 'Onde fica o arroz?',
    faLiteral: 'برنج کجاست؟',
    faNatural: 'برنج کجاست؟',
    pron: 'اُنجی فیکا او آهُس',
    cefr: 'A1',
    category: 'supermarket',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tem-em-estoque',
    pt: 'Vocês têm isto em estoque?',
    faLiteral: 'این را در انبار دارید؟',
    faNatural: 'این موجود دارید؟',
    pron: 'وُسِس تِین ایستو اِین اِستُکی',
    cefr: 'A2',
    category: 'supermarket',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-quanto-custa',
    pt: 'Quanto custa?',
    faLiteral: 'چقدر قیمتش است؟',
    faNatural: 'چند می‌شه؟',
    pron: 'کوانتو کوستا',
    cefr: 'A1',
    category: 'supermarket',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-esta-em-promocao',
    pt: 'Este produto está em promoção?',
    faLiteral: 'این محصول در تخفیف است؟',
    faNatural: 'این جنس تخفیف داره؟',
    pron: 'اِستی پرودوتو اِستا اِین پرومُسائو',
    cefr: 'A2',
    category: 'supermarket',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-uma-sacola',
    pt: 'Pode me dar uma sacola?',
    faLiteral: 'می‌توانی یک کیسه به من بدهی؟',
    faNatural: 'میشه یه کیسه بدید؟',
    pron: 'پُجی می دار اوما ساکُلا',
    cefr: 'A2',
    category: 'supermarket',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-onde-e-o-caixa',
    pt: 'Onde é o caixa?',
    faLiteral: 'صندوق کجاست؟',
    faNatural: 'صندوق پرداخت کجاست؟',
    pron: 'اُنجی اِ او کایشا',
    cefr: 'A1',
    category: 'supermarket',
    formality: 'neutral',
  }),

  // ─────────────────────────── bakery ───────────────────────────
  mkPhrase({
    id: 'p-um-pao-frances',
    pt: 'Me vê dois pães franceses, por favor.',
    faLiteral: 'دو تا نان فرانسوی به من بده، لطفاً.',
    faNatural: 'دو تا نون فرانسوی بدید لطفاً.',
    pron: 'می وه دُیس پَینز فرانسِزیس، پور فاوُر',
    cefr: 'A2',
    category: 'bakery',
    formality: 'informal',
    notes:
      '«pão francês» نانِ کوچک روزمره‌ی برزیلی است. «Me vê...» شکل بسیار رایج نانوایی است.',
  }),
  mkPhrase({
    id: 'p-um-cafezinho',
    pt: 'Um cafezinho, por favor.',
    faLiteral: 'یک قهوه‌ی کوچک، لطفاً.',
    faNatural: 'یه قهوه بدید لطفاً.',
    pron: 'اوم کافه‌زینیو، پور فاوُر',
    cefr: 'A1',
    category: 'bakery',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-pao-de-queijo',
    pt: 'Tem pão de queijo fresquinho?',
    faLiteral: 'نان پنیرِ تازه دارید؟',
    faNatural: 'پائو د کِیجوی تازه دارید؟',
    pron: 'تِین پائو جی کِیجو فرِسکینیو',
    cefr: 'A2',
    category: 'bakery',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-meio-quilo',
    pt: 'Meio quilo de presunto, por favor.',
    faLiteral: 'نیم کیلو ژامبون، لطفاً.',
    faNatural: 'نیم کیلو ژامبون لطفاً.',
    pron: 'مِیو کیلو جی پرِزونتو، پور فاوُر',
    cefr: 'A2',
    category: 'bakery',
    formality: 'neutral',
  }),

  // ─────────────────────────── pharmacy ───────────────────────────
  mkPhrase({
    id: 'p-preciso-remedio',
    pt: 'Preciso de um remédio para dor de cabeça.',
    faLiteral: 'به دارویی برای درد سر نیاز دارم.',
    faNatural: 'یه دارو برای سردرد لازم دارم.',
    pron: 'پرِسیزو جی اوم رِمِجیو پارا دُر جی کابِسا',
    cefr: 'A2',
    category: 'pharmacy',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tem-receita',
    pt: 'Este remédio precisa de receita?',
    faLiteral: 'این دارو به نسخه نیاز دارد؟',
    faNatural: 'این دارو نسخه می‌خواد؟',
    pron: 'اِستی رِمِجیو پرِسیزا جی رِسِیتا',
    cefr: 'A2',
    category: 'pharmacy',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-estou-com-febre',
    pt: 'Estou com febre.',
    faLiteral: 'من با تب هستم.',
    faNatural: 'تب دارم.',
    pron: 'اِستُو کُم فِبری',
    cefr: 'A1',
    category: 'pharmacy',
    formality: 'neutral',
    notes:
      'برزیلی‌ها حالت‌های بدنی را با «estar com» بیان می‌کنند: estou com febre / com dor / com tosse.',
  }),
  mkPhrase({
    id: 'p-tem-generico',
    pt: 'Tem a versão genérica?',
    faLiteral: 'نسخه‌ی ژنریک آن را دارید؟',
    faNatural: 'مدل ژنریکش رو دارید؟',
    pron: 'تِین آ وِرسائو ژِنِریکا',
    cefr: 'B1',
    category: 'pharmacy',
    formality: 'neutral',
  }),

  // ─────────────────────────── doctor ───────────────────────────
  mkPhrase({
    id: 'p-nao-me-sinto-bem',
    pt: 'Não estou me sentindo bem.',
    faLiteral: 'حالِ خوبی احساس نمی‌کنم.',
    faNatural: 'حالم خوب نیست.',
    pron: 'نائو اِستُو می سِنتیندو بِین',
    cefr: 'A2',
    category: 'doctor',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-dor-aqui',
    pt: 'Está doendo aqui.',
    faLiteral: 'اینجا دارد درد می‌کند.',
    faNatural: 'اینجا درد می‌کنه.',
    pron: 'اِستا دُاِندو آکی',
    cefr: 'A2',
    category: 'doctor',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-marcar-consulta',
    pt: 'Gostaria de marcar uma consulta.',
    faLiteral: 'می‌خواهم یک ویزیت قرار بگذارم.',
    faNatural: 'می‌خوام یه وقت ویزیت بگیرم.',
    pron: 'گُستاریا جی مارکار اوما کُنسولتا',
    cefr: 'A2',
    category: 'doctor',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-tomo-remedio',
    pt: 'Tomo este remédio todos os dias.',
    faLiteral: 'این دارو را هر روز می‌خورم.',
    faNatural: 'این دارو رو هر روز مصرف می‌کنم.',
    pron: 'تُمو اِستی رِمِجیو تُدوس اوس جیاس',
    cefr: 'A2',
    category: 'doctor',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tenho-plano',
    pt: 'Tenho plano de saúde.',
    faLiteral: 'بیمه‌ی درمانی دارم.',
    faNatural: 'بیمه‌ی درمانی دارم.',
    pron: 'تِنیو پلانو جی سائوجی',
    cefr: 'A2',
    category: 'doctor',
    formality: 'neutral',
    notes: 'خدمات درمانی دولتی رایگان برزیل «SUS» نام دارد.',
  }),

  // ─────────────────────────── bank ───────────────────────────
  mkPhrase({
    id: 'p-abrir-conta',
    pt: 'Gostaria de abrir uma conta.',
    faLiteral: 'می‌خواهم یک حساب باز کنم.',
    faNatural: 'می‌خوام حساب باز کنم.',
    pron: 'گُستاریا جی آبریر اوما کُنتا',
    cefr: 'A2',
    category: 'bank',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-fazer-um-pix',
    pt: 'Quero fazer um Pix.',
    faLiteral: 'می‌خواهم یک پیکس انجام دهم.',
    faNatural: 'می‌خوام پیکس بزنم.',
    pron: 'کِرو فازِر اوم پیکس',
    cefr: 'A2',
    category: 'bank',
    formality: 'neutral',
    notes: '«Pix» سامانه‌ی انتقال فوری پول در برزیل است و بسیار پرکاربرد است.',
  }),
  mkPhrase({
    id: 'p-cartao-nao-passou',
    pt: 'Meu cartão não passou.',
    faLiteral: 'کارتم رد نشد.',
    faNatural: 'کارتم نکشید / پرداخت انجام نشد.',
    pron: 'مِئو کارتائو نائو پاسُو',
    cefr: 'A2',
    category: 'bank',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tarifa',
    pt: 'Esta conta tem alguma tarifa?',
    faLiteral: 'این حساب کارمزدی دارد؟',
    faNatural: 'این حساب کارمزد داره؟',
    pron: 'اِستا کُنتا تِین آلگوما تاریفا',
    cefr: 'B1',
    category: 'bank',
    formality: 'formal',
  }),

  // ─────────────────────────── transport ───────────────────────────
  mkPhrase({
    id: 'p-onibus-para-o-centro',
    pt: 'Qual ônibus vai para o centro?',
    faLiteral: 'کدام اتوبوس به مرکز شهر می‌رود؟',
    faNatural: 'کدوم اتوبوس مرکز شهر می‌ره؟',
    pron: 'کوآو اُنیبوس وای پارا او سِنترو',
    cefr: 'A2',
    category: 'transport',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-passa-perto',
    pt: 'Este ônibus passa perto da estação?',
    faLiteral: 'این اتوبوس نزدیک ایستگاه رد می‌شود؟',
    faNatural: 'این اتوبوس نزدیک ایستگاه رد می‌شه؟',
    pron: 'اِستی اُنیبوس پاسا پِرتو دا اِستاسائو',
    cefr: 'A2',
    category: 'transport',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-recarregar-cartao',
    pt: 'Preciso recarregar meu cartão de transporte.',
    faLiteral: 'باید کارت حمل‌ونقلم را شارژ کنم.',
    faNatural: 'باید کارت اتوبوسم رو شارژ کنم.',
    pron: 'پرِسیزو رِکاهِگار مِئو کارتائو جی ترانسپُرتی',
    cefr: 'A2',
    category: 'transport',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-que-horas-passa',
    pt: 'Que horas passa o próximo trem?',
    faLiteral: 'قطار بعدی چه ساعتی رد می‌شود؟',
    faNatural: 'قطار بعدی کِی می‌رسه؟',
    pron: 'کی اُراس پاسا او پرُسیمو ترِین',
    cefr: 'A2',
    category: 'transport',
    formality: 'neutral',
  }),

  // ─────────────────────────── uber-taxi ───────────────────────────
  mkPhrase({
    id: 'p-pode-me-levar',
    pt: 'Pode me levar a este endereço?',
    faLiteral: 'می‌توانی مرا به این آدرس ببری؟',
    faNatural: 'میشه منو به این آدرس ببرید؟',
    pron: 'پُجی می لِوار آ اِستی اِندِرِسو',
    cefr: 'A2',
    category: 'uber-taxi',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-pode-parar-aqui',
    pt: 'Pode parar aqui, por favor.',
    faLiteral: 'می‌توانی همینجا بایستی، لطفاً.',
    faNatural: 'همینجا نگه دارید لطفاً.',
    pron: 'پُجی پارار آکی، پور فاوُر',
    cefr: 'A1',
    category: 'uber-taxi',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-quanto-fica-a-corrida',
    pt: 'Quanto fica a corrida até o aeroporto?',
    faLiteral: 'کرایه تا فرودگاه چقدر می‌شود؟',
    faNatural: 'تا فرودگاه چند می‌شه؟',
    pron: 'کوانتو فیکا آ کُهیدا آته او آئِروپُرتو',
    cefr: 'A2',
    category: 'uber-taxi',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-estou-na-esquina',
    pt: 'Estou na esquina, de camiseta azul.',
    faLiteral: 'سرِ نبش هستم، با تی‌شرت آبی.',
    faNatural: 'سرِ نبشم، تی‌شرت آبی تنمه.',
    pron: 'اِستُو نا اِسکینا، جی کامیزِتا آزوو',
    cefr: 'A2',
    category: 'uber-taxi',
    formality: 'neutral',
  }),

  // ─────────────────────────── directions ───────────────────────────
  mkPhrase({
    id: 'p-onde-fica',
    pt: 'Onde fica a farmácia mais próxima?',
    faLiteral: 'نزدیک‌ترین داروخانه کجاست؟',
    faNatural: 'نزدیک‌ترین داروخونه کجاست؟',
    pron: 'اُنجی فیکا آ فارماسیا مایس پرُسیما',
    cefr: 'A2',
    category: 'directions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-vira-a-direita',
    pt: 'Vire à direita na próxima rua.',
    faLiteral: 'در خیابان بعدی به راست بپیچ.',
    faNatural: 'خیابون بعدی بپیچ راست.',
    pron: 'ویری آ جیرِیتا نا پرُسیما هوآ',
    cefr: 'A2',
    category: 'directions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-e-longe',
    pt: 'É longe daqui?',
    faLiteral: 'از اینجا دور است؟',
    faNatural: 'از اینجا دوره؟',
    pron: 'اِ لُنژی داکی',
    cefr: 'A1',
    category: 'directions',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-estou-perdido',
    pt: 'Estou perdido, pode me ajudar?',
    faLiteral: 'گم شده‌ام، می‌توانی کمکم کنی؟',
    faNatural: 'گم شدم، میشه کمکم کنید؟',
    pron: 'اِستُو پِردیدو، پُجی می آژودار',
    cefr: 'A2',
    category: 'directions',
    formality: 'neutral',
    notes: 'زن: perdida (پِردیدا).',
  }),
  mkPhrase({
    id: 'p-fica-em-frente',
    pt: 'Fica em frente ao mercado.',
    faLiteral: 'روبه‌روی سوپرمارکت است.',
    faNatural: 'روبه‌روی سوپرمارکته.',
    pron: 'فیکا اِین فرِنتی آئو مِرکادو',
    cefr: 'A2',
    category: 'directions',
    formality: 'neutral',
  }),

  // ─────────────────────────── shopping ───────────────────────────
  mkPhrase({
    id: 'p-so-estou-olhando',
    pt: 'Só estou olhando, obrigado.',
    faLiteral: 'فقط دارم نگاه می‌کنم، ممنون.',
    faNatural: 'فقط دارم نگاه می‌کنم، ممنون.',
    pron: 'سُ اِستُو اُلیاندو، اُبریگادو',
    cefr: 'A2',
    category: 'shopping',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-posso-experimentar',
    pt: 'Posso experimentar?',
    faLiteral: 'می‌توانم امتحان کنم؟',
    faNatural: 'می‌تونم پرو کنم؟',
    pron: 'پُسو اِسپِریمِنتار',
    cefr: 'A2',
    category: 'shopping',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tem-outro-tamanho',
    pt: 'Tem outro tamanho?',
    faLiteral: 'سایز دیگری دارید؟',
    faNatural: 'سایز دیگه‌ای دارید؟',
    pron: 'تِین اُترو تامانیو',
    cefr: 'A2',
    category: 'shopping',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-tem-desconto',
    pt: 'Tem desconto à vista?',
    faLiteral: 'برای پرداخت نقدی تخفیف دارید؟',
    faNatural: 'نقدی بخرم تخفیف داره؟',
    pron: 'تِین دِسکُنتو آ ویستا',
    cefr: 'B1',
    category: 'shopping',
    formality: 'neutral',
    notes: '«à vista» یعنی پرداخت یکجا/نقدی؛ در مقابل «parcelado» یعنی قسطی.',
  }),
  mkPhrase({
    id: 'p-vou-pensar',
    pt: 'Vou pensar e volto depois.',
    faLiteral: 'فکر می‌کنم و بعداً برمی‌گردم.',
    faNatural: 'فکرامو می‌کنم بعداً می‌آم.',
    pron: 'وُو پِنسار ای وُلتو دِپُیس',
    cefr: 'A2',
    category: 'shopping',
    formality: 'neutral',
  }),

  // ─────────────────────────── phone ───────────────────────────
  mkPhrase({
    id: 'p-alo',
    pt: 'Alô?',
    faLiteral: 'الو؟',
    faNatural: 'الو؟',
    pron: 'آلُ',
    cefr: 'A1',
    category: 'phone',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-quem-esta-falando',
    pt: 'Quem está falando?',
    faLiteral: 'چه کسی صحبت می‌کند؟',
    faNatural: 'شما؟ / ببخشید شما؟',
    pron: 'کِین اِستا فالاندو',
    cefr: 'A2',
    category: 'phone',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-pode-repetir',
    pt: 'Pode repetir, por favor?',
    faLiteral: 'می‌توانی تکرار کنی، لطفاً؟',
    faNatural: 'میشه دوباره بگید لطفاً؟',
    pron: 'پُجی رِپِتیر، پور فاوُر',
    cefr: 'A1',
    category: 'phone',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-a-ligacao-caiu',
    pt: 'A ligação caiu.',
    faLiteral: 'تماس افتاد.',
    faNatural: 'تماس قطع شد.',
    pron: 'آ لیگاسائو کایو',
    cefr: 'A2',
    category: 'phone',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-me-manda-mensagem',
    pt: 'Me manda uma mensagem no WhatsApp.',
    faLiteral: 'یک پیام در واتساپ برایم بفرست.',
    faNatural: 'تو واتساپ برام پیام بده.',
    pron: 'می ماندا اوما مِنساژِین نو واتِس-اَپی',
    cefr: 'A2',
    category: 'phone',
    formality: 'informal',
  }),

  // ─────────────────────────── apologies ───────────────────────────
  mkPhrase({
    id: 'p-desculpa',
    pt: 'Desculpa!',
    faLiteral: 'ببخشید!',
    faNatural: 'ببخشید! / معذرت!',
    pron: 'جِسکولپا',
    cefr: 'A1',
    category: 'apologies',
    formality: 'informal',
    notes: 'رسمی‌تر: «Desculpe» (جِسکولپی).',
  }),
  mkPhrase({
    id: 'p-com-licenca',
    pt: 'Com licença.',
    faLiteral: 'با اجازه.',
    faNatural: 'ببخشید (اجازه بدید رد شم).',
    pron: 'کُم لیسِنسا',
    cefr: 'A1',
    category: 'apologies',
    formality: 'neutral',
    notes:
      'برای رد شدن از کنار کسی یا جلب توجه به کار می‌رود، نه برای عذرخواهی از اشتباه.',
    commonMistakes: [
      '«Com licença» با «Desculpa» فرق دارد؛ اولی برای اجازه‌گرفتن است، دومی برای عذرخواهی.',
    ],
  }),
  mkPhrase({
    id: 'p-foi-mal',
    pt: 'Foi mal!',
    faLiteral: 'بد شد!',
    faNatural: 'شرمنده! / ببخشید!',
    pron: 'فُی ماو',
    cefr: 'A2',
    category: 'apologies',
    formality: 'informal',
    notes: 'اصطلاح بسیار خودمانی برای عذرخواهی سبک.',
  }),
  mkPhrase({
    id: 'p-nao-foi-por-mal',
    pt: 'Não foi por mal.',
    faLiteral: 'از روی بدی نبود.',
    faNatural: 'قصد بدی نداشتم.',
    pron: 'نائو فُی پور ماو',
    cefr: 'B1',
    category: 'apologies',
    formality: 'neutral',
  }),

  // ─────────────────────────── thanks ───────────────────────────
  mkPhrase({
    id: 'p-obrigado',
    pt: 'Obrigado!',
    faLiteral: 'ممنون!',
    faNatural: 'ممنون! / مرسی!',
    pron: 'اُبریگادو',
    cefr: 'A1',
    category: 'thanks',
    formality: 'neutral',
    notes:
      'مرد می‌گوید «obrigado» و زن می‌گوید «obrigada» (اُبریگادا)؛ بستگی به جنسیتِ گوینده دارد.',
    commonMistakes: [
      'جنسیت واژه به گوینده بستگی دارد نه مخاطب: مرد همیشه obrigado، زن همیشه obrigada.',
    ],
  }),
  mkPhrase({
    id: 'p-muito-obrigado',
    pt: 'Muito obrigado pela ajuda!',
    faLiteral: 'بابت کمک خیلی ممنون!',
    faNatural: 'بابت کمکتون خیلی ممنون!',
    pron: 'مویتو اُبریگادو پِلا آژودا',
    cefr: 'A2',
    category: 'thanks',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-de-nada',
    pt: 'De nada!',
    faLiteral: 'از هیچ!',
    faNatural: 'خواهش می‌کنم!',
    pron: 'جی نادا',
    cefr: 'A1',
    category: 'thanks',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-imagina',
    pt: 'Imagina!',
    faLiteral: 'تصور کن!',
    faNatural: 'خواهش می‌کنم، حرفش رو نزن!',
    pron: 'ایماژینا',
    cefr: 'A2',
    category: 'thanks',
    formality: 'informal',
    notes: 'پاسخ خودمانی و رایج به تشکر، معادل «خواهش می‌کنم».',
  }),
  mkPhrase({
    id: 'p-agradeco',
    pt: 'Agradeço muito a atenção.',
    faLiteral: 'بابت توجه بسیار سپاسگزارم.',
    faNatural: 'از توجه شما بسیار سپاسگزارم.',
    pron: 'آگرادِسو مویتو آ آتِنسائو',
    cefr: 'B1',
    category: 'thanks',
    formality: 'formal',
  }),

  // ─────────────────────────── numbers-money ───────────────────────────
  mkPhrase({
    id: 'p-quanto-e-no-total',
    pt: 'Quanto é no total?',
    faLiteral: 'در مجموع چقدر می‌شود؟',
    faNatural: 'روی هم چند می‌شه؟',
    pron: 'کوانتو اِ نو تُتاو',
    cefr: 'A1',
    category: 'numbers-money',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-dez-reais',
    pt: 'São dez reais.',
    faLiteral: 'ده رئال است.',
    faNatural: 'ده رئال می‌شه.',
    pron: 'سائو دِز هِایس',
    cefr: 'A1',
    category: 'numbers-money',
    formality: 'neutral',
    notes: 'واحد پول برزیل «real» و جمع آن «reais» است.',
  }),
  mkPhrase({
    id: 'p-tem-troco',
    pt: 'Tem troco para cinquenta?',
    faLiteral: 'برای پنجاهی خرد دارید؟',
    faNatural: 'واسه پنجاهی خرد دارید؟',
    pron: 'تِین ترُکو پارا سینکوئنتا',
    cefr: 'A2',
    category: 'numbers-money',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-esta-caro',
    pt: 'Está muito caro.',
    faLiteral: 'خیلی گران است.',
    faNatural: 'خیلی گرونه.',
    pron: 'اِستا مویتو کارو',
    cefr: 'A1',
    category: 'numbers-money',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-posso-parcelar',
    pt: 'Posso parcelar em três vezes?',
    faLiteral: 'می‌توانم سه قسط کنم؟',
    faNatural: 'می‌تونم سه قسطی کنم؟',
    pron: 'پُسو پارسِلار اِین ترِس وِزیس',
    cefr: 'B1',
    category: 'numbers-money',
    formality: 'neutral',
  }),

  // ─────────────────────────── time ───────────────────────────
  mkPhrase({
    id: 'p-que-horas-sao',
    pt: 'Que horas são?',
    faLiteral: 'ساعت چند است؟',
    faNatural: 'ساعت چنده؟',
    pron: 'کی اُراس سائو',
    cefr: 'A1',
    category: 'time',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-a-que-horas-abre',
    pt: 'A que horas abre?',
    faLiteral: 'چه ساعتی باز می‌کند؟',
    faNatural: 'ساعت چند باز می‌کنه؟',
    pron: 'آ کی اُراس آبری',
    cefr: 'A2',
    category: 'time',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-estou-atrasado',
    pt: 'Estou atrasado.',
    faLiteral: 'دیر کرده‌ام.',
    faNatural: 'دیرم شده.',
    pron: 'اِستُو آترازادو',
    cefr: 'A2',
    category: 'time',
    formality: 'neutral',
    notes: 'زن: atrasada (آترازادا).',
  }),
  mkPhrase({
    id: 'p-daqui-a-pouco',
    pt: 'Chego daqui a pouco.',
    faLiteral: 'کمی دیگر می‌رسم.',
    faNatural: 'همین الاناست می‌رسم.',
    pron: 'شِگو داکی آ پُکو',
    cefr: 'A2',
    category: 'time',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-hoje-amanha',
    pt: 'Hoje não posso, mas amanhã sim.',
    faLiteral: 'امروز نمی‌توانم، اما فردا بله.',
    faNatural: 'امروز نمی‌تونم، ولی فردا آره.',
    pron: 'اُژی نائو پُسو، مایس آمانیا سین',
    cefr: 'A2',
    category: 'time',
    formality: 'neutral',
  }),

  // ─────────────────────────── family ───────────────────────────
  mkPhrase({
    id: 'p-tem-filhos',
    pt: 'Você tem filhos?',
    faLiteral: 'بچه داری؟',
    faNatural: 'بچه داری؟',
    pron: 'وُسه تِین فیلیوس',
    cefr: 'A1',
    category: 'family',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-sou-casado',
    pt: 'Sou casado.',
    faLiteral: 'متأهل هستم.',
    faNatural: 'متأهلم.',
    pron: 'سُو کازادو',
    cefr: 'A1',
    category: 'family',
    formality: 'neutral',
    notes: 'زن: casada (کازادا). مجرد: solteiro/solteira.',
  }),
  mkPhrase({
    id: 'p-minha-esposa',
    pt: 'Esta é a minha esposa.',
    faLiteral: 'این همسرِ (زنِ) من است.',
    faNatural: 'این همسرمه.',
    pron: 'اِستا اِ آ مینیا اِسپُزا',
    cefr: 'A1',
    category: 'family',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-minha-familia-mora',
    pt: 'Minha família mora no Irã.',
    faLiteral: 'خانواده‌ام در ایران زندگی می‌کند.',
    faNatural: 'خانواده‌ام ایران زندگی می‌کنن.',
    pron: 'مینیا فامیلیا مُرا نو ایرا',
    cefr: 'A2',
    category: 'family',
    formality: 'neutral',
  }),

  // ─────────────────────────── weather ───────────────────────────
  mkPhrase({
    id: 'p-que-calor',
    pt: 'Que calor hoje!',
    faLiteral: 'چه گرمایی امروز!',
    faNatural: 'امروز چقدر گرمه!',
    pron: 'کی کالُر اُژی',
    cefr: 'A1',
    category: 'weather',
    formality: 'informal',
  }),
  mkPhrase({
    id: 'p-vai-chover',
    pt: 'Acho que vai chover.',
    faLiteral: 'فکر می‌کنم باران خواهد آمد.',
    faNatural: 'فکر کنم بارون بیاد.',
    pron: 'آشو کی وای شُوِر',
    cefr: 'A2',
    category: 'weather',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-esta-frio',
    pt: 'Está frio lá fora.',
    faLiteral: 'بیرون سرد است.',
    faNatural: 'بیرون سرده.',
    pron: 'اِستا فریو لا فُرا',
    cefr: 'A1',
    category: 'weather',
    formality: 'neutral',
  }),

  // ─────────────────────────── emergencies ───────────────────────────
  mkPhrase({
    id: 'p-me-ajuda',
    pt: 'Me ajuda, por favor!',
    faLiteral: 'کمکم کن، لطفاً!',
    faNatural: 'کمکم کنید، لطفاً!',
    pron: 'می آژودا، پور فاوُر',
    cefr: 'A1',
    category: 'emergencies',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-chame-ambulancia',
    pt: 'Chame uma ambulância!',
    faLiteral: 'یک آمبولانس صدا بزن!',
    faNatural: 'آمبولانس خبر کنید!',
    pron: 'شامی اوما آمبولانسیا',
    cefr: 'A2',
    category: 'emergencies',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-e-uma-emergencia',
    pt: 'É uma emergência!',
    faLiteral: 'اورژانسی است!',
    faNatural: 'اضطراریه!',
    pron: 'اِ اوما اِمِرژِنسیا',
    cefr: 'A2',
    category: 'emergencies',
    formality: 'neutral',
  }),
  mkPhrase({
    id: 'p-chame-a-policia',
    pt: 'Chame a polícia!',
    faLiteral: 'پلیس را خبر کن!',
    faNatural: 'پلیس خبر کنید!',
    pron: 'شامی آ پولیسیا',
    cefr: 'A2',
    category: 'emergencies',
    formality: 'neutral',
    notes: 'شماره‌ی پلیس نظامی در برزیل ۱۹۰ و آمبولانس (SAMU) ۱۹۲ است.',
  }),
  mkPhrase({
    id: 'p-fui-roubado',
    pt: 'Fui roubado.',
    faLiteral: 'دزدیده شدم.',
    faNatural: 'ازم دزدی شد / بهم دستبرد زدن.',
    pron: 'فُی هُبادو',
    cefr: 'A2',
    category: 'emergencies',
    formality: 'neutral',
    notes: 'زن: roubada (هُبادا).',
  }),
  mkPhrase({
    id: 'p-perdi-meus-documentos',
    pt: 'Perdi os meus documentos.',
    faLiteral: 'مدارکم را گم کردم.',
    faNatural: 'مدارکم رو گم کردم.',
    pron: 'پِردی اوس مِئوس دوکومِنتوس',
    cefr: 'A2',
    category: 'emergencies',
    formality: 'neutral',
  }),

  // ═══════════════════ ADMINISTRATIVE / BUREAUCRACY ═══════════════════

  // ───────────────── admin-appointment ─────────────────
  mkPhrase({
    id: 'p-agendar-atendimento',
    pt: 'Gostaria de agendar um atendimento na Polícia Federal.',
    faLiteral: 'می‌خواهم یک نوبت در پلیس فدرال بگیرم.',
    faNatural: 'می‌خواهم برای پلیس فدرال وقت بگیرم.',
    pron: 'گُستاریا جی آژِندار اوم آتِندیمِنتو نا پولیسیا فِدِراو',
    cefr: 'B1',
    category: 'admin-appointment',
    formality: 'formal',
    notes:
      'نوبت‌های پلیس فدرال معمولاً از طریق سامانه‌ی اینترنتی گرفته می‌شود.',
  }),
  mkPhrase({
    id: 'p-tenho-agendamento',
    pt: 'Tenho um agendamento marcado para hoje às dez horas.',
    faLiteral: 'برای امروز ساعت ده یک نوبتِ رزروشده دارم.',
    faNatural: 'برای امروز ساعت ده وقت گرفته‌ام.',
    pron: 'تِنیو اوم آژِندامِنتو مارکادو پارا اُژی آس دِز اُراس',
    cefr: 'A2',
    category: 'admin-appointment',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-remarcar',
    pt: 'Preciso remarcar o meu agendamento.',
    faLiteral: 'باید نوبتم را دوباره تنظیم کنم.',
    faNatural: 'باید وقتم را جابه‌جا کنم.',
    pron: 'پرِسیزو هِمارکار او مِئو آژِندامِنتو',
    cefr: 'B1',
    category: 'admin-appointment',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-qual-o-horario',
    pt: 'Qual é o horário de atendimento?',
    faLiteral: 'ساعتِ کارِ خدمت‌رسانی چیست؟',
    faNatural: 'ساعت کاری‌تون چنده؟',
    pron: 'کوآو اِ او اُراریو جی آتِندیمِنتو',
    cefr: 'A2',
    category: 'admin-appointment',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-tem-vaga-antes',
    pt: 'Há alguma vaga em data anterior?',
    faLiteral: 'در تاریخِ زودتری جای خالی هست؟',
    faNatural: 'وقتِ زودتری هست؟',
    pron: 'آ آلگوما واگا اِین داتا آنتِریور',
    cefr: 'B1',
    category: 'admin-appointment',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-cheguei-para-atendimento',
    pt: 'Cheguei para o meu atendimento das quatorze horas.',
    faLiteral: 'برای نوبتِ ساعت چهاردهم رسیده‌ام.',
    faNatural: 'برای وقتِ ساعت دو اومدم.',
    pron: 'شِگِی پارا او مِئو آتِندیمِنتو داس کاتُرزی اُراس',
    cefr: 'B1',
    category: 'admin-appointment',
    formality: 'formal',
  }),

  // ───────────────── admin-documents ─────────────────
  mkPhrase({
    id: 'p-quais-documentos-faltando',
    pt: 'Quero saber quais documentos estão faltando.',
    faLiteral: 'می‌خواهم بدانم چه مدارکی کم است.',
    faNatural: 'می‌خواهم بدانم چه مدارکی کم دارم.',
    pron: 'کِرو سابِر کوآیس دوکومِنتوس اِستائو فالتاندو',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-preciso-original',
    pt: 'Preciso apresentar o original?',
    faLiteral: 'باید اصلِ مدرک را ارائه بدهم؟',
    faNatural: 'اصلِ مدرک رو باید بیارم؟',
    pron: 'پرِسیزو آپرِزِنتار او اُریژیناو',
    cefr: 'A2',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-enviar-pdf',
    pt: 'Posso enviar este documento em PDF?',
    faLiteral: 'می‌توانم این مدرک را در قالب پی‌دی‌اف بفرستم؟',
    faNatural: 'می‌تونم این مدرک رو پی‌دی‌اف بفرستم؟',
    pron: 'پُسو اِنویار اِستی دوکومِنتو اِین په-ده-اِفی',
    cefr: 'A2',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-onde-assinar',
    pt: 'Onde devo assinar?',
    faLiteral: 'کجا باید امضا کنم؟',
    faNatural: 'کجا رو امضا کنم؟',
    pron: 'اُنجی دِوو آسینار',
    cefr: 'A2',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-copia-autenticada',
    pt: 'Preciso de uma cópia autenticada?',
    faLiteral: 'به یک کپیِ برابر اصل نیاز دارم؟',
    faNatural: 'کپیِ برابر اصل لازمه؟',
    pron: 'پرِسیزو جی اوما کُپیا آاوتِنتیکادا',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
    notes: '«cópia autenticada» کپیِ تأییدشده توسط دفترِ اسناد (cartório) است.',
  }),
  mkPhrase({
    id: 'p-traducao-juramentada',
    pt: 'Este documento precisa de tradução juramentada?',
    faLiteral: 'این مدرک به ترجمه‌ی رسمیِ سوگندخورده نیاز دارد؟',
    faNatural: 'این مدرک ترجمه‌ی رسمی می‌خواد؟',
    pron: 'اِستی دوکومِنتو پرِسیزا جی ترادوسائو ژورامِنتادا',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
    notes:
      '«tradução juramentada» ترجمه‌ی رسمیِ قانونی است که فقط مترجمِ رسمی (tradutor juramentado) می‌تواند انجام دهد.',
  }),
  mkPhrase({
    id: 'p-precisa-apostila',
    pt: 'Este documento precisa de apostilamento?',
    faLiteral: 'این مدرک به تأییدیه‌ی آپوستیل نیاز دارد؟',
    faNatural: 'این مدرک آپوستیل می‌خواد؟',
    pron: 'اِستی دوکومِنتو پرِسیزا جی آپُستیلامِنتو',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
    notes:
      '«Apostila de Haia» تأییدیه‌ای بین‌المللی برای معتبر شدنِ اسناد در کشور دیگر است.',
  }),
  mkPhrase({
    id: 'p-onde-tiro-copia',
    pt: 'Onde posso tirar cópias por aqui?',
    faLiteral: 'کجا می‌توانم اینجا کپی بگیرم؟',
    faNatural: 'اینجا کجا می‌شه کپی گرفت؟',
    pron: 'اُنجی پُسو تیرار کُپیاس پور آکی',
    cefr: 'A2',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-esses-documentos-suficientes',
    pt: 'Esses documentos são suficientes?',
    faLiteral: 'این مدارک کافی هستند؟',
    faNatural: 'این مدارک کافیه؟',
    pron: 'اِسیس دوکومِنتوس سائو سوفیسیِنتیس',
    cefr: 'A2',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-comprovante-de-residencia',
    pt: 'Trouxe um comprovante de residência atualizado.',
    faLiteral: 'یک مدرکِ اثباتِ محلِ سکونتِ به‌روز آورده‌ام.',
    faNatural: 'یک مدرکِ محل سکونتِ جدید آورده‌ام.',
    pron: 'ترُسی اوم کُمپروانتی جی هِزیدِنسیا آتوالیزادو',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
    notes: '«comprovante de residência» معمولاً قبضِ آب، برق یا تلفن است.',
  }),
  mkPhrase({
    id: 'p-validade-documento',
    pt: 'Até quando este documento é válido?',
    faLiteral: 'این مدرک تا کِی معتبر است؟',
    faNatural: 'این مدرک تا کِی اعتبار داره؟',
    pron: 'آته کوآندو اِستی دوکومِنتو اِ والیدو',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-preencher-formulario',
    pt: 'Não sei como preencher este formulário.',
    faLiteral: 'نمی‌دانم چطور این فرم را پر کنم.',
    faNatural: 'نمی‌دونم این فرم رو چطور پر کنم.',
    pron: 'نائو سِی کُمو پرِاِنشِر اِستی فُرمولاریو',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-corrigir-informacao',
    pt: 'Gostaria de corrigir uma informação no formulário.',
    faLiteral: 'می‌خواهم یک اطلاعات را در فرم اصلاح کنم.',
    faNatural: 'می‌خواهم یک مورد را توی فرم اصلاح کنم.',
    pron: 'گُستاریا جی کُهیژیر اوما اینفُرماسائو نو فُرمولاریو',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-erro-no-nome',
    pt: 'Há um erro na grafia do meu nome.',
    faLiteral: 'در املای نامِ من یک اشتباه هست.',
    faNatural: 'اسمم اشتباه نوشته شده.',
    pron: 'آ اوم اِهو نا گرافیا دو مِئو نُمی',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-segunda-via',
    pt: 'Preciso da segunda via da minha certidão.',
    faLiteral: 'به نسخه‌ی دوم (المثنیِ) شناسنامه‌ام نیاز دارم.',
    faNatural: 'المثنیِ سندم رو لازم دارم.',
    pron: 'پرِسیزو دا سِگوندا ویا دا مینیا سِرتیدائو',
    cefr: 'B1',
    category: 'admin-documents',
    formality: 'formal',
    notes: '«segunda via» یعنی نسخه‌ی المثنی یا صدور مجددِ یک سند.',
  }),

  // ───────────────── admin-process ─────────────────
  mkPhrase({
    id: 'p-acompanhar-andamento',
    pt: 'Gostaria de acompanhar o andamento do meu processo.',
    faLiteral: 'می‌خواهم روندِ پرونده‌ام را پیگیری کنم.',
    faNatural: 'می‌خواهم وضعیتِ پرونده‌ام را پیگیری کنم.',
    pron: 'گُستاریا جی آکُمپانیار او آنداملِنتو دو مِئو پرُسِسو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-numero-do-protocolo',
    pt: 'Este é o número do meu protocolo.',
    faLiteral: 'این شماره‌ی رسیدِ (پروتکلِ) من است.',
    faNatural: 'این شماره‌ی پیگیریِ من است.',
    pron: 'اِستی اِ او نومِرو دو مِئو پروتوکُلو',
    cefr: 'A2',
    category: 'admin-process',
    formality: 'formal',
    notes:
      '«protocolo» شماره‌ی پیگیریِ درخواست است که هنگام ثبت دریافت می‌شود.',
  }),
  mkPhrase({
    id: 'p-recebi-exigencia',
    pt: 'Recebi uma exigência e preciso de orientação.',
    faLiteral: 'یک اخطارِ نقص دریافت کرده‌ام و به راهنمایی نیاز دارم.',
    faNatural: 'یک اخطارِ رفعِ نقص گرفته‌ام و راهنمایی می‌خواهم.',
    pron: 'هِسِبی اوما اِزیژِنسیا ای پرِسیزو جی اُریِنتاسائو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
    notes: '«exigência» درخواستِ رسمیِ اداره برای تکمیل یا اصلاحِ مدارک است.',
  }),
  mkPhrase({
    id: 'p-quanto-tempo-demora',
    pt: 'Quanto tempo demora para sair o resultado?',
    faLiteral: 'چقدر طول می‌کشد تا نتیجه صادر شود؟',
    faNatural: 'چقدر طول می‌کشه نتیجه بیاد؟',
    pron: 'کوانتو تِمپو دِمُرا پارا سایر او هِزولتادو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-processo-parado',
    pt: 'Meu processo está parado há dois meses.',
    faLiteral: 'پرونده‌ام دو ماه است متوقف مانده.',
    faNatural: 'پرونده‌ام دو ماهه راکد مونده.',
    pron: 'مِئو پرُسِسو اِستا پارادو آ دُیس مِزیس',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-em-qual-etapa',
    pt: 'Em qual etapa está o meu pedido?',
    faLiteral: 'درخواستِ من در کدام مرحله است؟',
    faNatural: 'درخواستم تو کدوم مرحله‌ست؟',
    pron: 'اِین کوآو اِتاپا اِستا او مِئو پِدیدو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-como-consulto-online',
    pt: 'Como faço para consultar o processo pela internet?',
    faLiteral: 'چطور می‌توانم پرونده را از طریق اینترنت بررسی کنم؟',
    faNatural: 'چطور می‌تونم پرونده رو اینترنتی چک کنم؟',
    pron: 'کُمو فاسو پارا کُنسولتار او پرُسِسو پِلا اینتِرنِتی',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-preciso-recorrer',
    pt: 'Meu pedido foi negado. Posso recorrer?',
    faLiteral: 'درخواستم رد شد. می‌توانم اعتراض (تجدیدنظر) کنم؟',
    faNatural: 'درخواستم رد شد. می‌تونم اعتراض بزنم؟',
    pron: 'مِئو پِدیدو فُی نِگادو. پُسو هِکُهِر',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
    notes: '«recorrer» یعنی اعتراض/تجدیدنظرخواهی نسبت به تصمیمِ اداری.',
  }),
  mkPhrase({
    id: 'p-prazo-para-resposta',
    pt: 'Qual é o prazo para eu responder?',
    faLiteral: 'مهلتِ من برای پاسخ دادن چقدر است؟',
    faNatural: 'تا کِی وقت دارم جواب بدم؟',
    pron: 'کوآو اِ او پرازو پارا اِئو هِسپُندِر',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-recebi-notificacao',
    pt: 'Recebi uma notificação, mas não entendi o motivo.',
    faLiteral: 'یک ابلاغیه دریافت کرده‌ام، اما دلیلش را نفهمیدم.',
    faNatural: 'یه ابلاغیه گرفتم ولی دلیلش رو نفهمیدم.',
    pron: 'هِسِبی اوما نُتیفیکاسائو، مایس نائو اِنتِندی او مُتیوو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),

  // ───────────────── admin-immigration (Polícia Federal) ─────────────────
  mkPhrase({
    id: 'p-solicitar-cpf',
    pt: 'Vim solicitar o meu CPF.',
    faLiteral: 'آمده‌ام تا سی‌پی‌اِف‌ام را درخواست کنم.',
    faNatural: 'اومدم CPF بگیرم.',
    pron: 'وین سُلیسیتار او مِئو سه-په-اِفی',
    cefr: 'A2',
    category: 'admin-immigration',
    formality: 'formal',
    notes:
      '«CPF» شماره‌ی مالیاتیِ افراد در برزیل است و برای تقریباً همه‌کار لازم است.',
  }),
  mkPhrase({
    id: 'p-registro-migratorio',
    pt: 'Preciso fazer o meu registro migratório.',
    faLiteral: 'باید ثبتِ مهاجرتی‌ام را انجام دهم.',
    faNatural: 'باید ثبت‌نامِ اقامتم رو انجام بدم.',
    pron: 'پرِسیزو فازِر او مِئو هِژیسترو میگراتُریو',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-solicitar-crnm',
    pt: 'Vim solicitar a minha Carteira de Registro Nacional Migratório.',
    faLiteral: 'آمده‌ام تا کارتِ ثبتِ ملیِ مهاجرتی‌ام را درخواست کنم.',
    faNatural: 'اومدم کارتِ اقامتم (CRNM) رو بگیرم.',
    pron: 'وین سُلیسیتار آ مینیا کارتِیرا جی هِژیسترو ناسیوناو میگراتُریو',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
    notes:
      '«CRNM» کارتِ اقامتِ اتباعِ خارجی در برزیل است (جایگزینِ RNE قدیمی).',
  }),
  mkPhrase({
    id: 'p-renovar-visto',
    pt: 'Gostaria de renovar o meu visto.',
    faLiteral: 'می‌خواهم ویزایم را تمدید کنم.',
    faNatural: 'می‌خوام ویزام رو تمدید کنم.',
    pron: 'گُستاریا جی هِنُوار او مِئو ویستو',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-prorrogar-prazo',
    pt: 'Preciso prorrogar o meu prazo de estada.',
    faLiteral: 'باید مهلتِ اقامتم را تمدید کنم.',
    faNatural: 'باید مدتِ اقامتم رو تمدید کنم.',
    pron: 'پرِسیزو پروهوگار او مِئو پرازو جی اِستادا',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-refugio',
    pt: 'Gostaria de solicitar refúgio.',
    faLiteral: 'می‌خواهم درخواستِ پناهندگی بدهم.',
    faNatural: 'می‌خوام درخواستِ پناهندگی بدم.',
    pron: 'گُستاریا جی سُلیسیتار هِفوژیو',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
    notes: 'درخواستِ پناهندگی در برزیل از طریقِ CONARE بررسی می‌شود.',
  }),
  mkPhrase({
    id: 'p-autorizacao-residencia',
    pt: 'Estou pedindo autorização de residência.',
    faLiteral: 'دارم مجوزِ اقامت درخواست می‌کنم.',
    faNatural: 'دارم برای اجازه‌ی اقامت درخواست می‌دم.',
    pron: 'اِستُو پِدیندو آاوتوریزاسائو جی هِزیدِنسیا',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-protocolo-vale-documento',
    pt: 'Este protocolo vale como documento provisório?',
    faLiteral: 'این رسید به‌عنوانِ مدرکِ موقت اعتبار دارد؟',
    faNatural: 'این رسید حکمِ مدرکِ موقت رو داره؟',
    pron: 'اِستی پروتوکُلو والی کُمو دوکومِنتو پروویزُریو',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-taxa-e-gru',
    pt: 'Onde pago a taxa da GRU?',
    faLiteral: 'کجا کارمزدِ GRU را پرداخت کنم؟',
    faNatural: 'کجا باید هزینه‌ی GRU رو بدم؟',
    pron: 'اُنجی پاگو آ تاکسا دا ژه-اِهه-او',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
    notes:
      '«GRU» قبضِ پرداختِ عوارضِ دولتی است که در بانک یا اینترنتی پرداخت می‌شود.',
  }),
  mkPhrase({
    id: 'p-onde-fica-a-pf',
    pt: 'Onde fica a unidade da Polícia Federal mais próxima?',
    faLiteral: 'نزدیک‌ترین شعبه‌ی پلیس فدرال کجاست؟',
    faNatural: 'نزدیک‌ترین دفترِ پلیس فدرال کجاست؟',
    pron: 'اُنجی فیکا آ اونیدادی دا پولیسیا فِدِراو مایس پرُسیما',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-preciso-tradutor',
    pt: 'Não falo bem português; posso trazer um tradutor?',
    faLiteral: 'پرتغالی را خوب صحبت نمی‌کنم؛ می‌توانم یک مترجم بیاورم؟',
    faNatural: 'پرتغالی‌ام خوب نیست؛ می‌تونم مترجم بیارم؟',
    pron: 'نائو فالو بِین پورتوگِس؛ پُسو ترازِر اوم ترادوتُر',
    cefr: 'B1',
    category: 'admin-immigration',
    formality: 'formal',
  }),

  // ───────────────── admin-cartorio ─────────────────
  mkPhrase({
    id: 'p-reconhecer-firma',
    pt: 'Preciso reconhecer firma neste documento.',
    faLiteral: 'باید امضای این مدرک را تأیید (گواهی) کنم.',
    faNatural: 'باید امضای این مدرک رو تو دفترخانه تأیید کنم.',
    pron: 'پرِسیزو هِکُنیِسِر فیرما نِستی دوکومِنتو',
    cefr: 'B1',
    category: 'admin-cartorio',
    formality: 'formal',
    notes:
      '«reconhecer firma» گواهیِ رسمیِ صحتِ امضا در دفترِ اسناد (cartório) است.',
  }),
  mkPhrase({
    id: 'p-autenticar-copia',
    pt: 'Gostaria de autenticar estas cópias.',
    faLiteral: 'می‌خواهم این کپی‌ها را برابرِ اصل کنم.',
    faNatural: 'می‌خوام این کپی‌ها رو برابر اصل کنم.',
    pron: 'گُستاریا جی آاوتِنتیکار اِستاس کُپیاس',
    cefr: 'B1',
    category: 'admin-cartorio',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-procuracao',
    pt: 'Preciso fazer uma procuração.',
    faLiteral: 'باید یک وکالت‌نامه تنظیم کنم.',
    faNatural: 'باید یه وکالت‌نامه بگیرم.',
    pron: 'پرِسیزو فازِر اوما پروکوراسائو',
    cefr: 'B1',
    category: 'admin-cartorio',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-certidao-nascimento',
    pt: 'Onde solicito a certidão de nascimento?',
    faLiteral: 'شناسنامه (گواهیِ تولد) را کجا درخواست کنم؟',
    faNatural: 'گواهیِ تولد رو کجا بگیرم؟',
    pron: 'اُنجی سُلیسیتو آ سِرتیدائو جی ناسیمِنتو',
    cefr: 'B1',
    category: 'admin-cartorio',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-certidao-casamento',
    pt: 'Quanto custa a certidão de casamento?',
    faLiteral: 'گواهیِ ازدواج چقدر هزینه دارد؟',
    faNatural: 'سندِ ازدواج چقدر می‌شه؟',
    pron: 'کوانتو کوستا آ سِرتیدائو جی کازامِنتو',
    cefr: 'B1',
    category: 'admin-cartorio',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-quanto-tempo-cartorio',
    pt: 'Quanto tempo leva para ficar pronto?',
    faLiteral: 'چقدر طول می‌کشد تا آماده شود؟',
    faNatural: 'چقدر طول می‌کشه آماده بشه؟',
    pron: 'کوانتو تِمپو لِوا پارا فیکار پرُنتو',
    cefr: 'A2',
    category: 'admin-cartorio',
    formality: 'formal',
  }),

  // ───────────────── admin-university ─────────────────
  mkPhrase({
    id: 'p-revalidar-diploma',
    pt: 'Gostaria de revalidar o meu diploma estrangeiro.',
    faLiteral:
      'می‌خواهم مدرکِ تحصیلیِ خارجی‌ام را معادل‌سازی (تأیید مجدد) کنم.',
    faNatural: 'می‌خوام مدرکِ خارجی‌ام رو معادل‌سازی کنم.',
    pron: 'گُستاریا جی هِوالیدار او مِئو دیپلوما اِسترانژِیرو',
    cefr: 'B1',
    category: 'admin-university',
    formality: 'formal',
    notes:
      '«revalidação» فرایندِ به‌رسمیت‌شناختنِ مدرکِ خارجی توسط دانشگاه‌های برزیل است.',
  }),
  mkPhrase({
    id: 'p-processo-seletivo',
    pt: 'Onde encontro o edital do processo seletivo?',
    faLiteral: 'فراخوانِ فرایندِ گزینش را کجا پیدا کنم؟',
    faNatural: 'اطلاعیه‌ی پذیرش رو کجا پیدا کنم؟',
    pron: 'اُنجی اِنکُنترو او اِدیتاو دو پرُسِسو سِلِتیوو',
    cefr: 'B1',
    category: 'admin-university',
    formality: 'formal',
    notes: '«edital» فراخوانِ رسمیِ حاویِ قوانین و مهلت‌های یک فرایند است.',
  }),
  mkPhrase({
    id: 'p-fazer-matricula',
    pt: 'Preciso fazer a minha matrícula.',
    faLiteral: 'باید ثبت‌نامم را انجام دهم.',
    faNatural: 'باید ثبت‌نام کنم.',
    pron: 'پرِسیزو فازِر آ مینیا ماتریکولا',
    cefr: 'A2',
    category: 'admin-university',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-historico-escolar',
    pt: 'Preciso apresentar o meu histórico escolar.',
    faLiteral: 'باید کارنامه‌ی تحصیلی‌ام را ارائه بدهم.',
    faNatural: 'باید ریزنمراتم رو بدم.',
    pron: 'پرِسیزو آپرِزِنتار او مِئو ایستُریکو اِسکُلار',
    cefr: 'B1',
    category: 'admin-university',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-comprovante-matricula',
    pt: 'Poderia me dar um comprovante de matrícula?',
    faLiteral: 'می‌توانید یک گواهیِ ثبت‌نام به من بدهید؟',
    faNatural: 'میشه گواهیِ ثبت‌نام بهم بدید؟',
    pron: 'پودِریا می دار اوم کُمپروانتی جی ماتریکولا',
    cefr: 'B1',
    category: 'admin-university',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-prova-de-proficiencia',
    pt: 'Preciso de um teste de proficiência em português?',
    faLiteral: 'به آزمونِ تسلط بر زبانِ پرتغالی نیاز دارم؟',
    faNatural: 'آزمونِ زبانِ پرتغالی لازم دارم؟',
    pron: 'پرِسیزو جی اوم تِستی جی پروفیسیِنسیا اِین پورتوگِس',
    cefr: 'B1',
    category: 'admin-university',
    formality: 'formal',
    notes: 'آزمونِ رسمیِ تسلط بر پرتغالی برای خارجی‌ها «Celpe-Bras» نام دارد.',
  }),

  // ───────────────── admin-general courtesy ─────────────────
  mkPhrase({
    id: 'p-poderia-me-ajudar',
    pt: 'Poderia me ajudar com este processo, por favor?',
    faLiteral: 'می‌توانید با این پرونده به من کمک کنید، لطفاً؟',
    faNatural: 'میشه توی این کار کمکم کنید لطفاً؟',
    pron: 'پودِریا می آژودار کُم اِستی پرُسِسو، پور فاوُر',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-nao-entendi-pode-explicar',
    pt: 'Não entendi. O senhor poderia explicar de novo?',
    faLiteral: 'نفهمیدم. آقا می‌توانید دوباره توضیح بدهید؟',
    faNatural: 'متوجه نشدم. میشه دوباره توضیح بدید؟',
    pron: 'نائو اِنتِندی. او سِنیُر پودِریا اِسپلیکار جی نُوو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
    notes:
      '«o senhor / a senhora» شکلِ محترمانه‌ی خطاب است؛ در ادارات همیشه از آن استفاده کنید.',
  }),
  mkPhrase({
    id: 'p-com-quem-eu-falo',
    pt: 'Com quem eu falo sobre isso?',
    faLiteral: 'درباره‌ی این با چه کسی صحبت کنم؟',
    faNatural: 'واسه این باید با کی حرف بزنم؟',
    pron: 'کُم کِین اِئو فالو سُبری ایسو',
    cefr: 'A2',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-pode-escrever',
    pt: 'Pode escrever isso para mim, por favor?',
    faLiteral: 'می‌توانید این را برایم بنویسید، لطفاً؟',
    faNatural: 'میشه اینو برام بنویسید لطفاً؟',
    pron: 'پُجی اِسکرِوِر ایسو پارا مین، پور فاوُر',
    cefr: 'A2',
    category: 'admin-process',
    formality: 'formal',
  }),
  mkPhrase({
    id: 'p-aguardo-retorno',
    pt: 'Fico no aguardo do retorno.',
    faLiteral: 'در انتظارِ پاسخِ شما می‌مانم.',
    faNatural: 'منتظرِ پاسختون می‌مونم.',
    pron: 'فیکو نو آگواردو دو هِتُرنو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
    notes: 'عبارتِ رایج و مؤدبانه برای پایانِ ایمیل یا مکالمه‌ی اداری.',
  }),
  mkPhrase({
    id: 'p-desde-ja-agradeco',
    pt: 'Desde já, agradeço a atenção.',
    faLiteral: 'از همین حالا، بابتِ توجه سپاسگزارم.',
    faNatural: 'پیشاپیش از توجه‌تون ممنونم.',
    pron: 'دِزدی ژا، آگرادِسو آ آتِنسائو',
    cefr: 'B1',
    category: 'admin-process',
    formality: 'formal',
  }),
];
