import { mkVocab } from './helpers';
import type { Vocab } from '@/domain/content/schema';

export const vocab: Vocab[] = [
  // ── greetings ──────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-ola',
    pt: 'olá',
    faLiteral: 'سلام',
    pron: 'اُ-لا',
    cefr: 'A1',
    category: 'greetings',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-oi',
    pt: 'oi',
    faLiteral: 'سلام',
    faNatural: 'سلام (خودمانی)',
    pron: 'اُی',
    cefr: 'A1',
    category: 'greetings',
    pos: 'other',
    formality: 'informal',
    notes: 'خودمانی‌تر از «olá» است.',
  }),
  mkVocab({
    id: 'v-tchau',
    pt: 'tchau',
    faLiteral: 'خداحافظ',
    pron: 'چاو',
    cefr: 'A1',
    category: 'greetings',
    pos: 'other',
    formality: 'informal',
  }),
  mkVocab({
    id: 'v-bom-dia',
    pt: 'bom dia',
    faLiteral: 'روزِ خوش',
    faNatural: 'صبح بخیر',
    pron: 'بُن جیا',
    cefr: 'A1',
    category: 'greetings',
    pos: 'phrase',
    notes: 'تا حدود ظهر استفاده می‌شود.',
  }),
  mkVocab({
    id: 'v-boa-tarde',
    pt: 'boa tarde',
    faLiteral: 'عصرِ خوش',
    faNatural: 'عصر بخیر',
    pron: 'بُآ تاردی',
    cefr: 'A1',
    category: 'greetings',
    pos: 'phrase',
    notes: 'از حدود ظهر تا غروب.',
  }),
  mkVocab({
    id: 'v-boa-noite',
    pt: 'boa noite',
    faLiteral: 'شبِ خوش',
    faNatural: 'شب بخیر',
    pron: 'بُآ نُی‌چی',
    cefr: 'A1',
    category: 'greetings',
    pos: 'phrase',
    notes: 'هم برای سلامِ شب و هم خداحافظیِ شب.',
  }),
  mkVocab({
    id: 'v-obrigado',
    pt: 'obrigado',
    faLiteral: 'ممنون (مرد)',
    faNatural: 'ممنون',
    pron: 'اُبری-گادو',
    cefr: 'A1',
    category: 'greetings',
    pos: 'other',
    commonMistakes: [
      'مردها «obrigado» و زن‌ها «obrigada» می‌گویند؛ بسته به گویندهٔ آن تغییر می‌کند.',
    ],
  }),
  mkVocab({
    id: 'v-obrigada',
    pt: 'obrigada',
    faLiteral: 'ممنون (زن)',
    faNatural: 'ممنون',
    pron: 'اُبری-گادا',
    cefr: 'A1',
    category: 'greetings',
    pos: 'other',
    notes: 'شکلِ مؤنث؛ اگر زن هستید این را بگویید.',
  }),
  mkVocab({
    id: 'v-por-favor',
    pt: 'por favor',
    faLiteral: 'لطفاً',
    pron: 'پور فاوُر',
    cefr: 'A1',
    category: 'greetings',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'v-de-nada',
    pt: 'de nada',
    faLiteral: 'قابلی نداشت',
    faNatural: 'خواهش می‌کنم',
    pron: 'جی نادا',
    cefr: 'A1',
    category: 'greetings',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'v-desculpa',
    pt: 'desculpa',
    faLiteral: 'ببخشید',
    pron: 'جیس-کولپا',
    cefr: 'A1',
    category: 'greetings',
    pos: 'other',
    formality: 'informal',
  }),
  mkVocab({
    id: 'v-com-licenca',
    pt: 'com licença',
    faLiteral: 'با اجازه',
    faNatural: 'اجازه بدهید / ببخشید (برای رد شدن)',
    pron: 'کُن لی-سِنسا',
    cefr: 'A1',
    category: 'greetings',
    pos: 'phrase',
  }),

  // ── numbers ────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-zero',
    pt: 'zero',
    faLiteral: 'صفر',
    pron: 'زِرو',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-um',
    pt: 'um',
    faLiteral: 'یک',
    pron: 'اونگ',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
    notes: 'برای اسم مؤنث «uma» می‌شود.',
  }),
  mkVocab({
    id: 'v-dois',
    pt: 'dois',
    faLiteral: 'دو',
    pron: 'دُیس',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
    notes: 'برای مؤنث «duas» می‌شود.',
  }),
  mkVocab({
    id: 'v-tres',
    pt: 'três',
    faLiteral: 'سه',
    pron: 'ترِس',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-quatro',
    pt: 'quatro',
    faLiteral: 'چهار',
    pron: 'کواترو',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-cinco',
    pt: 'cinco',
    faLiteral: 'پنج',
    pron: 'سینکو',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-seis',
    pt: 'seis',
    faLiteral: 'شش',
    pron: 'سِیس',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-sete',
    pt: 'sete',
    faLiteral: 'هفت',
    pron: 'سِچی',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-oito',
    pt: 'oito',
    faLiteral: 'هشت',
    pron: 'اُی‌تو',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-nove',
    pt: 'nove',
    faLiteral: 'نه',
    pron: 'نُوی',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-dez',
    pt: 'dez',
    faLiteral: 'ده',
    pron: 'دِس',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-vinte',
    pt: 'vinte',
    faLiteral: 'بیست',
    pron: 'وین‌چی',
    cefr: 'A1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'v-cem',
    pt: 'cem',
    faLiteral: 'صد',
    pron: 'سِنگ',
    cefr: 'A2',
    category: 'numbers',
    pos: 'other',
    notes: 'دقیقاً صد؛ برای «صد و…» می‌شود «cento».',
  }),
  mkVocab({
    id: 'v-mil',
    pt: 'mil',
    faLiteral: 'هزار',
    pron: 'میو',
    cefr: 'A2',
    category: 'numbers',
    pos: 'other',
  }),

  // ── days-time ──────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-segunda',
    pt: 'segunda-feira',
    faLiteral: 'دوشنبه',
    pron: 'سِگوندا فِیرا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
    notes: 'در گفتار اغلب فقط «segunda» گفته می‌شود.',
  }),
  mkVocab({
    id: 'v-terca',
    pt: 'terça-feira',
    faLiteral: 'سه‌شنبه',
    pron: 'تِرسا فِیرا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'v-quarta',
    pt: 'quarta-feira',
    faLiteral: 'چهارشنبه',
    pron: 'کوآرتا فِیرا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'v-quinta',
    pt: 'quinta-feira',
    faLiteral: 'پنجشنبه',
    pron: 'کین‌تا فِیرا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'v-sexta',
    pt: 'sexta-feira',
    faLiteral: 'جمعه',
    pron: 'سِستا فِیرا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'v-sabado',
    pt: 'sábado',
    faLiteral: 'شنبه',
    pron: 'سابادو',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-domingo',
    pt: 'domingo',
    faLiteral: 'یکشنبه',
    pron: 'دومینگو',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-hoje',
    pt: 'hoje',
    faLiteral: 'امروز',
    pron: 'اُجی',
    cefr: 'A1',
    category: 'days-time',
    pos: 'adv',
  }),
  mkVocab({
    id: 'v-amanha',
    pt: 'amanhã',
    faLiteral: 'فردا',
    pron: 'آ-مانیا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'adv',
    commonMistakes: ['«nh» مثل «نی» فارسی تلفظ می‌شود، نه «ن + ه».'],
  }),
  mkVocab({
    id: 'v-ontem',
    pt: 'ontem',
    faLiteral: 'دیروز',
    pron: 'اُن‌تِنگ',
    cefr: 'A1',
    category: 'days-time',
    pos: 'adv',
  }),
  mkVocab({
    id: 'v-agora',
    pt: 'agora',
    faLiteral: 'الان',
    pron: 'آ-گورا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'adv',
  }),
  mkVocab({
    id: 'v-dia',
    pt: 'dia',
    faLiteral: 'روز',
    pron: 'جیا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'm',
    plural: 'dias',
    commonMistakes: ['با اینکه به «a» ختم می‌شود، مذکر است: «o dia».'],
  }),
  mkVocab({
    id: 'v-semana',
    pt: 'semana',
    faLiteral: 'هفته',
    pron: 'سِمانا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
    plural: 'semanas',
  }),
  mkVocab({
    id: 'v-mes',
    pt: 'mês',
    faLiteral: 'ماه (تقویم)',
    pron: 'مِس',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'm',
    plural: 'meses',
  }),
  mkVocab({
    id: 'v-ano',
    pt: 'ano',
    faLiteral: 'سال',
    pron: 'آنو',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'm',
    plural: 'anos',
  }),
  mkVocab({
    id: 'v-hora',
    pt: 'hora',
    faLiteral: 'ساعت (زمان)',
    pron: 'اُرا',
    cefr: 'A1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
    plural: 'horas',
    notes: '«h» تلفظ نمی‌شود.',
  }),

  // ── family ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-familia',
    pt: 'família',
    faLiteral: 'خانواده',
    pron: 'فامیلیا',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
    plural: 'famílias',
  }),
  mkVocab({
    id: 'v-pai',
    pt: 'pai',
    faLiteral: 'پدر',
    pron: 'پای',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
    plural: 'pais',
    notes: '«pais» هم یعنی «پدرها» و هم «والدین».',
  }),
  mkVocab({
    id: 'v-mae',
    pt: 'mãe',
    faLiteral: 'مادر',
    pron: 'مای‌نگ',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
    plural: 'mães',
    commonMistakes: ['«ãe» صدای خیشومی دارد؛ تقریباً مثل «مای» با کمی «ن».'],
  }),
  mkVocab({
    id: 'v-filho',
    pt: 'filho',
    faLiteral: 'پسر (فرزند)',
    pron: 'فیلیو',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
    plural: 'filhos',
  }),
  mkVocab({
    id: 'v-filha',
    pt: 'filha',
    faLiteral: 'دختر (فرزند)',
    pron: 'فیلیا',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
    plural: 'filhas',
  }),
  mkVocab({
    id: 'v-irmao',
    pt: 'irmão',
    faLiteral: 'برادر',
    pron: 'ایر-مائو',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
    plural: 'irmãos',
    commonMistakes: ['پایانهٔ «ão» خیشومی است؛ جمعش «irmãos» می‌شود.'],
  }),
  mkVocab({
    id: 'v-irma',
    pt: 'irmã',
    faLiteral: 'خواهر',
    pron: 'ایر-ما',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
    plural: 'irmãs',
  }),
  mkVocab({
    id: 'v-avo-m',
    pt: 'avô',
    faLiteral: 'پدربزرگ',
    pron: 'آ-وُ',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
    plural: 'avôs',
    commonMistakes: [
      '«avô» (پدربزرگ) با «avó» (مادربزرگ) فقط در تلفظ فرق دارد: «اُ» بسته و «اُ» باز.',
    ],
  }),
  mkVocab({
    id: 'v-avo-f',
    pt: 'avó',
    faLiteral: 'مادربزرگ',
    pron: 'آ-وُ (باز)',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
    plural: 'avós',
  }),
  mkVocab({
    id: 'v-marido',
    pt: 'marido',
    faLiteral: 'شوهر',
    pron: 'ماریدو',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
    plural: 'maridos',
  }),
  mkVocab({
    id: 'v-esposa',
    pt: 'esposa',
    faLiteral: 'همسر (زن)',
    pron: 'اِس-پوزا',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
    plural: 'esposas',
  }),
  mkVocab({
    id: 'v-amigo',
    pt: 'amigo',
    faLiteral: 'دوست (مرد)',
    pron: 'آ-میگو',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
    plural: 'amigos',
    notes: 'برای زن «amiga» می‌شود.',
  }),
  mkVocab({
    id: 'v-crianca',
    pt: 'criança',
    faLiteral: 'کودک',
    pron: 'کری-آنسا',
    cefr: 'A1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
    plural: 'crianças',
    commonMistakes: ['همیشه مؤنث است، حتی برای پسربچه: «a criança».'],
  }),

  // ── house ──────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-casa',
    pt: 'casa',
    faLiteral: 'خانه',
    pron: 'کازا',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'casas',
  }),
  mkVocab({
    id: 'v-apartamento',
    pt: 'apartamento',
    faLiteral: 'آپارتمان',
    pron: 'آپارتامِنتو',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'm',
    plural: 'apartamentos',
  }),
  mkVocab({
    id: 'v-quarto',
    pt: 'quarto',
    faLiteral: 'اتاق‌خواب',
    pron: 'کوآرتو',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'm',
    plural: 'quartos',
    notes: '«quarto» هم یعنی اتاق‌خواب و هم «چهارم».',
  }),
  mkVocab({
    id: 'v-cozinha',
    pt: 'cozinha',
    faLiteral: 'آشپزخانه',
    pron: 'کو-زینیا',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'cozinhas',
  }),
  mkVocab({
    id: 'v-banheiro',
    pt: 'banheiro',
    faLiteral: 'دستشویی/حمام',
    pron: 'بانیِیرو',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'm',
    plural: 'banheiros',
  }),
  mkVocab({
    id: 'v-sala',
    pt: 'sala',
    faLiteral: 'اتاق نشیمن',
    pron: 'سالا',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'salas',
  }),
  mkVocab({
    id: 'v-porta',
    pt: 'porta',
    faLiteral: 'در',
    pron: 'پورتا',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'portas',
  }),
  mkVocab({
    id: 'v-janela',
    pt: 'janela',
    faLiteral: 'پنجره',
    pron: 'ژانِلا',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'janelas',
  }),
  mkVocab({
    id: 'v-mesa',
    pt: 'mesa',
    faLiteral: 'میز',
    pron: 'مِزا',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'mesas',
  }),
  mkVocab({
    id: 'v-cadeira',
    pt: 'cadeira',
    faLiteral: 'صندلی',
    pron: 'کا-دِیرا',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'cadeiras',
  }),
  mkVocab({
    id: 'v-cama',
    pt: 'cama',
    faLiteral: 'تخت',
    pron: 'کاما',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'camas',
  }),
  mkVocab({
    id: 'v-chave',
    pt: 'chave',
    faLiteral: 'کلید',
    pron: 'شاوی',
    cefr: 'A1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
    plural: 'chaves',
    commonMistakes: ['«ch» در پرتغالی صدای «ش» می‌دهد، نه «چ».'],
  }),

  // ── food ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-comida',
    pt: 'comida',
    faLiteral: 'غذا',
    pron: 'کو-میدا',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'f',
    plural: 'comidas',
  }),
  mkVocab({
    id: 'v-pao',
    pt: 'pão',
    faLiteral: 'نان',
    pron: 'پائو',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    plural: 'pães',
    commonMistakes: ['جمعِ نامنظم: «pães» (پائیس).'],
  }),
  mkVocab({
    id: 'v-arroz',
    pt: 'arroz',
    faLiteral: 'برنج',
    pron: 'آ-هوس',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    commonMistakes: ['«rr» و «r» آغازین در برزیل مثل «ه» تلفظ می‌شود.'],
  }),
  mkVocab({
    id: 'v-feijao',
    pt: 'feijão',
    faLiteral: 'لوبیا',
    pron: 'فِی-ژائو',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    plural: 'feijões',
  }),
  mkVocab({
    id: 'v-carne',
    pt: 'carne',
    faLiteral: 'گوشت',
    pron: 'کارنی',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'f',
    plural: 'carnes',
  }),
  mkVocab({
    id: 'v-frango',
    pt: 'frango',
    faLiteral: 'مرغ (گوشت)',
    pron: 'فرانگو',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    plural: 'frangos',
  }),
  mkVocab({
    id: 'v-peixe',
    pt: 'peixe',
    faLiteral: 'ماهی',
    pron: 'پِی‌شی',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    plural: 'peixes',
  }),
  mkVocab({
    id: 'v-ovo',
    pt: 'ovo',
    faLiteral: 'تخم‌مرغ',
    pron: 'اُوو',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    plural: 'ovos',
  }),
  mkVocab({
    id: 'v-queijo',
    pt: 'queijo',
    faLiteral: 'پنیر',
    pron: 'کِی‌ژو',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    plural: 'queijos',
  }),
  mkVocab({
    id: 'v-fruta',
    pt: 'fruta',
    faLiteral: 'میوه',
    pron: 'فروتا',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'f',
    plural: 'frutas',
  }),
  mkVocab({
    id: 'v-maca',
    pt: 'maçã',
    faLiteral: 'سیب',
    pron: 'ما-سا',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'f',
    plural: 'maçãs',
    commonMistakes: ['«ç» صدای «س» می‌دهد و «ã» خیشومی است.'],
  }),
  mkVocab({
    id: 'v-verdura',
    pt: 'verdura',
    faLiteral: 'سبزی',
    pron: 'وِر-دورا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
    plural: 'verduras',
  }),
  mkVocab({
    id: 'v-acucar',
    pt: 'açúcar',
    faLiteral: 'شکر',
    pron: 'آ-سوکار',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-sal',
    pt: 'sal',
    faLiteral: 'نمک',
    pron: 'سائو',
    cefr: 'A1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
    notes: '«al» پایانی مثل «ائو» تلفظ می‌شود.',
  }),

  // ── drinks ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-agua',
    pt: 'água',
    faLiteral: 'آب',
    pron: 'آگوا',
    cefr: 'A1',
    category: 'drinks',
    pos: 'noun',
    gender: 'f',
    plural: 'águas',
  }),
  mkVocab({
    id: 'v-cafe',
    pt: 'café',
    faLiteral: 'قهوه',
    pron: 'کا-فِ',
    cefr: 'A1',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
    plural: 'cafés',
    notes: '«café» هم قهوه و هم کافه/صبحانه.',
  }),
  mkVocab({
    id: 'v-leite',
    pt: 'leite',
    faLiteral: 'شیر (نوشیدنی)',
    pron: 'لِی‌چی',
    cefr: 'A1',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
    commonMistakes: ['مذکر است: «o leite».'],
  }),
  mkVocab({
    id: 'v-suco',
    pt: 'suco',
    faLiteral: 'آبمیوه',
    pron: 'سوکو',
    cefr: 'A1',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
    plural: 'sucos',
  }),
  mkVocab({
    id: 'v-cerveja',
    pt: 'cerveja',
    faLiteral: 'آبجو',
    pron: 'سِر-وِژا',
    cefr: 'A1',
    category: 'drinks',
    pos: 'noun',
    gender: 'f',
    plural: 'cervejas',
  }),
  mkVocab({
    id: 'v-vinho',
    pt: 'vinho',
    faLiteral: 'شراب',
    pron: 'وینیو',
    cefr: 'A2',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
    plural: 'vinhos',
  }),
  mkVocab({
    id: 'v-cha',
    pt: 'chá',
    faLiteral: 'چای',
    pron: 'شا',
    cefr: 'A1',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
    commonMistakes: ['«ch» صدای «ش» می‌دهد؛ پس «شا» نه «چا».'],
  }),

  // ── shopping ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-loja',
    pt: 'loja',
    faLiteral: 'مغازه',
    pron: 'لوژا',
    cefr: 'A1',
    category: 'shopping',
    pos: 'noun',
    gender: 'f',
    plural: 'lojas',
  }),
  mkVocab({
    id: 'v-mercado',
    pt: 'mercado',
    faLiteral: 'بازار/سوپرمارکت',
    pron: 'مِر-کادو',
    cefr: 'A1',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
    plural: 'mercados',
  }),
  mkVocab({
    id: 'v-feira',
    pt: 'feira',
    faLiteral: 'بازار محلی',
    pron: 'فِیرا',
    cefr: 'A2',
    category: 'shopping',
    pos: 'noun',
    gender: 'f',
    plural: 'feiras',
  }),
  mkVocab({
    id: 'v-preco',
    pt: 'preço',
    faLiteral: 'قیمت',
    pron: 'پرِسو',
    cefr: 'A1',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
    plural: 'preços',
  }),
  mkVocab({
    id: 'v-caro',
    pt: 'caro',
    faLiteral: 'گران',
    pron: 'کارو',
    cefr: 'A1',
    category: 'shopping',
    pos: 'adj',
    notes: 'مؤنث: «cara».',
  }),
  mkVocab({
    id: 'v-barato',
    pt: 'barato',
    faLiteral: 'ارزان',
    pron: 'با-راتو',
    cefr: 'A1',
    category: 'shopping',
    pos: 'adj',
    notes: 'مؤنث: «barata».',
  }),
  mkVocab({
    id: 'v-conta',
    pt: 'conta',
    faLiteral: 'صورتحساب',
    pron: 'کونتا',
    cefr: 'A1',
    category: 'shopping',
    pos: 'noun',
    gender: 'f',
    plural: 'contas',
  }),

  // ── money ──────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-dinheiro',
    pt: 'dinheiro',
    faLiteral: 'پول',
    pron: 'جینیِیرو',
    cefr: 'A1',
    category: 'money',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-real',
    pt: 'real',
    faLiteral: 'رئال (واحد پول برزیل)',
    pron: 'هِ-آو',
    cefr: 'A1',
    category: 'money',
    pos: 'noun',
    gender: 'm',
    plural: 'reais',
    notes: 'جمع: «reais» (هِ-آیس).',
  }),
  mkVocab({
    id: 'v-cartao',
    pt: 'cartão',
    faLiteral: 'کارت (بانکی)',
    pron: 'کار-تائو',
    cefr: 'A1',
    category: 'money',
    pos: 'noun',
    gender: 'm',
    plural: 'cartões',
    commonMistakes: ['جمعِ «ão» اینجا «ões» است: «cartões».'],
  }),
  mkVocab({
    id: 'v-troco',
    pt: 'troco',
    faLiteral: 'باقی پول',
    pron: 'تروکو',
    cefr: 'A2',
    category: 'money',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-banco',
    pt: 'banco',
    faLiteral: 'بانک',
    pron: 'بانکو',
    cefr: 'A1',
    category: 'money',
    pos: 'noun',
    gender: 'm',
    plural: 'bancos',
    notes: '«banco» هم بانک و هم نیمکت.',
  }),
  mkVocab({
    id: 'v-caro-custa',
    pt: 'custar',
    faLiteral: 'قیمت داشتن/هزینه بردن',
    pron: 'کوس-تار',
    cefr: 'A2',
    category: 'money',
    pos: 'verb',
  }),

  // ── transport ──────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-onibus',
    pt: 'ônibus',
    faLiteral: 'اتوبوس',
    pron: 'اُنیبوس',
    cefr: 'A1',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
    notes: 'مفرد و جمعش یکسان است: «o ônibus / os ônibus».',
  }),
  mkVocab({
    id: 'v-carro',
    pt: 'carro',
    faLiteral: 'ماشین',
    pron: 'کاهو',
    cefr: 'A1',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
    plural: 'carros',
    commonMistakes: ['«rr» مثل «ه» تلفظ می‌شود: «کاهو».'],
  }),
  mkVocab({
    id: 'v-metro',
    pt: 'metrô',
    faLiteral: 'مترو',
    pron: 'مِ-ترُ',
    cefr: 'A1',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-trem',
    pt: 'trem',
    faLiteral: 'قطار',
    pron: 'ترِنگ',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
    plural: 'trens',
  }),
  mkVocab({
    id: 'v-aviao',
    pt: 'avião',
    faLiteral: 'هواپیما',
    pron: 'آ-ویائو',
    cefr: 'A1',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
    plural: 'aviões',
  }),
  mkVocab({
    id: 'v-bicicleta',
    pt: 'bicicleta',
    faLiteral: 'دوچرخه',
    pron: 'بی-سی-کلِتا',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
    gender: 'f',
    plural: 'bicicletas',
  }),
  mkVocab({
    id: 'v-taxi',
    pt: 'táxi',
    faLiteral: 'تاکسی',
    pron: 'تاکسی',
    cefr: 'A1',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-passagem',
    pt: 'passagem',
    faLiteral: 'بلیط (سفر)',
    pron: 'پا-ساژِن',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
    gender: 'f',
    plural: 'passagens',
  }),

  // ── directions ─────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-direita',
    pt: 'direita',
    faLiteral: 'راست',
    pron: 'جی-رِی‌تا',
    cefr: 'A1',
    category: 'directions',
    pos: 'noun',
    gender: 'f',
    notes: '«à direita» یعنی «به راست/سمت راست».',
  }),
  mkVocab({
    id: 'v-esquerda',
    pt: 'esquerda',
    faLiteral: 'چپ',
    pron: 'اِس-کِردا',
    cefr: 'A1',
    category: 'directions',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'v-reto',
    pt: 'reto',
    faLiteral: 'مستقیم',
    pron: 'هِتو',
    cefr: 'A1',
    category: 'directions',
    pos: 'adv',
    notes: '«siga reto» یعنی «مستقیم برو».',
  }),
  mkVocab({
    id: 'v-perto',
    pt: 'perto',
    faLiteral: 'نزدیک',
    pron: 'پِرتو',
    cefr: 'A1',
    category: 'directions',
    pos: 'adv',
    notes: '«perto de» یعنی «نزدیکِ».',
  }),
  mkVocab({
    id: 'v-longe',
    pt: 'longe',
    faLiteral: 'دور',
    pron: 'لونژی',
    cefr: 'A1',
    category: 'directions',
    pos: 'adv',
  }),
  mkVocab({
    id: 'v-aqui',
    pt: 'aqui',
    faLiteral: 'اینجا',
    pron: 'آ-کی',
    cefr: 'A1',
    category: 'directions',
    pos: 'adv',
  }),
  mkVocab({
    id: 'v-ali',
    pt: 'ali',
    faLiteral: 'آنجا',
    pron: 'آ-لی',
    cefr: 'A1',
    category: 'directions',
    pos: 'adv',
  }),

  // ── colors ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-vermelho',
    pt: 'vermelho',
    faLiteral: 'قرمز',
    pron: 'وِر-مِلیو',
    cefr: 'A1',
    category: 'colors',
    pos: 'adj',
    notes: 'مؤنث: «vermelha».',
  }),
  mkVocab({
    id: 'v-azul',
    pt: 'azul',
    faLiteral: 'آبی',
    pron: 'آ-زوو',
    cefr: 'A1',
    category: 'colors',
    pos: 'adj',
    plural: 'azuis',
    notes: 'برای مذکر و مؤنث یکسان است.',
  }),
  mkVocab({
    id: 'v-verde',
    pt: 'verde',
    faLiteral: 'سبز',
    pron: 'وِردی',
    cefr: 'A1',
    category: 'colors',
    pos: 'adj',
    notes: 'برای مذکر و مؤنث یکسان.',
  }),
  mkVocab({
    id: 'v-amarelo',
    pt: 'amarelo',
    faLiteral: 'زرد',
    pron: 'آ-ما-رِلو',
    cefr: 'A1',
    category: 'colors',
    pos: 'adj',
    notes: 'مؤنث: «amarela».',
  }),
  mkVocab({
    id: 'v-preto',
    pt: 'preto',
    faLiteral: 'سیاه',
    pron: 'پرِتو',
    cefr: 'A1',
    category: 'colors',
    pos: 'adj',
    notes: 'مؤنث: «preta».',
  }),
  mkVocab({
    id: 'v-branco',
    pt: 'branco',
    faLiteral: 'سفید',
    pron: 'برانکو',
    cefr: 'A1',
    category: 'colors',
    pos: 'adj',
    notes: 'مؤنث: «branca».',
  }),

  // ── body ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-cabeca',
    pt: 'cabeça',
    faLiteral: 'سر',
    pron: 'کا-بِسا',
    cefr: 'A1',
    category: 'body',
    pos: 'noun',
    gender: 'f',
    plural: 'cabeças',
  }),
  mkVocab({
    id: 'v-mao',
    pt: 'mão',
    faLiteral: 'دست',
    pron: 'مائو',
    cefr: 'A1',
    category: 'body',
    pos: 'noun',
    gender: 'f',
    plural: 'mãos',
    commonMistakes: ['با اینکه به «ão» ختم می‌شود، مؤنث است: «a mão».'],
  }),
  mkVocab({
    id: 'v-pe',
    pt: 'pé',
    faLiteral: 'پا (کف پا)',
    pron: 'پِ',
    cefr: 'A1',
    category: 'body',
    pos: 'noun',
    gender: 'm',
    plural: 'pés',
  }),
  mkVocab({
    id: 'v-olho',
    pt: 'olho',
    faLiteral: 'چشم',
    pron: 'اُلیو',
    cefr: 'A1',
    category: 'body',
    pos: 'noun',
    gender: 'm',
    plural: 'olhos',
  }),
  mkVocab({
    id: 'v-boca',
    pt: 'boca',
    faLiteral: 'دهان',
    pron: 'بوکا',
    cefr: 'A1',
    category: 'body',
    pos: 'noun',
    gender: 'f',
    plural: 'bocas',
  }),
  mkVocab({
    id: 'v-perna',
    pt: 'perna',
    faLiteral: 'پا (ساق)',
    pron: 'پِرنا',
    cefr: 'A1',
    category: 'body',
    pos: 'noun',
    gender: 'f',
    plural: 'pernas',
  }),
  mkVocab({
    id: 'v-braco',
    pt: 'braço',
    faLiteral: 'بازو',
    pron: 'براسو',
    cefr: 'A1',
    category: 'body',
    pos: 'noun',
    gender: 'm',
    plural: 'braços',
  }),

  // ── health ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-medico',
    pt: 'médico',
    faLiteral: 'پزشک',
    pron: 'مِ-جیکو',
    cefr: 'A1',
    category: 'health',
    pos: 'noun',
    gender: 'm',
    plural: 'médicos',
    notes: 'زن: «médica».',
  }),
  mkVocab({
    id: 'v-hospital',
    pt: 'hospital',
    faLiteral: 'بیمارستان',
    pron: 'اُس-پی-تاو',
    cefr: 'A1',
    category: 'health',
    pos: 'noun',
    gender: 'm',
    plural: 'hospitais',
    notes: '«h» تلفظ نمی‌شود.',
  }),
  mkVocab({
    id: 'v-farmacia',
    pt: 'farmácia',
    faLiteral: 'داروخانه',
    pron: 'فار-ماسیا',
    cefr: 'A1',
    category: 'health',
    pos: 'noun',
    gender: 'f',
    plural: 'farmácias',
  }),
  mkVocab({
    id: 'v-remedio',
    pt: 'remédio',
    faLiteral: 'دارو',
    pron: 'هِ-مِجیو',
    cefr: 'A2',
    category: 'health',
    pos: 'noun',
    gender: 'm',
    plural: 'remédios',
  }),
  mkVocab({
    id: 'v-dor',
    pt: 'dor',
    faLiteral: 'درد',
    pron: 'دُر',
    cefr: 'A2',
    category: 'health',
    pos: 'noun',
    gender: 'f',
    plural: 'dores',
    commonMistakes: ['مؤنث است: «a dor».'],
  }),
  mkVocab({
    id: 'v-doente',
    pt: 'doente',
    faLiteral: 'بیمار',
    pron: 'دو-اِن‌چی',
    cefr: 'A1',
    category: 'health',
    pos: 'adj',
    notes: 'برای مذکر و مؤنث یکسان.',
  }),

  // ── clothing ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-roupa',
    pt: 'roupa',
    faLiteral: 'لباس',
    pron: 'هوپا',
    cefr: 'A1',
    category: 'clothing',
    pos: 'noun',
    gender: 'f',
    plural: 'roupas',
  }),
  mkVocab({
    id: 'v-camisa',
    pt: 'camisa',
    faLiteral: 'پیراهن',
    pron: 'کا-میزا',
    cefr: 'A1',
    category: 'clothing',
    pos: 'noun',
    gender: 'f',
    plural: 'camisas',
  }),
  mkVocab({
    id: 'v-calca',
    pt: 'calça',
    faLiteral: 'شلوار',
    pron: 'کاوسا',
    cefr: 'A1',
    category: 'clothing',
    pos: 'noun',
    gender: 'f',
    plural: 'calças',
    notes: 'در پرتغالی معمولاً مفرد به‌کار می‌رود.',
  }),
  mkVocab({
    id: 'v-sapato',
    pt: 'sapato',
    faLiteral: 'کفش',
    pron: 'سا-پاتو',
    cefr: 'A1',
    category: 'clothing',
    pos: 'noun',
    gender: 'm',
    plural: 'sapatos',
  }),
  mkVocab({
    id: 'v-vestido',
    pt: 'vestido',
    faLiteral: 'پیراهن (زنانه)/لباس',
    pron: 'وِس-چیدو',
    cefr: 'A2',
    category: 'clothing',
    pos: 'noun',
    gender: 'm',
    plural: 'vestidos',
  }),
  mkVocab({
    id: 'v-casaco',
    pt: 'casaco',
    faLiteral: 'کت/پالتو',
    pron: 'کا-زاکو',
    cefr: 'A2',
    category: 'clothing',
    pos: 'noun',
    gender: 'm',
    plural: 'casacos',
  }),

  // ── weather ────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-tempo',
    pt: 'tempo',
    faLiteral: 'هوا/زمان',
    pron: 'تِمپو',
    cefr: 'A1',
    category: 'weather',
    pos: 'noun',
    gender: 'm',
    notes: '«tempo» هم «هوا» و هم «زمان» است.',
  }),
  mkVocab({
    id: 'v-sol',
    pt: 'sol',
    faLiteral: 'خورشید/آفتاب',
    pron: 'سُو',
    cefr: 'A1',
    category: 'weather',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'v-chuva',
    pt: 'chuva',
    faLiteral: 'باران',
    pron: 'شووا',
    cefr: 'A1',
    category: 'weather',
    pos: 'noun',
    gender: 'f',
    plural: 'chuvas',
  }),
  mkVocab({
    id: 'v-calor',
    pt: 'calor',
    faLiteral: 'گرما',
    pron: 'کا-لُر',
    cefr: 'A1',
    category: 'weather',
    pos: 'noun',
    gender: 'm',
    notes: '«está calor» یعنی «هوا گرم است».',
  }),
  mkVocab({
    id: 'v-frio',
    pt: 'frio',
    faLiteral: 'سرما/سرد',
    pron: 'فریو',
    cefr: 'A1',
    category: 'weather',
    pos: 'noun',
    gender: 'm',
    notes: 'هم اسم (سرما) و هم صفت (سرد).',
  }),
  mkVocab({
    id: 'v-vento',
    pt: 'vento',
    faLiteral: 'باد',
    pron: 'وِنتو',
    cefr: 'A2',
    category: 'weather',
    pos: 'noun',
    gender: 'm',
    plural: 'ventos',
  }),

  // ── work ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-trabalho',
    pt: 'trabalho',
    faLiteral: 'کار/شغل',
    pron: 'تراباليو',
    cefr: 'A1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
    plural: 'trabalhos',
  }),
  mkVocab({
    id: 'v-emprego',
    pt: 'emprego',
    faLiteral: 'استخدام/شغل',
    pron: 'اِم-پرِگو',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'm',
    plural: 'empregos',
  }),
  mkVocab({
    id: 'v-chefe',
    pt: 'chefe',
    faLiteral: 'رئیس',
    pron: 'شِفی',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'mf',
    notes: 'برای مرد و زن یکسان؛ فقط حرف تعریف عوض می‌شود.',
  }),
  mkVocab({
    id: 'v-escritorio',
    pt: 'escritório',
    faLiteral: 'دفتر (کار)',
    pron: 'اِس-کری-توریو',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'm',
    plural: 'escritórios',
  }),
  mkVocab({
    id: 'v-reuniao',
    pt: 'reunião',
    faLiteral: 'جلسه',
    pron: 'هِ-او-نیائو',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'f',
    plural: 'reuniões',
  }),
  mkVocab({
    id: 'v-professor',
    pt: 'professor',
    faLiteral: 'معلم',
    pron: 'پرو-فِ-سُر',
    cefr: 'A1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
    plural: 'professores',
    notes: 'زن: «professora».',
  }),

  // ── verbs-basic ────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-ser',
    pt: 'ser',
    faLiteral: 'بودن (دائمی)',
    pron: 'سِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
    commonMistakes: [
      '«ser» برای ویژگی‌های دائمی و «estar» برای حالت‌های گذرا؛ هر دو یعنی «بودن».',
    ],
  }),
  mkVocab({
    id: 'v-estar',
    pt: 'estar',
    faLiteral: 'بودن (موقت)',
    pron: 'اِس-تار',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
    notes: 'برای حالت‌ها و مکان‌های موقت.',
  }),
  mkVocab({
    id: 'v-ter',
    pt: 'ter',
    faLiteral: 'داشتن',
    pron: 'تِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
    notes: 'برای سن هم به‌کار می‌رود: «tenho 30 anos».',
  }),
  mkVocab({
    id: 'v-ir',
    pt: 'ir',
    faLiteral: 'رفتن',
    pron: 'ایر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-fazer',
    pt: 'fazer',
    faLiteral: 'انجام دادن/ساختن',
    pron: 'فا-زِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-querer',
    pt: 'querer',
    faLiteral: 'خواستن',
    pron: 'کِ-رِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-poder',
    pt: 'poder',
    faLiteral: 'توانستن',
    pron: 'پو-دِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-falar',
    pt: 'falar',
    faLiteral: 'حرف زدن',
    pron: 'فا-لار',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-comer',
    pt: 'comer',
    faLiteral: 'خوردن',
    pron: 'کو-مِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-beber',
    pt: 'beber',
    faLiteral: 'نوشیدن',
    pron: 'بِ-بِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-comprar',
    pt: 'comprar',
    faLiteral: 'خریدن',
    pron: 'کوم-پرار',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-morar',
    pt: 'morar',
    faLiteral: 'زندگی/سکونت کردن',
    pron: 'مو-رار',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
    notes: '«moro em São Paulo» یعنی «در سائوپائولو زندگی می‌کنم».',
  }),
  mkVocab({
    id: 'v-trabalhar',
    pt: 'trabalhar',
    faLiteral: 'کار کردن',
    pron: 'تراباليار',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'v-gostar',
    pt: 'gostar',
    faLiteral: 'دوست داشتن',
    pron: 'گوس-تار',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
    commonMistakes: ['همیشه با حرف اضافهٔ «de» می‌آید: «gosto de café».'],
  }),
  mkVocab({
    id: 'v-saber',
    pt: 'saber',
    faLiteral: 'دانستن',
    pron: 'سا-بِر',
    cefr: 'A1',
    category: 'verbs-basic',
    pos: 'verb',
  }),

  // ── adjectives-basic ───────────────────────────────────────────────────
  mkVocab({
    id: 'v-bom',
    pt: 'bom',
    faLiteral: 'خوب',
    pron: 'بُنگ',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'مؤنث: «boa».',
  }),
  mkVocab({
    id: 'v-mau',
    pt: 'mau',
    faLiteral: 'بد',
    pron: 'مائو',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'مؤنث: «má». نباید با قید «mal» اشتباه شود.',
  }),
  mkVocab({
    id: 'v-grande',
    pt: 'grande',
    faLiteral: 'بزرگ',
    pron: 'گراندی',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'برای مذکر و مؤنث یکسان.',
  }),
  mkVocab({
    id: 'v-pequeno',
    pt: 'pequeno',
    faLiteral: 'کوچک',
    pron: 'پِ-کِنو',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'مؤنث: «pequena».',
  }),
  mkVocab({
    id: 'v-novo',
    pt: 'novo',
    faLiteral: 'جدید/جوان',
    pron: 'نُوو',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'مؤنث: «nova».',
  }),
  mkVocab({
    id: 'v-velho',
    pt: 'velho',
    faLiteral: 'قدیمی/پیر',
    pron: 'وِليو',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'مؤنث: «velha».',
  }),
  mkVocab({
    id: 'v-bonito',
    pt: 'bonito',
    faLiteral: 'زیبا/قشنگ',
    pron: 'بو-نیتو',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'مؤنث: «bonita».',
  }),
  mkVocab({
    id: 'v-feio',
    pt: 'feio',
    faLiteral: 'زشت',
    pron: 'فِیو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
    notes: 'مؤنث: «feia».',
  }),
  mkVocab({
    id: 'v-facil',
    pt: 'fácil',
    faLiteral: 'آسان',
    pron: 'فاسیو',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    plural: 'fáceis',
  }),
  mkVocab({
    id: 'v-dificil',
    pt: 'difícil',
    faLiteral: 'سخت/دشوار',
    pron: 'جی-فیسیو',
    cefr: 'A1',
    category: 'adjectives-basic',
    pos: 'adj',
    plural: 'difíceis',
  }),

  // ── pronouns ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-eu',
    pt: 'eu',
    faLiteral: 'من',
    pron: 'اِئو',
    cefr: 'A1',
    category: 'pronouns',
    pos: 'pron',
  }),
  mkVocab({
    id: 'v-voce',
    pt: 'você',
    faLiteral: 'تو/شما',
    pron: 'وو-سِ',
    cefr: 'A1',
    category: 'pronouns',
    pos: 'pron',
    notes: 'در برزیل رایج‌ترین شکل خطاب است؛ فعل مثل سوم‌شخص صرف می‌شود.',
  }),
  mkVocab({
    id: 'v-ele',
    pt: 'ele',
    faLiteral: 'او (مرد)',
    pron: 'اِلی',
    cefr: 'A1',
    category: 'pronouns',
    pos: 'pron',
  }),
  mkVocab({
    id: 'v-ela',
    pt: 'ela',
    faLiteral: 'او (زن)',
    pron: 'اِلا',
    cefr: 'A1',
    category: 'pronouns',
    pos: 'pron',
  }),
  mkVocab({
    id: 'v-nos',
    pt: 'nós',
    faLiteral: 'ما',
    pron: 'نُس',
    cefr: 'A1',
    category: 'pronouns',
    pos: 'pron',
    notes: 'در گفتار محاوره اغلب «a gente» گفته می‌شود.',
  }),
  mkVocab({
    id: 'v-eles',
    pt: 'eles',
    faLiteral: 'آن‌ها (مذکر/مختلط)',
    pron: 'اِلیس',
    cefr: 'A1',
    category: 'pronouns',
    pos: 'pron',
    notes: 'گروه مؤنث خالص: «elas».',
  }),
  mkVocab({
    id: 'v-meu',
    pt: 'meu',
    faLiteral: 'مالِ من/ـم',
    pron: 'مِئو',
    cefr: 'A1',
    category: 'pronouns',
    pos: 'pron',
    notes: 'مؤنث: «minha».',
  }),

  // ── prepositions ───────────────────────────────────────────────────────
  mkVocab({
    id: 'v-de',
    pt: 'de',
    faLiteral: 'از/مالِ',
    pron: 'جی',
    cefr: 'A1',
    category: 'prepositions',
    pos: 'prep',
    notes: 'با حرف تعریف ترکیب می‌شود: de + o = do، de + a = da.',
  }),
  mkVocab({
    id: 'v-em',
    pt: 'em',
    faLiteral: 'در/توی',
    pron: 'اِنگ',
    cefr: 'A1',
    category: 'prepositions',
    pos: 'prep',
    notes: 'em + o = no، em + a = na.',
  }),
  mkVocab({
    id: 'v-para',
    pt: 'para',
    faLiteral: 'برای/به‌سوی',
    pron: 'پارا',
    cefr: 'A1',
    category: 'prepositions',
    pos: 'prep',
    notes: 'در گفتار اغلب «pra» گفته می‌شود.',
  }),
  mkVocab({
    id: 'v-com',
    pt: 'com',
    faLiteral: 'با',
    pron: 'کُنگ',
    cefr: 'A1',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'v-sem',
    pt: 'sem',
    faLiteral: 'بدونِ',
    pron: 'سِنگ',
    cefr: 'A1',
    category: 'prepositions',
    pos: 'prep',
    commonMistakes: [
      '«sem» (بدون) با «cem» (صد) هم‌آوا است؛ از بافت تشخیص دهید.',
    ],
  }),
  mkVocab({
    id: 'v-sobre',
    pt: 'sobre',
    faLiteral: 'دربارهٔ/روی',
    pron: 'سوبری',
    cefr: 'A2',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'v-entre',
    pt: 'entre',
    faLiteral: 'بینِ',
    pron: 'اِنتری',
    cefr: 'A2',
    category: 'prepositions',
    pos: 'prep',
  }),

  // ── question-words ─────────────────────────────────────────────────────
  mkVocab({
    id: 'v-que',
    pt: 'que',
    faLiteral: 'چه/که',
    pron: 'کی',
    cefr: 'A1',
    category: 'question-words',
    pos: 'pron',
    notes: 'در پرسش اغلب «o que» گفته می‌شود: «o que é isso?».',
  }),
  mkVocab({
    id: 'v-quem',
    pt: 'quem',
    faLiteral: 'چه‌کسی',
    pron: 'کِنگ',
    cefr: 'A1',
    category: 'question-words',
    pos: 'pron',
  }),
  mkVocab({
    id: 'v-onde',
    pt: 'onde',
    faLiteral: 'کجا',
    pron: 'اُندی',
    cefr: 'A1',
    category: 'question-words',
    pos: 'adv',
  }),
  mkVocab({
    id: 'v-quando',
    pt: 'quando',
    faLiteral: 'کِی',
    pron: 'کواندو',
    cefr: 'A1',
    category: 'question-words',
    pos: 'adv',
  }),
  mkVocab({
    id: 'v-como',
    pt: 'como',
    faLiteral: 'چطور/چگونه',
    pron: 'کومو',
    cefr: 'A1',
    category: 'question-words',
    pos: 'adv',
    notes: '«como você está?» یعنی «حالت چطوره؟».',
  }),
  mkVocab({
    id: 'v-porque',
    pt: 'por que',
    faLiteral: 'چرا',
    pron: 'پور کی',
    cefr: 'A1',
    category: 'question-words',
    pos: 'adv',
    commonMistakes: [
      'در پرسش جدا «por que» و در پاسخ سرِهم «porque» (چون) نوشته می‌شود.',
    ],
  }),
  mkVocab({
    id: 'v-quanto',
    pt: 'quanto',
    faLiteral: 'چقدر/چندتا',
    pron: 'کوانتو',
    cefr: 'A1',
    category: 'question-words',
    pos: 'pron',
    notes: '«quanto custa?» یعنی «چقدر می‌شود؟».',
  }),

  // ── city ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-cidade',
    pt: 'cidade',
    faLiteral: 'شهر',
    pron: 'سی-داجی',
    cefr: 'A1',
    category: 'city',
    pos: 'noun',
    gender: 'f',
    plural: 'cidades',
  }),
  mkVocab({
    id: 'v-rua',
    pt: 'rua',
    faLiteral: 'خیابان',
    pron: 'هوآ',
    cefr: 'A1',
    category: 'city',
    pos: 'noun',
    gender: 'f',
    plural: 'ruas',
    commonMistakes: ['«r» آغازین مثل «ه» تلفظ می‌شود: «هوآ».'],
  }),
  mkVocab({
    id: 'v-praca',
    pt: 'praça',
    faLiteral: 'میدان',
    pron: 'پراسا',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
    plural: 'praças',
  }),
  mkVocab({
    id: 'v-escola',
    pt: 'escola',
    faLiteral: 'مدرسه',
    pron: 'اِس-کولا',
    cefr: 'A1',
    category: 'city',
    pos: 'noun',
    gender: 'f',
    plural: 'escolas',
  }),
  mkVocab({
    id: 'v-restaurante',
    pt: 'restaurante',
    faLiteral: 'رستوران',
    pron: 'هِس-تاو-رانچی',
    cefr: 'A1',
    category: 'city',
    pos: 'noun',
    gender: 'm',
    plural: 'restaurantes',
  }),
  mkVocab({
    id: 'v-igreja',
    pt: 'igreja',
    faLiteral: 'کلیسا',
    pron: 'ای-گرِژا',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
    plural: 'igrejas',
  }),
  mkVocab({
    id: 'v-hotel',
    pt: 'hotel',
    faLiteral: 'هتل',
    pron: 'اُ-تِو',
    cefr: 'A1',
    category: 'city',
    pos: 'noun',
    gender: 'm',
    plural: 'hotéis',
  }),

  // ── emotions ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'v-feliz',
    pt: 'feliz',
    faLiteral: 'خوشحال',
    pron: 'فِ-لیس',
    cefr: 'A1',
    category: 'emotions',
    pos: 'adj',
    plural: 'felizes',
    notes: 'برای مذکر و مؤنث یکسان.',
  }),
  mkVocab({
    id: 'v-triste',
    pt: 'triste',
    faLiteral: 'غمگین',
    pron: 'تریس-چی',
    cefr: 'A1',
    category: 'emotions',
    pos: 'adj',
    notes: 'برای مذکر و مؤنث یکسان.',
  }),
  mkVocab({
    id: 'v-cansado',
    pt: 'cansado',
    faLiteral: 'خسته',
    pron: 'کان-سادو',
    cefr: 'A1',
    category: 'emotions',
    pos: 'adj',
    notes: 'مؤنث: «cansada». معمولاً با «estar».',
  }),
  mkVocab({
    id: 'v-com-medo',
    pt: 'com medo',
    faLiteral: 'ترسیده/ترسان',
    pron: 'کُن مِدو',
    cefr: 'A2',
    category: 'emotions',
    pos: 'phrase',
    notes: '«estou com medo» یعنی «می‌ترسم».',
  }),
  mkVocab({
    id: 'v-com-raiva',
    pt: 'com raiva',
    faLiteral: 'عصبانی',
    pron: 'کُن هایوا',
    cefr: 'A2',
    category: 'emotions',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'v-nervoso',
    pt: 'nervoso',
    faLiteral: 'مضطرب/عصبی',
    pron: 'نِر-ووزو',
    cefr: 'A2',
    category: 'emotions',
    pos: 'adj',
    notes: 'مؤنث: «nervosa».',
  }),
  mkVocab({
    id: 'v-amor',
    pt: 'amor',
    faLiteral: 'عشق',
    pron: 'آ-مُر',
    cefr: 'A1',
    category: 'emotions',
    pos: 'noun',
    gender: 'm',
    plural: 'amores',
  }),
];
