/**
 * Extended vocabulary, wave 2 — deepens each category further and adds the
 * upper levels (B2, C1), with a strong focus on verbs, adjectives and the
 * everyday + civic words a newcomer to Brazil actually needs. Merged in
 * ./index.ts alongside vocab.ts and vocabExtra.ts (duplicates are dropped).
 */
import { mkVocab } from './helpers';
import type { Vocab } from '@/domain/content/schema';

export const vocabExtra2: Vocab[] = [
  // ── verbs-basic (a big, high-value batch) ────────────────────────────────
  mkVocab({
    id: 'vy-comprar',
    pt: 'comprar',
    faLiteral: 'خریدن',
    pron: 'کُمپرار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-vender',
    pt: 'vender',
    faLiteral: 'فروختن',
    pron: 'وِندِر',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-pagar',
    pt: 'pagar',
    faLiteral: 'پرداختن',
    pron: 'پاگار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-abrir',
    pt: 'abrir',
    faLiteral: 'باز کردن',
    pron: 'آبریر',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-fechar',
    pt: 'fechar',
    faLiteral: 'بستن',
    pron: 'فِشار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-chegar',
    pt: 'chegar',
    faLiteral: 'رسیدن',
    pron: 'شِگار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-sair',
    pt: 'sair',
    faLiteral: 'بیرون رفتن',
    pron: 'سایر',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-entrar',
    pt: 'entrar',
    faLiteral: 'وارد شدن',
    pron: 'اِنترار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-esperar',
    pt: 'esperar',
    faLiteral: 'منتظر ماندن/امید داشتن',
    pron: 'اِسپِرار',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-perguntar',
    pt: 'perguntar',
    faLiteral: 'پرسیدن',
    pron: 'پِرگونتار',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-responder',
    pt: 'responder',
    faLiteral: 'پاسخ دادن',
    pron: 'هِسپوندِر',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-mostrar',
    pt: 'mostrar',
    faLiteral: 'نشان دادن',
    pron: 'موسترار',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-encontrar',
    pt: 'encontrar',
    faLiteral: 'پیدا کردن/ملاقات کردن',
    pron: 'اِنکُنترار',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-explicar',
    pt: 'explicar',
    faLiteral: 'توضیح دادن',
    pron: 'اِسپلیکار',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-resolver',
    pt: 'resolver',
    faLiteral: 'حل کردن',
    pron: 'هِزولوِر',
    cefr: 'B2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-conseguir2',
    pt: 'permitir',
    faLiteral: 'اجازه دادن',
    pron: 'پِرمیتیر',
    cefr: 'B2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-garantir',
    pt: 'garantir',
    faLiteral: 'تضمین کردن',
    pron: 'گارانتیر',
    cefr: 'B2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-pertencer',
    pt: 'pertencer',
    faLiteral: 'تعلق داشتن',
    pron: 'پِرتِنسِر',
    cefr: 'C1',
    category: 'verbs-basic',
    pos: 'verb',
  }),

  // ── adjectives-basic ─────────────────────────────────────────────────────
  mkVocab({
    id: 'vy-bonito',
    pt: 'bonito',
    faLiteral: 'زیبا/خوشگل',
    pron: 'بونیتو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-feio',
    pt: 'feio',
    faLiteral: 'زشت',
    pron: 'فِیو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-quente',
    pt: 'quente',
    faLiteral: 'گرم/داغ',
    pron: 'کِنتی',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-frio-adj',
    pt: 'frio',
    faLiteral: 'سرد',
    pron: 'فریو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-limpo',
    pt: 'limpo',
    faLiteral: 'تمیز',
    pron: 'لیمپو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-sujo',
    pt: 'sujo',
    faLiteral: 'کثیف',
    pron: 'سوژو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-rapido',
    pt: 'rápido',
    faLiteral: 'سریع',
    pron: 'هاپیدو',
    cefr: 'B1',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-lento',
    pt: 'lento',
    faLiteral: 'کند/آهسته',
    pron: 'لِنتو',
    cefr: 'B1',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-forte',
    pt: 'forte',
    faLiteral: 'قوی',
    pron: 'فُرتی',
    cefr: 'B1',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-fraco',
    pt: 'fraco',
    faLiteral: 'ضعیف',
    pron: 'فراکو',
    cefr: 'B1',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-gratuito',
    pt: 'gratuito',
    faLiteral: 'رایگان',
    pron: 'گراتویتو',
    cefr: 'B1',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-obrigatorio',
    pt: 'obrigatório',
    faLiteral: 'اجباری',
    pron: 'اوبریگاتوریو',
    cefr: 'B2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-disponivel',
    pt: 'disponível',
    faLiteral: 'در دسترس/موجود',
    pron: 'جیسپونیوِل',
    cefr: 'B2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),

  // ── food (more everyday items) ───────────────────────────────────────────
  mkVocab({
    id: 'vy-frango',
    pt: 'frango',
    faLiteral: 'مرغ (گوشت)',
    pron: 'فرانگو',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-batata',
    pt: 'batata',
    faLiteral: 'سیب‌زمینی',
    pron: 'باتاتا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-tomate',
    pt: 'tomate',
    faLiteral: 'گوجه‌فرنگی',
    pron: 'توماتی',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-cebola',
    pt: 'cebola',
    faLiteral: 'پیاز',
    pron: 'سِبولا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-alho',
    pt: 'alho',
    faLiteral: 'سیر',
    pron: 'آلیو',
    cefr: 'B1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-banana',
    pt: 'banana',
    faLiteral: 'موز',
    pron: 'بانانا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-laranja-fruit',
    pt: 'laranja',
    faLiteral: 'پرتقال',
    pron: 'لارانژا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),

  // ── house ────────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vy-chave2',
    pt: 'chave',
    faLiteral: 'کلید',
    pron: 'شاوی',
    cefr: 'A2',
    category: 'house',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-luz',
    pt: 'luz',
    faLiteral: 'چراغ/برق',
    pron: 'لوز',
    cefr: 'A2',
    category: 'house',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-agua-casa',
    pt: 'torneira',
    faLiteral: 'شیر آب',
    pron: 'تورنِیرا',
    cefr: 'B1',
    category: 'house',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-lixo',
    pt: 'lixo',
    faLiteral: 'زباله',
    pron: 'لیشو',
    cefr: 'B1',
    category: 'house',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-condominio',
    pt: 'condomínio',
    faLiteral: 'شارژ/مجتمع مسکونی',
    pron: 'کُندومینیو',
    cefr: 'B2',
    category: 'house',
    pos: 'noun',
    gender: 'm',
  }),

  // ── work & civic (higher levels, newcomer-critical) ──────────────────────
  mkVocab({
    id: 'vy-emprego2',
    pt: 'desempregado',
    faLiteral: 'بیکار',
    pron: 'جِزِمپرِگادو',
    cefr: 'B1',
    category: 'work',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-horario',
    pt: 'horário',
    faLiteral: 'ساعت کاری/برنامهٔ زمانی',
    pron: 'اوراریو',
    cefr: 'B1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-ferias',
    pt: 'férias',
    faLiteral: 'مرخصی/تعطیلات',
    pron: 'فِریاس',
    cefr: 'B1',
    category: 'work',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-sindicato',
    pt: 'sindicato',
    faLiteral: 'اتحادیهٔ کارگری',
    pron: 'سیندیکاتو',
    cefr: 'C1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),

  // ── city & civic (citizenship-relevant) ─────────────────────────────────
  mkVocab({
    id: 'vy-hospital',
    pt: 'hospital',
    faLiteral: 'بیمارستان',
    pron: 'اوسپیتال',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-escola-city',
    pt: 'escola',
    faLiteral: 'مدرسه',
    pron: 'اِسکولا',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-cidadania',
    pt: 'cidadania',
    faLiteral: 'شهروندی',
    pron: 'سیدادانیا',
    cefr: 'B2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-naturalizacao',
    pt: 'naturalização',
    faLiteral: 'تابعیت (ناتورالیزاسیون)',
    pron: 'ناتورالیزاسائو',
    cefr: 'C1',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-residencia',
    pt: 'residência',
    faLiteral: 'اقامت',
    pron: 'هِزیدِنسیا',
    cefr: 'B2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),

  // ── emotions ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vy-com-medo',
    pt: 'com medo',
    faLiteral: 'ترسیده',
    pron: 'کُن مِدو',
    cefr: 'A2',
    category: 'emotions',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'vy-animado',
    pt: 'animado',
    faLiteral: 'سرحال/هیجان‌زده',
    pron: 'آنیمادو',
    cefr: 'B1',
    category: 'emotions',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vy-com-raiva',
    pt: 'com raiva',
    faLiteral: 'عصبانی',
    pron: 'کُن هایوا',
    cefr: 'B1',
    category: 'emotions',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'vy-esperanca',
    pt: 'esperança',
    faLiteral: 'امید',
    pron: 'اِسپِرانسا',
    cefr: 'B2',
    category: 'emotions',
    pos: 'noun',
    gender: 'f',
  }),

  // ── health ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vy-tosse',
    pt: 'tosse',
    faLiteral: 'سرفه',
    pron: 'تُسی',
    cefr: 'A2',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-exame',
    pt: 'exame',
    faLiteral: 'آزمایش/معاینه',
    pron: 'اِزامی',
    cefr: 'B1',
    category: 'health',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-emergencia',
    pt: 'emergência',
    faLiteral: 'اورژانس',
    pron: 'اِمِرژِنسیا',
    cefr: 'B2',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),

  // ── directions / transport extras ────────────────────────────────────────
  mkVocab({
    id: 'vy-mapa',
    pt: 'mapa',
    faLiteral: 'نقشه',
    pron: 'ماپا',
    cefr: 'A2',
    category: 'directions',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-semaforo',
    pt: 'semáforo',
    faLiteral: 'چراغ راهنمایی',
    pron: 'سِمافورو',
    cefr: 'B1',
    category: 'directions',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vy-motorista',
    pt: 'motorista',
    faLiteral: 'راننده',
    pron: 'موتوریستا',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
  }),

  // ── shopping / money ─────────────────────────────────────────────────────
  mkVocab({
    id: 'vy-fatura',
    pt: 'fatura',
    faLiteral: 'صورت‌حساب',
    pron: 'فاتورا',
    cefr: 'B2',
    category: 'money',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-parcelar',
    pt: 'parcelar',
    faLiteral: 'قسطی کردن',
    pron: 'پارسِلار',
    cefr: 'B2',
    category: 'shopping',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vy-promocao',
    pt: 'promoção',
    faLiteral: 'حراج/تخفیف ویژه',
    pron: 'پروموسائو',
    cefr: 'B1',
    category: 'shopping',
    pos: 'noun',
    gender: 'f',
  }),

  // ── weather ──────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vy-neve',
    pt: 'neve',
    faLiteral: 'برف',
    pron: 'نِوی',
    cefr: 'B1',
    category: 'weather',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vy-nevoa',
    pt: 'neblina',
    faLiteral: 'مه',
    pron: 'نِبلینا',
    cefr: 'B2',
    category: 'weather',
    pos: 'noun',
    gender: 'f',
  }),
];
