/**
 * Extended vocabulary, wave 3 — tops up the thinnest categories (work,
 * directions, drinks, colors, question-words, prepositions, city, shopping)
 * so no category feels sparse. Merged in ./index.ts (duplicates dropped).
 */
import { mkVocab } from './helpers';
import type { Vocab } from '@/domain/content/schema';

export const vocabExtra3: Vocab[] = [
  // ── work ─────────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-professor',
    pt: 'professor',
    faLiteral: 'معلم',
    pron: 'پروفِسور',
    cefr: 'A1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-medico',
    pt: 'médico',
    faLiteral: 'پزشک',
    pron: 'مِجیکو',
    cefr: 'A1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-cozinheiro',
    pt: 'cozinheiro',
    faLiteral: 'آشپز',
    pron: 'کوزینیِیرو',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-pedreiro',
    pt: 'pedreiro',
    faLiteral: 'بنّا',
    pron: 'پِدرِیرو',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-vendedor',
    pt: 'vendedor',
    faLiteral: 'فروشنده',
    pron: 'وِندِدور',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-faxineira',
    pt: 'faxineira',
    faLiteral: 'نظافتچی',
    pron: 'فاشینِیرا',
    cefr: 'B1',
    category: 'work',
    pos: 'noun',
    gender: 'f',
  }),

  // ── directions ────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-norte',
    pt: 'norte',
    faLiteral: 'شمال',
    pron: 'نُرتی',
    cefr: 'A2',
    category: 'directions',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-sul',
    pt: 'sul',
    faLiteral: 'جنوب',
    pron: 'سول',
    cefr: 'A2',
    category: 'directions',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-leste',
    pt: 'leste',
    faLiteral: 'شرق',
    pron: 'لِستی',
    cefr: 'B1',
    category: 'directions',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-oeste',
    pt: 'oeste',
    faLiteral: 'غرب',
    pron: 'اُئِستی',
    cefr: 'B1',
    category: 'directions',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-subir',
    pt: 'subir',
    faLiteral: 'بالا رفتن',
    pron: 'سوبیر',
    cefr: 'A2',
    category: 'directions',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vz-descer',
    pt: 'descer',
    faLiteral: 'پایین آمدن/پیاده شدن',
    pron: 'دِسِر',
    cefr: 'A2',
    category: 'directions',
    pos: 'verb',
  }),

  // ── drinks ────────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-vinho',
    pt: 'vinho',
    faLiteral: 'شراب',
    pron: 'وینیو',
    cefr: 'A2',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-agua-coco',
    pt: 'água de coco',
    faLiteral: 'آب نارگیل',
    pron: 'آگوا جی کوکو',
    cefr: 'B1',
    category: 'drinks',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vz-cafezinho',
    pt: 'cafezinho',
    faLiteral: 'قهوهٔ کوچک برزیلی',
    pron: 'کافِزینیو',
    cefr: 'B1',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
  }),

  // ── colors ────────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-claro',
    pt: 'claro',
    faLiteral: 'روشن (رنگ)',
    pron: 'کلارو',
    cefr: 'B1',
    category: 'colors',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vz-escuro',
    pt: 'escuro',
    faLiteral: 'تیره (رنگ)',
    pron: 'اِسکورو',
    cefr: 'B1',
    category: 'colors',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vz-colorido',
    pt: 'colorido',
    faLiteral: 'رنگارنگ',
    pron: 'کولوریدو',
    cefr: 'B2',
    category: 'colors',
    pos: 'adj',
  }),

  // ── question-words ──────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-quantos',
    pt: 'quantos',
    faLiteral: 'چند تا (مذکر)',
    pron: 'کوانتوس',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vz-quantas',
    pt: 'quantas',
    faLiteral: 'چند تا (مؤنث)',
    pron: 'کوانتاس',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vz-para-que',
    pt: 'para quê',
    faLiteral: 'برای چه',
    pron: 'پارا که',
    cefr: 'B1',
    category: 'question-words',
    pos: 'other',
  }),

  // ── prepositions ──────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-de',
    pt: 'de',
    faLiteral: 'از/مالِ',
    pron: 'جی',
    cefr: 'A2',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vz-em',
    pt: 'em',
    faLiteral: 'در',
    pron: 'اِین',
    cefr: 'A2',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vz-desde',
    pt: 'desde',
    faLiteral: 'از (زمان)',
    pron: 'دِزدی',
    cefr: 'B2',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vz-durante',
    pt: 'durante',
    faLiteral: 'در طولِ',
    pron: 'دورانتی',
    cefr: 'B1',
    category: 'prepositions',
    pos: 'prep',
  }),

  // ── city ────────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-banco-city',
    pt: 'banco',
    faLiteral: 'بانک',
    pron: 'بانکو',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-mercado-city',
    pt: 'supermercado',
    faLiteral: 'سوپرمارکت',
    pron: 'سوپِرمِرکادو',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-padaria',
    pt: 'padaria',
    faLiteral: 'نانوایی',
    pron: 'پاداریا',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vz-parque',
    pt: 'parque',
    faLiteral: 'پارک',
    pron: 'پارکی',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'm',
  }),

  // ── shopping ──────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-preco',
    pt: 'preço',
    faLiteral: 'قیمت',
    pron: 'پرِسو',
    cefr: 'A2',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vz-barato-shop',
    pt: 'oferta',
    faLiteral: 'پیشنهاد ویژه/حراج',
    pron: 'اُفِرتا',
    cefr: 'B1',
    category: 'shopping',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vz-sacola',
    pt: 'sacola',
    faLiteral: 'کیسهٔ خرید',
    pron: 'ساکولا',
    cefr: 'A2',
    category: 'shopping',
    pos: 'noun',
    gender: 'f',
  }),

  // ── numbers ────────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vz-terceiro',
    pt: 'terceiro',
    faLiteral: 'سوم',
    pron: 'تِرسِیرو',
    cefr: 'A2',
    category: 'numbers',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vz-ultimo',
    pt: 'último',
    faLiteral: 'آخرین',
    pron: 'اولتیمو',
    cefr: 'B1',
    category: 'numbers',
    pos: 'adj',
  }),
];
