/**
 * Extended vocabulary — a large second wave of words that fills out every
 * category and adds the higher CEFR levels (A2, B1, B2) on top of the core
 * A1 set in vocab.ts. Merged into the bundle in ./index.ts.
 */
import { mkVocab } from './helpers';
import type { Vocab } from '@/domain/content/schema';

export const vocabExtra: Vocab[] = [
  // ── greetings ──────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-e-ai',
    pt: 'e aí?',
    faLiteral: 'چطوری؟',
    faNatural: 'چطوری؟ (خیلی خودمانی)',
    pron: 'ای آیی',
    cefr: 'A2',
    category: 'greetings',
    pos: 'phrase',
    formality: 'informal',
  }),
  mkVocab({
    id: 'vx-beleza',
    pt: 'beleza?',
    faLiteral: 'خوبی؟',
    pron: 'بِلِزا',
    cefr: 'A2',
    category: 'greetings',
    pos: 'phrase',
    formality: 'informal',
  }),
  mkVocab({
    id: 'vx-seja-bem-vindo',
    pt: 'seja bem-vindo',
    faLiteral: 'خوش آمدی',
    pron: 'سِژا بِین-ویندو',
    cefr: 'A2',
    category: 'greetings',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'vx-ate-breve',
    pt: 'até breve',
    faLiteral: 'به‌زودی می‌بینمت',
    pron: 'آته برِوی',
    cefr: 'A2',
    category: 'greetings',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'vx-bom-fds',
    pt: 'bom fim de semana',
    faLiteral: 'آخر هفتهٔ خوبی داشته باشی',
    pron: 'بُن فین جی سِمانا',
    cefr: 'A2',
    category: 'greetings',
    pos: 'phrase',
  }),
  mkVocab({
    id: 'vx-cumprimentar',
    pt: 'cumprimentar',
    faLiteral: 'سلام و احوال‌پرسی کردن',
    pron: 'کومپریمِنتار',
    cefr: 'B1',
    category: 'greetings',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-despedir-se',
    pt: 'despedir-se',
    faLiteral: 'خداحافظی کردن',
    pron: 'جِسپِجیر-سی',
    cefr: 'B1',
    category: 'greetings',
    pos: 'verb',
  }),

  // ── family ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-avo-m2',
    pt: 'avô',
    faLiteral: 'پدربزرگ',
    pron: 'آوُو',
    cefr: 'A2',
    category: 'family',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-neto',
    pt: 'neto',
    faLiteral: 'نوه (پسر)',
    pron: 'نِتو',
    cefr: 'A2',
    category: 'family',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-neta',
    pt: 'neta',
    faLiteral: 'نوه (دختر)',
    pron: 'نِتا',
    cefr: 'A2',
    category: 'family',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-sobrinho',
    pt: 'sobrinho',
    faLiteral: 'خواهرزاده/برادرزاده (پسر)',
    pron: 'سوبرینیو',
    cefr: 'B1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-cunhado',
    pt: 'cunhado',
    faLiteral: 'برادرشوهر/برادرزن',
    pron: 'کونیادو',
    cefr: 'B1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-sogro',
    pt: 'sogro',
    faLiteral: 'پدرشوهر/پدرزن',
    pron: 'سُگرو',
    cefr: 'B1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-genro',
    pt: 'genro',
    faLiteral: 'داماد',
    pron: 'ژِنرو',
    cefr: 'B1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-nora',
    pt: 'nora',
    faLiteral: 'عروس',
    pron: 'نُرا',
    cefr: 'B1',
    category: 'family',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-padrasto',
    pt: 'padrasto',
    faLiteral: 'ناپدری',
    pron: 'پادراستو',
    cefr: 'B1',
    category: 'family',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-parente',
    pt: 'parente',
    faLiteral: 'خویشاوند',
    pron: 'پارِنتی',
    cefr: 'B1',
    category: 'family',
    pos: 'noun',
  }),

  // ── food ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-manteiga',
    pt: 'manteiga',
    faLiteral: 'کره',
    pron: 'مانتِیگا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-acucar2',
    pt: 'açúcar',
    faLiteral: 'شکر',
    pron: 'آسوکار',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-sal2',
    pt: 'sal',
    faLiteral: 'نمک',
    pron: 'سال',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-macarrao',
    pt: 'macarrão',
    faLiteral: 'ماکارونی',
    pron: 'ماکاهائو',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-sopa',
    pt: 'sopa',
    faLiteral: 'سوپ',
    pron: 'سُپا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-salada',
    pt: 'salada',
    faLiteral: 'سالاد',
    pron: 'سالادا',
    cefr: 'A2',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-feijoada',
    pt: 'feijoada',
    faLiteral: 'فِیژوآدا (خوراک ملی برزیل)',
    pron: 'فِیژوآدا',
    cefr: 'B1',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-farinha',
    pt: 'farinha',
    faLiteral: 'آرد',
    pron: 'فارینیا',
    cefr: 'B1',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-tempero',
    pt: 'tempero',
    faLiteral: 'چاشنی/ادویه',
    pron: 'تِمپِرو',
    cefr: 'B1',
    category: 'food',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-sobremesa',
    pt: 'sobremesa',
    faLiteral: 'دسر',
    pron: 'سوبرِمِزا',
    cefr: 'B1',
    category: 'food',
    pos: 'noun',
    gender: 'f',
  }),

  // ── drinks ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-suco2',
    pt: 'suco',
    faLiteral: 'آبمیوه',
    pron: 'سوکو',
    cefr: 'A2',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-refrigerante',
    pt: 'refrigerante',
    faLiteral: 'نوشابه',
    pron: 'هِفریژِرانتی',
    cefr: 'A2',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-cha2',
    pt: 'chá',
    faLiteral: 'چای',
    pron: 'شا',
    cefr: 'A2',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-cerveja2',
    pt: 'cerveja',
    faLiteral: 'آبجو',
    pron: 'سِر‌وِژا',
    cefr: 'A2',
    category: 'drinks',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-vitamina',
    pt: 'vitamina',
    faLiteral: 'اسموتی/معجون میوه',
    pron: 'ویتامینا',
    cefr: 'B1',
    category: 'drinks',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-caldo-cana',
    pt: 'caldo de cana',
    faLiteral: 'آب نیشکر',
    pron: 'کالدو جی کانا',
    cefr: 'B1',
    category: 'drinks',
    pos: 'noun',
    gender: 'm',
  }),

  // ── house ──────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-sofa',
    pt: 'sofá',
    faLiteral: 'مبل',
    pron: 'سُفا',
    cefr: 'A2',
    category: 'house',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-geladeira',
    pt: 'geladeira',
    faLiteral: 'یخچال',
    pron: 'ژِلادِیرا',
    cefr: 'A2',
    category: 'house',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-fogao',
    pt: 'fogão',
    faLiteral: 'اجاق گاز',
    pron: 'فُگائو',
    cefr: 'A2',
    category: 'house',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-armario',
    pt: 'armário',
    faLiteral: 'کمد',
    pron: 'آرماریو',
    cefr: 'A2',
    category: 'house',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-parede',
    pt: 'parede',
    faLiteral: 'دیوار',
    pron: 'پارِجی',
    cefr: 'A2',
    category: 'house',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-telhado',
    pt: 'telhado',
    faLiteral: 'سقف/بام',
    pron: 'تِلیادو',
    cefr: 'B1',
    category: 'house',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-aluguel',
    pt: 'aluguel',
    faLiteral: 'اجاره',
    pron: 'آلوگِل',
    cefr: 'B1',
    category: 'house',
    pos: 'noun',
    gender: 'm',
    notes: 'واژهٔ کلیدی برای اجاره‌کردن خانه.',
  }),
  mkVocab({
    id: 'vx-vizinho',
    pt: 'vizinho',
    faLiteral: 'همسایه',
    pron: 'ویزینیو',
    cefr: 'B1',
    category: 'house',
    pos: 'noun',
    gender: 'm',
  }),

  // ── body ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-cabeca2',
    pt: 'cabeça',
    faLiteral: 'سر',
    pron: 'کابِسا',
    cefr: 'A2',
    category: 'body',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-costas',
    pt: 'costas',
    faLiteral: 'پشت/کمر',
    pron: 'کُستاس',
    cefr: 'A2',
    category: 'body',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-dente',
    pt: 'dente',
    faLiteral: 'دندان',
    pron: 'دِنتی',
    cefr: 'A2',
    category: 'body',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-coracao',
    pt: 'coração',
    faLiteral: 'قلب',
    pron: 'کوراسائو',
    cefr: 'B1',
    category: 'body',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-estomago',
    pt: 'estômago',
    faLiteral: 'معده',
    pron: 'اِستوماگو',
    cefr: 'B1',
    category: 'body',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-pele',
    pt: 'pele',
    faLiteral: 'پوست',
    pron: 'پِلی',
    cefr: 'B1',
    category: 'body',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-osso',
    pt: 'osso',
    faLiteral: 'استخوان',
    pron: 'اُسو',
    cefr: 'B1',
    category: 'body',
    pos: 'noun',
    gender: 'm',
  }),

  // ── health ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-febre',
    pt: 'febre',
    faLiteral: 'تب',
    pron: 'فِبری',
    cefr: 'A2',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-dor',
    pt: 'dor',
    faLiteral: 'درد',
    pron: 'دُر',
    cefr: 'A2',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-remedio',
    pt: 'remédio',
    faLiteral: 'دارو',
    pron: 'هِمِجیو',
    cefr: 'A2',
    category: 'health',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-gripe',
    pt: 'gripe',
    faLiteral: 'آنفلوانزا',
    pron: 'گریپی',
    cefr: 'A2',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-consulta',
    pt: 'consulta',
    faLiteral: 'ویزیت/نوبت پزشک',
    pron: 'کُنسولتا',
    cefr: 'B1',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-receita-med',
    pt: 'receita médica',
    faLiteral: 'نسخهٔ پزشکی',
    pron: 'هِسِیتا مِجیکا',
    cefr: 'B1',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-vacina',
    pt: 'vacina',
    faLiteral: 'واکسن',
    pron: 'واسینا',
    cefr: 'B1',
    category: 'health',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-posto-saude',
    pt: 'posto de saúde',
    faLiteral: 'مرکز بهداشت',
    pron: 'پُستو جی ساوجی',
    cefr: 'B1',
    category: 'health',
    pos: 'noun',
    gender: 'm',
  }),

  // ── clothing ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-camiseta',
    pt: 'camiseta',
    faLiteral: 'تی‌شرت',
    pron: 'کامیزِتا',
    cefr: 'A2',
    category: 'clothing',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-calca-jeans',
    pt: 'calça jeans',
    faLiteral: 'شلوار جین',
    pron: 'کالسا ژینز',
    cefr: 'A2',
    category: 'clothing',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-meia',
    pt: 'meia',
    faLiteral: 'جوراب',
    pron: 'مِیا',
    cefr: 'A2',
    category: 'clothing',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-jaqueta',
    pt: 'jaqueta',
    faLiteral: 'کاپشن',
    pron: 'ژاکِتا',
    cefr: 'A2',
    category: 'clothing',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-chapeu',
    pt: 'chapéu',
    faLiteral: 'کلاه',
    pron: 'شاپِئو',
    cefr: 'B1',
    category: 'clothing',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-cinto',
    pt: 'cinto',
    faLiteral: 'کمربند',
    pron: 'سینتو',
    cefr: 'B1',
    category: 'clothing',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-oculos',
    pt: 'óculos',
    faLiteral: 'عینک',
    pron: 'اُکولوس',
    cefr: 'B1',
    category: 'clothing',
    pos: 'noun',
    gender: 'm',
  }),

  // ── colors ─────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-rosa',
    pt: 'rosa',
    faLiteral: 'صورتی',
    pron: 'هُزا',
    cefr: 'A2',
    category: 'colors',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-roxo',
    pt: 'roxo',
    faLiteral: 'بنفش',
    pron: 'هُشو',
    cefr: 'A2',
    category: 'colors',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-laranja2',
    pt: 'laranja',
    faLiteral: 'نارنجی',
    pron: 'لارانژا',
    cefr: 'A2',
    category: 'colors',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-cinza',
    pt: 'cinza',
    faLiteral: 'خاکستری',
    pron: 'سینزا',
    cefr: 'A2',
    category: 'colors',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-marrom',
    pt: 'marrom',
    faLiteral: 'قهوه‌ای',
    pron: 'ماهُن',
    cefr: 'A2',
    category: 'colors',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-dourado',
    pt: 'dourado',
    faLiteral: 'طلایی',
    pron: 'دورادو',
    cefr: 'B1',
    category: 'colors',
    pos: 'adj',
  }),

  // ── numbers ────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-cem',
    pt: 'cem',
    faLiteral: 'صد',
    pron: 'سِن',
    cefr: 'A2',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-mil',
    pt: 'mil',
    faLiteral: 'هزار',
    pron: 'میل',
    cefr: 'A2',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-milhao',
    pt: 'um milhão',
    faLiteral: 'یک میلیون',
    pron: 'اوم میلیائو',
    cefr: 'B1',
    category: 'numbers',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-primeiro',
    pt: 'primeiro',
    faLiteral: 'اول',
    pron: 'پریمِیرو',
    cefr: 'A2',
    category: 'numbers',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-segundo-ord',
    pt: 'segundo',
    faLiteral: 'دوم',
    pron: 'سِگوندو',
    cefr: 'A2',
    category: 'numbers',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-metade',
    pt: 'metade',
    faLiteral: 'نصف',
    pron: 'مِتاجی',
    cefr: 'B1',
    category: 'numbers',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-dobro',
    pt: 'dobro',
    faLiteral: 'دو برابر',
    pron: 'دُبرو',
    cefr: 'B1',
    category: 'numbers',
    pos: 'noun',
    gender: 'm',
  }),

  // ── days-time ──────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-ontem',
    pt: 'ontem',
    faLiteral: 'دیروز',
    pron: 'اُنتِین',
    cefr: 'A2',
    category: 'days-time',
    pos: 'adv',
  }),
  mkVocab({
    id: 'vx-hoje',
    pt: 'hoje',
    faLiteral: 'امروز',
    pron: 'اُژی',
    cefr: 'A2',
    category: 'days-time',
    pos: 'adv',
  }),
  mkVocab({
    id: 'vx-amanha',
    pt: 'amanhã',
    faLiteral: 'فردا',
    pron: 'آمانیا',
    cefr: 'A2',
    category: 'days-time',
    pos: 'adv',
  }),
  mkVocab({
    id: 'vx-semana',
    pt: 'semana',
    faLiteral: 'هفته',
    pron: 'سِمانا',
    cefr: 'A2',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-mes',
    pt: 'mês',
    faLiteral: 'ماه (تقویم)',
    pron: 'مِس',
    cefr: 'A2',
    category: 'days-time',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-ano',
    pt: 'ano',
    faLiteral: 'سال',
    pron: 'آنو',
    cefr: 'A2',
    category: 'days-time',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-cedo',
    pt: 'cedo',
    faLiteral: 'زود',
    pron: 'سِدو',
    cefr: 'B1',
    category: 'days-time',
    pos: 'adv',
  }),
  mkVocab({
    id: 'vx-madrugada',
    pt: 'madrugada',
    faLiteral: 'سحر/بامداد',
    pron: 'مادروگادا',
    cefr: 'B1',
    category: 'days-time',
    pos: 'noun',
    gender: 'f',
  }),

  // ── weather ────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-sol',
    pt: 'sol',
    faLiteral: 'آفتاب',
    pron: 'سُل',
    cefr: 'A2',
    category: 'weather',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-chuva',
    pt: 'chuva',
    faLiteral: 'باران',
    pron: 'شووا',
    cefr: 'A2',
    category: 'weather',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-vento',
    pt: 'vento',
    faLiteral: 'باد',
    pron: 'وِنتو',
    cefr: 'A2',
    category: 'weather',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-nuvem',
    pt: 'nuvem',
    faLiteral: 'ابر',
    pron: 'نووِن',
    cefr: 'B1',
    category: 'weather',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-tempestade',
    pt: 'tempestade',
    faLiteral: 'طوفان',
    pron: 'تِمپِستاجی',
    cefr: 'B1',
    category: 'weather',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-umidade',
    pt: 'umidade',
    faLiteral: 'رطوبت',
    pron: 'اومیداجی',
    cefr: 'B2',
    category: 'weather',
    pos: 'noun',
    gender: 'f',
  }),

  // ── transport ──────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-metro2',
    pt: 'metrô',
    faLiteral: 'مترو',
    pron: 'مِترو',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-trem2',
    pt: 'trem',
    faLiteral: 'قطار',
    pron: 'ترِین',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-aviao2',
    pt: 'avião',
    faLiteral: 'هواپیما',
    pron: 'آویائو',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-passagem2',
    pt: 'passagem',
    faLiteral: 'بلیت (سفر)',
    pron: 'پاساژِین',
    cefr: 'A2',
    category: 'transport',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-estacao',
    pt: 'estação',
    faLiteral: 'ایستگاه',
    pron: 'اِستاسائو',
    cefr: 'B1',
    category: 'transport',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-ponto-onibus',
    pt: 'ponto de ônibus',
    faLiteral: 'ایستگاه اتوبوس',
    pron: 'پُنتو جی اُنیبوس',
    cefr: 'B1',
    category: 'transport',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-baldeacao',
    pt: 'baldeação',
    faLiteral: 'تعویض خط/وسیله',
    pron: 'بالدِآسائو',
    cefr: 'B2',
    category: 'transport',
    pos: 'noun',
    gender: 'f',
  }),

  // ── directions ─────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-esquerda',
    pt: 'esquerda',
    faLiteral: 'چپ',
    pron: 'اِسکِردا',
    cefr: 'A2',
    category: 'directions',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-direita',
    pt: 'direita',
    faLiteral: 'راست',
    pron: 'جیرِیتا',
    cefr: 'A2',
    category: 'directions',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-reto',
    pt: 'em frente',
    faLiteral: 'مستقیم/روبه‌رو',
    pron: 'اِین فرِنتی',
    cefr: 'A2',
    category: 'directions',
    pos: 'adv',
  }),
  mkVocab({
    id: 'vx-perto',
    pt: 'perto',
    faLiteral: 'نزدیک',
    pron: 'پِرتو',
    cefr: 'A2',
    category: 'directions',
    pos: 'adv',
  }),
  mkVocab({
    id: 'vx-longe',
    pt: 'longe',
    faLiteral: 'دور',
    pron: 'لُنژی',
    cefr: 'A2',
    category: 'directions',
    pos: 'adv',
  }),
  mkVocab({
    id: 'vx-esquina',
    pt: 'esquina',
    faLiteral: 'نبش/گوشهٔ خیابان',
    pron: 'اِسکینا',
    cefr: 'B1',
    category: 'directions',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-quarteirao',
    pt: 'quarteirão',
    faLiteral: 'یک بلوک (کوی)',
    pron: 'کوارتِیرائو',
    cefr: 'B1',
    category: 'directions',
    pos: 'noun',
    gender: 'm',
  }),

  // ── city ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-praca',
    pt: 'praça',
    faLiteral: 'میدان',
    pron: 'پراسا',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-bairro',
    pt: 'bairro',
    faLiteral: 'محله',
    pron: 'بایهو',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-igreja2',
    pt: 'igreja',
    faLiteral: 'کلیسا',
    pron: 'ایگرِژا',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-farmacia',
    pt: 'farmácia',
    faLiteral: 'داروخانه',
    pron: 'فارماسیا',
    cefr: 'A2',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-prefeitura',
    pt: 'prefeitura',
    faLiteral: 'شهرداری',
    pron: 'پرِفِیتورا',
    cefr: 'B1',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-delegacia',
    pt: 'delegacia',
    faLiteral: 'کلانتری',
    pron: 'دِلِگاسیا',
    cefr: 'B1',
    category: 'city',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-correio',
    pt: 'correio',
    faLiteral: 'ادارهٔ پست',
    pron: 'کوهِیو',
    cefr: 'B1',
    category: 'city',
    pos: 'noun',
    gender: 'm',
  }),

  // ── shopping ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-mercado',
    pt: 'mercado',
    faLiteral: 'فروشگاه/بازار',
    pron: 'مِرکادو',
    cefr: 'A2',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-feira2',
    pt: 'feira',
    faLiteral: 'بازارچهٔ خیابانی',
    pron: 'فِیرا',
    cefr: 'A2',
    category: 'shopping',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-desconto',
    pt: 'desconto',
    faLiteral: 'تخفیف',
    pron: 'جِسکونتو',
    cefr: 'B1',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-caixa2',
    pt: 'caixa',
    faLiteral: 'صندوق (پرداخت)',
    pron: 'کایشا',
    cefr: 'B1',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-recibo',
    pt: 'recibo',
    faLiteral: 'رسید',
    pron: 'هِسیبو',
    cefr: 'B1',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-troco',
    pt: 'troco',
    faLiteral: 'پول خرد/باقی‌مانده',
    pron: 'ترُکو',
    cefr: 'B1',
    category: 'shopping',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-a-vista',
    pt: 'à vista',
    faLiteral: 'نقدی',
    pron: 'آ ویستا',
    cefr: 'B2',
    category: 'shopping',
    pos: 'phrase',
  }),

  // ── money ──────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-dinheiro2',
    pt: 'dinheiro',
    faLiteral: 'پول',
    pron: 'جینیِیرو',
    cefr: 'A2',
    category: 'money',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-cartao',
    pt: 'cartão',
    faLiteral: 'کارت بانکی',
    pron: 'کارتائو',
    cefr: 'A2',
    category: 'money',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-conta-bank',
    pt: 'conta bancária',
    faLiteral: 'حساب بانکی',
    pron: 'کُنتا بانکاریا',
    cefr: 'B1',
    category: 'money',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-salario',
    pt: 'salário',
    faLiteral: 'حقوق/دستمزد',
    pron: 'سالاریو',
    cefr: 'B1',
    category: 'money',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-boleto',
    pt: 'boleto',
    faLiteral: 'قبض پرداخت (بولِتو)',
    pron: 'بولِتو',
    cefr: 'B2',
    category: 'money',
    pos: 'noun',
    gender: 'm',
    notes: 'روش رایج پرداخت قبض در برزیل.',
  }),
  mkVocab({
    id: 'vx-pix',
    pt: 'Pix',
    faLiteral: 'پیکس (انتقال فوری پول)',
    pron: 'پیکس',
    cefr: 'B1',
    category: 'money',
    pos: 'noun',
    gender: 'm',
  }),

  // ── work ───────────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-emprego',
    pt: 'emprego',
    faLiteral: 'شغل/کار',
    pron: 'اِمپرِگو',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-chefe',
    pt: 'chefe',
    faLiteral: 'رئیس',
    pron: 'شِفی',
    cefr: 'A2',
    category: 'work',
    pos: 'noun',
  }),
  mkVocab({
    id: 'vx-curriculo',
    pt: 'currículo',
    faLiteral: 'رزومه',
    pron: 'کوهیکولو',
    cefr: 'B1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-entrevista',
    pt: 'entrevista',
    faLiteral: 'مصاحبه',
    pron: 'اِنترِویستا',
    cefr: 'B1',
    category: 'work',
    pos: 'noun',
    gender: 'f',
  }),
  mkVocab({
    id: 'vx-contrato',
    pt: 'contrato',
    faLiteral: 'قرارداد',
    pron: 'کُنتراتو',
    cefr: 'B1',
    category: 'work',
    pos: 'noun',
    gender: 'm',
  }),
  mkVocab({
    id: 'vx-carteira-trab',
    pt: 'carteira de trabalho',
    faLiteral: 'دفترچهٔ کار',
    pron: 'کارتِیرا جی ترابالیو',
    cefr: 'B2',
    category: 'work',
    pos: 'noun',
    gender: 'f',
  }),

  // ── emotions ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-feliz',
    pt: 'feliz',
    faLiteral: 'خوشحال',
    pron: 'فِلیز',
    cefr: 'A2',
    category: 'emotions',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-triste',
    pt: 'triste',
    faLiteral: 'ناراحت/غمگین',
    pron: 'تریستی',
    cefr: 'A2',
    category: 'emotions',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-cansado',
    pt: 'cansado',
    faLiteral: 'خسته',
    pron: 'کانسادو',
    cefr: 'A2',
    category: 'emotions',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-nervoso',
    pt: 'nervoso',
    faLiteral: 'عصبی/مضطرب',
    pron: 'نِرووزو',
    cefr: 'B1',
    category: 'emotions',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-preocupado',
    pt: 'preocupado',
    faLiteral: 'نگران',
    pron: 'پرِئوکوپادو',
    cefr: 'B1',
    category: 'emotions',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-orgulhoso',
    pt: 'orgulhoso',
    faLiteral: 'سربلند/مغرور',
    pron: 'اورگولیوزو',
    cefr: 'B2',
    category: 'emotions',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-saudade',
    pt: 'saudade',
    faLiteral: 'دلتنگی',
    pron: 'ساودادی',
    cefr: 'B1',
    category: 'emotions',
    pos: 'noun',
    gender: 'f',
    notes: 'واژهٔ خاص برزیلی برای حس دلتنگی.',
  }),

  // ── verbs-basic ────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-poder',
    pt: 'poder',
    faLiteral: 'توانستن',
    pron: 'پودِر',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-querer',
    pt: 'querer',
    faLiteral: 'خواستن',
    pron: 'کِرِر',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-precisar',
    pt: 'precisar',
    faLiteral: 'نیاز داشتن',
    pron: 'پرِسیزار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-saber',
    pt: 'saber',
    faLiteral: 'دانستن',
    pron: 'سابِر',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-trabalhar',
    pt: 'trabalhar',
    faLiteral: 'کار کردن',
    pron: 'ترابالیار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-morar',
    pt: 'morar',
    faLiteral: 'سکونت داشتن',
    pron: 'مورار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-conseguir',
    pt: 'conseguir',
    faLiteral: 'موفق شدن/توانستن',
    pron: 'کُنسِگیر',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-precisar-de',
    pt: 'ajudar',
    faLiteral: 'کمک کردن',
    pron: 'آژودار',
    cefr: 'A2',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-esquecer',
    pt: 'esquecer',
    faLiteral: 'فراموش کردن',
    pron: 'اِسکِسِر',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),
  mkVocab({
    id: 'vx-lembrar',
    pt: 'lembrar',
    faLiteral: 'به یاد آوردن',
    pron: 'لِمبرار',
    cefr: 'B1',
    category: 'verbs-basic',
    pos: 'verb',
  }),

  // ── adjectives-basic ───────────────────────────────────────────────────
  mkVocab({
    id: 'vx-grande',
    pt: 'grande',
    faLiteral: 'بزرگ',
    pron: 'گرانجی',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-pequeno',
    pt: 'pequeno',
    faLiteral: 'کوچک',
    pron: 'پِکِنو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-novo',
    pt: 'novo',
    faLiteral: 'نو/جدید',
    pron: 'نُوو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-velho',
    pt: 'velho',
    faLiteral: 'کهنه/پیر',
    pron: 'وِلیو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-caro',
    pt: 'caro',
    faLiteral: 'گران',
    pron: 'کارو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-barato',
    pt: 'barato',
    faLiteral: 'ارزان',
    pron: 'باراتو',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-facil',
    pt: 'fácil',
    faLiteral: 'آسان',
    pron: 'فاسیل',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-dificil',
    pt: 'difícil',
    faLiteral: 'سخت/دشوار',
    pron: 'جیفیسیل',
    cefr: 'A2',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-importante',
    pt: 'importante',
    faLiteral: 'مهم',
    pron: 'ایمپورتانتی',
    cefr: 'B1',
    category: 'adjectives-basic',
    pos: 'adj',
  }),
  mkVocab({
    id: 'vx-perigoso',
    pt: 'perigoso',
    faLiteral: 'خطرناک',
    pron: 'پِریگوزو',
    cefr: 'B1',
    category: 'adjectives-basic',
    pos: 'adj',
  }),

  // ── pronouns ───────────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-a-gente',
    pt: 'a gente',
    faLiteral: 'ما (خودمانی)',
    pron: 'آ ژِنتی',
    cefr: 'A2',
    category: 'pronouns',
    pos: 'pron',
    notes: 'معنی «ما» می‌دهد ولی فعلش مفرد است.',
  }),
  mkVocab({
    id: 'vx-meu',
    pt: 'meu / minha',
    faLiteral: 'مالِ من',
    pron: 'مِئو / مینیا',
    cefr: 'A2',
    category: 'pronouns',
    pos: 'pron',
  }),
  mkVocab({
    id: 'vx-seu',
    pt: 'seu / sua',
    faLiteral: 'مالِ تو/شما',
    pron: 'سِئو / سوآ',
    cefr: 'A2',
    category: 'pronouns',
    pos: 'pron',
  }),
  mkVocab({
    id: 'vx-nosso',
    pt: 'nosso / nossa',
    faLiteral: 'مالِ ما',
    pron: 'نُسو / نُسا',
    cefr: 'A2',
    category: 'pronouns',
    pos: 'pron',
  }),
  mkVocab({
    id: 'vx-dele',
    pt: 'dele / dela',
    faLiteral: 'مالِ او',
    pron: 'دِلی / دِلا',
    cefr: 'B1',
    category: 'pronouns',
    pos: 'pron',
  }),
  mkVocab({
    id: 'vx-me',
    pt: 'me',
    faLiteral: 'به من/مرا (ضمیر مفعولی)',
    pron: 'می',
    cefr: 'B1',
    category: 'pronouns',
    pos: 'pron',
  }),

  // ── prepositions ───────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-com',
    pt: 'com',
    faLiteral: 'با',
    pron: 'کُن',
    cefr: 'A2',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vx-sem',
    pt: 'sem',
    faLiteral: 'بدون',
    pron: 'سِین',
    cefr: 'A2',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vx-para',
    pt: 'para',
    faLiteral: 'برای/به‌سوی',
    pron: 'پارا',
    cefr: 'A2',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vx-por',
    pt: 'por',
    faLiteral: 'از طریق/به‌خاطر',
    pron: 'پور',
    cefr: 'B1',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vx-ate',
    pt: 'até',
    faLiteral: 'تا',
    pron: 'آته',
    cefr: 'B1',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vx-sobre',
    pt: 'sobre',
    faLiteral: 'دربارهٔ/روی',
    pron: 'سُبری',
    cefr: 'B1',
    category: 'prepositions',
    pos: 'prep',
  }),
  mkVocab({
    id: 'vx-entre',
    pt: 'entre',
    faLiteral: 'بینِ',
    pron: 'اِنتری',
    cefr: 'B1',
    category: 'prepositions',
    pos: 'prep',
  }),

  // ── question-words ─────────────────────────────────────────────────────
  mkVocab({
    id: 'vx-quem',
    pt: 'quem',
    faLiteral: 'کی/چه کسی',
    pron: 'کِین',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-onde',
    pt: 'onde',
    faLiteral: 'کجا',
    pron: 'اُندی',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-quando',
    pt: 'quando',
    faLiteral: 'کِی/چه وقت',
    pron: 'کواندو',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-como',
    pt: 'como',
    faLiteral: 'چطور/چگونه',
    pron: 'کُمو',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-porque',
    pt: 'por que',
    faLiteral: 'چرا',
    pron: 'پور که',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-quanto',
    pt: 'quanto',
    faLiteral: 'چقدر/چند',
    pron: 'کوانتو',
    cefr: 'A2',
    category: 'question-words',
    pos: 'other',
  }),
  mkVocab({
    id: 'vx-qual',
    pt: 'qual',
    faLiteral: 'کدام',
    pron: 'کوال',
    cefr: 'B1',
    category: 'question-words',
    pos: 'other',
  }),
];
